// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={210}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>投書</rb><rt>とうしょ</rt></ruby></span>をそのまま<span><ruby><rb>出</rb><rt>だ</rt></ruby>した</span><span>に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない</span>。けっして<span><ruby><rb>社</rb><rt>しゃ</rt></ruby></span>のほうで<span><ruby><rb>調</rb><rt>しら</rt></ruby>べた</span>ものじゃない。<span><ruby><rb>文芸時評</rb><rt>ぶんげいじひょう</rt></ruby></span>の<span><ruby><rb>六号</rb><rt>ろくごう</rt></ruby><ruby><rb>活字</rb><rt>かつじ</rt></ruby></span>の投書にこんなのが、いくらでも<span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>。六号活字はほとんど<span><ruby><rb>罪悪</rb><rt>ざいあく</rt></ruby></span>のかたまりだ。よくよく<span><ruby><rb>探</rb><rt>さぐ</rt></ruby>って</span>みると<span><ruby><rb>嘘</rb><rt>うそ</rt></ruby></span>が<span><ruby><rb>多</rb><rt>おお</rt></ruby>い</span>。<span><ruby><rb>目</rb><rt>め</rt></ruby>に<ruby><rb>見</rb><rt>み</rt></ruby>えた</span>嘘をついているのもある。なぜそんな<span><ruby><rb>愚</rb><rt>おろか</rt></ruby>な</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>をやるかというとね、<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>。みんな<span><ruby><rb>利害</rb><rt>りがい</rt></ruby></span><span><ruby><rb>問題</rb><rt>もんだい</rt></ruby></span>が<span><ruby><rb>動機</rb><rt>どうき</rt></ruby></span>になっているらしい。それでぼくが六号活字を<span><ruby><rb>受持</rb><rt>うけも</rt></ruby>って</span>いる<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>には、<span><ruby><rb>性質</rb><rt>たち</rt></ruby></span>のよくないのは、たいてい<span><ruby><rb>屑籠</rb><rt>くずかご</rt></ruby></span>へ<span><ruby><rb>放</rb><rt>ほう</rt></ruby>り<ruby><rb>込</rb><rt>こ</rt></ruby>んだ</span>。この<span><ruby><rb>記事</rb><rt>きじ</rt></ruby></span>もまったくそれだね。<span><ruby><rb>反対</rb><rt>はんたい</rt></ruby><ruby><rb>運動</rb><rt>うんどう</rt></ruby></span>の<span><ruby><rb>結果</rb><rt>けっか</rt></ruby></span>だ」</p>
		<p>「なぜ、君の<span><ruby><rb>名</rb><rt>な</rt></ruby></span>が<span><ruby><rb>出</rb><rt>で</rt></ruby>ない</span>で、ぼくの名が出たものだろうな」</p>
		<p><span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>は「そうさ」と<span><ruby><rb>言</rb><rt>い</rt></ruby>って</span>いる。しばらくしてから、</p>
		<p>「やっぱり、なんだろう。君は<span><ruby><rb>本科生</rb><rt>ほんかせい</rt></ruby></span>でぼくは<span><ruby><rb>選科生</rb><rt>せんかせい</rt></ruby></span>だからだろう」と<span><ruby><rb>説明</rb><rt>せつめい</rt></ruby>した</span>。けれども<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>には、これが説明にもなんにもならなかった。三四郎は<span><ruby><rb>依然</rb><rt>いぜん</rt></ruby>として</span><span><ruby><rb>迷惑</rb><rt>めいわく</rt></ruby></span>である。</p>
		<p>「ぜんたいぼくが<span><ruby><rb>零余子</rb><rt>れいよし</rt></ruby></span>なんて<span>けちな</span><span><ruby><rb>号</rb><rt>ごう</rt></ruby></span>を<span><ruby><rb>使</rb><rt>つか</rt></ruby>わずに</span>、<span><ruby><rb>堂々</rb><rt>どうどう</rt></ruby>と</span><span><ruby><rb>佐々木</rb><rt>ささき</rt></ruby></span>与次郎と<span><ruby><rb>署名</rb><rt>しょめい</rt></ruby>して</span>おけばよかった。じっさいあの<span><ruby><rb>論文</rb><rt>ろんぶん</rt></ruby></span>は佐々木与次郎<span><ruby><rb>以外</rb><rt>いがい</rt></ruby></span>に<span><ruby><rb>書</rb><rt>か</rt></ruby>ける</span><span><ruby><rb>者</rb><rt>もの</rt></ruby></span>は<span><ruby><rb>一人</rb><rt>ひとり</rt></ruby></span>もないんだからなあ」</p>
		<p>与次郎はまじめである。三四郎に「<span><ruby><rb>偉大</rb><rt>いだい</rt></ruby>なる</span><span><ruby><rb>暗闇</rb><rt>くらやみ</rt></ruby></span>」の<span><ruby><rb>著作権</rb><rt>ちょさくけん</rt></ruby></span>を<span><ruby><rb>奪</rb><rt>うば</rt></ruby>われて</span>、かえって迷惑しているのかもしれない。三四郎はばかばかしくなった。</p>
		<p>「君、<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>に<span><ruby><rb>話</rb><rt>はな</rt></ruby>した</span>か」と<span><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。</p>
		<p>「さあ、そこだ。偉大なる暗闇の<span><ruby><rb>作者</rb><rt>さくしゃ</rt></ruby></span>なんか、君だって、ぼくだって、どちらだってかまわないが、こと先生の<span><ruby><rb>人格</rb><rt>じんかく</rt></ruby></span>に<span><ruby><rb>関係</rb><rt>かんけい</rt></ruby>してくる</span><span><ruby><rb>以上</rb><rt>いじょう</rt></ruby>は</span>、話さずにはいられない。ああいう先生だから、いっこう<span><ruby><rb>知</rb><rt>し</rt></ruby>りません</span>、<span><ruby><rb>何</rb><rt>なに</rt></ruby>か</span><span><ruby><rb>間違</rb><rt>まちが</rt></ruby>い</span>でしょう、偉大なる暗闇という論文は<span><ruby><rb>雑誌</rb><rt>ざっし</rt></ruby></span>に出ましたが、<span><ruby><rb>匿名</rb><rt>とくめい</rt></ruby></span>です、先生の<span><ruby><rb>崇拝者</rb><rt>すうはいしゃ</rt></ruby></span>が書いたものですから<span><ruby><rb>御安心</rb><rt>ごあんしん</rt></ruby>なさい</span>くらいに言っておけば、そうかで、すぐ<span><ruby><rb>済</rb><rt>す</rt></ruby>んでしまう</span>わけだが、このさいそうはいかん。どうしたってぼくが<span><ruby><rb>責任</rb><rt>せきにん</rt></ruby></span>を<span><ruby><rb>明</rb><rt>あき</rt></ruby>らかにしなくっちゃ</span>。事がうまくいって、知らん<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>をしているのは、<span><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち</span>がいいが、やりそくなって<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>いるのは<span><ruby><rb>不愉快</rb><rt>ふゆかい</rt></ruby></span>でたまらない。<span><ruby><rb>第一</rb><rt>だいいち</rt></ruby></span><span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>が事を<span><ruby><rb>起</rb><rt>お</rt></ruby>こして</span>おいて、ああいう<span><ruby><rb>善良</rb><rt>ぜんりょう</rt></ruby>な</span><span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>を迷惑な<span><ruby><rb>状態</rb><rt>じょうたい</rt></ruby></span>に<span><ruby><rb>陥</rb><rt>おちい</rt></ruby>らして</span>、それで<span><ruby><rb>平気</rb><rt>へいき</rt></ruby>に</span><span><ruby><rb>見物</rb><rt>けんぶつ</rt></ruby>がしておられる</span>ものじゃない。<span><ruby><rb>正邪</rb><rt>せいじゃ</rt></ruby><ruby><rb>曲直</rb><rt>きょくちょく</rt></ruby></span>なんてむずかしい問題は<span><ruby><rb>別</rb><rt>べつ</rt></ruby>として</span>、ただ<span><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby></span>で、<span>いたわしくって</span>いけない」</p>
		<p>三四郎ははじめて与次郎を<span><ruby><rb>感心</rb><rt>かんしん</rt></ruby>な</span><span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>だと<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>"No doubt it's a reader's submission, published verbatim. The news staff did nothing to confirm it. There's no shortage of such fodder at Literary Review. Most of what comes in is outright villainous. If you dig deep enough, it's concocted rubbish, some even blatantly so. You want to know why? They're all motivated by desire for personal gain. When I held the editor's pen, these sordid submissions went straight to the trash. That's exactly what this is - the work of our opposition."</p>
		<p>"Why my name and not yours?"</p>
		<p>"I wonder," Yojirō said and paused for a moment, then proposed an explanation. "That could be it. You're a regular student, and I'm an elective studies student. That's why."</p>
		<p>To Sanshirō, however, this explanation was wholly inadequate. He was still put out.</p>
		<p>"I should never have used that petty 'Reiyoshi' pen name. I should have gone boldly as 'Yojirō Sasaki.' Who else but Yojirō Sasaki could have authored such a piece?"</p>
		<p>Yojirō was serious. He was, it seemed, genuinely upset that credit for 'Great Dark Void' had been usurped from him and assigned to Sanshirō. To Sanshirō, this was all asinine.</p>
		<p>"Have you talked to the professor?" he asked.</p>
		<p>"That's the crux of it. It's not about who authored 'Great Dark Void,' be it you, me, or whomever. The professor's character is under attack, so I have to tell him. Under normal circumstances, I could simply feign ignorance, say it was some sort of mistake. An essay titled 'Great Dark Void' had appeared in a periodical under an assumed name. It was penned by an admirer, so he needn't worry about it. He'd simply raise his eyebrows and that would be the end of it. I can't do that this time. I have to come clean and take full responsibility. If all had gone well, I'd have gladly denied involvement. To stand silent as all goes awry, though, is sheer torture. After all, I started this, and I can't watch from the sideline as a virtuous man is dragged through the muck on my account.  Aside from the issues of right vs wrong, I simply will not see him suffer."</p>
		<p>Sanshirō, for the first time, regarded Yojirō with a sense of admiration.</p>  

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>投書</rb><rt>とうしょ</rt></ruby>&nbsp;letter to the editor; letter from a reader</span><span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;put out; published</span><span class="vocabstudy">に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない&nbsp;no doubt ...</span><span class="vocabstudy"><ruby><rb>社</rb><rt>しゃ</rt></ruby>&nbsp;(newspaper) company</span><span class="vocabstudy"><ruby><rb>調</rb><rt>しら</rt></ruby>べた&nbsp;investigated; checked; verified</span><span class="vocabstudy"><ruby><rb>文芸時評</rb><rt>ぶんげいじひょう</rt></ruby>&nbsp;Literary Review</span><span class="vocabstudy"><ruby><rb>六号</rb><rt>ろくごう</rt></ruby><ruby><rb>活字</rb><rt>かつじ</rt></ruby>&nbsp;size six type; small print; filler material</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come; arrive</span><span class="vocabstudy"><ruby><rb>罪悪</rb><rt>ざいあく</rt></ruby>&nbsp;evil; villainy</span><span class="vocabstudy"><ruby><rb>探</rb><rt>さぐ</rt></ruby>って&nbsp;investigate; look into</span><span class="vocabstudy"><ruby><rb>嘘</rb><rt>うそ</rt></ruby>&nbsp;concoction; fabrication</span><span class="vocabstudy"><ruby><rb>多</rb><rt>おお</rt></ruby>い&nbsp;many; numerous</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>に<ruby><rb>見</rb><rt>み</rt></ruby>えた&nbsp;blatant; obvious</span><span class="vocabstudy"><ruby><rb>愚</rb><rt>おろか</rt></ruby>な&nbsp;silly; foolish</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;act; action</span><span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you (used here as form of address)</span><span class="vocabstudy"><ruby><rb>利害</rb><rt>りがい</rt></ruby>&nbsp;advantages and disadvantages; interests</span><span class="vocabstudy"><ruby><rb>問題</rb><rt>もんだい</rt></ruby>&nbsp;problem; question (of)</span><span class="vocabstudy"><ruby><rb>動機</rb><rt>どうき</rt></ruby>&nbsp;motivation</span><span class="vocabstudy"><ruby><rb>受持</rb><rt>うけも</rt></ruby>って&nbsp;have charge of; administer</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;times; occasions</span><span class="vocabstudy"><ruby><rb>性質</rb><rt>たち</rt></ruby>&nbsp;quality; nature</span><span class="vocabstudy"><ruby><rb>屑籠</rb><rt>くずかご</rt></ruby>&nbsp;wastebasket</span><span class="vocabstudy"><ruby><rb>放</rb><rt>ほう</rt></ruby>り<ruby><rb>込</rb><rt>こ</rt></ruby>んだ&nbsp;tossed into</span><span class="vocabstudy"><ruby><rb>記事</rb><rt>きじ</rt></ruby>&nbsp;article</span><span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby><ruby><rb>運動</rb><rt>うんどう</rt></ruby>&nbsp;opposing movement; opposition camp</span><span class="vocabstudy"><ruby><rb>結果</rb><rt>けっか</rt></ruby>&nbsp;result; output (of)</span>
		<span class="vocabstudy"><ruby><rb>名</rb><rt>な</rt></ruby>&nbsp;name</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>ない&nbsp;not appear</span>
		<span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>って&nbsp;say; remark</span>
		<span class="vocabstudy"><ruby><rb>本科生</rb><rt>ほんかせい</rt></ruby>&nbsp;regular student</span><span class="vocabstudy"><ruby><rb>選科生</rb><rt>せんかせい</rt></ruby>&nbsp;elective studies student</span><span class="vocabstudy"><ruby><rb>説明</rb><rt>せつめい</rt></ruby>した&nbsp;explained; proposed an explanation</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>依然</rb><rt>いぜん</rt></ruby>として&nbsp;still; as before</span><span class="vocabstudy"><ruby><rb>迷惑</rb><rt>めいわく</rt></ruby>&nbsp;bothered; annoyed</span>
		<span class="vocabstudy"><ruby><rb>零余子</rb><rt>れいよし</rt></ruby>&nbsp;Reiyoshi (propagule; one of Yojirō's pen names)</span><span class="vocabstudy">けちな&nbsp;petty</span><span class="vocabstudy"><ruby><rb>号</rb><rt>ごう</rt></ruby>&nbsp;pen name</span><span class="vocabstudy"><ruby><rb>使</rb><rt>つか</rt></ruby>わずに&nbsp;without using; without resorting to</span><span class="vocabstudy"><ruby><rb>堂々</rb><rt>どうどう</rt></ruby>と&nbsp;grandly; boldly</span><span class="vocabstudy"><ruby><rb>佐々木</rb><rt>ささき</rt></ruby>&nbsp;Sasaki (Yojirō's family name)</span><span class="vocabstudy"><ruby><rb>署名</rb><rt>しょめい</rt></ruby>して&nbsp;sign</span><span class="vocabstudy"><ruby><rb>論文</rb><rt>ろんぶん</rt></ruby>&nbsp;essay; composition</span><span class="vocabstudy"><ruby><rb>以外</rb><rt>いがい</rt></ruby>&nbsp;apart from; other than</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>ける&nbsp;can write</span><span class="vocabstudy"><ruby><rb>者</rb><rt>もの</rt></ruby>&nbsp;person</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>&nbsp;one (single) person</span>
		<span class="vocabstudy"><ruby><rb>偉大</rb><rt>いだい</rt></ruby>なる&nbsp;great; mighty</span><span class="vocabstudy"><ruby><rb>暗闇</rb><rt>くらやみ</rt></ruby>&nbsp;darkness; void</span><span class="vocabstudy"><ruby><rb>著作権</rb><rt>ちょさくけん</rt></ruby>&nbsp;authorship</span><span class="vocabstudy"><ruby><rb>奪</rb><rt>うば</rt></ruby>われて&nbsp;have taken away (by someone)</span>
		<span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;professor</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>した&nbsp;confessed; explained</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span>
		<span class="vocabstudy"><ruby><rb>作者</rb><rt>さくしゃ</rt></ruby>&nbsp;writer; author</span><span class="vocabstudy"><ruby><rb>人格</rb><rt>じんかく</rt></ruby>&nbsp;character</span><span class="vocabstudy"><ruby><rb>関係</rb><rt>かんけい</rt></ruby>してくる&nbsp;come to affect; make an impact (on)</span><span class="vocabstudy"><ruby><rb>以上</rb><rt>いじょう</rt></ruby>は&nbsp;once ...; given that ...</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>りません&nbsp;don't know</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>か&nbsp;some sort of</span><span class="vocabstudy"><ruby><rb>間違</rb><rt>まちが</rt></ruby>い&nbsp;mistake</span><span class="vocabstudy"><ruby><rb>雑誌</rb><rt>ざっし</rt></ruby>&nbsp;magazine; periodical</span><span class="vocabstudy"><ruby><rb>匿名</rb><rt>とくめい</rt></ruby>&nbsp;assumed name</span><span class="vocabstudy"><ruby><rb>崇拝者</rb><rt>すうはいしゃ</rt></ruby>&nbsp;admirer</span><span class="vocabstudy"><ruby><rb>御安心</rb><rt>ごあんしん</rt></ruby>なさい&nbsp;don't worry about it</span><span class="vocabstudy"><ruby><rb>済</rb><rt>す</rt></ruby>んでしまう&nbsp;be settled; be at its end</span><span class="vocabstudy"><ruby><rb>責任</rb><rt>せきにん</rt></ruby>&nbsp;responsibility</span><span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかにしなくっちゃ&nbsp;have to make clear; have to come clean about</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face; facial expression</span><span class="vocabstudy"><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち&nbsp;feeling</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;remain silent</span><span class="vocabstudy"><ruby><rb>不愉快</rb><rt>ふゆかい</rt></ruby>&nbsp;unpleasant; disagreeable</span><span class="vocabstudy"><ruby><rb>第一</rb><rt>だいいち</rt></ruby>&nbsp;for one thing; first of all</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>起</rb><rt>お</rt></ruby>こして&nbsp;set in motion; instigate</span><span class="vocabstudy"><ruby><rb>善良</rb><rt>ぜんりょう</rt></ruby>な&nbsp;good; virtuous</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;person</span><span class="vocabstudy"><ruby><rb>状態</rb><rt>じょうたい</rt></ruby>&nbsp;situation</span><span class="vocabstudy"><ruby><rb>陥</rb><rt>おちい</rt></ruby>らして&nbsp;cause to fall into</span><span class="vocabstudy"><ruby><rb>平気</rb><rt>へいき</rt></ruby>に&nbsp;calmly; cooly</span><span class="vocabstudy"><ruby><rb>見物</rb><rt>けんぶつ</rt></ruby>がしておられる&nbsp;can view from a distance; can watch from the wings</span><span class="vocabstudy"><ruby><rb>正邪</rb><rt>せいじゃ</rt></ruby><ruby><rb>曲直</rb><rt>きょくちょく</rt></ruby>&nbsp;right and wrong</span><span class="vocabstudy"><ruby><rb>別</rb><rt>べつ</rt></ruby>として&nbsp;putting aside</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby>&nbsp;pitiable; unfortunate</span><span class="vocabstudy">いたわしくって&nbsp;heartrending</span>
		<span class="vocabstudy"><ruby><rb>感心</rb><rt>かんしん</rt></ruby>な&nbsp;admirable; praiseworthy</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man; fellow</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought (of as); regarded (as)</span>

	</StudyGuide>
);
