// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={52}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>きょうは<span><ruby><rb>白</rb><rt>しろ</rt></ruby>い</span>ものを<span><ruby><rb>薄</rb><rt>うす</rt></ruby>く</span><span><ruby><rb>塗</rb><rt>ぬ</rt></ruby>って</span>いる。けれども<span><ruby><rb>本来</rb><rt>ほんらい</rt></ruby>の</span><span><ruby><rb>地</rb><rt>じ</rt></ruby></span>を<span><ruby><rb>隠</rb><rt>かく</rt></ruby>す</span>ほどに<span><ruby><rb>無趣味</rb><rt>むしゅみ</rt></ruby></span>ではなかった。<span>こまやかな</span><span><ruby><rb>肉</rb><rt>にく</rt></ruby></span>が、<span>ほどよく</span><span><ruby><rb>色</rb><rt>いろ</rt></ruby>づいて</span>、<span><ruby><rb>強</rb><rt>つよ</rt></ruby>い</span><span><ruby><rb>日光</rb><rt>ひ</rt></ruby></span>に<span>めげない</span>ように<span><ruby><rb>見</rb><rt>み</rt></ruby>える</span><span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>を、きわめて薄く<span><ruby><rb>粉</rb><rt>こ</rt></ruby>が<ruby><rb>吹</rb><rt>ふ</rt></ruby>いて</span>いる。<span>てらてら</span><span><ruby><rb>照</rb><rt>ひか</rt></ruby>る</span><span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>ではない。</p>
		<p>肉は<span><ruby><rb>頬</rb><rt>ほお</rt></ruby></span>といわず<span><ruby><rb>顎</rb><rt>あご</rt></ruby></span>といわず<span>きちりと</span><span><ruby><rb>締</rb><rt>し</rt></ruby>まって</span>いる。<span><ruby><rb>骨</rb><rt>ほね</rt></ruby></span>の上に<span><ruby><rb>余</rb><rt>あま</rt></ruby>った</span>ものは<span>たんと</span>ないくらいである。それでいて、顔<span><ruby><rb>全体</rb><rt>ぜんたい</rt></ruby></span>が<span><ruby><rb>柔</rb><rt>やわら</rt></ruby>かい</span>。肉が柔かいのではない骨そのものが柔かいように<span><ruby><rb>思</rb><rt>おも</rt></ruby>われる</span>。<span><ruby><rb>奥行</rb><rt>おくゆ</rt></ruby>きの<ruby><rb>長</rb><rt>なが</rt></ruby>い</span><span><ruby><rb>感</rb><rt>かん</rt></ruby>じ</span>を<span><ruby><rb>起</rb><rt>お</rt></ruby>こさせる</span>顔である。</p>
		<p><span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は<span><ruby><rb>腰</rb><rt>こし</rt></ruby>をかがめた</span>。<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>知</rb><rt>し</rt></ruby>らぬ</span><span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>に<span><ruby><rb>礼</rb><rt>れい</rt></ruby></span>をされて<span><ruby><rb>驚</rb><rt>おどろ</rt></ruby>いた</span>というよりも、むしろ礼のしかたの<span><ruby><rb>巧</rb><rt>たく</rt></ruby>みな</span>のに驚いた。腰から上が、<span><ruby><rb>風</rb><rt>かぜ</rt></ruby></span>に<span><ruby><rb>乗</rb><rt>の</rt></ruby>る</span><span><ruby><rb>紙</rb><rt>かみ</rt></ruby></span>のように<span>ふわりと</span><span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>に<span><ruby><rb>落</rb><rt>お</rt></ruby>ちた</span>。しかも<span><ruby><rb>早</rb><rt>はや</rt></ruby>い</span>。それで、ある<span><ruby><rb>角度</rb><rt>かくど</rt></ruby></span>まで<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span><span><ruby><rb>苦</rb><rt>く</rt></ruby>もなく</span>はっきりととまった。むろん<span><ruby><rb>習</rb><rt>なら</rt></ruby>って</span><span><ruby><rb>覚</rb><rt>おぼ</rt></ruby>えた</span>ものではない。</p>
		<p>「ちょっと<span><ruby><rb>伺</rb><rt>うかが</rt></ruby>います</span>が……」と<span><ruby><rb>言</rb><rt>い</rt></ruby>う</span><span><ruby><rb>声</rb><rt>こえ</rt></ruby></span>が<span><ruby><rb>白</rb><rt>しろ</rt></ruby>い</span><span><ruby><rb>歯</rb><rt>は</rt></ruby></span>のあいだから<span><ruby><rb>出</rb><rt>で</rt></ruby>た</span>。<span>きりりとして</span>いる。しかし<span><ruby><rb>鷹揚</rb><rt>おうよう</rt></ruby></span>である。ただ<span><ruby><rb>夏</rb><rt>なつ</rt></ruby></span>の<span>さかり</span>に<span><ruby><rb>椎</rb><rt>しい</rt></ruby></span>の<span><ruby><rb>実</rb><rt>み</rt></ruby></span>がなっているかと<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>に<span><ruby><rb>聞</rb><rt>き</rt></ruby>きそう</span>には思われなかった。三四郎はそんな<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>に<span><ruby><rb>気</rb><rt>き</rt></ruby>のつく</span><span><ruby><rb>余裕</rb><rt>よゆう</rt></ruby></span>はない。</p>
		<p>「はあ」と言って<span><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>止</rb><rt>ど</rt></ruby>まった</span>。</p>
		<p>「<span><ruby><rb>十五</rb><rt>じゅうご</rt></ruby><ruby><rb>号室</rb><rt>ごうしつ</rt></ruby></span>はどの<span><ruby><rb>辺</rb><rt>へん</rt></ruby></span>になりましょう」</p>
		<p>十五号は三四郎が<span><ruby><rb>今</rb><rt>いま</rt></ruby></span><span><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た</span><span><ruby><rb>部屋</rb><rt>へや</rt></ruby></span>である。</p>
		<p>「<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さんの部屋ですか」</p>
		<p><span><ruby><rb>今度</rb><rt>こんど</rt></ruby></span>は女のほうが「はあ」と言う。</p>
		<p>「野々宮さんの部屋はね、その<span><ruby><rb>角</rb><rt>かど</rt></ruby></span>を<span><ruby><rb>曲</rb><rt>ま</rt></ruby>がって</span><span><ruby><rb>突</rb><rt>つ</rt></ruby>き<ruby><rb>当</rb><rt>あた</rt></ruby>って</span>、また<span><ruby><rb>左</rb><rt>ひだり</rt></ruby></span>へ曲がって、<span><ruby><rb>二番目</rb><rt>にばんめ</rt></ruby></span>の<span><ruby><rb>右側</rb><rt>みぎがわ</rt></ruby></span>です」</p>
		<p>「その角を……」と言いながら女は<span><ruby><rb>細</rb><rt>ほそ</rt></ruby>い</span><span><ruby><rb>指</rb><rt>ゆび</rt></ruby></span>を前へ出した。</p>
		<p>「ええ、ついその<span><ruby><rb>先</rb><rt>さき</rt></ruby></span>の角です」</p>
		<p>「どうもありがとう」</p>

		<h3 class="section">Rough translation</h3>
		<p>Today she had powdered her face lightly. However, she hadn't overdone it to where it masked her natural color. Her fine skin, which was just dark enough to hold its own against the sun's strong rays, was dusted with the finest trace of white. It was not a face that shone lustrously.</p>
		<p>Her flesh, both on her cheeks and her jaw, was perfectly taut. There was little on her bones in excess, yet there was a softness to her overall countenance. More than a softness of flesh, it seemed as though the bones themselves were soft. Her face impressed the observer as having great depth.</p>
		<p>The young lady bent forward in a bow. Sanshirō was surprised to be greeted by a stranger, but it was the artful nature of her greeting that most attracted his interest. Her upper body dropped lightly forward like fine paper floating on a breeze. And it was a quick motion. At a certain angle, she stopped herself precisely without effort. This was not a learned movement.</p> 
		<p>"I beg your pardon ..." Her voice flowed past white teeth. It was a crisp voice, but generous in its tone. It was hard to imagine it inquiring after acorns on an oak tree in the height of summer. Sanshirō was in no state to take notice of this point.</p>
		<p>"Yes." He replied, coming to a stop.</p>
		<p>"Do you know where I might find room 15?"</p>
		<p>15 was the room from which Sanshirō had just departed.</p>
		<p>"Miss Nonomiya's room?"</p>
		<p>This time the young lady, in turn, said "Yes."</p>
		<p>"For Miss Nonomiya's room, turn at that corner then take a left at the end of the hall. It's the second room on the right."</p>
		<p>"That corner ..." The young lady pointed with a slender finger as she spoke.</p>
		<p>"Yes, that corner just ahead there."</p>
		<p>"Thank you."</p>           

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>白</rb><rt>しろ</rt></ruby>い&nbsp;white</span><span class="vocabstudy"><ruby><rb>薄</rb><rt>うす</rt></ruby>く&nbsp;thinly; lightly</span><span class="vocabstudy"><ruby><rb>塗</rb><rt>ぬ</rt></ruby>って&nbsp;paint; apply (makeup)</span><span class="vocabstudy"><ruby><rb>本来</rb><rt>ほんらい</rt></ruby>の&nbsp;original; natural</span><span class="vocabstudy"><ruby><rb>地</rb><rt>じ</rt></ruby>&nbsp;ground; base (color)</span><span class="vocabstudy"><ruby><rb>隠</rb><rt>かく</rt></ruby>す&nbsp;hide; conceal</span><span class="vocabstudy"><ruby><rb>無趣味</rb><rt>むしゅみ</rt></ruby>&nbsp;lacking in refinement</span><span class="vocabstudy">こまやかな&nbsp;tender; fine</span><span class="vocabstudy"><ruby><rb>肉</rb><rt>にく</rt></ruby>&nbsp;flesh</span><span class="vocabstudy">ほどよく&nbsp;judiciously; to the proper degree</span><span class="vocabstudy"><ruby><rb>色</rb><rt>いろ</rt></ruby>づいて&nbsp;be colored</span><span class="vocabstudy"><ruby><rb>強</rb><rt>つよ</rt></ruby>い&nbsp;strong; intense</span><span class="vocabstudy"><ruby><rb>日光</rb><rt>ひ</rt></ruby>&nbsp;sunlight; sun's rays</span><span class="vocabstudy">めげない&nbsp;not succumb to</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>える&nbsp;appear</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;top of</span><span class="vocabstudy"><ruby><rb>粉</rb><rt>こ</rt></ruby>が<ruby><rb>吹</rb><rt>ふ</rt></ruby>いて&nbsp;be dusted with powder</span><span class="vocabstudy">てらてら&nbsp;lustrously; glossily</span><span class="vocabstudy"><ruby><rb>照</rb><rt>ひか</rt></ruby>る&nbsp;shine</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span>
		<span class="vocabstudy"><ruby><rb>頬</rb><rt>ほお</rt></ruby>&nbsp;cheek</span><span class="vocabstudy"><ruby><rb>顎</rb><rt>あご</rt></ruby>&nbsp;jaw</span><span class="vocabstudy">きちりと&nbsp;nicely; perfectly (= きっちりと)</span><span class="vocabstudy"><ruby><rb>締</rb><rt>し</rt></ruby>まって&nbsp;be firm; be taut</span><span class="vocabstudy"><ruby><rb>骨</rb><rt>ほね</rt></ruby>&nbsp;bones; frame</span><span class="vocabstudy"><ruby><rb>余</rb><rt>あま</rt></ruby>った&nbsp;excess</span><span class="vocabstudy">たんと&nbsp;a lot; very much (= たくさん)</span><span class="vocabstudy"><ruby><rb>全体</rb><rt>ぜんたい</rt></ruby>&nbsp;as a whole; overall</span><span class="vocabstudy"><ruby><rb>柔</rb><rt>やわら</rt></ruby>かい&nbsp;soft; tender</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>われる&nbsp;it seemed that ...</span><span class="vocabstudy"><ruby><rb>奥行</rb><rt>おくゆ</rt></ruby>きの<ruby><rb>長</rb><rt>なが</rt></ruby>い&nbsp;having depth</span><span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>じ&nbsp;feeling; impression</span><span class="vocabstudy"><ruby><rb>起</rb><rt>お</rt></ruby>こさせる&nbsp;stir; evoke</span>
		<span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;young lady</span><span class="vocabstudy"><ruby><rb>腰</rb><rt>こし</rt></ruby>をかがめた&nbsp;bowed (lit: bent at the waist)</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らぬ&nbsp;unknown; unfamiliar</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;person</span><span class="vocabstudy"><ruby><rb>礼</rb><rt>れい</rt></ruby>&nbsp;salutation</span><span class="vocabstudy"><ruby><rb>驚</rb><rt>おどろ</rt></ruby>いた&nbsp;be surprised</span><span class="vocabstudy"><ruby><rb>巧</rb><rt>たく</rt></ruby>みな&nbsp;skillful; artful</span><span class="vocabstudy"><ruby><rb>風</rb><rt>かぜ</rt></ruby>&nbsp;wind; breeze</span><span class="vocabstudy"><ruby><rb>乗</rb><rt>の</rt></ruby>る&nbsp;ride (on)</span><span class="vocabstudy"><ruby><rb>紙</rb><rt>かみ</rt></ruby>&nbsp;paper</span><span class="vocabstudy">ふわりと&nbsp;softly; lightly</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;forward</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちた&nbsp;fell; dropped</span><span class="vocabstudy"><ruby><rb>早</rb><rt>はや</rt></ruby>い&nbsp;simple; quick</span><span class="vocabstudy"><ruby><rb>角度</rb><rt>かくど</rt></ruby>&nbsp;angle</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;arrive (at)</span><span class="vocabstudy"><ruby><rb>苦</rb><rt>く</rt></ruby>もなく&nbsp;without difficulty</span><span class="vocabstudy"><ruby><rb>習</rb><rt>なら</rt></ruby>って&nbsp;be taught</span><span class="vocabstudy"><ruby><rb>覚</rb><rt>おぼ</rt></ruby>えた&nbsp;learned</span>
		<span class="vocabstudy"><ruby><rb>伺</rb><rt>うかが</rt></ruby>います&nbsp;ask; inquire</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;say; speak</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice</span><span class="vocabstudy"><ruby><rb>白</rb><rt>しろ</rt></ruby>い&nbsp;white</span><span class="vocabstudy"><ruby><rb>歯</rb><rt>は</rt></ruby>&nbsp;teeth</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;came forth (from)</span><span class="vocabstudy">きりりとして&nbsp;be tight; be crisp</span><span class="vocabstudy"><ruby><rb>鷹揚</rb><rt>おうよう</rt></ruby>&nbsp;large-hearted; generous</span><span class="vocabstudy"><ruby><rb>夏</rb><rt>なつ</rt></ruby>&nbsp;summer</span><span class="vocabstudy">さかり&nbsp;the height (of)</span><span class="vocabstudy"><ruby><rb>椎</rb><rt>しい</rt></ruby>&nbsp;chinquapin oak</span><span class="vocabstudy"><ruby><rb>実</rb><rt>み</rt></ruby>&nbsp;acorns</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;a person</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>きそう&nbsp;ask</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;fact; matter</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>のつく&nbsp;take notice (of)</span><span class="vocabstudy"><ruby><rb>余裕</rb><rt>よゆう</rt></ruby>&nbsp;composure; margin</span>
		<span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>止</rb><rt>ど</rt></ruby>まった&nbsp;came to a stop</span>
		<span class="vocabstudy"><ruby><rb>十五</rb><rt>じゅうご</rt></ruby><ruby><rb>号室</rb><rt>ごうしつ</rt></ruby>&nbsp;room number 15</span><span class="vocabstudy"><ruby><rb>辺</rb><rt>へん</rt></ruby>&nbsp;area; vicinity</span>
		<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; just now</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came out (of)</span><span class="vocabstudy"><ruby><rb>部屋</rb><rt>へや</rt></ruby>&nbsp;room</span>
		<span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span>
		<span class="vocabstudy"><ruby><rb>今度</rb><rt>こんど</rt></ruby>&nbsp;this time</span>
		<span class="vocabstudy"><ruby><rb>角</rb><rt>かど</rt></ruby>&nbsp;corner</span><span class="vocabstudy"><ruby><rb>曲</rb><rt>ま</rt></ruby>がって&nbsp;turn (a corner)</span><span class="vocabstudy"><ruby><rb>突</rb><rt>つ</rt></ruby>き<ruby><rb>当</rb><rt>あた</rt></ruby>って&nbsp;at the end</span><span class="vocabstudy"><ruby><rb>左</rb><rt>ひだり</rt></ruby>&nbsp;left</span><span class="vocabstudy"><ruby><rb>二番目</rb><rt>にばんめ</rt></ruby>&nbsp;the second (one)</span><span class="vocabstudy"><ruby><rb>右側</rb><rt>みぎがわ</rt></ruby>&nbsp;right side</span>
		<span class="vocabstudy"><ruby><rb>細</rb><rt>ほそ</rt></ruby>い&nbsp;slender</span><span class="vocabstudy"><ruby><rb>指</rb><rt>ゆび</rt></ruby>&nbsp;finger</span>
		<span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;ahead</span>

	</StudyGuide>
);
