// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={50}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>戸</rb><rt>と</rt></ruby></span>のうしろへ<span><ruby><rb>回</rb><rt>まわ</rt></ruby>って</span>、はじめて<span><ruby><rb>正面</rb><rt>しょうめん</rt></ruby></span>に<span><ruby><rb>向</rb><rt>む</rt></ruby>いた</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>、<span><ruby><rb>五十</rb><rt>ごじゅう</rt></ruby></span>あまりの<span><ruby><rb>婦人</rb><rt>ふじん</rt></ruby></span>が<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>に<span><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby></span>をした。この婦人は三四郎のからだがまだ<span><ruby><rb>扉</rb><rt>とびら</rt></ruby></span>の<span><ruby><rb>陰</rb><rt>かげ</rt></ruby></span>を<span><ruby><rb>出</rb><rt>で</rt></ruby>ない</span>まえから<span><ruby><rb>席</rb><rt>せき</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>って</span><span><ruby><rb>待</rb><rt>ま</rt></ruby>って</span>いたものとみえる。</p>
		<p>「<span><ruby><rb>小川</rb><rt>おがわ</rt></ruby></span>さんですか」と<span><ruby><rb>向</rb><rt>む</rt></ruby>こう</span>から<span><ruby><rb>尋</rb><rt>たず</rt></ruby>ねて</span>くれた。<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>は<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span><span><ruby><rb>君</rb><rt>くん</rt></ruby></span>に<span><ruby><rb>似</rb><rt>に</rt></ruby>て</span>いる。<span><ruby><rb>娘</rb><rt>むすめ</rt></ruby></span>にも似ている。しかしただ似ているというだけである。<span><ruby><rb>頼</rb><rt>たの</rt></ruby>まれた</span><span><ruby><rb>風呂敷包</rb><rt>ふろしきづつ</rt></ruby>み</span>を<span><ruby><rb>出</rb><rt>だ</rt></ruby>す</span>と、<span><ruby><rb>受</rb><rt>う</rt></ruby>け<ruby><rb>取</rb><rt>と</rt></ruby>って</span>、<span><ruby><rb>礼</rb><rt>れい</rt></ruby>を<ruby><rb>述</rb><rt>の</rt></ruby>べて</span>、</p>
		<p>「どうぞ」と言いながら<span><ruby><rb>椅子</rb><rt>いす</rt></ruby></span>をすすめたまま、<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>は<span><ruby><rb>寝台</rb><rt>ベッド</rt></ruby></span>の<span><ruby><rb>向</rb><rt>む</rt></ruby>こう<ruby><rb>側</rb><rt>がわ</rt></ruby></span>へ回った。</p>
		<p>寝台の<span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>に<span><ruby><rb>敷</rb><rt>し</rt></ruby>いた</span><span><ruby><rb>蒲団</rb><rt>ふとん</rt></ruby></span>を<span><ruby><rb>見</rb><rt>み</rt></ruby>る</span>と<span>まっ<ruby><rb>白</rb><rt>しろ</rt></ruby></span>である。上へ<span><ruby><rb>掛</rb><rt>か</rt></ruby>ける</span>ものもまっ白である。それを<span><ruby><rb>半分</rb><rt>はんぶん</rt></ruby></span>ほど<span><ruby><rb>斜</rb><rt>はす</rt></ruby>に</span><span>はぐって</span>、<span><ruby><rb>裾</rb><rt>すそ</rt></ruby></span>のほうが<span><ruby><rb>厚</rb><rt>あつ</rt></ruby>く</span>見えるところを、よけるように、<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は<span><ruby><rb>窓</rb><rt>まど</rt></ruby></span>を<span><ruby><rb>背</rb><rt>せ</rt></ruby>にして</span><span><ruby><rb>腰</rb><rt>こし</rt></ruby>をかけた</span>。<span><ruby><rb>足</rb><rt>あし</rt></ruby></span>は<span><ruby><rb>床</rb><rt>ゆか</rt></ruby></span>に<span><ruby><rb>届</rb><rt>とど</rt></ruby>かない</span>。<span><ruby><rb>手</rb><rt>て</rt></ruby></span>に<span><ruby><rb>編針</rb><rt>あみばり</rt></ruby></span>を<span><ruby><rb>持</rb><rt>も</rt></ruby>って</span>いる。<span><ruby><rb>毛糸</rb><rt>けいと</rt></ruby></span>のたまが寝台の<span><ruby><rb>下</rb><rt>した</rt></ruby></span>に<span><ruby><rb>転</rb><rt>ころ</rt></ruby>がった</span>。女の手から<span><ruby><rb>長</rb><rt>なが</rt></ruby>い</span><span><ruby><rb>赤</rb><rt>あか</rt></ruby>い</span><span><ruby><rb>糸</rb><rt>いと</rt></ruby></span>が<span><ruby><rb>筋</rb><rt>すじ</rt></ruby>を<ruby><rb>引</rb><rt>ひ</rt></ruby>いて</span>いる。三四郎は寝台の下から、毛糸のたまを<span><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>出</rb><rt>だ</rt></ruby>して</span>やろうかと<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>、けれども、女が毛糸にはまるで<span><ruby><rb>無頓着</rb><rt>むとんじゃく</rt></ruby></span>でいるので<span><ruby><rb>控</rb><rt>ひか</rt></ruby>えた</span>。</p>
		<p>おっかさんが向こう側から、しきりに<span><ruby><rb>昨夜</rb><rt>さくや</rt></ruby></span>の礼を述べる。<span>お<ruby><rb>忙</rb><rt>いそが</rt></ruby>しい</span>ところをなどと言う。三四郎は、いいえ、どうせ<span><ruby><rb>遊</rb><rt>あそ</rt></ruby>んで</span>いますからと言う。<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>が<span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>をしているあいだ、<span>よし<ruby><rb>子</rb><rt>こ</rt></ruby></span>は<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>いた。二人の話が<span><ruby><rb>切</rb><rt>き</rt></ruby>れた</span>時、<span><ruby><rb>突然</rb><rt>とつぜん</rt></ruby></span>、</p>
		<p>「ゆうべの<span><ruby><rb>轢死</rb><rt>れきし</rt></ruby></span>を<span><ruby><rb>御覧</rb><rt>ごらん</rt></ruby>になって</span>」と<span><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。見ると<span><ruby><rb>部屋</rb><rt>へや</rt></ruby></span>のすみに<span><ruby><rb>新聞</rb><rt>しんぶん</rt></ruby></span>がある。三四郎が、</p>
		<p>「ええ」と言う。</p>
		<p>「こわかったでしょう」と言いながら、<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span class="vocabstudy"><ruby><rb>首</rb><rt>くび</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>横</rb><rt>よこ</rt></ruby>に</span><span class="vocabstudy"><ruby><rb>曲</rb><rt>ま</rt></ruby>げて</span>、三四郎を見た。<span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby></span>に似て首の<span class="vocabstudy"><ruby><rb>長</rb><rt>なが</rt></ruby>い</span>女である。三四郎はこわいともこわくないとも<span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えずに</span>、女の首の曲がりぐあいをながめていた。半分は<span class="vocabstudy"><ruby><rb>質問</rb><rt>しつもん</rt></ruby></span>があまり<span class="vocabstudy"><ruby><rb>単純</rb><rt>たんじゅん</rt></ruby>な</span>ので、答に<span class="vocabstudy"><ruby><rb>窮</rb><rt>きゅう</rt></ruby>した</span>のである。半分は答えるのを<span class="vocabstudy"><ruby><rb>忘</rb><rt>わす</rt></ruby>れた</span>のである。女は<span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>がついた</span>とみえて、すぐ首をまっすぐにした。そうして<span class="vocabstudy"><ruby><rb>青白</rb><rt>あおじろ</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>頬</rb><rt>ほお</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>奥</rb><rt>おく</rt></ruby></span>を少し<span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>くした</span>。三四郎はもう<span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>る</span>べき<span class="vocabstudy"><ruby><rb>時間</rb><rt>じかん</rt></ruby></span>だと<span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えた</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>As he stepped around the door and fully entered the room, Sanshirō was greeted by an older lady of about fifty. It appeared that she had risen from her seat as soon as he'd cracked the door and was waiting to greet him.</p>
		<p>"Mr. Ogawa?" she asked him. Her face resembled both Nonomiya's and that of her daughter, but was otherwise unremarkable. Sanshirō presented the wrapped bundle with which he'd been entrusted. She thanked him and offered her chair, taking a new place for herself around by the bed.</p>
		<p>The mattress on the bed was pure white, as were the sheets and top covers. The covers had been folded back halfway at an angle, creating a thick edge on the far side. To avoid this thick edge, the young lady was sitting up on the near edge with her back to the window. Her feet did not reach the floor. she held knitting needles in her hands, and a ball of yarn had rolled under the bed. A long red line extended downward from her hands. Sanshirō thought to retrieve the yarn from under the bed for her, but she seemed unconcerned about it, so he refrained.</p>
		<p>From her place on the other side, the mother thanked him repeatedly for the previous evening when he was so busy. Sanshirō replied that it was nothing, as he had plenty of time on his hands.</p>
		<p>Yoshiko remained silent as the two of them talked. When their conversation ended she asked abruptly, "Did you see the death on the tracks last night?" Sanshirō noticed a newspaper in the corner of the room.</p>
		<p>"I did," he replied.</p>
		<p>"It must have been dreadful." As she spoke, she tilted her head to the side and looked at Sanshirō. She had a long neck like her brother. Sanshirō didn't say whether it was dreadful or not, but was focused rather on the way she tilted her head. Part of it was that her comment didn't require a response, and part of it was the distraction of her gesture. She noted his reaction and immediately straightened her neck. Within her pale cheeks, a mild blush arose. Sanshirō decided he should take his leave.</p>           

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>戸</rb><rt>と</rt></ruby>&nbsp;door</span><span class="vocabstudy"><ruby><rb>回</rb><rt>まわ</rt></ruby>って&nbsp;step around (to)</span><span class="vocabstudy"><ruby><rb>正面</rb><rt>しょうめん</rt></ruby>&nbsp;straight ahead; forward</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>いた&nbsp;faced</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>五十</rb><rt>ごじゅう</rt></ruby>&nbsp;fifty (years of age)</span><span class="vocabstudy"><ruby><rb>婦人</rb><rt>ふじん</rt></ruby>&nbsp;lady</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>&nbsp;greeting</span><span class="vocabstudy"><ruby><rb>扉</rb><rt>とびら</rt></ruby>&nbsp;door</span><span class="vocabstudy"><ruby><rb>陰</rb><rt>かげ</rt></ruby>&nbsp;shadow; shelter of</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>ない&nbsp;not be emerged (from)</span><span class="vocabstudy"><ruby><rb>席</rb><rt>せき</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;rise from one's seat</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>って&nbsp;wait</span>
		<span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby>&nbsp;Ogawa (Sanshirō's family name)</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう&nbsp;the other party</span><span class="vocabstudy"><ruby><rb>尋</rb><rt>たず</rt></ruby>ねて&nbsp;inquired</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>君</rb><rt>くん</rt></ruby>&nbsp;(suffix of familiarity for males)</span><span class="vocabstudy"><ruby><rb>似</rb><rt>に</rt></ruby>て&nbsp;resemble</span><span class="vocabstudy"><ruby><rb>娘</rb><rt>むすめ</rt></ruby>&nbsp;daughter</span><span class="vocabstudy"><ruby><rb>頼</rb><rt>たの</rt></ruby>まれた&nbsp;requested; entrusted</span><span class="vocabstudy"><ruby><rb>風呂敷包</rb><rt>ふろしきづつ</rt></ruby>み&nbsp;bundle wrapped with a furoshiki (carrying cloth)</span><span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>す&nbsp;take out; present</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>け<ruby><rb>取</rb><rt>と</rt></ruby>って&nbsp;receive; take possession of</span><span class="vocabstudy"><ruby><rb>礼</rb><rt>れい</rt></ruby>を<ruby><rb>述</rb><rt>の</rt></ruby>べて&nbsp;express one's thanks</span>
		<span class="vocabstudy"><ruby><rb>椅子</rb><rt>いす</rt></ruby>&nbsp;chair</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>寝台</rb><rt>ベッド</rt></ruby>&nbsp;bed</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう<ruby><rb>側</rb><rt>がわ</rt></ruby>&nbsp;other side; far side</span>
		<span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;top of</span><span class="vocabstudy"><ruby><rb>敷</rb><rt>し</rt></ruby>いた&nbsp;laid out; spread out</span><span class="vocabstudy"><ruby><rb>蒲団</rb><rt>ふとん</rt></ruby>&nbsp;futon; quilted mattress</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>る&nbsp;look at</span><span class="vocabstudy">まっ<ruby><rb>白</rb><rt>しろ</rt></ruby>&nbsp;pure white</span><span class="vocabstudy"><ruby><rb>掛</rb><rt>か</rt></ruby>ける&nbsp;spread</span><span class="vocabstudy"><ruby><rb>半分</rb><rt>はんぶん</rt></ruby>&nbsp;half</span><span class="vocabstudy"><ruby><rb>斜</rb><rt>はす</rt></ruby>に&nbsp;at an angle</span><span class="vocabstudy">はぐって&nbsp;turned down</span><span class="vocabstudy"><ruby><rb>裾</rb><rt>すそ</rt></ruby>&nbsp;skirt; edge</span><span class="vocabstudy"><ruby><rb>厚</rb><rt>あつ</rt></ruby>く&nbsp;thick</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;young lady</span><span class="vocabstudy"><ruby><rb>窓</rb><rt>まど</rt></ruby>&nbsp;window</span><span class="vocabstudy"><ruby><rb>背</rb><rt>せ</rt></ruby>にして&nbsp;turning one's back toward</span><span class="vocabstudy"><ruby><rb>腰</rb><rt>こし</rt></ruby>をかけた&nbsp;sat; was seated</span><span class="vocabstudy"><ruby><rb>足</rb><rt>あし</rt></ruby>&nbsp;feet</span><span class="vocabstudy"><ruby><rb>床</rb><rt>ゆか</rt></ruby>&nbsp;floor</span><span class="vocabstudy"><ruby><rb>届</rb><rt>とど</rt></ruby>かない&nbsp;didn't reach</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;hands</span><span class="vocabstudy"><ruby><rb>編針</rb><rt>あみばり</rt></ruby>&nbsp;knitting needles</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って&nbsp;hold; have</span><span class="vocabstudy"><ruby><rb>毛糸</rb><rt>けいと</rt></ruby>&nbsp;yarn</span><span class="vocabstudy"><ruby><rb>下</rb><rt>した</rt></ruby>&nbsp;below; beneath</span><span class="vocabstudy"><ruby><rb>転</rb><rt>ころ</rt></ruby>がった&nbsp;rolled</span><span class="vocabstudy"><ruby><rb>長</rb><rt>なが</rt></ruby>い&nbsp;long</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>い&nbsp;red</span><span class="vocabstudy"><ruby><rb>糸</rb><rt>いと</rt></ruby>&nbsp;yarn; string</span><span class="vocabstudy"><ruby><rb>筋</rb><rt>すじ</rt></ruby>を<ruby><rb>引</rb><rt>ひ</rt></ruby>いて&nbsp;drawing a line</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>出</rb><rt>だ</rt></ruby>して&nbsp;retrieve</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought (of doing)</span><span class="vocabstudy"><ruby><rb>無頓着</rb><rt>むとんじゃく</rt></ruby>&nbsp;indifferent; unconcerned</span><span class="vocabstudy"><ruby><rb>控</rb><rt>ひか</rt></ruby>えた&nbsp;refrained</span>
		<span class="vocabstudy"><ruby><rb>昨夜</rb><rt>さくや</rt></ruby>&nbsp;last night; the previous night</span><span class="vocabstudy">お<ruby><rb>忙</rb><rt>いそが</rt></ruby>しい&nbsp;busy</span><span class="vocabstudy"><ruby><rb>遊</rb><rt>あそ</rt></ruby>んで&nbsp;be idle; have time on one's hands</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;talk; conversation</span><span class="vocabstudy">よし<ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;Yoshiko (name of Nonomiya's younger sister)</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;remain quiet</span><span class="vocabstudy"><ruby><rb>切</rb><rt>き</rt></ruby>れた&nbsp;ended; broke off</span><span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>&nbsp;suddenly; abruptly</span>
		<span class="vocabstudy"><ruby><rb>轢死</rb><rt>れきし</rt></ruby>&nbsp;death on impact (by train or car)</span><span class="vocabstudy"><ruby><rb>御覧</rb><rt>ごらん</rt></ruby>になって&nbsp;see; witness</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span><span class="vocabstudy"><ruby><rb>部屋</rb><rt>へや</rt></ruby>&nbsp;room</span><span class="vocabstudy"><ruby><rb>新聞</rb><rt>しんぶん</rt></ruby>&nbsp;newspaper</span>
		<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>首</rb><rt>くび</rt></ruby>&nbsp;head; neck</span><span class="vocabstudy"><ruby><rb>横</rb><rt>よこ</rt></ruby>に&nbsp;to the side</span><span class="vocabstudy"><ruby><rb>曲</rb><rt>ま</rt></ruby>げて&nbsp;bent; inclined</span><span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;older brother</span><span class="vocabstudy"><ruby><rb>長</rb><rt>なが</rt></ruby>い&nbsp;long</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えずに&nbsp;without replying</span><span class="vocabstudy"><ruby><rb>質問</rb><rt>しつもん</rt></ruby>&nbsp;question</span><span class="vocabstudy"><ruby><rb>単純</rb><rt>たんじゅん</rt></ruby>な&nbsp;simple</span><span class="vocabstudy"><ruby><rb>窮</rb><rt>きゅう</rt></ruby>した&nbsp;be hard pressed; be at a loss</span><span class="vocabstudy"><ruby><rb>忘</rb><rt>わす</rt></ruby>れた&nbsp;forgot</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>がついた&nbsp;noticed; realized</span><span class="vocabstudy"><ruby><rb>青白</rb><rt>あおじろ</rt></ruby>い&nbsp;pale; pallid</span><span class="vocabstudy"><ruby><rb>頬</rb><rt>ほお</rt></ruby>&nbsp;cheeks</span><span class="vocabstudy"><ruby><rb>奥</rb><rt>おく</rt></ruby>&nbsp;interior; depths</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>くした&nbsp;reddened (blushed)</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>る&nbsp;return; take one's leave</span><span class="vocabstudy"><ruby><rb>時間</rb><rt>じかん</rt></ruby>&nbsp;time</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えた&nbsp;decided</span>

	</StudyGuide>
);
