// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={141}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「<span><ruby><rb>里見</rb><rt>さとみ</rt></ruby></span>の<span><ruby><rb>妹</rb><rt>いもうと</rt></ruby></span>の。どうも<span><ruby><rb>普通</rb><rt>ふつう</rt></ruby>の</span><span><ruby><rb>日本</rb><rt>にほん</rt></ruby></span>の<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>の<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>は<span><ruby><rb>歌麿</rb><rt>うたまろ</rt></ruby></span><span><ruby><rb>式</rb><rt>しき</rt></ruby></span>や<span><ruby><rb>何</rb><rt>なに</rt></ruby>か</span>ばかりで、<span><ruby><rb>西洋</rb><rt>せいよう</rt></ruby></span>の<span><ruby><rb>画布</rb><rt>カンバス</rt></ruby></span>にはうつりが<span><ruby><rb>悪</rb><rt>わる</rt></ruby>くって</span>いけないが、あの女や<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さんはいい。<span><ruby><rb>両方</rb><rt>りょうほう</rt></ruby>ともに</span><span><ruby><rb>絵</rb><rt>え</rt></ruby></span>になる。あの女が<span><ruby><rb>団扇</rb><rt>うちわ</rt></ruby></span>をかざして、<span><ruby><rb>木立</rb><rt>こだち</rt></ruby></span>をうしろに、<span><ruby><rb>明</rb><rt>あか</rt></ruby>るい</span><span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>を<span><ruby><rb>向</rb><rt>む</rt></ruby>いて</span>いるところを<span><ruby><rb>等身</rb><rt>ライフサイズ</rt></ruby></span>に<span><ruby><rb>写</rb><rt>うつ</rt></ruby>して</span>みようかしらと<span><ruby><rb>思</rb><rt>おも</rt></ruby>って</span>いる。西洋の<span><ruby><rb>扇</rb><rt>おうぎ</rt></ruby></span>は<span><ruby><rb>厭味</rb><rt>いやみ</rt></ruby></span>でいけないが、日本の団扇は<span><ruby><rb>新</rb><rt>あたら</rt></ruby>しくって</span>おもしろいだろう。とにかくはやくしないとだめだ。いまに<span><ruby><rb>嫁</rb><rt>よめ</rt></ruby></span>にでもいかれようものなら、そうこっちの<span><ruby><rb>自由</rb><rt>じゆ</rt></ruby></span>にいかなくなるかもしれないから」</p>
		<p><span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>多大</rb><rt>ただい</rt></ruby>な</span><span><ruby><rb>興味</rb><rt>きょうみ</rt></ruby></span>をもって<span><ruby><rb>原口</rb><rt>はらぐち</rt></ruby></span>の<span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>を<span><ruby><rb>聞</rb><rt>き</rt></ruby>いて</span>いた。ことに<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>が団扇をかざしている<span><ruby><rb>構図</rb><rt>こうず</rt></ruby></span>は<span><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>な</span><span><ruby><rb>感動</rb><rt>かんどう</rt></ruby></span>を三四郎に<span><ruby><rb>与</rb><rt>あた</rt></ruby>えた</span>。<span><ruby><rb>不思議</rb><rt>ふしぎ</rt></ruby>の</span><span><ruby><rb>因縁</rb><rt>いんえん</rt></ruby></span>が<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>の<span><ruby><rb>間</rb><rt>あいだ</rt></ruby></span>に<span><ruby><rb>存在</rb><rt>そんざい</rt></ruby>して</span>いるのではないかと思うほどであった。すると<span><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>が、「そんな<span><ruby><rb>図</rb><rt>ず</rt></ruby></span>はそうおもしろいこともないじゃないか」と<span><ruby><rb>無遠慮</rb><rt>むえんりょ</rt></ruby>な</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>を<span><ruby><rb>言</rb><rt>い</rt></ruby>いだした</span>。</p>
		<p>「でも<span><ruby><rb>当人</rb><rt>とうにん</rt></ruby></span>の<span><ruby><rb>希望</rb><rt>きぼう</rt></ruby></span>なんだもの。団扇をかざしているところは、どうでしょうと言うから、すこぶる<span><ruby><rb>妙</rb><rt>みょう</rt></ruby></span>でしょうと言って<span><ruby><rb>承知</rb><rt>しょうち</rt></ruby>した</span>のさ。なに、悪い<span><ruby><rb>図</rb><rt>ず</rt></ruby>どり</span>ではないよ。かきようにもよるが」</p>
		<p>「あんまり<span><ruby><rb>美</rb><rt>うつく</rt></ruby>しく</span>かくと、<span><ruby><rb>結婚</rb><rt>けっこん</rt></ruby></span>の<span><ruby><rb>申込</rb><rt>もうしこ</rt></ruby>み</span>が<span><ruby><rb>多</rb><rt>おお</rt></ruby>く</span>なって<span><ruby><rb>困</rb><rt>こま</rt></ruby>る</span>ぜ」</p>
		<p>「ハハハじゃ<span><ruby><rb>中</rb><rt>ちゅう</rt></ruby></span>ぐらいにかいておこう。結婚といえば、あの女も、もう嫁にゆく<span><ruby><rb>時期</rb><rt>じき</rt></ruby></span>だね。どうだろう、どこかいい<span><ruby><rb>口</rb><rt>くち</rt></ruby></span>はないだろうか。里見にも<span><ruby><rb>頼</rb><rt>たの</rt></ruby>まれて</span>いるんだが」</p>
		<p>「<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>もらっちゃどうだ」</p>
		<p>「ぼくか。ぼくでよければもらうが、どうもあの女には<span><ruby><rb>信用</rb><rt>しんよう</rt></ruby></span>がなくってね」</p>
		<p>「なぜ」</p>

		<h3 class="section">Rough translation</h3>
		<p>"Satomi's younger sister's. Most Japanese women have Utamaro-type faces or similar such looks, unfit for the Western canvas. But that young lady, or the Nonomiya girl for that matter, is different. I could paint either one of them. I'm thinking to do her in life size, with a stand of trees as the backdrop, holding up her round fan and turned toward the light. A folded Western fan would be garish, but a simple Japanese fan will be fresh and alluring. Anyway, I'll need to act soon. If she goes off as someone's bride then I won't get my chance with her."</p>
		<p>Sanshirō listened to Haraguchi with extreme interest. The thought of Mineko, and especially of Mineko holding her fan, aroused his deepest emotions. He wondered, even, if there wasn't some mystical bond between the two of them.</p> 
		<p>At this point, Professor Hirota interjected his blunt opinion. "Don't you think such a scene might not be rather dull?"</p>
		<p>"Actually, it's at her suggestion. She asked what I thought of her posing with her fan, and I agreed wholeheartedly. It's not a bad idea, provided I can do it justice."</p>
		<p>"Don't make her too attractive. She'll be hounded by suitors."</p>
		<p>"Ha ha. I'll tone her down to 'medium' appeal. Speaking of marriage, she's about that age, isn't she? What do you think? Know of any good prospects? Her brother's been asking."</p>
		<p>"Why not take her for yourself?"</p>
		<p>"Me? I'd take her if she'd have me, but I'm afraid she's soured on me."</p>
		<p>"Why?"</p>      

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>里見</rb><rt>さとみ</rt></ruby>&nbsp;Satomi (Mineko's family name)</span><span class="vocabstudy"><ruby><rb>妹</rb><rt>いもうと</rt></ruby>&nbsp;younger sister</span><span class="vocabstudy"><ruby><rb>普通</rb><rt>ふつう</rt></ruby>の&nbsp;ordinary; typical</span><span class="vocabstudy"><ruby><rb>日本</rb><rt>にほん</rt></ruby>&nbsp;Japan</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;woman</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>歌麿</rb><rt>うたまろ</rt></ruby>&nbsp;Kitagawa Utamaro (woodblock print artist in ukiyo-e genre; 1753-1806)</span><span class="vocabstudy"><ruby><rb>式</rb><rt>しき</rt></ruby>&nbsp;style</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>か&nbsp;something; some such thing</span><span class="vocabstudy"><ruby><rb>西洋</rb><rt>せいよう</rt></ruby>&nbsp;West; Occident</span><span class="vocabstudy"><ruby><rb>画布</rb><rt>カンバス</rt></ruby>&nbsp;(painting) canvas</span><span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>くって&nbsp;no good; unsatisfactory</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>両方</rb><rt>りょうほう</rt></ruby>ともに&nbsp;both (of them)</span><span class="vocabstudy"><ruby><rb>絵</rb><rt>え</rt></ruby>&nbsp;painting</span><span class="vocabstudy"><ruby><rb>団扇</rb><rt>うちわ</rt></ruby>&nbsp;(round) fan</span><span class="vocabstudy"><ruby><rb>木立</rb><rt>こだち</rt></ruby>&nbsp;grove of trees; stand of trees</span><span class="vocabstudy"><ruby><rb>明</rb><rt>あか</rt></ruby>るい&nbsp;light; bright</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>いて&nbsp;turn toward; face</span><span class="vocabstudy"><ruby><rb>等身</rb><rt>ライフサイズ</rt></ruby>&nbsp;life size</span><span class="vocabstudy"><ruby><rb>写</rb><rt>うつ</rt></ruby>して&nbsp;depict; reproduce</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>って&nbsp;think (to do)</span><span class="vocabstudy"><ruby><rb>扇</rb><rt>おうぎ</rt></ruby>&nbsp;folding fan</span><span class="vocabstudy"><ruby><rb>厭味</rb><rt>いやみ</rt></ruby>&nbsp;in bad taste; garish</span><span class="vocabstudy"><ruby><rb>新</rb><rt>あたら</rt></ruby>しくって&nbsp;fresh; novel</span><span class="vocabstudy"><ruby><rb>嫁</rb><rt>よめ</rt></ruby>&nbsp;bride</span><span class="vocabstudy"><ruby><rb>自由</rb><rt>じゆ</rt></ruby>&nbsp;liberty; as one wishes</span>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>多大</rb><rt>ただい</rt></ruby>な&nbsp;a great deal of</span><span class="vocabstudy"><ruby><rb>興味</rb><rt>きょうみ</rt></ruby>&nbsp;interest</span><span class="vocabstudy"><ruby><rb>原口</rb><rt>はらぐち</rt></ruby>&nbsp;Haraguchi (name)</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;talk</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;listen to</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>構図</rb><rt>こうず</rt></ruby>&nbsp;composition</span><span class="vocabstudy"><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>な&nbsp;unusual; extraordinary</span><span class="vocabstudy"><ruby><rb>感動</rb><rt>かんどう</rt></ruby>&nbsp;emotion; passion</span><span class="vocabstudy"><ruby><rb>与</rb><rt>あた</rt></ruby>えた&nbsp;aroused; evoked</span><span class="vocabstudy"><ruby><rb>不思議</rb><rt>ふしぎ</rt></ruby>の&nbsp;mysterious; mystical</span><span class="vocabstudy"><ruby><rb>因縁</rb><rt>いんえん</rt></ruby>&nbsp;bond; connection</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>間</rb><rt>あいだ</rt></ruby>&nbsp;between</span><span class="vocabstudy"><ruby><rb>存在</rb><rt>そんざい</rt></ruby>して&nbsp;exist</span><span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Professor Hirota</span><span class="vocabstudy"><ruby><rb>図</rb><rt>ず</rt></ruby>&nbsp;image; view; scene</span><span class="vocabstudy"><ruby><rb>無遠慮</rb><rt>むえんりょ</rt></ruby>な&nbsp;straight; blunt</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;matter; thing</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>いだした&nbsp;voiced</span>
		<span class="vocabstudy"><ruby><rb>当人</rb><rt>とうにん</rt></ruby>&nbsp;the person in question</span><span class="vocabstudy"><ruby><rb>希望</rb><rt>きぼう</rt></ruby>&nbsp;wish; preference</span><span class="vocabstudy"><ruby><rb>妙</rb><rt>みょう</rt></ruby>&nbsp;superb; excellent</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>した&nbsp;agreed</span><span class="vocabstudy"><ruby><rb>図</rb><rt>ず</rt></ruby>どり&nbsp;plan; layout</span>
		<span class="vocabstudy"><ruby><rb>美</rb><rt>うつく</rt></ruby>しく&nbsp;attractively</span><span class="vocabstudy"><ruby><rb>結婚</rb><rt>けっこん</rt></ruby>&nbsp;marriage</span><span class="vocabstudy"><ruby><rb>申込</rb><rt>もうしこ</rt></ruby>み&nbsp;overture; proposal</span><span class="vocabstudy"><ruby><rb>多</rb><rt>おお</rt></ruby>く&nbsp;many; numerous</span><span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>る&nbsp;be in trouble; be in a bind</span>
		<span class="vocabstudy"><ruby><rb>中</rb><rt>ちゅう</rt></ruby>&nbsp;medium; average</span><span class="vocabstudy"><ruby><rb>時期</rb><rt>じき</rt></ruby>&nbsp;time; season</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>&nbsp;opening; prospect</span><span class="vocabstudy"><ruby><rb>頼</rb><rt>たの</rt></ruby>まれて&nbsp;be requested</span>
		<span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you</span>
		<span class="vocabstudy"><ruby><rb>信用</rb><rt>しんよう</rt></ruby>&nbsp;reputation; credibility</span>

	</StudyGuide>
);
