// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Botchan' num={116}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>翌日</rb><rt>あくるひ</rt></ruby></span>おれは<span><ruby><rb>学校</rb><rt>がっこう</rt></ruby></span>へ<span><ruby><rb>出</rb><rt>で</rt></ruby>て</span><span><ruby><rb>校長室</rb><rt>こうちょうしつ</rt></ruby></span>へ<span><ruby><rb>入</rb><rt>はい</rt></ruby>って</span><span><ruby><rb>談判</rb><rt>だんぱん</rt></ruby></span>を<span><ruby><rb>始</rb><rt>はじ</rt></ruby>めた</span>。</p>
		<p>「<span><ruby><rb>何</rb><rt>なん</rt></ruby>で</span><span><ruby><rb>私</rb><rt>わたし</rt></ruby></span>に<span><ruby><rb>辞表</rb><rt>じひょう</rt></ruby></span>を<span><ruby><rb>出</rb><rt>だ</rt></ruby>せ</span>と<span><ruby><rb>云</rb><rt>い</rt></ruby>わない</span>んですか」</p>
		<p>「へえ？」と<span><ruby><rb>狸</rb><rt>たぬき</rt></ruby></span>は<span>あっけに<ruby><rb>取</rb><rt>と</rt></ruby>られて</span>いる。</p>
		<p>「<span><ruby><rb>堀田</rb><rt>ほった</rt></ruby></span>には出せ、私には出さないで<span><ruby><rb>好</rb><rt>い</rt></ruby>い</span>と云う<span><ruby><rb>法</rb><rt>ほう</rt></ruby>がありますか</span>」</p>
		<p>「それは学校の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>の<span><ruby><rb>都合</rb><rt>つごう</rt></ruby></span>で……」</p>
		<p>「その都合が<span><ruby><rb>間違</rb><rt>まちが</rt></ruby>ってまさあ</span>。私が出さなくって<span><ruby><rb>済</rb><rt>す</rt></ruby>む</span>なら堀田だって、出す<span><ruby><rb>必要</rb><rt>ひつよう</rt></ruby></span>はないでしょう」</p>
		<p>「<span>その<ruby><rb>辺</rb><rt>へん</rt></ruby></span>は<span><ruby><rb>説明</rb><rt>せつめい</rt></ruby></span>が<span><ruby><rb>出来</rb><rt>でき</rt></ruby>かねます</span>が――堀田君は<span><ruby><rb>去</rb><rt>さ</rt></ruby>られて</span>もやむをえんのですが、あなたは辞表をお出しになる必要を<span><ruby><rb>認</rb><rt>みと</rt></ruby>めません</span>から」</p>
		<p>なるほど狸だ、<span><ruby><rb>要領</rb><rt>ようりょう</rt></ruby>を<ruby><rb>得</rb><rt>え</rt></ruby>ない</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>ばかり<span><ruby><rb>並</rb><rt>なら</rt></ruby>べて</span>、しかも<span><ruby><rb>落</rb><rt>お</rt></ruby>ち<ruby><rb>付</rb><rt>つ</rt></ruby>き<ruby><rb>払</rb><rt>はら</rt></ruby>って</span>る。おれは<span><ruby><rb>仕様</rb><rt>しよう</rt></ruby>がない</span>から</p>
		<p>「それじゃ私も辞表を出しましょう。堀田<span><ruby><rb>君</rb><rt>くん</rt></ruby></span><span><ruby><rb>一人</rb><rt>ひとり</rt></ruby></span><span><ruby><rb>辞職</rb><rt>じしょく</rt></ruby></span>させて、私が<span><ruby><rb>安閑</rb><rt>あんかん</rt></ruby>として</span>、<span><ruby><rb>留</rb><rt>とど</rt></ruby>まって</span>いられると<span><ruby><rb>思</rb><rt>おも</rt></ruby>って</span>いらっしゃる<span>かも<ruby><rb>知</rb><rt>し</rt></ruby>れない</span>が、私にはそんな<span><ruby><rb>不人情</rb><rt>ふにんじょう</rt></ruby>な</span>事は出来ません」</p>
		<p>「それは<span><ruby><rb>困</rb><rt>こま</rt></ruby>る</span>。堀田も去りあなたも去ったら、学校の<span><ruby><rb>数学</rb><rt>すうがく</rt></ruby></span>の<span><ruby><rb>授業</rb><rt>じゅぎょう</rt></ruby></span>がまるで出来なくなってしまうから……」</p>
		<p>「出来なくなっても私の<span><ruby><rb>知</rb><rt>し</rt></ruby>った</span>事じゃありません」</p>
		<p>「君そう<span><ruby><rb>我儘</rb><rt>わがまま</rt></ruby></span>を云うものじゃない、<span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span>は学校の<span><ruby><rb>事情</rb><rt>じじょう</rt></ruby></span>も<span><ruby><rb>察</rb><rt>さっ</rt></ruby>して</span>くれなくっちゃ困る。それに、<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span>から<span><ruby><rb>一月</rb><rt>いっかげつ</rt></ruby></span><span><ruby><rb>立</rb><rt>た</rt></ruby>つ</span>か立たないのに辞職したと云うと、君の<span><ruby><rb>将来</rb><rt>しょうらい</rt></ruby></span>の<span><ruby><rb>履歴</rb><rt>りれき</rt></ruby></span>に<span><ruby><rb>関係</rb><rt>かんけい</rt></ruby>する</span>から、その辺も少しは<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えたら</span>いいでしょう」</p>
		<p>「履歴なんか<span><ruby><rb>構</rb><rt>かま</rt></ruby>う</span>もんですか、履歴より<span><ruby><rb>義理</rb><rt>ぎり</rt></ruby></span>が<span><ruby><rb>大切</rb><rt>たいせつ</rt></ruby></span>です」</p>
		<p>「そりゃごもっとも――君の云うところは<span><ruby><rb>一々</rb><rt>いちいち</rt></ruby></span>ごもっともだが、わたしの云う方も少しは察して<span><ruby><rb>下</rb><rt>くだ</rt></ruby>さい</span>。君が<span><ruby><rb>是非</rb><rt>ぜひ</rt></ruby></span>辞職すると云うなら辞職されてもいいから、<span><ruby><rb>代</rb><rt>かわ</rt></ruby>り</span>のあるまでどうかやってもらいたい。とにかく、うちで<span>もう<ruby><rb>一返</rb><rt>いっぺん</rt></ruby></span><span><ruby><rb>考</rb><rt>かんが</rt></ruby>え<ruby><rb>直</rb><rt>なお</rt></ruby>して</span>みて下さい」</p>
		<p>考え直すって、直しようのない<span><ruby><rb>明々白々</rb><rt>めいめいはくはく</rt></ruby>たる</span><span><ruby><rb>理由</rb><rt>りゆ</rt></ruby></span>だが、狸が<span><ruby><rb>蒼</rb><rt>あお</rt></ruby>くなったり</span>、<span><ruby><rb>赤</rb><rt>あか</rt></ruby>くなったり</span>して、<span><ruby><rb>可愛想</rb><rt>かわいそう</rt></ruby></span>になったからひとまず考え直す事として<span><ruby><rb>引</rb><rt>ひ</rt></ruby>き<ruby><rb>下</rb><rt>さ</rt></ruby>がった</span>。<span><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ</span>には<span><ruby><rb>口</rb><rt>くち</rt></ruby>もきかなかった</span>。どうせ<span><ruby><rb>遣</rb><rt>や</rt></ruby>っつける</span>なら<span><ruby><rb>塊</rb><rt>かた</rt></ruby>めて</span>、うんと遣っつける方がいい。</p>
		<p><span><ruby><rb>山嵐</rb><rt>やまあらし</rt></ruby></span>に狸と談判した<span><ruby><rb>模様</rb><rt>もよう</rt></ruby></span>を<span><ruby><rb>話</rb><rt>はな</rt></ruby>したら</span>、<span><ruby><rb>大方</rb><rt>おおかた</rt></ruby></span>そんな事だろうと思った。辞表の事はいざとなるまでそのままにしておいても<span><ruby><rb>差支</rb><rt>さしつか</rt></ruby>え</span>あるまいとの<span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>だったから、山嵐の云う<span><ruby><rb>通</rb><rt>とお</rt></ruby>り</span>にした。どうも山嵐の方がおれよりも<span><ruby><rb>利巧</rb><rt>りこう</rt></ruby></span>らしいから<span><ruby><rb>万事</rb><rt>ばんじ</rt></ruby></span>山嵐の<span><ruby><rb>忠告</rb><rt>ちゅうこく</rt></ruby></span>に<span><ruby><rb>従</rb><rt>したが</rt></ruby>う</span>事にした。</p>

		<h3 class="section">Rough translation</h3>
		<p>The next day I arrived at the school and went straight to the principal's office.</p>
		<p>"Why wasn't I asked to tender my resignation?"</p>
		<p>"Huh?" Tanuki seemed caught off guard.</p>
		<p>"How is it possible that Hotta has to resign and I don't?"</p>
		<p>"Circumstances at the school dictate that ..."</p>
		<p>"Those circumstances are in error. If my resignation's not required, then neither is Hotta's."</p>
		<p>"I don't know that I can explain it -- it's necessary that Hotta leave, but I see no need to ask for your resignation."</p>
		<p>It was just like Tanuki to maintain his composure and dish out convoluted logic. He left me with no alternative.</p>
		<p>"In that case, I'll bring you my letter of resignation as well. You shouldn't imagine that I can sit idly by as Hotta alone is dismissed. I'm not so coldhearted."</p>
		<p>"I can't allow that. If Hotta leaves and you leave, we'll have no mathematics instructor at the school."</p>
		<p>"Then have no mathematics. See if I care."</p>
		<p>"Don't be so self-centered. Give some thought to the school's circumstances. And consider your own future. How will it look on your resumé if you resign after only a month?"</p>
		<p>"What do I care how it looks? I won't shirk my obligations in favor of my resumé."</p>
		<p>"You're quite right about that -- each of your points in itself is correct, but try to understand my position too. If you're intent on resigning then I can't stand in your way, but I ask that you at least stay on until a replacement arrives. Please go home and think things over once more."</p>
		<p>My reasons were clear as day, and there was nothing to reconsider. However, Tanuki cut a pitiful figure as he alternately turned pale and flushed red. I agreed to give it further thought and took my leave. I did not speak with Red Shirt. Best to let him have it full force when the time was right.</p>
		<p>I told Yama Arashi of my discussion with Tanuki, and he indicated that the situation was as he had thought. He pointed out that I could tender my resignation at any time and suggested I should hold off for now. I decided to accept his counsel. Yama Arashi was wiser about the world than I was, so I thought it best to adhere to his guidance from then on.</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>翌日</rb><rt>あくるひ</rt></ruby>&nbsp;the next day</span><span class="vocabstudy"><ruby><rb>学校</rb><rt>がっこう</rt></ruby>&nbsp;school</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て&nbsp;arrived (at)</span><span class="vocabstudy"><ruby><rb>校長室</rb><rt>こうちょうしつ</rt></ruby>&nbsp;principal's office</span><span class="vocabstudy"><ruby><rb>入</rb><rt>はい</rt></ruby>って&nbsp;entered</span><span class="vocabstudy"><ruby><rb>談判</rb><rt>だんぱん</rt></ruby>&nbsp;discussion; debate</span><span class="vocabstudy"><ruby><rb>始</rb><rt>はじ</rt></ruby>めた&nbsp;began</span>
		<span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>で&nbsp;why</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>&nbsp;me</span><span class="vocabstudy"><ruby><rb>辞表</rb><rt>じひょう</rt></ruby>&nbsp;letter of resignation</span><span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>せ&nbsp;present; submit</span><span class="vocabstudy"><ruby><rb>云</rb><rt>い</rt></ruby>わない&nbsp;not request</span>
		<span class="vocabstudy"><ruby><rb>狸</rb><rt>たぬき</rt></ruby>&nbsp;Tanuki (nickname for the school principal)</span><span class="vocabstudy">あっけに<ruby><rb>取</rb><rt>と</rt></ruby>られて&nbsp;be surprised; be taken aback</span>
		<span class="vocabstudy"><ruby><rb>堀田</rb><rt>ほった</rt></ruby>&nbsp;Hotta (a.k.a. Yama Arashi)</span><span class="vocabstudy"><ruby><rb>好</rb><rt>い</rt></ruby>い&nbsp;fine; okay</span><span class="vocabstudy"><ruby><rb>法</rb><rt>ほう</rt></ruby>がありますか&nbsp;how can it possibly be that ...</span>
		<span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;side; direction</span><span class="vocabstudy"><ruby><rb>都合</rb><rt>つごう</rt></ruby>&nbsp;circumstances</span>
		<span class="vocabstudy"><ruby><rb>間違</rb><rt>まちが</rt></ruby>ってまさあ&nbsp;in the wrong; mistaken</span><span class="vocabstudy"><ruby><rb>済</rb><rt>す</rt></ruby>む&nbsp;be resolved; be settled</span><span class="vocabstudy"><ruby><rb>必要</rb><rt>ひつよう</rt></ruby>&nbsp;necessity</span>
		<span class="vocabstudy">その<ruby><rb>辺</rb><rt>へん</rt></ruby>&nbsp;on that matter</span><span class="vocabstudy"><ruby><rb>説明</rb><rt>せつめい</rt></ruby>&nbsp;explanation</span><span class="vocabstudy"><ruby><rb>出来</rb><rt>でき</rt></ruby>かねます&nbsp;can't provide</span><span class="vocabstudy"><ruby><rb>去</rb><rt>さ</rt></ruby>られて&nbsp;be separated; leave</span><span class="vocabstudy"><ruby><rb>認</rb><rt>みと</rt></ruby>めません&nbsp;do not accept; will not acknowledge</span>
		<span class="vocabstudy"><ruby><rb>要領</rb><rt>ようりょう</rt></ruby>を<ruby><rb>得</rb><rt>え</rt></ruby>ない&nbsp;senseless; incomprehensible</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;facts; things</span><span class="vocabstudy"><ruby><rb>並</rb><rt>なら</rt></ruby>べて&nbsp;lay out; set forth</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ち<ruby><rb>付</rb><rt>つ</rt></ruby>き<ruby><rb>払</rb><rt>はら</rt></ruby>って&nbsp;maintain perfect composure</span><span class="vocabstudy"><ruby><rb>仕様</rb><rt>しよう</rt></ruby>がない&nbsp;be left with no alternative</span>
		<span class="vocabstudy"><ruby><rb>君</rb><rt>くん</rt></ruby>&nbsp;(suffix of familiarity for males)</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>&nbsp;alone; by oneself</span><span class="vocabstudy"><ruby><rb>辞職</rb><rt>じしょく</rt></ruby>&nbsp;resignation</span><span class="vocabstudy"><ruby><rb>安閑</rb><rt>あんかん</rt></ruby>として&nbsp;sit idly by</span><span class="vocabstudy"><ruby><rb>留</rb><rt>とど</rt></ruby>まって&nbsp;stay behind; continue on (in one's present position)</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>って&nbsp;think</span><span class="vocabstudy">かも<ruby><rb>知</rb><rt>し</rt></ruby>れない&nbsp;it may be that ...</span><span class="vocabstudy"><ruby><rb>不人情</rb><rt>ふにんじょう</rt></ruby>な&nbsp;unkind; coldhearted</span>
		<span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>る&nbsp;be in a bind; be troubled</span><span class="vocabstudy"><ruby><rb>数学</rb><rt>すうがく</rt></ruby>&nbsp;mathematics</span><span class="vocabstudy"><ruby><rb>授業</rb><rt>じゅぎょう</rt></ruby>&nbsp;class; instruction</span>
		<span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>る&nbsp;be in a bind; be troubled</span><span class="vocabstudy"><ruby><rb>数学</rb><rt>すうがく</rt></ruby>&nbsp;mathematics</span><span class="vocabstudy"><ruby><rb>授業</rb><rt>じゅぎょう</rt></ruby>&nbsp;class; instruction</span>
		<span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>った&nbsp;know of; care about</span>
		<span class="vocabstudy"><ruby><rb>我儘</rb><rt>わがまま</rt></ruby>&nbsp;selfishness; waywardness</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>事情</rb><rt>じじょう</rt></ruby>&nbsp;circumstances</span><span class="vocabstudy"><ruby><rb>察</rb><rt>さっ</rt></ruby>して&nbsp;consider; understand</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;came; arrived</span><span class="vocabstudy"><ruby><rb>一月</rb><rt>いっかげつ</rt></ruby>&nbsp;one month (usually <ruby><rb>一ヶ月</rb><rt>いっかげつ</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>つ&nbsp;pass (time)</span><span class="vocabstudy"><ruby><rb>将来</rb><rt>しょうらい</rt></ruby>&nbsp;future</span><span class="vocabstudy"><ruby><rb>履歴</rb><rt>りれき</rt></ruby>&nbsp;one's resumé</span><span class="vocabstudy"><ruby><rb>関係</rb><rt>かんけい</rt></ruby>する&nbsp;affect; reflect (on)</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えたら&nbsp;consider</span>
		<span class="vocabstudy"><ruby><rb>構</rb><rt>かま</rt></ruby>う&nbsp;care about</span><span class="vocabstudy"><ruby><rb>義理</rb><rt>ぎり</rt></ruby>&nbsp;duty; obligation</span><span class="vocabstudy"><ruby><rb>大切</rb><rt>たいせつ</rt></ruby>&nbsp;important</span>
		<span class="vocabstudy"><ruby><rb>一々</rb><rt>いちいち</rt></ruby>&nbsp;one by one; point by point</span><span class="vocabstudy"><ruby><rb>下</rb><rt>くだ</rt></ruby>さい&nbsp;please ...</span><span class="vocabstudy"><ruby><rb>是非</rb><rt>ぜひ</rt></ruby>&nbsp;of necessity; in any case</span><span class="vocabstudy"><ruby><rb>代</rb><rt>かわ</rt></ruby>り&nbsp;replacement</span><span class="vocabstudy">もう<ruby><rb>一返</rb><rt>いっぺん</rt></ruby>&nbsp;one more time</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>え<ruby><rb>直</rb><rt>なお</rt></ruby>して&nbsp;reconsider</span>
		<span class="vocabstudy"><ruby><rb>明々白々</rb><rt>めいめいはくはく</rt></ruby>たる&nbsp;obvious; clear as day</span><span class="vocabstudy"><ruby><rb>理由</rb><rt>りゆ</rt></ruby>&nbsp;reason; grounds</span><span class="vocabstudy"><ruby><rb>蒼</rb><rt>あお</rt></ruby>くなったり&nbsp;turning pale</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>くなったり&nbsp;turning red; becoming flushed</span><span class="vocabstudy"><ruby><rb>可愛想</rb><rt>かわいそう</rt></ruby>&nbsp;pitiable</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>き<ruby><rb>下</rb><rt>さ</rt></ruby>がった&nbsp;took leave; withdrew</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ&nbsp;Red Shirt (nickname for the head teacher)</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>もきかなかった&nbsp;didn't talk to</span><span class="vocabstudy"><ruby><rb>遣</rb><rt>や</rt></ruby>っつける&nbsp;criticize; attack</span><span class="vocabstudy"><ruby><rb>塊</rb><rt>かた</rt></ruby>めて&nbsp;bunched together; all at once</span>
		<span class="vocabstudy"><ruby><rb>山嵐</rb><rt>やまあらし</rt></ruby>&nbsp;Yama Arashi (nickname for Hotta, the head mathematics teacher)</span><span class="vocabstudy"><ruby><rb>模様</rb><rt>もよう</rt></ruby>&nbsp;gist; tone</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>したら&nbsp;explained; conveyed</span><span class="vocabstudy"><ruby><rb>大方</rb><rt>おおかた</rt></ruby>&nbsp;probably; likely</span><span class="vocabstudy"><ruby><rb>差支</rb><rt>さしつか</rt></ruby>え&nbsp;hindrance; inconvenience</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;response; opinion</span><span class="vocabstudy"><ruby><rb>通</rb><rt>とお</rt></ruby>り&nbsp;exactly as</span><span class="vocabstudy"><ruby><rb>利巧</rb><rt>りこう</rt></ruby>&nbsp;clever; savvy</span><span class="vocabstudy"><ruby><rb>万事</rb><rt>ばんじ</rt></ruby>&nbsp;all things; everything</span><span class="vocabstudy"><ruby><rb>忠告</rb><rt>ちゅうこく</rt></ruby>&nbsp;advice; counsel</span><span class="vocabstudy"><ruby><rb>従</rb><rt>したが</rt></ruby>う&nbsp;follow; adhere to</span>

	</StudyGuide>
);
