// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Botchan' num={122}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>おれが<span><ruby><rb>玉子</rb><rt>たまご</rt></ruby></span>をたたきつけているうち、<span><ruby><rb>山嵐</rb><rt>やまあらし</rt></ruby></span>と<span><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ</span>はまだ<span><ruby><rb>談判</rb><rt>だんぱん</rt></ruby></span><span><ruby><rb>最中</rb><rt>さいちゅう</rt></ruby></span>である。</p>
		<p>「<span><ruby><rb>芸者</rb><rt>げいしゃ</rt></ruby></span>をつれて<span><ruby><rb>僕</rb><rt>ぼく</rt></ruby></span>が<span><ruby><rb>宿屋</rb><rt>やどや</rt></ruby></span>へ<span><ruby><rb>泊</rb><rt>とま</rt></ruby>った</span><span>と<ruby><rb>云</rb><rt>い</rt></ruby>う</span><span><ruby><rb>証拠</rb><rt>しょうこ</rt></ruby></span>がありますか」</p>
		<p>「<span><ruby><rb>宵</rb><rt>よい</rt></ruby></span>に<span><ruby><rb>貴様</rb><rt>きさま</rt></ruby></span>のなじみの芸者が<span><ruby><rb>角屋</rb><rt>かどや</rt></ruby></span>へはいったのを<span><ruby><rb>見</rb><rt>み</rt></ruby>て</span>云う<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>だ。<span><ruby><rb>胡魔化</rb><rt>ごまか</rt></ruby>せる</span>ものか」</p>
		<p>「胡魔化す<span><ruby><rb>必要</rb><rt>ひつよう</rt></ruby></span>はない。僕は<span><ruby><rb>吉川</rb><rt>よしかわ</rt></ruby></span><span><ruby><rb>君</rb><rt>くん</rt></ruby></span>と<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>で泊ったのである。芸者が宵にはいろうが、はいるまいが、僕の<span><ruby><rb>知</rb><rt>し</rt></ruby>った</span>事ではない」</p>
		<p>「だまれ」と山嵐は<span><ruby><rb>拳骨</rb><rt>げんこつ</rt></ruby></span>を<span><ruby><rb>食</rb><rt>く</rt></ruby>わした</span>。赤シャツはよろよろしたが「これは<span><ruby><rb>乱暴</rb><rt>らんぼう</rt></ruby></span>だ、<span><ruby><rb>狼藉</rb><rt>ろうぜき</rt></ruby></span>である。<span><ruby><rb>理非</rb><rt>りひ</rt></ruby></span>を<span><ruby><rb>弁</rb><rt>べん</rt></ruby>じないで</span><span><ruby><rb>腕力</rb><rt>わんりょく</rt></ruby></span><span>に<ruby><rb>訴</rb><rt>うった</rt></ruby>える</span>のは<span><ruby><rb>無法</rb><rt>むほう</rt></ruby></span>だ」</p>
		<p>「無法でたくさんだ」とまた<span>ぽかりと<ruby><rb>撲</rb><rt>な</rt></ruby>ぐる</span>。「貴様のような<span><ruby><rb>奸物</rb><rt>かんぶつ</rt></ruby></span>はなぐらなくっちゃ、<span><ruby><rb>答</rb><rt>こた</rt></ruby>えない</span>んだ」とぽかぽかなぐる。おれも<span><ruby><rb>同時</rb><rt>どうじ</rt></ruby>に</span><span><ruby><rb>野</rb><rt>の</rt></ruby>だ</span>を<span><ruby><rb>散々</rb><rt>さんざん</rt></ruby>に</span><span><ruby><rb>擲</rb><rt>たた</rt></ruby>き<ruby><rb>据</rb><rt>す</rt></ruby>えた</span>。しまいには二人とも<span><ruby><rb>杉</rb><rt>すぎ</rt></ruby></span>の<span><ruby><rb>根方</rb><rt>ねかた</rt></ruby></span>にうずくまって<span><ruby><rb>動</rb><rt>うご</rt></ruby>けない</span>のか、<span><ruby><rb>眼</rb><rt>め</rt></ruby>がちらちらする</span>のか<span><ruby><rb>逃</rb><rt>に</rt></ruby>げよう</span>ともしない。</p>
		<p>「もうたくさんか、たくさんでなけりゃ、まだ<span><ruby><rb>撲</rb><rt>なぐ</rt></ruby>って</span>やる」とぽかんぽかんと<span><ruby><rb>両人</rb><rt>ふたり</rt></ruby></span>でなぐったら「もうたくさんだ」と云った。野だに「貴様もたくさんか」と<span><ruby><rb>聞</rb><rt>き</rt></ruby>いたら</span>「<span><ruby><rb>無論</rb><rt>むろん</rt></ruby></span>たくさんだ」と<span><ruby><rb>答</rb><rt>こた</rt></ruby>えた</span>。</p>
		<p>「<span><ruby><rb>貴様等</rb><rt>きさまら</rt></ruby></span>は奸物だから、こうやって<span><ruby><rb>天誅</rb><rt>てんちゅう</rt></ruby></span>を<span><ruby><rb>加</rb><rt>くわ</rt></ruby>える</span>んだ。これに<span><ruby><rb>懲</rb><rt>こ</rt></ruby>りて</span><span><ruby><rb>以来</rb><rt>いらい</rt></ruby></span><span>つつしむ</span>がいい。いくら<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span><span><ruby><rb>巧</rb><rt>たく</rt></ruby>みに</span><span><ruby><rb>弁解</rb><rt>べんかい</rt></ruby></span>が<span><ruby><rb>立</rb><rt>た</rt></ruby>って</span>も<span><ruby><rb>正義</rb><rt>せいぎ</rt></ruby></span>は<span><ruby><rb>許</rb><rt>ゆる</rt></ruby>さん</span>ぞ」と山嵐が云ったら<span><ruby><rb>両人共</rb><rt>ふたりとも</rt></ruby></span>だまっていた。ことによると<span><ruby><rb>口</rb><rt>くち</rt></ruby>をきく</span>のが<span><ruby><rb>退儀</rb><rt>たいぎ</rt></ruby></span>なの<span>かも<ruby><rb>知</rb><rt>し</rt></ruby>れない</span>。</p>
		<p>「おれは<span><ruby><rb>逃</rb><rt>に</rt></ruby>げ</span>も<span><ruby><rb>隠</rb><rt>かく</rt></ruby>れ</span>もせん。<span><ruby><rb>今夜</rb><rt>こんや</rt></ruby></span><span><ruby><rb>五時</rb><rt>ごじ</rt></ruby></span>までは<span><ruby><rb>浜</rb><rt>はま</rt></ruby></span>の<span><ruby><rb>港屋</rb><rt>みなとや</rt></ruby></span>に<span><ruby><rb>居</rb><rt>い</rt></ruby>る</span>。<span><ruby><rb>用</rb><rt>よう</rt></ruby></span>があるなら<span><ruby><rb>巡査</rb><rt>じゅんさ</rt></ruby></span>なりなんなり、よこせ」と山嵐が云うから、おれも「おれも逃げも隠れもしないぞ。<span><ruby><rb>堀田</rb><rt>ほった</rt></ruby></span>と<span><ruby><rb>同</rb><rt>おな</rt></ruby>じ</span><span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>に<span><ruby><rb>待</rb><rt>ま</rt></ruby>って</span>るから<span><ruby><rb>警察</rb><rt>けいさつ</rt></ruby></span>へ<span><ruby><rb>訴</rb><rt>うった</rt></ruby>えたければ</span>、<span><ruby><rb>勝手</rb><rt>かって</rt></ruby>に</span>訴えろ」と云って、二人して<span>すたすた</span><span>あるき<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>While I was smashing eggs over Noda, Yama Arashi and Red Shirt were still engaged in debate.</p>
		<p>"Can you prove that I spent my night at the inn with a geisha?"</p>
		<p>"I saw your pet geisha enter Kadoya earlier in the evening. Are you trying to deny it?"</p>
		<p>"I've no need to deny anything. Yoshikawa and I spend the night there. The fact that a geisha did or didn't enter earlier that evening doesn't concern me."</p>
		<p>"Doesn't it?" Yama Arashi delivered a knuckle sandwich. Red Shirt staggered. "This is appalling. It's outrageous. Brute force without due process is gross injustice."</p>
		<p>"Then injustice it is." Yama Arashi whacked him again. "For a scoundrel of your caliber, nothing short of a sound thrashing will do." The beating continued. At the same time, I went to work on Noda and drubbed him good. When we finished, the two of them were cowering motionless at the base of a cedar tree. They either couldn't move or were too disoriented to try.</p>
		<p>"Had enough? If not, then here's some more." The two of us continued with more blows. "Enough. Enough." I asked Noda if he'd had enough too. "Yes, yes. Of course."</p>
		<p>"Consider this divine retribution for a couple of first-rate scoundrels. You'd best take a lesson and change your ways. Righteousness will always triumph over cunning deceit." The two of them remained silent as Yama Arashi lectured. They may have been incapable of speech by this point.</p>
		<p>"I'm not going to run or hide. I'll be at Minatoya by the beach until five o'clock this evening. If you have business to settle, come with police officers or whomever you like." I followed with, "I'm not going to run or hide either. I'll be waiting with Hotta. If you want to file a complaint with the police then go ahead." With that, Yama Arashi and I set off walking at a brisk pace.</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>玉子</rb><rt>たまご</rt></ruby>&nbsp;eggs</span><span class="vocabstudy"><ruby><rb>山嵐</rb><rt>やまあらし</rt></ruby>&nbsp;Yama Arashi (nickname for Hotta, the head mathematics teacher)</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ&nbsp;Red Shirt (nickname for the head teacher)</span><span class="vocabstudy"><ruby><rb>談判</rb><rt>だんぱん</rt></ruby>&nbsp;debate; argument</span><span class="vocabstudy"><ruby><rb>最中</rb><rt>さいちゅう</rt></ruby>&nbsp;in the midst of</span>
		<span class="vocabstudy"><ruby><rb>芸者</rb><rt>げいしゃ</rt></ruby>&nbsp;geisha</span><span class="vocabstudy"><ruby><rb>僕</rb><rt>ぼく</rt></ruby>&nbsp;I</span><span class="vocabstudy"><ruby><rb>宿屋</rb><rt>やどや</rt></ruby>&nbsp;inn</span><span class="vocabstudy"><ruby><rb>泊</rb><rt>とま</rt></ruby>った&nbsp;spent the night</span><span class="vocabstudy">と<ruby><rb>云</rb><rt>い</rt></ruby>う&nbsp;saying ...; showing ...</span><span class="vocabstudy"><ruby><rb>証拠</rb><rt>しょうこ</rt></ruby>&nbsp;evidence; proof</span>
		<span class="vocabstudy"><ruby><rb>宵</rb><rt>よい</rt></ruby>&nbsp;early evening</span><span class="vocabstudy"><ruby><rb>貴様</rb><rt>きさま</rt></ruby>&nbsp;you (condescending)</span><span class="vocabstudy"><ruby><rb>角屋</rb><rt>かどや</rt></ruby>&nbsp;Kadoya (name of an inn / restaurant)</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;saw; witnessed</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;fact; matter</span><span class="vocabstudy"><ruby><rb>胡魔化</rb><rt>ごまか</rt></ruby>せる&nbsp;can cover up; can deceive</span>
		<span class="vocabstudy"><ruby><rb>必要</rb><rt>ひつよう</rt></ruby>&nbsp;necessity</span><span class="vocabstudy"><ruby><rb>吉川</rb><rt>よしかわ</rt></ruby>&nbsp;Yoshikawa (a.k.a. Nodaiko)</span><span class="vocabstudy"><ruby><rb>君</rb><rt>くん</rt></ruby>&nbsp;(suffix of familiarity for males)</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>った&nbsp;know (about); be aware of</span>
		<span class="vocabstudy"><ruby><rb>拳骨</rb><rt>げんこつ</rt></ruby>&nbsp;fist</span><span class="vocabstudy"><ruby><rb>食</rb><rt>く</rt></ruby>わした&nbsp;fed; made (someone) eat</span><span class="vocabstudy"><ruby><rb>乱暴</rb><rt>らんぼう</rt></ruby>&nbsp;rude; disorderly</span><span class="vocabstudy"><ruby><rb>狼藉</rb><rt>ろうぜき</rt></ruby>&nbsp;violence; outrage</span><span class="vocabstudy"><ruby><rb>理非</rb><rt>りひ</rt></ruby>&nbsp;rights and wrongs; relative merits</span><span class="vocabstudy"><ruby><rb>弁</rb><rt>べん</rt></ruby>じないで&nbsp;without properly arguing; without fair hearing</span><span class="vocabstudy"><ruby><rb>腕力</rb><rt>わんりょく</rt></ruby>&nbsp;brute force</span><span class="vocabstudy">に<ruby><rb>訴</rb><rt>うった</rt></ruby>える&nbsp;resort to; have recourse to</span><span class="vocabstudy"><ruby><rb>無法</rb><rt>むほう</rt></ruby>&nbsp;injustice</span>
		<span class="vocabstudy">ぽかりと<ruby><rb>撲</rb><rt>な</rt></ruby>ぐる&nbsp;whack; thwack</span><span class="vocabstudy"><ruby><rb>奸物</rb><rt>かんぶつ</rt></ruby>&nbsp;villain; scoundrel</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えない&nbsp;won't get through (to someone); won't make any impression</span><span class="vocabstudy"><ruby><rb>同時</rb><rt>どうじ</rt></ruby>に&nbsp;at the same time</span><span class="vocabstudy"><ruby><rb>野</rb><rt>の</rt></ruby>だ&nbsp;Noda (short for Nodaiko, nickname for Yoshikawa, the art teacher)</span><span class="vocabstudy"><ruby><rb>散々</rb><rt>さんざん</rt></ruby>に&nbsp;harshly; severely</span><span class="vocabstudy"><ruby><rb>擲</rb><rt>たた</rt></ruby>き<ruby><rb>据</rb><rt>す</rt></ruby>えた&nbsp;thrashed; drubbed</span><span class="vocabstudy"><ruby><rb>杉</rb><rt>すぎ</rt></ruby>&nbsp;cedars</span><span class="vocabstudy"><ruby><rb>根方</rb><rt>ねかた</rt></ruby>&nbsp;lower part; root</span><span class="vocabstudy"><ruby><rb>動</rb><rt>うご</rt></ruby>けない&nbsp;unable to move</span><span class="vocabstudy"><ruby><rb>眼</rb><rt>め</rt></ruby>がちらちらする&nbsp;be dazzled; be blinded</span><span class="vocabstudy"><ruby><rb>逃</rb><rt>に</rt></ruby>げよう&nbsp;flee; run away</span>
		<span class="vocabstudy"><ruby><rb>撲</rb><rt>なぐ</rt></ruby>って&nbsp;hit; smack</span><span class="vocabstudy"><ruby><rb>両人</rb><rt>ふたり</rt></ruby>&nbsp;both (people)</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いたら&nbsp;asked; inquired</span><span class="vocabstudy"><ruby><rb>無論</rb><rt>むろん</rt></ruby>&nbsp;of course</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた&nbsp;responded; answered</span>
		<span class="vocabstudy"><ruby><rb>貴様等</rb><rt>きさまら</rt></ruby>&nbsp;you (plural)</span><span class="vocabstudy"><ruby><rb>天誅</rb><rt>てんちゅう</rt></ruby>&nbsp;divine justice</span><span class="vocabstudy"><ruby><rb>加</rb><rt>くわ</rt></ruby>える&nbsp;administer; dole out</span><span class="vocabstudy"><ruby><rb>懲</rb><rt>こ</rt></ruby>りて&nbsp;learn a hard lesson</span><span class="vocabstudy"><ruby><rb>以来</rb><rt>いらい</rt></ruby>&nbsp;after ...</span><span class="vocabstudy">つつしむ&nbsp;be prudent; behave oneself</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words; speech</span><span class="vocabstudy"><ruby><rb>巧</rb><rt>たく</rt></ruby>みに&nbsp;cleverly; skillfully</span><span class="vocabstudy"><ruby><rb>弁解</rb><rt>べんかい</rt></ruby>&nbsp;explanation; defense</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;be formed; be constructed</span><span class="vocabstudy"><ruby><rb>正義</rb><rt>せいぎ</rt></ruby>&nbsp;justice; righteousness</span><span class="vocabstudy"><ruby><rb>許</rb><rt>ゆる</rt></ruby>さん&nbsp;won't allow (it)</span><span class="vocabstudy"><ruby><rb>両人共</rb><rt>ふたりとも</rt></ruby>&nbsp;both together</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>をきく&nbsp;talk; speak</span><span class="vocabstudy"><ruby><rb>退儀</rb><rt>たいぎ</rt></ruby>&nbsp;beyond one's capacity</span><span class="vocabstudy">かも<ruby><rb>知</rb><rt>し</rt></ruby>れない&nbsp;it could be that ...</span>
		<span class="vocabstudy"><ruby><rb>逃</rb><rt>に</rt></ruby>げ&nbsp;escape; flight</span><span class="vocabstudy"><ruby><rb>隠</rb><rt>かく</rt></ruby>れ&nbsp;hiding</span><span class="vocabstudy"><ruby><rb>今夜</rb><rt>こんや</rt></ruby>&nbsp;tonight</span><span class="vocabstudy"><ruby><rb>五時</rb><rt>ごじ</rt></ruby>&nbsp;five (o'clock)</span><span class="vocabstudy"><ruby><rb>浜</rb><rt>はま</rt></ruby>&nbsp;beach; shore</span><span class="vocabstudy"><ruby><rb>港屋</rb><rt>みなとや</rt></ruby>&nbsp;Minatoya (name of an inn)</span><span class="vocabstudy"><ruby><rb>居</rb><rt>い</rt></ruby>る&nbsp;be (in a place)</span><span class="vocabstudy"><ruby><rb>用</rb><rt>よう</rt></ruby>&nbsp;business</span><span class="vocabstudy"><ruby><rb>巡査</rb><rt>じゅんさ</rt></ruby>&nbsp;police officer</span><span class="vocabstudy"><ruby><rb>堀田</rb><rt>ほった</rt></ruby>&nbsp;Hotta (a.k.a. Yama Arashi)</span><span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じ&nbsp;same</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>って&nbsp;wait</span><span class="vocabstudy"><ruby><rb>警察</rb><rt>けいさつ</rt></ruby>&nbsp;police</span><span class="vocabstudy"><ruby><rb>訴</rb><rt>うった</rt></ruby>えたければ&nbsp;(if you) want to file a complaint</span><span class="vocabstudy"><ruby><rb>勝手</rb><rt>かって</rt></ruby>に&nbsp;as one pleases</span><span class="vocabstudy">すたすた&nbsp;at a brisk pace</span><span class="vocabstudy">あるき<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;started out walking</span>

	</StudyGuide>
);
