// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={76}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>は<span><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がない</span>から、<span><ruby><rb>母</rb><rt>はは</rt></ruby></span>をそのままにしておいて<span><ruby><rb>直接</rb><rt>ちょくせつ</rt></ruby></span><span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>に<span><ruby><rb>向</rb><rt>む</rt></ruby>かった</span>。父は私の<span><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby></span>を母よりは<span><ruby><rb>真面目</rb><rt>まじめ</rt></ruby>に</span><span><ruby><rb>聞</rb><rt>き</rt></ruby>いて</span>くれた。「もっともだ。<span>お<ruby><rb>前</rb><rt>まえ</rt></ruby></span>の<span>いう<ruby><rb>通</rb><rt>とお</rt></ruby>り</span>だ。けれども、<span><ruby><rb>己</rb><rt>おれ</rt></ruby></span>の<span><ruby><rb>身体</rb><rt>からだ</rt></ruby></span>は<span><ruby><rb>必竟</rb><rt>ひっきょう</rt></ruby></span>己の身体で、その己の身体についての<span><ruby><rb>養生法</rb><rt>ようじょうほう</rt></ruby></span>は、<span><ruby><rb>多年</rb><rt>たねん</rt></ruby></span>の<span><ruby><rb>経験</rb><rt>けいけん</rt></ruby></span><span><ruby><rb>上</rb><rt>じょう</rt></ruby></span>、己が<span><ruby><rb>一番</rb><rt>いちばん</rt></ruby></span><span><ruby><rb>能</rb><rt>よ</rt></ruby>く</span><span><ruby><rb>心得</rb><rt>こころえ</rt></ruby>て</span>いるはずだからね」といった。それを聞いた母は<span><ruby><rb>苦笑</rb><rt>くしょう</rt></ruby>した</span>。「<span>それご<ruby><rb>覧</rb><rt>らん</rt></ruby>な</span>」といった。</p>
		<p>「でも、あれで<span>お<ruby><rb>父</rb><rt>とう</rt></ruby>さん</span>は<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>でちゃんと<span><ruby><rb>覚悟</rb><rt>かくご</rt></ruby></span>だけはしているんですよ。<span><ruby><rb>今度</rb><rt>こんど</rt></ruby></span>私が<span><ruby><rb>卒業</rb><rt>そつぎょう</rt></ruby>して</span><span><ruby><rb>帰</rb><rt>かえ</rt></ruby>った</span>のを<span><ruby><rb>大変</rb><rt>たいへん</rt></ruby></span><span><ruby><rb>喜</rb><rt>よろこ</rt></ruby>んでいる</span>のも、<span><ruby><rb>全</rb><rt>まった</rt></ruby>く</span>そのためなんです。<span><ruby><rb>生</rb><rt>い</rt></ruby>きてる</span>うちに卒業はできまいと<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>のが、<span><ruby><rb>達者</rb><rt>たっしゃ</rt></ruby></span>なうちに<span><ruby><rb>免状</rb><rt>めんじょう</rt></ruby></span>を<span><ruby><rb>持</rb><rt>も</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た</span>から、それが<span><ruby><rb>嬉</rb><rt>うれ</rt></ruby>しい</span>んだって、お父さんは自分でそういっていましたぜ」</p>
		<p>「そりゃ、お前、<span><ruby><rb>口</rb><rt>くち</rt></ruby>で</span>こそそうおいいだけれどもね。<span>お<ruby><rb>腹</rb><rt>なか</rt></ruby>のなかでは</span>まだ<span><ruby><rb>大丈夫</rb><rt>だいじょうぶ</rt></ruby></span>だと<span><ruby><rb>思</rb><rt>おも</rt></ruby>ってお<ruby><rb>出</rb><rt>いで</rt></ruby></span>のだよ」</p>
		<p>「そうでしょうか」</p>
		<p>「まだまだ<span><ruby><rb>十年</rb><rt>じゅうねん</rt></ruby></span>も<span><ruby><rb>二十年</rb><rt>にじゅうねん</rt></ruby></span>も生きる<span><ruby><rb>気</rb><rt>き</rt></ruby></span>でお出のだよ。もっとも<span><ruby><rb>時々</rb><rt>ときどき</rt></ruby></span>はわたしにも<span><ruby><rb>心細</rb><rt>こころぼそ</rt></ruby>い</span>ような<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>をおいいだがね。おれも<span>この<ruby><rb>分</rb><rt>ぶん</rt></ruby>じゃ</span>もう<span><ruby><rb>長</rb><rt>なが</rt></ruby>い</span>事もあるまいよ、おれが<span><ruby><rb>死</rb><rt>し</rt></ruby>んだら</span>、お前はどうする、<span><ruby><rb>一人</rb><rt>ひとり</rt></ruby>で</span>この<span><ruby><rb>家</rb><rt>うち</rt></ruby></span>にいる気かなんて」</p>
		<p>私は<span><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span>父がいなくなって母一人が<span><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>残</rb><rt>のこ</rt></ruby>された</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>の、<span><ruby><rb>古</rb><rt>ふる</rt></ruby>い</span><span><ruby><rb>広</rb><rt>ひろ</rt></ruby>い</span><span><ruby><rb>田舎家</rb><rt>いなかや</rt></ruby></span>を<span><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>して<ruby><rb>見</rb><rt>み</rt></ruby>た</span>。この<span><ruby><rb>家</rb><rt>いえ</rt></ruby></span>から父一人を<span><ruby><rb>引</rb><rt>ひ</rt></ruby>き<ruby><rb>去</rb><rt>さ</rt></ruby>った</span><span><ruby><rb>後</rb><rt>あと</rt></ruby></span>は、そのままで<span><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>行</rb><rt>ゆ</rt></ruby>く</span>だろうか。<span><ruby><rb>兄</rb><rt>あに</rt></ruby></span>はどうするだろうか。母は<span><ruby><rb>何</rb><rt>なん</rt></ruby></span>というだろうか。そう<span><ruby><rb>考</rb><rt>かんが</rt></ruby>える</span>私はまたここの<span><ruby><rb>土</rb><rt>つち</rt></ruby></span>を<span><ruby><rb>離</rb><rt>はな</rt></ruby>れて</span>、<span><ruby><rb>東京</rb><rt>とうきょう</rt></ruby></span>で<span><ruby><rb>気楽</rb><rt>きらく</rt></ruby>に</span><span><ruby><rb>暮</rb><rt>く</rt></ruby>らして<ruby><rb>行</rb><rt>い</rt></ruby>ける</span>だろうか。私は母を<span><ruby><rb>眼</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby></span>に<span><ruby><rb>置</rb><rt>お</rt></ruby>いて</span>、<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>の注意――父の<span><ruby><rb>丈夫</rb><rt>じょうぶ</rt></ruby></span>でいるうちに、<span><ruby><rb>分</rb><rt>わ</rt></ruby>けて<ruby><rb>貰</rb><rt>もら</rt></ruby>う</span>ものは、分けて貰って置けという注意を、<span><ruby><rb>偶然</rb><rt>ぐうぜん</rt></ruby></span><span><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「なにね、自分で死ぬ死ぬっていう人に死んだ<span><ruby><rb>試</rb><rt>ため</rt></ruby>し</span>はないんだから<span><ruby><rb>安心</rb><rt>あんしん</rt></ruby></span>だよ。お父さんなんぞも、死ぬ死ぬっていいながら、これから<span><ruby><rb>先</rb><rt>さき</rt></ruby></span>まだ<span><ruby><rb>何年</rb><rt>なんねん</rt></ruby></span>生きなさるか<span><ruby><rb>分</rb><rt>わか</rt></ruby>るまい</span>よ。それよりか<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>る丈夫の<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>が<span><ruby><rb>剣呑</rb><rt>けんのん</rt></ruby></span>さ」</p>
		<p>私は<span><ruby><rb>理屈</rb><rt>りくつ</rt></ruby></span>から<span><ruby><rb>出</rb><rt>で</rt></ruby>た</span>とも<span><ruby><rb>統計</rb><rt>とうけい</rt></ruby></span>から来たとも<span><ruby><rb>知</rb><rt>し</rt></ruby>れない</span>、この<span><ruby><rb>陳腐</rb><rt>ちんぷ</rt></ruby>な</span>ような母の<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>を<span><ruby><rb>黙然</rb><rt>もくねん</rt></ruby>と</span>聞いていた。</p>

		<h3 class="section">Rough translation</h3>
		<p>The only thing to do, I decided, was to talk to Father directly. He listened more receptively to my counsel than my mother had.</p>
		<p>"No doubt, no doubt. You're absolutely correct. However, at the end of the day it's my body, and over the years I've come to know it well. More than any one else, I believe I know its limitations and its needs."</p>
		<p>My mother listened with a wry smile. "See what I mean?" she said.</p>
		<p>"Even so, Father's resolved himself to what's coming. That's why he was so pleased to see me graduate and return home with my diploma. He told me himself he didn't think he'd live to see the day, much less still have his health."</p>
		<p>"Don't be fooled by what he says. Deep down, he knows he still has time."</p>
		<p>"You really think so?"</p>
		<p>"He intends to keep on. Maybe for ten years, maybe for twenty. Granted, he does worry me at times. He tells me he doesn't have long. Then he asks what I'll do when he's gone, if I can manage alone."</p>
		<p>I suddenly imagined my mother, minus my father, in this big old country house. Could she run things herself with Father gone? What would my elder brother do? What would Mother's wishes be? In light of all that, could I leave this place for a comfortable existence in Tōkyō? As thoughts of Mother filled my mind, I also recalled what Sensei had said - if there's property involved, receive your due share now, while your father is still of sound mind and body.</p>
		<p>"Not to worry. The ones who say they're dying never do. Who knows how many years he'll go on, pronouncing his own demise all the while. It's the healthy ones, with nothing to complain of, who end up going first."</p>
		<p>I listened in silence to my mother's clichéd remark, defensible by neither rational thought nor statistical evidence.</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がない&nbsp;have no other recourse</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span><span class="vocabstudy"><ruby><rb>直接</rb><rt>ちょくせつ</rt></ruby>&nbsp;directly</span><span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>かった&nbsp;turned to</span><span class="vocabstudy"><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby>&nbsp;advice; counsel</span><span class="vocabstudy"><ruby><rb>真面目</rb><rt>まじめ</rt></ruby>に&nbsp;earnestly; sincerely</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;listen</span><span class="vocabstudy">お<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;you</span><span class="vocabstudy">いう<ruby><rb>通</rb><rt>とお</rt></ruby>り&nbsp;just as (one) says</span><span class="vocabstudy"><ruby><rb>己</rb><rt>おれ</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>身体</rb><rt>からだ</rt></ruby>&nbsp;body</span><span class="vocabstudy"><ruby><rb>必竟</rb><rt>ひっきょう</rt></ruby>&nbsp;after all; at the end of the day</span><span class="vocabstudy"><ruby><rb>養生法</rb><rt>ようじょうほう</rt></ruby>&nbsp;how to take care of</span><span class="vocabstudy"><ruby><rb>多年</rb><rt>たねん</rt></ruby>&nbsp;many years</span><span class="vocabstudy"><ruby><rb>経験</rb><rt>けいけん</rt></ruby>&nbsp;experience</span><span class="vocabstudy"><ruby><rb>上</rb><rt>じょう</rt></ruby>&nbsp;building on; based on</span><span class="vocabstudy"><ruby><rb>一番</rb><rt>いちばん</rt></ruby>&nbsp;first; foremost</span><span class="vocabstudy"><ruby><rb>能</rb><rt>よ</rt></ruby>く&nbsp;properly; well</span><span class="vocabstudy"><ruby><rb>心得</rb><rt>こころえ</rt></ruby>て&nbsp;know; understand</span><span class="vocabstudy"><ruby><rb>苦笑</rb><rt>くしょう</rt></ruby>した&nbsp;floated a wry smile</span><span class="vocabstudy">それご<ruby><rb>覧</rb><rt>らん</rt></ruby>な&nbsp;there you have it; see what I mean</span>
		<span class="vocabstudy">お<ruby><rb>父</rb><rt>とう</rt></ruby>さん&nbsp;father</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>覚悟</rb><rt>かくご</rt></ruby>&nbsp;resolution; resolve</span><span class="vocabstudy"><ruby><rb>今度</rb><rt>こんど</rt></ruby>&nbsp;this time</span><span class="vocabstudy"><ruby><rb>卒業</rb><rt>そつぎょう</rt></ruby>して&nbsp;graduate</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>った&nbsp;returned home</span><span class="vocabstudy"><ruby><rb>大変</rb><rt>たいへん</rt></ruby>&nbsp;very much; terribly</span><span class="vocabstudy"><ruby><rb>喜</rb><rt>よろこ</rt></ruby>んでいる&nbsp;be pleased; be delighted</span><span class="vocabstudy"><ruby><rb>全</rb><rt>まった</rt></ruby>く&nbsp;utterly; completely</span><span class="vocabstudy"><ruby><rb>生</rb><rt>い</rt></ruby>きてる&nbsp;be alive</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought; believed</span><span class="vocabstudy"><ruby><rb>達者</rb><rt>たっしゃ</rt></ruby>&nbsp;in good health</span><span class="vocabstudy"><ruby><rb>免状</rb><rt>めんじょう</rt></ruby>&nbsp;diploma</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;brought; brought with</span><span class="vocabstudy"><ruby><rb>嬉</rb><rt>うれ</rt></ruby>しい&nbsp;happy; pleased</span>
		<span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>で&nbsp;with one's mouth; verbally; in words</span><span class="vocabstudy">お<ruby><rb>腹</rb><rt>なか</rt></ruby>のなかでは&nbsp;deep down; inside</span><span class="vocabstudy"><ruby><rb>大丈夫</rb><rt>だいじょうぶ</rt></ruby>&nbsp;all right; okay</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>ってお<ruby><rb>出</rb><rt>いで</rt></ruby>&nbsp;thinks; believes</span>
		<span class="vocabstudy"><ruby><rb>十年</rb><rt>じゅうねん</rt></ruby>&nbsp;ten years</span><span class="vocabstudy"><ruby><rb>二十年</rb><rt>にじゅうねん</rt></ruby>&nbsp;twenty years</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>&nbsp;intention</span><span class="vocabstudy"><ruby><rb>時々</rb><rt>ときどき</rt></ruby>&nbsp;from time to time; on occasion</span><span class="vocabstudy"><ruby><rb>心細</rb><rt>こころぼそ</rt></ruby>い&nbsp;discouraging; disheartening</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;things</span><span class="vocabstudy">この<ruby><rb>分</rb><rt>ぶん</rt></ruby>じゃ&nbsp;at this rate</span><span class="vocabstudy"><ruby><rb>長</rb><rt>なが</rt></ruby>い&nbsp;long; lengthy</span><span class="vocabstudy"><ruby><rb>死</rb><rt>し</rt></ruby>んだら&nbsp;die; pass away</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>で&nbsp;by oneself; alone</span><span class="vocabstudy"><ruby><rb>家</rb><rt>うち</rt></ruby>&nbsp;house</span>
		<span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>残</rb><rt>のこ</rt></ruby>された&nbsp;be left behind</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time</span><span class="vocabstudy"><ruby><rb>古</rb><rt>ふる</rt></ruby>い&nbsp;old</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い&nbsp;large; spacious</span><span class="vocabstudy"><ruby><rb>田舎家</rb><rt>いなかや</rt></ruby>&nbsp;farm house</span><span class="vocabstudy"><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>して<ruby><rb>見</rb><rt>み</rt></ruby>た&nbsp;imagined</span><span class="vocabstudy"><ruby><rb>家</rb><rt>いえ</rt></ruby>&nbsp;house; home</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>き<ruby><rb>去</rb><rt>さ</rt></ruby>った&nbsp;took away; withdrew</span><span class="vocabstudy"><ruby><rb>後</rb><rt>あと</rt></ruby>&nbsp;after</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>行</rb><rt>ゆ</rt></ruby>く&nbsp;keep going; carry on</span><span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;elder brother</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>&nbsp;what</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>える&nbsp;consider; think about</span><span class="vocabstudy"><ruby><rb>土</rb><rt>つち</rt></ruby>&nbsp;earth; land</span><span class="vocabstudy"><ruby><rb>離</rb><rt>はな</rt></ruby>れて&nbsp;disengage from; leave</span><span class="vocabstudy"><ruby><rb>東京</rb><rt>とうきょう</rt></ruby>&nbsp;Tōkyō</span><span class="vocabstudy"><ruby><rb>気楽</rb><rt>きらく</rt></ruby>に&nbsp;in comfort</span><span class="vocabstudy"><ruby><rb>暮</rb><rt>く</rt></ruby>らして<ruby><rb>行</rb><rt>い</rt></ruby>ける&nbsp;live one's life</span><span class="vocabstudy"><ruby><rb>眼</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before one's eyes</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いて&nbsp;set; place</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>丈夫</rb><rt>じょうぶ</rt></ruby>&nbsp;healthy; robust</span><span class="vocabstudy"><ruby><rb>分</rb><rt>わ</rt></ruby>けて<ruby><rb>貰</rb><rt>もら</rt></ruby>う&nbsp;have divide; have divvy up</span><span class="vocabstudy"><ruby><rb>偶然</rb><rt>ぐうぜん</rt></ruby>&nbsp;at this same time</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;remembered; recalled</span>
		<span class="vocabstudy"><ruby><rb>試</rb><rt>ため</rt></ruby>し&nbsp;precedent; example</span><span class="vocabstudy"><ruby><rb>安心</rb><rt>あんしん</rt></ruby>&nbsp;not to worry</span><span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;ahead; in the future</span><span class="vocabstudy"><ruby><rb>何年</rb><rt>なんねん</rt></ruby>&nbsp;how many years</span><span class="vocabstudy"><ruby><rb>分</rb><rt>わか</rt></ruby>るまい&nbsp;no one knows</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;say nothing; keep quiet</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;people; persons</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;alternative (of two choices)</span><span class="vocabstudy"><ruby><rb>剣呑</rb><rt>けんのん</rt></ruby>&nbsp;at risk; in danger</span>
		<span class="vocabstudy"><ruby><rb>理屈</rb><rt>りくつ</rt></ruby>&nbsp;theory; reason</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;came from</span><span class="vocabstudy"><ruby><rb>統計</rb><rt>とうけい</rt></ruby>&nbsp;statistics</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>れない&nbsp;not known to ...</span><span class="vocabstudy"><ruby><rb>陳腐</rb><rt>ちんぷ</rt></ruby>な&nbsp;stale; hackneyed; clichéd</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>黙然</rb><rt>もくねん</rt></ruby>と&nbsp;in silence</span>

	</StudyGuide>
);
