// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={80}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>はこの<span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>の<span><ruby><rb>冬</rb><rt>ふゆ</rt></ruby></span>に<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>ほど<span><ruby><rb>将棋</rb><rt>しょうぎ</rt></ruby></span>を<span><ruby><rb>差</rb><rt>さ</rt></ruby>したがらなくなった</span>。<span><ruby><rb>将棋盤</rb><rt>しょうぎばん</rt></ruby></span>はほこりの<span><ruby><rb>溜</rb><rt>たま</rt></ruby>った</span>まま、<span><ruby><rb>床</rb><rt>とこ</rt></ruby>の<ruby><rb>間</rb><rt>ま</rt></ruby></span>の<span><ruby><rb>隅</rb><rt>すみ</rt></ruby></span>に<span><ruby><rb>片寄</rb><rt>かたよ</rt></ruby>せられてあった</span>。ことに<span><ruby><rb>陛下</rb><rt>へいか</rt></ruby></span>の<span>ご<ruby><rb>病気</rb><rt>びょうき</rt></ruby></span><span><ruby><rb>以後</rb><rt>いご</rt></ruby></span>父は<span><ruby><rb>凝</rb><rt>じっ</rt></ruby>と</span><span><ruby><rb>考</rb><rt>かんが</rt></ruby>え<ruby><rb>込</rb><rt>こ</rt></ruby>んで</span>いるように<span><ruby><rb>見</rb><rt>み</rt></ruby>えた</span>。<span><ruby><rb>毎日</rb><rt>まいにち</rt></ruby></span><span><ruby><rb>新聞</rb><rt>しんぶん</rt></ruby></span>の<span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>のを<span><ruby><rb>待</rb><rt>ま</rt></ruby>ち<ruby><rb>受</rb><rt>う</rt></ruby>けて</span>、<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>が<span><ruby><rb>一番</rb><rt>いちばん</rt></ruby></span><span><ruby><rb>先</rb><rt>さき</rt></ruby></span>へ<span><ruby><rb>読</rb><rt>よ</rt></ruby>んだ</span>。それからその<span><ruby><rb>読</rb><rt>よみ</rt></ruby>がら</span>をわざわざ<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>のいる<span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>へ<span><ruby><rb>持</rb><rt>も</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>て</span>くれた。</p>
		<p>「おい<span>ご<ruby><rb>覧</rb><rt>らん</rt></ruby></span>、<span><ruby><rb>今日</rb><rt>きょう</rt></ruby></span>も<span><ruby><rb>天子</rb><rt>てんし</rt></ruby>さま</span>の<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>が<span><ruby><rb>詳</rb><rt>くわ</rt></ruby>しく</span><span><ruby><rb>出</rb><rt>で</rt></ruby>て</span>いる」</p>
		<p>父は陛下のことを、つねに天子さまといっていた。</p>
		<p>「<span><ruby><rb>勿体</rb><rt>もったい</rt></ruby>ない</span><span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>だが、天子さまのご病気も、<span>お<ruby><rb>父</rb><rt>とう</rt></ruby>さん</span>のとまあ<span><ruby><rb>似</rb><rt>に</rt></ruby>た</span>ものだろうな」</p>
		<p>こういう父の<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>には<span><ruby><rb>深</rb><rt>ふか</rt></ruby>い</span><span><ruby><rb>掛念</rb><rt>けねん</rt></ruby></span>の<span><ruby><rb>曇</rb><rt>くも</rt></ruby>り</span>がかかっていた。こういわれる私の<span><ruby><rb>胸</rb><rt>むね</rt></ruby></span>にはまた父がいつ<span><ruby><rb>斃</rb><rt>たお</rt></ruby>れる</span>か<span><ruby><rb>分</rb><rt>わか</rt></ruby>らない</span>という<span><ruby><rb>心配</rb><rt>しんぱい</rt></ruby></span>がひらめいた。</p>
		<p>「しかし<span><ruby><rb>大丈夫</rb><rt>だいじょうぶ</rt></ruby></span>だろう。おれのような<span><ruby><rb>下</rb><rt>くだ</rt></ruby>らない</span>ものでも、まだこうしていられるくらいだから」</p>
		<p>父は自分の<span><ruby><rb>達者</rb><rt>たっしゃ</rt></ruby></span>な<span><ruby><rb>保証</rb><rt>ほしょう</rt></ruby></span>を自分で<span><ruby><rb>与</rb><rt>あた</rt></ruby>えながら</span>、<span><ruby><rb>今</rb><rt>いま</rt></ruby>にも</span><span><ruby><rb>己</rb><rt>おの</rt></ruby>れ</span>に<span><ruby><rb>落</rb><rt>お</rt></ruby>ちかかって<ruby><rb>来</rb><rt>き</rt></ruby>そうな</span><span><ruby><rb>危険</rb><rt>きけん</rt></ruby></span>を<span><ruby><rb>予感</rb><rt>よかん</rt></ruby>して</span>いるらしかった。</p>
		<p>「お父さんは<span><ruby><rb>本当</rb><rt>ほんとう</rt></ruby>に</span>病気を<span><ruby><rb>怖</rb><rt>こわ</rt></ruby>がって</span>るんですよ。<span>お<ruby><rb>母</rb><rt>かあ</rt></ruby>さん</span>のおっしゃるように、<span><ruby><rb>十年</rb><rt>じゅうねん</rt></ruby></span>も<span><ruby><rb>二十年</rb><rt>にじゅうねん</rt></ruby></span>も<span><ruby><rb>生</rb><rt>い</rt></ruby>きる</span><span><ruby><rb>気</rb><rt>き</rt></ruby></span>じゃなさそうですぜ」</p>
		<p><span><ruby><rb>母</rb><rt>はは</rt></ruby></span>は私の<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>を<span><ruby><rb>聞</rb><rt>き</rt></ruby>いて</span><span><ruby><rb>当惑</rb><rt>とうわく</rt></ruby>そうな</span>顔をした。</p>
		<p>「ちょっとまた将棋でも差すように<span><ruby><rb>勧</rb><rt>すす</rt></ruby>めてご<ruby><rb>覧</rb><rt>らん</rt></ruby>な</span>」</p>
		<p>私は床の間から将棋盤を<span><ruby><rb>取</rb><rt>と</rt></ruby>りおろして</span>、ほこりを<span><ruby><rb>拭</rb><rt>ふ</rt></ruby>いた</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>Unlike during my home time the previous winter, Father this time was uninterested in shōgi. The shōgi board had been set aside in a corner of the alcove, and it remained there gathering dust. Especially since the Emperor's illness, Father seemed lost in his own thoughts. Each day he waited on the newspaper, and each day he read it first off. When done, he would seek me out, paper still in hand.</p>
		<p>"Take a look. There's lots again on His Highness."</p>
		<p>Father always referred to the Emperor as His Highness.</p>
		<p>"It may be presumptuous of me, but I believe His Highness and I are suffering from the same thing."</p>
		<p>As he spoke, a dark shadow of concern clouded his features. I felt anxious myself at his words, wondering when he might next be forced off his feet.</p>
		<p>"He'll be all right, though. If a common man like myself can manage ..."</p>
		<p>Even as he sought to reassure himself, his words fell heavy with an imminent sense of foreboding.</p>
		<p>"Father really fears for his health," I told my mother. "He doesn't share your confidence in ten or twenty more years."</p>
		<p>Mother seemed at a loss.</p>
		<p>"See if he'll play shōgi with you."</p> 
		<p>I pulled the shōgi board from the alcove and dusted it off.</p>    

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;earlier; before</span><span class="vocabstudy"><ruby><rb>冬</rb><rt>ふゆ</rt></ruby>&nbsp;winter</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came back; returned</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; occasion</span><span class="vocabstudy"><ruby><rb>将棋</rb><rt>しょうぎ</rt></ruby>&nbsp;shōgi (board game)</span><span class="vocabstudy"><ruby><rb>差</rb><rt>さ</rt></ruby>したがらなくなった&nbsp;was less interested in playing</span><span class="vocabstudy"><ruby><rb>将棋盤</rb><rt>しょうぎばん</rt></ruby>&nbsp;shōgi board</span><span class="vocabstudy"><ruby><rb>溜</rb><rt>たま</rt></ruby>った&nbsp;collected; gathered; accumulated</span><span class="vocabstudy"><ruby><rb>床</rb><rt>とこ</rt></ruby>の<ruby><rb>間</rb><rt>ま</rt></ruby>&nbsp;alcove</span><span class="vocabstudy"><ruby><rb>隅</rb><rt>すみ</rt></ruby>&nbsp;corner</span><span class="vocabstudy"><ruby><rb>片寄</rb><rt>かたよ</rt></ruby>せられてあった&nbsp;had been pushed aside; had been set aside</span><span class="vocabstudy"><ruby><rb>陛下</rb><rt>へいか</rt></ruby>&nbsp;His Majesty (the Emperor)</span><span class="vocabstudy">ご<ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;sickness; illness</span><span class="vocabstudy"><ruby><rb>以後</rb><rt>いご</rt></ruby>&nbsp;since ...</span><span class="vocabstudy"><ruby><rb>凝</rb><rt>じっ</rt></ruby>と&nbsp;fixedly; intently</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>え<ruby><rb>込</rb><rt>こ</rt></ruby>んで&nbsp;ponder; brood</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>えた&nbsp;appeared; seemed (to do)</span><span class="vocabstudy"><ruby><rb>毎日</rb><rt>まいにち</rt></ruby>&nbsp;each day; every day</span><span class="vocabstudy"><ruby><rb>新聞</rb><rt>しんぶん</rt></ruby>&nbsp;newspaper</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come; arrive</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>ち<ruby><rb>受</rb><rt>う</rt></ruby>けて&nbsp;wait on; await</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>一番</rb><rt>いちばん</rt></ruby>&nbsp;first; foremost</span><span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;ahead; in advance</span><span class="vocabstudy"><ruby><rb>読</rb><rt>よ</rt></ruby>んだ&nbsp;read</span><span class="vocabstudy"><ruby><rb>読</rb><rt>よみ</rt></ruby>がら&nbsp;read-and-done-with (newspaper)</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;carry in; bring</span>
		<span class="vocabstudy">ご<ruby><rb>覧</rb><rt>らん</rt></ruby>&nbsp;take a look</span><span class="vocabstudy"><ruby><rb>今日</rb><rt>きょう</rt></ruby>&nbsp;today</span><span class="vocabstudy"><ruby><rb>天子</rb><rt>てんし</rt></ruby>さま&nbsp;His Highness</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;matter; affair</span><span class="vocabstudy"><ruby><rb>詳</rb><rt>くわ</rt></ruby>しく&nbsp;in detail</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て&nbsp;appear</span>
		<span class="vocabstudy"><ruby><rb>勿体</rb><rt>もったい</rt></ruby>ない&nbsp;presumptuous; overreaching</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;talk</span><span class="vocabstudy">お<ruby><rb>父</rb><rt>とう</rt></ruby>さん&nbsp;father</span><span class="vocabstudy"><ruby><rb>似</rb><rt>に</rt></ruby>た&nbsp;similar; same kind of</span>
		<span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face; (facial) expression</span><span class="vocabstudy"><ruby><rb>深</rb><rt>ふか</rt></ruby>い&nbsp;deep</span><span class="vocabstudy"><ruby><rb>掛念</rb><rt>けねん</rt></ruby>&nbsp;anxiety; concern (usually <ruby><rb>懸念</rb><rt>けねん</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>曇</rb><rt>くも</rt></ruby>り&nbsp;darkness; shadow</span><span class="vocabstudy"><ruby><rb>胸</rb><rt>むね</rt></ruby>&nbsp;breast; bosom</span><span class="vocabstudy"><ruby><rb>斃</rb><rt>たお</rt></ruby>れる&nbsp;collapse; fall ill</span><span class="vocabstudy"><ruby><rb>分</rb><rt>わか</rt></ruby>らない&nbsp;don't know; can't say</span><span class="vocabstudy"><ruby><rb>心配</rb><rt>しんぱい</rt></ruby>&nbsp;worry; angst</span>
		<span class="vocabstudy"><ruby><rb>大丈夫</rb><rt>だいじょうぶ</rt></ruby>&nbsp;all right; okay; fine</span><span class="vocabstudy"><ruby><rb>下</rb><rt>くだ</rt></ruby>らない&nbsp;common; good-for-nothing; trivial</span>
		<span class="vocabstudy"><ruby><rb>達者</rb><rt>たっしゃ</rt></ruby>&nbsp;good health; wellness</span><span class="vocabstudy"><ruby><rb>保証</rb><rt>ほしょう</rt></ruby>&nbsp;assurance</span><span class="vocabstudy"><ruby><rb>与</rb><rt>あた</rt></ruby>えながら&nbsp;bestowing; imparting</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>にも&nbsp;at any moment</span><span class="vocabstudy"><ruby><rb>己</rb><rt>おの</rt></ruby>れ&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちかかって<ruby><rb>来</rb><rt>き</rt></ruby>そうな&nbsp;seemingly about to befall one</span><span class="vocabstudy"><ruby><rb>危険</rb><rt>きけん</rt></ruby>&nbsp;peril; hazard</span><span class="vocabstudy"><ruby><rb>予感</rb><rt>よかん</rt></ruby>して&nbsp;sense; feel coming</span>
		<span class="vocabstudy"><ruby><rb>本当</rb><rt>ほんとう</rt></ruby>に&nbsp;truly; in fact</span><span class="vocabstudy"><ruby><rb>怖</rb><rt>こわ</rt></ruby>がって&nbsp;fear; dread</span><span class="vocabstudy">お<ruby><rb>母</rb><rt>かあ</rt></ruby>さん&nbsp;mother</span><span class="vocabstudy"><ruby><rb>十年</rb><rt>じゅうねん</rt></ruby>&nbsp;ten years</span><span class="vocabstudy"><ruby><rb>二十年</rb><rt>にじゅうねん</rt></ruby>&nbsp;twenty years</span><span class="vocabstudy"><ruby><rb>生</rb><rt>い</rt></ruby>きる&nbsp;live</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>&nbsp;intention</span>
		<span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;listen to</span><span class="vocabstudy"><ruby><rb>当惑</rb><rt>とうわく</rt></ruby>そうな&nbsp;at a loss; nonplussed</span>
		<span class="vocabstudy"><ruby><rb>勧</rb><rt>すす</rt></ruby>めてご<ruby><rb>覧</rb><rt>らん</rt></ruby>な&nbsp;try offering; try suggesting</span>
		<span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>りおろして&nbsp;took out (from)</span><span class="vocabstudy"><ruby><rb>拭</rb><rt>ふ</rt></ruby>いた&nbsp;wiped off</span>

	</StudyGuide>
);
