// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={85}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>七</rb><rt>しち</rt></ruby></span></p>
		<p><span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>は<span><ruby><rb>明</rb><rt>あき</rt></ruby>らかに</span><span><ruby><rb>自分</rb><rt>じぶん</rt></ruby>の</span><span><ruby><rb>病気</rb><rt>びょうき</rt></ruby></span>を<span><ruby><rb>恐</rb><rt>おそ</rt></ruby>れて</span>いた。しかし<span><ruby><rb>医者</rb><rt>いしゃ</rt></ruby></span>の<span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>たびに<span><ruby><rb>蒼蠅</rb><rt>うるさ</rt></ruby>い</span><span><ruby><rb>質問</rb><rt>しつもん</rt></ruby></span>を<span><ruby><rb>掛</rb><rt>か</rt></ruby>けて</span><span><ruby><rb>相手</rb><rt>あいて</rt></ruby></span>を<span><ruby><rb>困</rb><rt>こま</rt></ruby>らす</span><span><ruby><rb>質</rb><rt>たち</rt></ruby></span>でもなかった。医者の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>でもまた<span><ruby><rb>遠慮</rb><rt>えんりょ</rt></ruby>して</span><span><ruby><rb>何</rb><rt>なん</rt></ruby>とも</span>いわなかった。</p>
		<p>父は<span><ruby><rb>死後</rb><rt>しご</rt></ruby></span>の<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>を<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えて</span>いるらしかった。<span><ruby><rb>少</rb><rt>すく</rt></ruby>なくとも</span>自分がいなくなった<span><ruby><rb>後</rb><rt>あと</rt></ruby></span>の<span>わが<ruby><rb>家</rb><rt>いえ</rt></ruby></span>を<span><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>して<ruby><rb>見</rb><rt>み</rt></ruby>る</span>らしかった。</p>
		<p>「<span><ruby><rb>小供</rb><rt>こども</rt></ruby></span>に<span><ruby><rb>学問</rb><rt>がくもん</rt></ruby></span>をさせるのも、<span><ruby><rb>好</rb><rt>よ</rt></ruby>し<ruby><rb>悪</rb><rt>あ</rt></ruby>し</span>だね。せっかく<span><ruby><rb>修業</rb><rt>しゅうぎょう</rt></ruby></span>をさせると、その小供は<span><ruby><rb>決</rb><rt>けっ</rt></ruby>して</span><span><ruby><rb>宅</rb><rt>うち</rt></ruby></span>へ<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>こ</rt></ruby>ない</span>。これじゃ<span><ruby><rb>手</rb><rt>て</rt></ruby>もなく</span><span><ruby><rb>親子</rb><rt>おやこ</rt></ruby></span>を<span><ruby><rb>隔離</rb><rt>かくり</rt></ruby>する</span>ために学問させるようなものだ」</p>
		<p>学問をした<span><ruby><rb>結果</rb><rt>けっか</rt></ruby></span><span><ruby><rb>兄</rb><rt>あに</rt></ruby></span>は<span><ruby><rb>今</rb><rt>いま</rt></ruby></span><span><ruby><rb>遠国</rb><rt>えんごく</rt></ruby></span>にいた。<span><ruby><rb>教育</rb><rt>きょういく</rt></ruby></span>を<span><ruby><rb>受</rb><rt>う</rt></ruby>けた</span><span><ruby><rb>因果</rb><rt>いんが</rt></ruby></span>で、<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>はまた<span><ruby><rb>東京</rb><rt>とうきょう</rt></ruby></span>に<span><ruby><rb>住</rb><rt>す</rt></ruby>む</span><span><ruby><rb>覚悟</rb><rt>かくご</rt></ruby></span>を<span><ruby><rb>固</rb><rt>かた</rt></ruby>くした</span>。こういう<span><ruby><rb>子</rb><rt>こ</rt></ruby></span>を<span><ruby><rb>育</rb><rt>そだ</rt></ruby>てた</span>父の<span><ruby><rb>愚痴</rb><rt>ぐち</rt></ruby></span>は<span>もとより</span><span><ruby><rb>不合理</rb><rt>ふごうり</rt></ruby></span>ではなかった。<span><ruby><rb>永年</rb><rt>えいねん</rt></ruby></span><span><ruby><rb>住</rb><rt>す</rt></ruby>み<ruby><rb>古</rb><rt>ふる</rt></ruby>した</span><span><ruby><rb>田舎家</rb><rt>いなかや</rt></ruby></span>の<span><ruby><rb>中</rb><rt>なか</rt></ruby></span>に、たった<span><ruby><rb>一人</rb><rt>ひとり</rt></ruby></span><span><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>残</rb><rt>のこ</rt></ruby>されそうな</span>母を<span><ruby><rb>描</rb><rt>えが</rt></ruby>き<ruby><rb>出</rb><rt>だ</rt></ruby>す</span>父の想像はもとより<span><ruby><rb>淋</rb><rt>さび</rt></ruby>しい</span><span>に<ruby><rb>違</rb><rt>ちが</rt></ruby>いなかった</span>。</p>
		<p>わが家は<span><ruby><rb>動</rb><rt>うご</rt></ruby>かす</span>事のできないものと父は<span><ruby><rb>信</rb><rt>しん</rt></ruby>じ<ruby><rb>切</rb><rt>き</rt></ruby>っていた</span>。その<span><ruby><rb>中</rb><rt>うち</rt></ruby></span>に住む母もまた<span><ruby><rb>命</rb><rt>いのち</rt></ruby></span>のある<span><ruby><rb>間</rb><rt>あいだ</rt></ruby></span>は、動かす事のできないものと信じていた。自分が<span><ruby><rb>死</rb><rt>し</rt></ruby>んだ</span>後、この<span><ruby><rb>孤独</rb><rt>こどく</rt></ruby>な</span>母を、たった一人<span><ruby><rb>伽藍堂</rb><rt>がらんどう</rt></ruby></span>のわが家に取り残すのもまた<span><ruby><rb>甚</rb><rt>はなはだ</rt></ruby>しい</span><span><ruby><rb>不安</rb><rt>ふあん</rt></ruby></span>であった。それだのに、東京で<span><ruby><rb>好</rb><rt>い</rt></ruby>い</span><span><ruby><rb>地位</rb><rt>ちい</rt></ruby></span>を<span><ruby><rb>求</rb><rt>もと</rt></ruby>めろ</span>といって、私を<span><ruby><rb>強</rb><rt>し</rt></ruby>いたがる</span>父の<span><ruby><rb>頭</rb><rt>あたま</rt></ruby></span>には<span><ruby><rb>矛盾</rb><rt>むじゅん</rt></ruby></span>があった。私はその矛盾をおかしく<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span><span>と<ruby><rb>同時</rb><rt>どうじ</rt></ruby>に</span>、その<span>お<ruby><rb>蔭</rb><rt>かげ</rt></ruby>で</span>また東京へ<span><ruby><rb>出</rb><rt>で</rt></ruby>られる</span>のを<span><ruby><rb>喜</rb><rt>よろこ</rt></ruby>んだ</span>。</p>
		<p>私は父や母の<span><ruby><rb>手前</rb><rt>てまえ</rt></ruby></span>、この地位をできるだけの<span><ruby><rb>努力</rb><rt>どりょく</rt></ruby></span>で求めつつあるごとくに<span><ruby><rb>装</rb><rt>よそ</rt></ruby>おわなくてはならなかった</span>。私は<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>に<span><ruby><rb>手紙</rb><rt>てがみ</rt></ruby></span>を<span><ruby><rb>書</rb><rt>か</rt></ruby>いて</span>、<span><ruby><rb>家</rb><rt>いえ</rt></ruby></span>の<span><ruby><rb>事情</rb><rt>じじょう</rt></ruby></span>を<span><ruby><rb>精</rb><rt>くわ</rt></ruby>しく</span><span><ruby><rb>述</rb><rt>の</rt></ruby>べた</span>。もし自分の<span><ruby><rb>力</rb><rt>ちから</rt></ruby></span>でできる事があったら何でもするから<span><ruby><rb>周旋</rb><rt>しゅうせん</rt></ruby></span>してくれと<span><ruby><rb>頼</rb><rt>たの</rt></ruby>んだ</span>。私は先生が私の<span><ruby><rb>依頼</rb><rt>いらい</rt></ruby></span>に<span><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>合</rb><rt>あ</rt></ruby>う</span>まいと思いながらこの手紙を書いた。また取り合うつもりでも、<span><ruby><rb>世間</rb><rt>せけん</rt></ruby>の<ruby><rb>狭</rb><rt>せま</rt></ruby>い</span>先生としてはどうする事もできまいと思いながらこの手紙を書いた。しかし私は先生からこの手紙<span>に<ruby><rb>対</rb><rt>たい</rt></ruby>する</span><span><ruby><rb>返事</rb><rt>へんじ</rt></ruby></span>がきっと来るだろうと思って書いた。</p>

		<h3 class="section">Rough translation</h3>
		<p>7</p>
		<p>Father was clearly apprehensive about his health. However, he was not one to pester the doctor with pointless questions. The doctor, for his part, refrained from belaboring the situation.</p>
		<p>Father, it seemed, was considering our lives without him. At the very least, he was considering the fate of his household.</p>
		<p>"Educating one's children is both good and bad. You work to provide them with schooling, and it's guaranteed they won't stay home. Higher learning is an expedient for dissolving one's family."</p>
		<p>My older brother's education had drawn him far away. The result of my own education was a firm resolve to reside in Tōkyō. Father's grumblings on this account were not unjustified. The idea of my mother left alone in this old country house to fend for herself clearly unsettled him.</p>
		<p>Father firmly believed that his household was rooted in place. He also believed that my mother would remain there for all of her days. He worried greatly for her, left alone to care for the large house without him. At the same time, he urged me to secure a prominent position in Tōkyō. His inconsistency afforded me the chance to return to Tōkyō, and for this I was grateful.</p>
		<p>Before my parents, I did my best to feign an effort at securing a prominent post. I wrote to Sensei and explained the situation at home. I asked if he couldn't, through his connections, mediate any sort of position on my behalf. Even as I penned my request, I didn't expect he would act. Even if he wanted to, I thought as I wrote, he had no network to draw on. I did expect, however, that this letter must certainly merit a response.</p>     

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>七</rb><rt>しち</rt></ruby>&nbsp;(part) 7</span>
		<span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかに&nbsp;clearly</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>の&nbsp;one's own</span><span class="vocabstudy"><ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;sickness; illness</span><span class="vocabstudy"><ruby><rb>恐</rb><rt>おそ</rt></ruby>れて&nbsp;fear; be afraid of</span><span class="vocabstudy"><ruby><rb>医者</rb><rt>いしゃ</rt></ruby>&nbsp;doctor</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come; call</span><span class="vocabstudy"><ruby><rb>蒼蠅</rb><rt>うるさ</rt></ruby>い&nbsp;tiresome; persistent; pointless</span><span class="vocabstudy"><ruby><rb>質問</rb><rt>しつもん</rt></ruby>&nbsp;questions</span><span class="vocabstudy"><ruby><rb>掛</rb><rt>か</rt></ruby>けて&nbsp;pose (questions)</span><span class="vocabstudy"><ruby><rb>相手</rb><rt>あいて</rt></ruby>&nbsp;the other party</span><span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>らす&nbsp;press (a person); put on the spot</span><span class="vocabstudy"><ruby><rb>質</rb><rt>たち</rt></ruby>&nbsp;quality; nature</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;side; part</span><span class="vocabstudy"><ruby><rb>遠慮</rb><rt>えんりょ</rt></ruby>して&nbsp;hold back; refrain</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>とも&nbsp;(no)thing</span>
		<span class="vocabstudy"><ruby><rb>死後</rb><rt>しご</rt></ruby>&nbsp;after death</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;matters; affairs</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えて&nbsp;consider; think about</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すく</rt></ruby>なくとも&nbsp;at the very least</span><span class="vocabstudy"><ruby><rb>後</rb><rt>あと</rt></ruby>&nbsp;after</span><span class="vocabstudy">わが<ruby><rb>家</rb><rt>いえ</rt></ruby>&nbsp;one's home; one's house</span><span class="vocabstudy"><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>して<ruby><rb>見</rb><rt>み</rt></ruby>る&nbsp;imagine; contemplate</span>
		<span class="vocabstudy"><ruby><rb>小供</rb><rt>こども</rt></ruby>&nbsp;children</span><span class="vocabstudy"><ruby><rb>学問</rb><rt>がくもん</rt></ruby>&nbsp;learning; studies</span><span class="vocabstudy"><ruby><rb>好</rb><rt>よ</rt></ruby>し<ruby><rb>悪</rb><rt>あ</rt></ruby>し&nbsp;good and bad; plusses and minuses; pros and cons</span><span class="vocabstudy"><ruby><rb>修業</rb><rt>しゅうぎょう</rt></ruby>&nbsp;pursuit of knowledge</span><span class="vocabstudy"><ruby><rb>決</rb><rt>けっ</rt></ruby>して&nbsp;by (no) means</span><span class="vocabstudy"><ruby><rb>宅</rb><rt>うち</rt></ruby>&nbsp;home</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>こ</rt></ruby>ない&nbsp;don't return</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>もなく&nbsp;easily</span><span class="vocabstudy"><ruby><rb>親子</rb><rt>おやこ</rt></ruby>&nbsp;parent and child</span><span class="vocabstudy"><ruby><rb>隔離</rb><rt>かくり</rt></ruby>する&nbsp;separate; pull apart</span>
		<span class="vocabstudy"><ruby><rb>結果</rb><rt>けっか</rt></ruby>&nbsp;result; consequence</span><span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;elder brother; older brother</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; the present</span><span class="vocabstudy"><ruby><rb>遠国</rb><rt>えんごく</rt></ruby>&nbsp;distant land; far-off region</span><span class="vocabstudy"><ruby><rb>教育</rb><rt>きょういく</rt></ruby>&nbsp;education</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>けた&nbsp;received</span><span class="vocabstudy"><ruby><rb>因果</rb><rt>いんが</rt></ruby>&nbsp;cause and effect; causal relationship</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>東京</rb><rt>とうきょう</rt></ruby>&nbsp;Tōkyō</span><span class="vocabstudy"><ruby><rb>住</rb><rt>す</rt></ruby>む&nbsp;live; reside</span><span class="vocabstudy"><ruby><rb>覚悟</rb><rt>かくご</rt></ruby>&nbsp;resolution; readiness</span><span class="vocabstudy"><ruby><rb>固</rb><rt>かた</rt></ruby>くした&nbsp;firmed; cemented (a decision)</span><span class="vocabstudy"><ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;children</span><span class="vocabstudy"><ruby><rb>育</rb><rt>そだ</rt></ruby>てた&nbsp;brought up; raised</span><span class="vocabstudy"><ruby><rb>愚痴</rb><rt>ぐち</rt></ruby>&nbsp;complaint; grumbling</span><span class="vocabstudy">もとより&nbsp;of course</span><span class="vocabstudy"><ruby><rb>不合理</rb><rt>ふごうり</rt></ruby>&nbsp;unreasonable; irrational</span><span class="vocabstudy"><ruby><rb>永年</rb><rt>えいねん</rt></ruby>&nbsp;many years</span><span class="vocabstudy"><ruby><rb>住</rb><rt>す</rt></ruby>み<ruby><rb>古</rb><rt>ふる</rt></ruby>した&nbsp;be long settled (in a place)</span><span class="vocabstudy"><ruby><rb>田舎家</rb><rt>いなかや</rt></ruby>&nbsp;country house</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;inside; within</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>&nbsp;alone</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>残</rb><rt>のこ</rt></ruby>されそうな&nbsp;about to be left behind</span><span class="vocabstudy"><ruby><rb>描</rb><rt>えが</rt></ruby>き<ruby><rb>出</rb><rt>だ</rt></ruby>す&nbsp;picture; imagine</span><span class="vocabstudy"><ruby><rb>淋</rb><rt>さび</rt></ruby>しい&nbsp;lonely; forlorn</span><span class="vocabstudy">に<ruby><rb>違</rb><rt>ちが</rt></ruby>いなかった&nbsp;no doubt ...</span>
		<span class="vocabstudy"><ruby><rb>動</rb><rt>うご</rt></ruby>かす&nbsp;move; relocate</span><span class="vocabstudy"><ruby><rb>信</rb><rt>しん</rt></ruby>じ<ruby><rb>切</rb><rt>き</rt></ruby>っていた&nbsp;believe firmly; be certain of</span><span class="vocabstudy"><ruby><rb>中</rb><rt>うち</rt></ruby>&nbsp;inside; within</span><span class="vocabstudy"><ruby><rb>命</rb><rt>いのち</rt></ruby>&nbsp;life; life force</span><span class="vocabstudy"><ruby><rb>間</rb><rt>あいだ</rt></ruby>&nbsp;span; duration; interval (of time)</span><span class="vocabstudy"><ruby><rb>死</rb><rt>し</rt></ruby>んだ&nbsp;died; passed away</span><span class="vocabstudy"><ruby><rb>孤独</rb><rt>こどく</rt></ruby>な&nbsp;solitary; forsaken</span><span class="vocabstudy"><ruby><rb>伽藍堂</rb><rt>がらんどう</rt></ruby>&nbsp;monastery hall; spacious structure</span><span class="vocabstudy"><ruby><rb>甚</rb><rt>はなはだ</rt></ruby>しい&nbsp;terrible; intense</span><span class="vocabstudy"><ruby><rb>不安</rb><rt>ふあん</rt></ruby>&nbsp;uneasiness; insecurity</span><span class="vocabstudy"><ruby><rb>好</rb><rt>い</rt></ruby>い&nbsp;good; fine</span><span class="vocabstudy"><ruby><rb>地位</rb><rt>ちい</rt></ruby>&nbsp;(social) position</span><span class="vocabstudy"><ruby><rb>求</rb><rt>もと</rt></ruby>めろ&nbsp;seek out; go after</span><span class="vocabstudy"><ruby><rb>強</rb><rt>し</rt></ruby>いたがる&nbsp;look to compel (someone to do something)</span><span class="vocabstudy"><ruby><rb>頭</rb><rt>あたま</rt></ruby>&nbsp;head; mind</span><span class="vocabstudy"><ruby><rb>矛盾</rb><rt>むじゅん</rt></ruby>&nbsp;contradiction; inconsistency</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought; considered</span><span class="vocabstudy">と<ruby><rb>同時</rb><rt>どうじ</rt></ruby>に&nbsp;while ...</span><span class="vocabstudy">お<ruby><rb>蔭</rb><rt>かげ</rt></ruby>で&nbsp;owing to; because of</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>られる&nbsp;can set out (to)</span><span class="vocabstudy"><ruby><rb>喜</rb><rt>よろこ</rt></ruby>んだ&nbsp;was happy; was pleased (about)</span>
		<span class="vocabstudy"><ruby><rb>手前</rb><rt>てまえ</rt></ruby>&nbsp;before; in front of</span><span class="vocabstudy"><ruby><rb>努力</rb><rt>どりょく</rt></ruby>&nbsp;effort; exertion</span><span class="vocabstudy"><ruby><rb>装</rb><rt>よそ</rt></ruby>おわなくてはならなかった&nbsp;had to feign; had to go through the motions</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>手紙</rb><rt>てがみ</rt></ruby>&nbsp;letter</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>いて&nbsp;write</span><span class="vocabstudy"><ruby><rb>家</rb><rt>いえ</rt></ruby>&nbsp;house; home</span><span class="vocabstudy"><ruby><rb>事情</rb><rt>じじょう</rt></ruby>&nbsp;situation; circumstances</span><span class="vocabstudy"><ruby><rb>精</rb><rt>くわ</rt></ruby>しく&nbsp;in detail</span><span class="vocabstudy"><ruby><rb>述</rb><rt>の</rt></ruby>べた&nbsp;mentioned; noted</span><span class="vocabstudy"><ruby><rb>力</rb><rt>ちから</rt></ruby>&nbsp;good offices; influence</span><span class="vocabstudy"><ruby><rb>周旋</rb><rt>しゅうせん</rt></ruby>&nbsp;brokering; mediation</span><span class="vocabstudy"><ruby><rb>頼</rb><rt>たの</rt></ruby>んだ&nbsp;asked; requested</span><span class="vocabstudy"><ruby><rb>依頼</rb><rt>いらい</rt></ruby>&nbsp;request; ask</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>合</rb><rt>あ</rt></ruby>う&nbsp;respond to; take action on</span><span class="vocabstudy"><ruby><rb>世間</rb><rt>せけん</rt></ruby>の<ruby><rb>狭</rb><rt>せま</rt></ruby>い&nbsp;limited in social connections</span><span class="vocabstudy">に<ruby><rb>対</rb><rt>たい</rt></ruby>する&nbsp;with respect to; regarding</span><span class="vocabstudy"><ruby><rb>返事</rb><rt>へんじ</rt></ruby>&nbsp;reply; response</span>

	</StudyGuide>
);
