// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={227}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>すると<span><ruby><rb>突然</rb><rt>とつぜん</rt></ruby></span><span><ruby><rb>原口</rb><rt>はらぐち</rt></ruby></span>さんが<span><ruby><rb>幕</rb><rt>まく</rt></ruby></span>の<span><ruby><rb>間</rb><rt>あいだ</rt></ruby></span>から<span><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。<span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>と<span><ruby><rb>並</rb><rt>なら</rt></ruby>んで</span>しきりに<span><ruby><rb>土間</rb><rt>どま</rt></ruby></span>の<span><ruby><rb>中</rb><rt>なか</rt></ruby></span>をのぞきこむ。<span><ruby><rb>口</rb><rt>くち</rt></ruby></span>はむろん<span><ruby><rb>動</rb><rt>うご</rt></ruby>かして</span>いるのだろう。<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さんは<span><ruby><rb>合</rb><rt>あ</rt></ruby>い<ruby><rb>図</rb><rt>ず</rt></ruby></span>のような<span><ruby><rb>首</rb><rt>くび</rt></ruby></span>を<span><ruby><rb>縦</rb><rt>たて</rt></ruby>に</span><span><ruby><rb>振</rb><rt>ふ</rt></ruby>った</span>。その時原口さんはうしろから、<span><ruby><rb>平手</rb><rt>ひらて</rt></ruby></span>で、与次郎の<span><ruby><rb>背中</rb><rt>せなか</rt></ruby></span>をたたいた。与次郎はくるりと<span><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>繰</rb><rt>く</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>って</span>、幕の<span><ruby><rb>裾</rb><rt>すそ</rt></ruby></span>をもぐってどこかへ<span><ruby><rb>消</rb><rt>き</rt></ruby>えうせた</span>。原口さんは、<span><ruby><rb>舞台</rb><rt>ぶたい</rt></ruby></span>を<span><ruby><rb>降</rb><rt>お</rt></ruby>りて</span>、<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>と人との間を<span><ruby><rb>伝</rb><rt>つた</rt></ruby>わって</span>、野々宮さんのそばまで来た。野々宮さんは、<span><ruby><rb>腰</rb><rt>こし</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>てて</span>原口さんを<span><ruby><rb>通</rb><rt>とお</rt></ruby>した</span>。原口さんはぽかりと人の中へ<span><ruby><rb>飛</rb><rt>と</rt></ruby>び<ruby><rb>込</rb><rt>こ</rt></ruby>んだ</span>。<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>と<span>よし<ruby><rb>子</rb><rt>こ</rt></ruby></span>のいるあたりで<span><ruby><rb>見</rb><rt>み</rt></ruby>えなくなった</span>。</p>
		<p>この<span><ruby><rb>連中</rb><rt>れんじゅう</rt></ruby></span>の<span><ruby><rb>一挙一動</rb><rt>いっきょいちどう</rt></ruby></span>を<span><ruby><rb>演芸</rb><rt>えんげい</rt></ruby></span><span><ruby><rb>以上</rb><rt>いじょう</rt></ruby></span>の<span><ruby><rb>興味</rb><rt>きょうみ</rt></ruby></span>をもって<span><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby>して</span>いた<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は、この<span><ruby><rb>時</rb><rt>とき</rt></ruby></span><span><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span><span><ruby><rb>原口</rb><rt>はらぐち</rt></ruby><ruby><rb>流</rb><rt>りゅう</rt></ruby></span>の<span><ruby><rb>所作</rb><rt>しょさ</rt></ruby></span>がうらやましくなった。ああいう<span><ruby><rb>便利</rb><rt>べんり</rt></ruby>な</span><span><ruby><rb>方法</rb><rt>ほうほう</rt></ruby></span>で人のそばへ<span><ruby><rb>寄</rb><rt>よ</rt></ruby>る</span>ことができようとは<span><ruby><rb>毫</rb><rt>ごう</rt></ruby>も</span><span><ruby><rb>思</rb><rt>おも</rt></ruby>いつかなかった</span>。<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>もひとつ<span>まねて</span>みようかしらと思った。しかしまねるという<span><ruby><rb>自覚</rb><rt>じかく</rt></ruby></span>が、すでに<span><ruby><rb>実行</rb><rt>じっこう</rt></ruby></span>の<span><ruby><rb>勇気</rb><rt>ゆうき</rt></ruby></span>を<span>くじいた</span>うえに、もうはいる<span><ruby><rb>席</rb><rt>せき</rt></ruby></span>は、いくら<span><ruby><rb>詰</rb><rt>つ</rt></ruby>めて</span>も、むずかしかろうという<span><ruby><rb>遠慮</rb><rt>えんりょ</rt></ruby></span>が<span><ruby><rb>手伝</rb><rt>てつだ</rt></ruby>って</span>、三四郎の<span><ruby><rb>尻</rb><rt>しり</rt></ruby></span>は<span><ruby><rb>依然</rb><rt>いぜん</rt></ruby>として</span>、もとの席を<span><ruby><rb>去</rb><rt>さ</rt></ruby>りえなかった</span>。</p>
		<p>そのうち幕があいて、<span>ハムレット</span>が<span><ruby><rb>始</rb><rt>はじ</rt></ruby>まった</span>。三四郎は<span><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>のうちで<span><ruby><rb>西洋</rb><rt>せいよう</rt></ruby></span>のなんとかいう<span><ruby><rb>名優</rb><rt>めいゆう</rt></ruby></span>の<span>ふんした</span>ハムレットの<span><ruby><rb>写真</rb><rt>しゃしん</rt></ruby></span>を見たことがある。<span><ruby><rb>今</rb><rt>いま</rt></ruby></span>三四郎の<span><ruby><rb>目</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby></span>にあらわれたハムレットは、これとほぼ<span><ruby><rb>同様</rb><rt>どうよう</rt></ruby></span>の<span><ruby><rb>服装</rb><rt>なり</rt></ruby></span>をしている。服装ばかりではない。<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>まで<span><ruby><rb>似</rb><rt>に</rt></ruby>ている</span>。<span><ruby><rb>両方</rb><rt>りょうほう</rt></ruby></span>とも<span><ruby><rb>八</rb><rt>はち</rt></ruby>の<ruby><rb>字</rb><rt>じ</rt></ruby>を<ruby><rb>寄</rb><rt>よ</rt></ruby>せて</span>いる。</p>

		<h3 class="section">Rough translation</h3>
		<p>Haraguchi suddenly appeared from behind the curtain. He came to Yojirō's side and fixed his gaze on the parterre boxes. Most certainly he was calling to someone. Nonomiya gave an affirmative nod in response. Haraguchi then slapped Yojirō's back with the flat of his hand. Yojirō did an about face and disappeared under the edge of the curtain. Haraguchi climbed down from the stage and made his way through the crowd to Nonomiya. Nonomiya straightened up to let him pass. He plunged into the masses and dropped from sight, about where Mineko and Yoshiko were seated.</p>
		<p>Sanshirō, who observed every movement of this group with greater interest than he'd watched the performance, felt a sudden tinge of envy. Never had he imagined that a certain someone could be approached with such ease. He wondered if he should dare to follow Haraguchi's lead. The thought of actually doing so, however, immediately sapped him of the courage to act. Then there was the worry that, however much they squeezed, there wouldn't be room for him. Sanshirō refrained, his haunches rooted squarely to their present spot.</p>
		<p>By and by the curtain rose, and Hamlet took the stage. At Professor Hirota's house, Sanshirō had seen a photograph in which some-such famous Western actor portrayed Hamlet. The Hamlet before him now was dressed identically. The resemblance didn't end with attire. The facial expression was also the same - both showing knitted brows.</p>      

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>原口</rb><rt>はらぐち</rt></ruby>&nbsp;Haraguchi (name)</span><span class="vocabstudy"><ruby><rb>幕</rb><rt>まく</rt></ruby>&nbsp;curtain</span><span class="vocabstudy"><ruby><rb>間</rb><rt>あいだ</rt></ruby>&nbsp;midst</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;emerged; appeared</span><span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy"><ruby><rb>並</rb><rt>なら</rt></ruby>んで&nbsp;come next to; be side-by-side</span><span class="vocabstudy"><ruby><rb>土間</rb><rt>どま</rt></ruby>&nbsp;parterre; parquet circle (theater seating)</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;inside</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>&nbsp;mouth</span><span class="vocabstudy"><ruby><rb>動</rb><rt>うご</rt></ruby>かして&nbsp;move</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>合</rb><rt>あ</rt></ruby>い<ruby><rb>図</rb><rt>ず</rt></ruby>&nbsp;signal; sign</span><span class="vocabstudy"><ruby><rb>首</rb><rt>くび</rt></ruby>&nbsp;head</span><span class="vocabstudy"><ruby><rb>縦</rb><rt>たて</rt></ruby>に&nbsp;vertically; up and down</span><span class="vocabstudy"><ruby><rb>振</rb><rt>ふ</rt></ruby>った&nbsp;nodded</span><span class="vocabstudy"><ruby><rb>平手</rb><rt>ひらて</rt></ruby>&nbsp;palm; open hand</span><span class="vocabstudy"><ruby><rb>背中</rb><rt>せなか</rt></ruby>&nbsp;back</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>繰</rb><rt>く</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>って&nbsp;turn around; do an about-face</span><span class="vocabstudy"><ruby><rb>裾</rb><rt>すそ</rt></ruby>&nbsp;hem; lower edge</span><span class="vocabstudy"><ruby><rb>消</rb><rt>き</rt></ruby>えうせた&nbsp;disappeared; vanished</span><span class="vocabstudy"><ruby><rb>舞台</rb><rt>ぶたい</rt></ruby>&nbsp;stage</span><span class="vocabstudy"><ruby><rb>降</rb><rt>お</rt></ruby>りて&nbsp;descend from</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;people</span><span class="vocabstudy"><ruby><rb>伝</rb><rt>つた</rt></ruby>わって&nbsp;pass among; move through</span><span class="vocabstudy"><ruby><rb>腰</rb><rt>こし</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>てて&nbsp;straighten up</span><span class="vocabstudy"><ruby><rb>通</rb><rt>とお</rt></ruby>した&nbsp;let pass; made way for</span><span class="vocabstudy"><ruby><rb>飛</rb><rt>と</rt></ruby>び<ruby><rb>込</rb><rt>こ</rt></ruby>んだ&nbsp;plunged into</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy">よし<ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;Yoshiko (Nonomiya's younger sister)</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>えなくなった&nbsp;disappeared from view</span>
		<span class="vocabstudy"><ruby><rb>連中</rb><rt>れんじゅう</rt></ruby>&nbsp;group</span><span class="vocabstudy"><ruby><rb>一挙一動</rb><rt>いっきょいちどう</rt></ruby>&nbsp;one's every action</span><span class="vocabstudy"><ruby><rb>演芸</rb><rt>えんげい</rt></ruby>&nbsp;performance</span><span class="vocabstudy"><ruby><rb>以上</rb><rt>いじょう</rt></ruby>&nbsp;more than</span><span class="vocabstudy"><ruby><rb>興味</rb><rt>きょうみ</rt></ruby>&nbsp;interest</span><span class="vocabstudy"><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby>して&nbsp;be attentive to; follow</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>原口</rb><rt>はらぐち</rt></ruby><ruby><rb>流</rb><rt>りゅう</rt></ruby>&nbsp;in the manner of Haraguchi; Haraguchi-style</span><span class="vocabstudy"><ruby><rb>所作</rb><rt>しょさ</rt></ruby>&nbsp;movement; action</span><span class="vocabstudy"><ruby><rb>便利</rb><rt>べんり</rt></ruby>な&nbsp;convenient; pragmatic</span><span class="vocabstudy"><ruby><rb>方法</rb><rt>ほうほう</rt></ruby>&nbsp;method; technique</span><span class="vocabstudy"><ruby><rb>寄</rb><rt>よ</rt></ruby>る&nbsp;approach; draw near to</span><span class="vocabstudy"><ruby><rb>毫</rb><rt>ごう</rt></ruby>も&nbsp;(not) at all</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>いつかなかった&nbsp;hadn't thought of; hadn't hit upon</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy">まねて&nbsp;follow suit; imitate</span><span class="vocabstudy"><ruby><rb>自覚</rb><rt>じかく</rt></ruby>&nbsp;consciousness; awareness (of)</span><span class="vocabstudy"><ruby><rb>実行</rb><rt>じっこう</rt></ruby>&nbsp;practice; execution</span><span class="vocabstudy"><ruby><rb>勇気</rb><rt>ゆうき</rt></ruby>&nbsp;boldness; courage</span><span class="vocabstudy">くじいた&nbsp;discouraged; unnerved</span><span class="vocabstudy"><ruby><rb>席</rb><rt>せき</rt></ruby>&nbsp;seat</span><span class="vocabstudy"><ruby><rb>詰</rb><rt>つ</rt></ruby>めて&nbsp;crowd; squeeze together</span><span class="vocabstudy"><ruby><rb>遠慮</rb><rt>えんりょ</rt></ruby>&nbsp;discretion; reserve</span><span class="vocabstudy"><ruby><rb>手伝</rb><rt>てつだ</rt></ruby>って&nbsp;lend a hand; assist</span><span class="vocabstudy"><ruby><rb>尻</rb><rt>しり</rt></ruby>&nbsp;haunches</span><span class="vocabstudy"><ruby><rb>依然</rb><rt>いぜん</rt></ruby>として&nbsp;still; as yet</span><span class="vocabstudy"><ruby><rb>去</rb><rt>さ</rt></ruby>りえなかった&nbsp;couldn't move from</span>
		<span class="vocabstudy">ハムレット&nbsp;Hamlet</span><span class="vocabstudy"><ruby><rb>始</rb><rt>はじ</rt></ruby>まった&nbsp;started; began</span><span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Professor Hirota</span><span class="vocabstudy"><ruby><rb>西洋</rb><rt>せいよう</rt></ruby>&nbsp;the West</span><span class="vocabstudy"><ruby><rb>名優</rb><rt>めいゆう</rt></ruby>&nbsp;famous actor</span><span class="vocabstudy">ふんした&nbsp;acted out; portrayed</span><span class="vocabstudy"><ruby><rb>写真</rb><rt>しゃしん</rt></ruby>&nbsp;photograph</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; at present</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before one's eyes</span><span class="vocabstudy"><ruby><rb>同様</rb><rt>どうよう</rt></ruby>&nbsp;identical</span><span class="vocabstudy"><ruby><rb>服装</rb><rt>なり</rt></ruby>&nbsp;clothing; attire; dress</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face; facial expression</span><span class="vocabstudy"><ruby><rb>似</rb><rt>に</rt></ruby>ている&nbsp;be similar; be alike</span><span class="vocabstudy"><ruby><rb>両方</rb><rt>りょうほう</rt></ruby>&nbsp;both</span><span class="vocabstudy"><ruby><rb>八</rb><rt>はち</rt></ruby>の<ruby><rb>字</rb><rt>じ</rt></ruby>を<ruby><rb>寄</rb><rt>よ</rt></ruby>せて&nbsp;knit one's brows; frown</span>

	</StudyGuide>
);
