// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={237}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>朝飯</rb><rt>あさめし</rt></ruby><ruby><rb>後</rb><rt>ご</rt></ruby></span>、<span>シャツ</span>を<span><ruby><rb>重</rb><rt>かさ</rt></ruby>ねて</span>、<span><ruby><rb>外套</rb><rt>がいとう</rt></ruby></span>を<span><ruby><rb>着</rb><rt>き</rt></ruby>て</span>、<span><ruby><rb>寒</rb><rt>さむ</rt></ruby>くない</span>ようにして<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>の<span><ruby><rb>家</rb><rt>いえ</rt></ruby></span>へ<span><ruby><rb>行</rb><rt>い</rt></ruby>った</span>。<span><ruby><rb>玄関</rb><rt>げんかん</rt></ruby></span>に<span>よし<ruby><rb>子</rb><rt>こ</rt></ruby></span>が<span><ruby><rb>立</rb><rt>た</rt></ruby>って</span>、<span><ruby><rb>今</rb><rt>いま</rt></ruby></span><span><ruby><rb>沓脱</rb><rt>くつぬぎ</rt></ruby></span>へ<span><ruby><rb>降</rb><rt>お</rt></ruby>りようとして</span>いる。今<span><ruby><rb>兄</rb><rt>あに</rt></ruby></span>の<span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>へ行くところだと<span><ruby><rb>言</rb><rt>い</rt></ruby>う</span>。美禰子はいない。<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>はいっしょに<span><ruby><rb>表</rb><rt>おもて</rt></ruby></span>へ<span><ruby><rb>出</rb><rt>で</rt></ruby>た</span>。</p>
		<p>「もうすっかりいいんですか」</p>
		<p>「ありがとう。もう<span class="vocabstudy"><ruby><rb>直</rb><rt>なお</rt></ruby>りました</span>。――<span class="vocabstudy"><ruby><rb>里見</rb><rt>さとみ</rt></ruby></span>さんはどこへ行ったんですか」</p>
		<p>「にいさん？」</p>
		<p>「いいえ、美禰子さんです」</p>
		<p>「美禰子さんは<span class="vocabstudy"><ruby><rb>会堂</rb><rt>チャーチ</rt></ruby></span>」</p>
		<p>美禰子の会堂へ行くことは、はじめて<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。どこの会堂か<span class="vocabstudy"><ruby><rb>教</rb><rt>おし</rt></ruby>えて</span>もらって、三四郎はよし子に<span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れた</span>。<span class="vocabstudy"><ruby><rb>横町</rb><rt>よこちょう</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>三</rb><rt>みっ</rt></ruby>つ</span>ほど<span class="vocabstudy"><ruby><rb>曲</rb><rt>ま</rt></ruby>がる</span>と、<span class="vocabstudy">すぐ<ruby><rb>前</rb><rt>まえ</rt></ruby></span>へ出た。三四郎はまったく<span class="vocabstudy"><ruby><rb>耶蘇教</rb><rt>やそきょう</rt></ruby></span>に<span class="vocabstudy"><ruby><rb>縁</rb><rt>えん</rt></ruby>のない</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>である。会堂の<span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby></span>は<span class="vocabstudy">のぞいて<ruby><rb>見</rb><rt>み</rt></ruby>た</span>こともない。前へ立って、<span class="vocabstudy"><ruby><rb>建物</rb><rt>たてもの</rt></ruby></span>をながめた。<span class="vocabstudy"><ruby><rb>説教</rb><rt>せっきょう</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>掲示</rb><rt>けいじ</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>読</rb><rt>よ</rt></ruby>んだ</span>。<span class="vocabstudy"><ruby><rb>鉄柵</rb><rt>てっさく</rt></ruby></span>の所を<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>ったり<ruby><rb>来</rb><rt>き</rt></ruby>たりした</span>。ある<span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>寄</rb><rt>よ</rt></ruby>りかかって</span>みた。三四郎はともかくもして、美禰子の出てくるのを<span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>つ</span>つもりである。</p>
		<p>やがて<span class="vocabstudy"><ruby><rb>唱歌</rb><rt>しょうか</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby></span>が聞こえた。<span class="vocabstudy"><ruby><rb>賛美歌</rb><rt>さんびか</rt></ruby></span>というものだろうと<span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えた</span>。<span class="vocabstudy"><ruby><rb>締</rb><rt>し</rt></ruby>め<ruby><rb>切</rb><rt>き</rt></ruby>った</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>窓</rb><rt>まど</rt></ruby></span>のうちの<span class="vocabstudy">でき<ruby><rb>事</rb><rt>ごと</rt></ruby></span>である。<span class="vocabstudy"><ruby><rb>音量</rb><rt>おんりょう</rt></ruby></span>から<span class="vocabstudy"><ruby><rb>察</rb><rt>さっ</rt></ruby>する</span>とよほどの<span class="vocabstudy"><ruby><rb>人数</rb><rt>にんずう</rt></ruby></span>らしい。美禰子の声もそのうちにある。三四郎は<span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>を<ruby><rb>傾</rb><rt>かたむ</rt></ruby>けた</span>。<span class="vocabstudy"><ruby><rb>歌</rb><rt>うた</rt></ruby></span>はやんだ。<span class="vocabstudy"><ruby><rb>風</rb><rt>かぜ</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>吹</rb><rt>ふ</rt></ruby>く</span>。三四郎は外套の<span class="vocabstudy"><ruby><rb>襟</rb><rt>えり</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>てた</span>。<span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby></span>に美禰子の<span class="vocabstudy"><ruby><rb>好</rb><rt>す</rt></ruby>きな</span><span class="vocabstudy"><ruby><rb>雲</rb><rt>くも</rt></ruby></span>が出た。</p>
		<p>かつて美禰子といっしょに<span class="vocabstudy"><ruby><rb>秋</rb><rt>あき</rt></ruby></span>の空を見たこともあった。所は<span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>二階</rb><rt>にかい</rt></ruby></span>であった。<span class="vocabstudy"><ruby><rb>田端</rb><rt>たばた</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>縁</rb><rt>ふち</rt></ruby></span>にすわったこともあった。その時も<span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby></span>ではなかった。<span class="vocabstudy"><ruby><rb>迷羊</rb><rt>ストレイ・シープ</rt></ruby></span>。迷羊。雲が<span class="vocabstudy"><ruby><rb>羊</rb><rt>ひつじ</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>形</rb><rt>かたち</rt></ruby></span>をしている。</p>

		<h3 class="section">Rough translation</h3>
		<p>After breakfast, Sanshirō dressed warmly in his winter shirt and overcoat and set out for Mineko's house. Yoshiko was standing in the entry hall, about to step down and put on her shoes. She explained that she was off to visit her brother. Mineko wasn't home. Sanshirō accompanied Yoshiko out front.</p>
		<p>"Are you better now?"</p>
		<p>"Yes, I'm pretty well recovered. Thanks. Can you tell me where Satomi-san went?"</p>
		<p>"The older brother?"</p>
		<p>"Mineko, actually."</p>
		<p>"Mineko's at church."</p>
		<p>Sanshirō hadn't known that Mineko attended church. Yoshiko told him where it was, and he took his leave of her. Traversing several side streets, he found himself before the church. Sanshirō knew nothing of Christianity. He'd never even looked inside a church. Standing out front, he gazed at the construction. He read the notice for the sermon. He paced the iron fence, leaning against it from time to time. However long it might take, he was resolved to wait for Mineko.</p> 
		<p>After a time, the sound of voices in song arose. Sanshirō assumed it must be a hymn - something sung behind tall sealed windows. Judging by the way it carried, there were a great many voices engaged. Mineko's voice was among them. Sanshirō listened attentively. The song ended. The wind gusted. Sanshirō turned up the collar of his coat. A cloud appeared in the sky - a cloud of the kind that Mineko fancied.</p>
		<p>Sanshirō had once gazed on the autumn sky with Mineko. From the second floor at Professor Hirota's. They'd also sat by the edge of a stream in Tabata. In those times, he'd found a companion. Stray sheep. Stray sheep. The cloud took the form of a sheep.</p>    

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>朝飯</rb><rt>あさめし</rt></ruby><ruby><rb>後</rb><rt>ご</rt></ruby>&nbsp;after breakfast</span><span class="vocabstudy">シャツ&nbsp;shirt; dress shirt</span><span class="vocabstudy"><ruby><rb>重</rb><rt>かさ</rt></ruby>ねて&nbsp;layer on (clothing)</span><span class="vocabstudy"><ruby><rb>外套</rb><rt>がいとう</rt></ruby>&nbsp;overcoat</span><span class="vocabstudy"><ruby><rb>着</rb><rt>き</rt></ruby>て&nbsp;wear; don</span><span class="vocabstudy"><ruby><rb>寒</rb><rt>さむ</rt></ruby>くない&nbsp;not (get; be) cold</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>家</rb><rt>いえ</rt></ruby>&nbsp;house; residence</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>った&nbsp;went (to); set out (for)</span><span class="vocabstudy"><ruby><rb>玄関</rb><rt>げんかん</rt></ruby>&nbsp;entry hall</span><span class="vocabstudy">よし<ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;Yoshiko (Nonomiya's younger sister)</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;stand</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; just now</span><span class="vocabstudy"><ruby><rb>沓脱</rb><rt>くつぬぎ</rt></ruby>&nbsp;platform for changing one's shoes</span><span class="vocabstudy"><ruby><rb>降</rb><rt>お</rt></ruby>りようとして&nbsp;be about to descend; be about to step down (to)</span><span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;older brother</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place; home</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;remark; explain</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>表</rb><rt>おもて</rt></ruby>&nbsp;out front</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;departed; went out (to)</span>
		<span class="vocabstudy"><ruby><rb>直</rb><rt>なお</rt></ruby>りました&nbsp;recovered; feeling better</span><span class="vocabstudy"><ruby><rb>里見</rb><rt>さとみ</rt></ruby>&nbsp;Satomi (Mineko's family name)</span>
		<span class="vocabstudy"><ruby><rb>会堂</rb><rt>チャーチ</rt></ruby>&nbsp;church</span>
		<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;heard</span><span class="vocabstudy"><ruby><rb>教</rb><rt>おし</rt></ruby>えて&nbsp;tell; inform</span><span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れた&nbsp;parted (from); took leave (of)</span><span class="vocabstudy"><ruby><rb>横町</rb><rt>よこちょう</rt></ruby>&nbsp;side streets; lanes</span><span class="vocabstudy"><ruby><rb>三</rb><rt>みっ</rt></ruby>つ&nbsp;three (things)</span><span class="vocabstudy"><ruby><rb>曲</rb><rt>ま</rt></ruby>がる&nbsp;turn (at; onto)</span><span class="vocabstudy">すぐ<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;immediately in front (of something)</span><span class="vocabstudy"><ruby><rb>耶蘇教</rb><rt>やそきょう</rt></ruby>&nbsp;Christianity</span><span class="vocabstudy"><ruby><rb>縁</rb><rt>えん</rt></ruby>のない&nbsp;have no connection to; have no experience with</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man; fellow</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;inside</span><span class="vocabstudy">のぞいて<ruby><rb>見</rb><rt>み</rt></ruby>た&nbsp;taken a look (at)</span><span class="vocabstudy"><ruby><rb>建物</rb><rt>たてもの</rt></ruby>&nbsp;building</span><span class="vocabstudy"><ruby><rb>説教</rb><rt>せっきょう</rt></ruby>&nbsp;sermon</span><span class="vocabstudy"><ruby><rb>掲示</rb><rt>けいじ</rt></ruby>&nbsp;notice; bulletin</span><span class="vocabstudy"><ruby><rb>読</rb><rt>よ</rt></ruby>んだ&nbsp;read</span><span class="vocabstudy"><ruby><rb>鉄柵</rb><rt>てっさく</rt></ruby>&nbsp;iron fence</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>ったり<ruby><rb>来</rb><rt>き</rt></ruby>たりした&nbsp;paced to and fro; walked back and forth</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; occasion</span><span class="vocabstudy"><ruby><rb>寄</rb><rt>よ</rt></ruby>りかかって&nbsp;lean on</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>つ&nbsp;wait for</span>
		<span class="vocabstudy"><ruby><rb>唱歌</rb><rt>しょうか</rt></ruby>&nbsp;singing</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voices</span><span class="vocabstudy"><ruby><rb>賛美歌</rb><rt>さんびか</rt></ruby>&nbsp;hymn; song of praise</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えた&nbsp;thought; assumed</span><span class="vocabstudy"><ruby><rb>締</rb><rt>し</rt></ruby>め<ruby><rb>切</rb><rt>き</rt></ruby>った&nbsp;closed; shut; sealed</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い&nbsp;high; tall</span><span class="vocabstudy"><ruby><rb>窓</rb><rt>まど</rt></ruby>&nbsp;windows</span><span class="vocabstudy">でき<ruby><rb>事</rb><rt>ごと</rt></ruby>&nbsp;event; happening</span><span class="vocabstudy"><ruby><rb>音量</rb><rt>おんりょう</rt></ruby>&nbsp;volume (of sound)</span><span class="vocabstudy"><ruby><rb>察</rb><rt>さっ</rt></ruby>する&nbsp;guess; surmise</span><span class="vocabstudy"><ruby><rb>人数</rb><rt>にんずう</rt></ruby>&nbsp;number of people</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>を<ruby><rb>傾</rb><rt>かたむ</rt></ruby>けた&nbsp;listened attentively</span><span class="vocabstudy"><ruby><rb>歌</rb><rt>うた</rt></ruby>&nbsp;song</span><span class="vocabstudy"><ruby><rb>風</rb><rt>かぜ</rt></ruby>&nbsp;wind</span><span class="vocabstudy"><ruby><rb>吹</rb><rt>ふ</rt></ruby>く&nbsp;blow</span><span class="vocabstudy"><ruby><rb>襟</rb><rt>えり</rt></ruby>&nbsp;collar</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>てた&nbsp;turned up; straightened</span><span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby>&nbsp;sky</span><span class="vocabstudy"><ruby><rb>好</rb><rt>す</rt></ruby>きな&nbsp;favored; preferred</span><span class="vocabstudy"><ruby><rb>雲</rb><rt>くも</rt></ruby>&nbsp;clouds</span>
		<span class="vocabstudy"><ruby><rb>秋</rb><rt>あき</rt></ruby>&nbsp;autumn</span><span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Professor Hirota</span><span class="vocabstudy"><ruby><rb>二階</rb><rt>にかい</rt></ruby>&nbsp;second floor</span><span class="vocabstudy"><ruby><rb>田端</rb><rt>たばた</rt></ruby>&nbsp;Tabata (place name)</span><span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby>&nbsp;small river; stream</span><span class="vocabstudy"><ruby><rb>縁</rb><rt>ふち</rt></ruby>&nbsp;edge</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>&nbsp;alone; by oneself</span><span class="vocabstudy"><ruby><rb>迷羊</rb><rt>ストレイ・シープ</rt></ruby>&nbsp;stray sheep</span><span class="vocabstudy"><ruby><rb>羊</rb><rt>ひつじ</rt></ruby>&nbsp;sheep</span><span class="vocabstudy"><ruby><rb>形</rb><rt>かたち</rt></ruby>&nbsp;shape; form</span>

	</StudyGuide>
);
