// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={239}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「あなた、<span><ruby><rb>御不自由</rb><rt>ごふじゆう</rt></ruby></span>じゃなくって」</p>
		<p>「いいえ、このあいだからそのつもりで<span><ruby><rb>国</rb><rt>くに</rt></ruby></span>から<span><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>寄</rb><rt>よ</rt></ruby>せて</span>おいたのだから、どうか取ってください」</p>
		<p>「そう。じゃいただいておきましょう」</p>
		<p><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>紙包</rb><rt>かみづつ</rt></ruby>み</span>を<span class="vocabstudy"><ruby><rb>懐</rb><rt>ふところ</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>入</rb><rt>い</rt></ruby>れた</span>。その<span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>吾妻</rb><rt>あずま</rt></ruby>コート</span>から<span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>した</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby></span>、<span class="vocabstudy"><ruby><rb>白</rb><rt>しろ</rt></ruby>い</span><span class="vocabstudy">ハンケチ</span>を<span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って</span>いた。<span class="vocabstudy"><ruby><rb>鼻</rb><rt>はな</rt></ruby></span>のところへあてて、<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て</span>いる。ハンケチをかぐ<span class="vocabstudy"><ruby><rb>様子</rb><rt>ようす</rt></ruby></span>でもある。やがて、その手を<span class="vocabstudy"><ruby><rb>不意</rb><rt>ふい</rt></ruby>に</span><span class="vocabstudy"><ruby><rb>延</rb><rt>の</rt></ruby>ばした</span>。ハンケチが三四郎の<span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>た</span>。<span class="vocabstudy"><ruby><rb>鋭</rb><rt>するど</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>香</rb><rt>かおり</rt></ruby></span>がぷんとする。</p>
		<p>「<span class="vocabstudy">ヘリオトロープ</span>」と女が<span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かに</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った</span>。三四郎は<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>わず</span>顔を<span class="vocabstudy">あとへ<ruby><rb>引</rb><rt>ひ</rt></ruby>いた</span>。ヘリオトロープの<span class="vocabstudy"><ruby><rb>罎</rb><rt>びん</rt></ruby></span>。<span class="vocabstudy"><ruby><rb>四丁目</rb><rt>よんちょうめ</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>夕暮</rb><rt>ゆうぐれ</rt></ruby></span>。<span class="vocabstudy"><ruby><rb>迷羊</rb><rt>ストレイ・シープ</rt></ruby></span>。迷羊。<span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby></span>には<span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>日</rb><rt>ひ</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかにかかる</span>。</p>
		<p>「<span class="vocabstudy"><ruby><rb>結婚</rb><rt>けっこん</rt></ruby>なさる</span>そうですね」</p>
		<p><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>は白いハンケチを<span class="vocabstudy"><ruby><rb>袂</rb><rt>たもと</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>とした</span>。</p>
		<p>「<span class="vocabstudy"><ruby><rb>御存</rb><rt>ごぞん</rt></ruby>じなの</span>」と言いながら、<span class="vocabstudy"><ruby><rb>二重瞼</rb><rt>ふたえまぶた</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>細目</rb><rt>ほそめ</rt></ruby>にして</span>、<span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>の顔を見た。三四郎を<span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くに</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いて</span>、かえって遠くにいるのを<span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>づかいすぎた</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>つき</span>である。そのくせ<span class="vocabstudy"><ruby><rb>眉</rb><rt>まゆ</rt></ruby></span>だけははっきりおちついている。三四郎の<span class="vocabstudy"><ruby><rb>舌</rb><rt>した</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>上顎</rb><rt>うわあご</rt></ruby></span>へひっついてしまった。</p>
		<p>女はややしばらく三四郎をながめたのち、<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>きかねる</span>ほどの<span class="vocabstudy">ため<ruby><rb>息</rb><rt>いき</rt></ruby></span>をかすかにもらした。やがて<span class="vocabstudy"><ruby><rb>細</rb><rt>ほそ</rt></ruby>い</span>手を<span class="vocabstudy"><ruby><rb>濃</rb><rt>こ</rt></ruby>い</span>眉の<span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby></span>に<span class="vocabstudy"><ruby><rb>加</rb><rt>くわ</rt></ruby>えて</span>言った。</p>
		<p>「<span class="vocabstudy"><ruby><rb>我</rb><rt>われ</rt></ruby></span>は<span class="vocabstudy">わが</span><span class="vocabstudy"><ruby><rb>愆</rb><rt>とが</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>る</span>。わが<span class="vocabstudy"><ruby><rb>罪</rb><rt>つみ</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>常</rb><rt>つね</rt></ruby>に</span>わが<span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby></span>にあり」</p>
		<p><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>き<ruby><rb>取</rb><rt>と</rt></ruby>れない</span>くらいな<span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby></span>であった。それを三四郎は明らかに聞き取った。三四郎と美禰子はかようにして<span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れた</span>。<span class="vocabstudy"><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>ったら</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby></span>からの<span class="vocabstudy"><ruby><rb>電報</rb><rt>でんぽう</rt></ruby></span>が来ていた。あけて見ると、いつ<span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>つ</span>とある。</p>

		<h3 class="section">Rough translation</h3>
		<p>"You won't be inconvenienced?"</p>
		<p>"No. I wrote home, and they've covered it for me. Please."</p>
		<p>"In that case, I suppose I should take it back."</p>
		<p>Mineko put the packet into her pocket. As her hand re-emerged from her coat, she was clutching a white handkerchief. She held it to her nose and looked at Sanshirō. She seemed to be taking in its aroma. Then, suddenly, she extended her hand, bringing the handkerchief close to Sanshirō's face. He was hit by a powerful scent.</p>
		<p>"Heliotrope," she said quietly.</p>
		<p>Sanshirō reflexively drew back his nose. That 'Heliotrope' bottle. That evening in Yonchōme. Stray sheep. Stray sheep. The sun, high overhead, shone brightly in the sky.</p>
		<p>"They say you're to be wed."</p>
		<p>Mineko dropped the white handkerchief into her sleeve pocket.</p>
		<p>"You know, then," she said, narrowing her contoured eyes as she looked up at him. She seemed to place him at a distance, while at the same time fearing he was too far away. Her eyebrows, on the other hand, were unmistakably at ease. Sanshirō's tongue was stuck to the roof of his mouth.</p>
		<p>After she'd gazed at him for a moment, a sigh, barely audible, escaped her lips. Then she placed her slender hand over her thick eyebrows. "For I acknowledge my transgressions, and my sin is ever before me."</p>
		<p>Her voice was barely discernible, but Sanshirō heard each word clearly. With this, Sanshirō and Mineko parted.</p>
		<p>When Sanshirō returned to his lodgings, a telegram from his mother awaited him. When, it asked, was he coming.</p>      

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>御不自由</rb><rt>ごふじゆう</rt></ruby>&nbsp;inconvenience; encumbrance</span>
		<span class="vocabstudy"><ruby><rb>国</rb><rt>くに</rt></ruby>&nbsp;country; one's native place</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>寄</rb><rt>よ</rt></ruby>せて&nbsp;call for; have send</span>
		<span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;woman; young lady</span><span class="vocabstudy"><ruby><rb>紙包</rb><rt>かみづつ</rt></ruby>み&nbsp;paper-wrapped packet</span><span class="vocabstudy"><ruby><rb>懐</rb><rt>ふところ</rt></ruby>&nbsp;pocket</span><span class="vocabstudy"><ruby><rb>入</rb><rt>い</rt></ruby>れた&nbsp;put into</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;hand</span><span class="vocabstudy"><ruby><rb>吾妻</rb><rt>あずま</rt></ruby>コート&nbsp;ladies coat (of style popular in Meiji era)</span><span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;took out (from)</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; when ...</span><span class="vocabstudy"><ruby><rb>白</rb><rt>しろ</rt></ruby>い&nbsp;white</span><span class="vocabstudy">ハンケチ&nbsp;handkerchief</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って&nbsp;have; hold</span><span class="vocabstudy"><ruby><rb>鼻</rb><rt>はな</rt></ruby>&nbsp;nose</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;look at</span><span class="vocabstudy"><ruby><rb>様子</rb><rt>ようす</rt></ruby>&nbsp;appearance</span><span class="vocabstudy"><ruby><rb>不意</rb><rt>ふい</rt></ruby>に&nbsp;suddenly; abruptly</span><span class="vocabstudy"><ruby><rb>延</rb><rt>の</rt></ruby>ばした&nbsp;stretched forth</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;front of</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came (to)</span><span class="vocabstudy"><ruby><rb>鋭</rb><rt>するど</rt></ruby>い&nbsp;sharp; piquant</span><span class="vocabstudy"><ruby><rb>香</rb><rt>かおり</rt></ruby>&nbsp;fragrance</span>
		<span class="vocabstudy">ヘリオトロープ&nbsp;heliotrope (pink-purple flowering plant; perfume of same name)</span><span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かに&nbsp;quietly</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;said; remarked</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>わず&nbsp;reflexively</span><span class="vocabstudy">あとへ<ruby><rb>引</rb><rt>ひ</rt></ruby>いた&nbsp;pulled away</span><span class="vocabstudy"><ruby><rb>罎</rb><rt>びん</rt></ruby>&nbsp;bottle</span><span class="vocabstudy"><ruby><rb>四丁目</rb><rt>よんちょうめ</rt></ruby>&nbsp;Yonchōme (fourth sub-district)</span><span class="vocabstudy"><ruby><rb>夕暮</rb><rt>ゆうぐれ</rt></ruby>&nbsp;evening</span><span class="vocabstudy"><ruby><rb>迷羊</rb><rt>ストレイ・シープ</rt></ruby>&nbsp;stray sheep</span><span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby>&nbsp;sky</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い&nbsp;high</span><span class="vocabstudy"><ruby><rb>日</rb><rt>ひ</rt></ruby>&nbsp;sun</span><span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかにかかる&nbsp;shine clearly; shine brightly</span>
		<span class="vocabstudy"><ruby><rb>結婚</rb><rt>けっこん</rt></ruby>なさる&nbsp;marry; wed</span>
		<span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>袂</rb><rt>たもと</rt></ruby>&nbsp;sleeve pocket</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>とした&nbsp;dropped (into)</span>
		<span class="vocabstudy"><ruby><rb>御存</rb><rt>ごぞん</rt></ruby>じなの&nbsp;you've heard</span><span class="vocabstudy"><ruby><rb>二重瞼</rb><rt>ふたえまぶた</rt></ruby>&nbsp;contoured eyelids</span><span class="vocabstudy"><ruby><rb>細目</rb><rt>ほそめ</rt></ruby>にして&nbsp;narrow (one's eyes)</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man; fellow</span><span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くに&nbsp;at a distance</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いて&nbsp;place; set</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>づかいすぎた&nbsp;overly concerned (about)</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>つき&nbsp;look; expression (of the eyes)</span><span class="vocabstudy"><ruby><rb>眉</rb><rt>まゆ</rt></ruby>&nbsp;eyebrows</span><span class="vocabstudy"><ruby><rb>舌</rb><rt>した</rt></ruby>&nbsp;tongue</span><span class="vocabstudy"><ruby><rb>上顎</rb><rt>うわあご</rt></ruby>&nbsp;palate; roof of the mouth</span>
		<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>きかねる&nbsp;hard to hear; inaudible</span><span class="vocabstudy">ため<ruby><rb>息</rb><rt>いき</rt></ruby>&nbsp;sigh</span><span class="vocabstudy"><ruby><rb>細</rb><rt>ほそ</rt></ruby>い&nbsp;slender; delicate</span><span class="vocabstudy"><ruby><rb>濃</rb><rt>こ</rt></ruby>い&nbsp;thick</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;above</span><span class="vocabstudy"><ruby><rb>加</rb><rt>くわ</rt></ruby>えて&nbsp;bring to; join with</span>
		<span class="vocabstudy"><ruby><rb>我</rb><rt>われ</rt></ruby>&nbsp;I; me (note: this passage quotes Psalm 51:3)</span><span class="vocabstudy">わが&nbsp;my; one's own</span><span class="vocabstudy"><ruby><rb>愆</rb><rt>とが</rt></ruby>&nbsp;offense; transgression</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>る&nbsp;know; recognize; acknowledge</span><span class="vocabstudy"><ruby><rb>罪</rb><rt>つみ</rt></ruby>&nbsp;sin</span><span class="vocabstudy"><ruby><rb>常</rb><rt>つね</rt></ruby>に&nbsp;always; ever</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before; in front (of)</span>
		<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>き<ruby><rb>取</rb><rt>と</rt></ruby>れない&nbsp;indiscernible</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice</span><span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れた&nbsp;parted</span><span class="vocabstudy"><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby>&nbsp;lodgings</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>ったら&nbsp;returned (to)</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span><span class="vocabstudy"><ruby><rb>電報</rb><rt>でんぽう</rt></ruby>&nbsp;telegram</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>つ&nbsp;leave; depart</span>

	</StudyGuide>
);
