#!/bin/bash

wget -O Chapter1.js http://www.sosekiproject.org/botchan/botchanchapter1.html
wget -O StudyGuide1.js http://www.sosekiproject.org/botchan/botchanchapter01-001.html
wget -O StudyGuide2.js http://www.sosekiproject.org/botchan/botchanchapter01-002.html
wget -O StudyGuide3.js http://www.sosekiproject.org/botchan/botchanchapter01-003.html
wget -O StudyGuide4.js http://www.sosekiproject.org/botchan/botchanchapter01-004.html
wget -O StudyGuide5.js http://www.sosekiproject.org/botchan/botchanchapter01-005.html
wget -O StudyGuide6.js http://www.sosekiproject.org/botchan/botchanchapter01-006.html
wget -O StudyGuide7.js http://www.sosekiproject.org/botchan/botchanchapter01-007.html
wget -O StudyGuide8.js http://www.sosekiproject.org/botchan/botchanchapter01-008.html
wget -O StudyGuide9.js http://www.sosekiproject.org/botchan/botchanchapter01-009.html
wget -O StudyGuide10.js http://www.sosekiproject.org/botchan/botchanchapter01-010.html
wget -O StudyGuide11.js http://www.sosekiproject.org/botchan/botchanchapter01-011.html
#wget -O StudyGuide12.js http://www.sosekiproject.org/botchan/botchanchapter01-012.html
#wget -O StudyGuide13.js http://www.sosekiproject.org/botchan/botchanchapter01-013.html
#wget -O StudyGuide14.js http://www.sosekiproject.org/botchan/botchanchapter01-014.html
#wget -O StudyGuide15.js http://www.sosekiproject.org/botchan/botchanchapter01-015.html
#wget -O StudyGuide16.js http://www.sosekiproject.org/botchan/botchanchapter01-016.html
#wget -O StudyGuide17.js http://www.sosekiproject.org/botchan/botchanchapter01-017.html
#wget -O StudyGuide18.js http://www.sosekiproject.org/botchan/botchanchapter01-018.html
#wget -O StudyGuide19.js http://www.sosekiproject.org/botchan/botchanchapter01-019.html
#wget -O StudyGuide20.js http://www.sosekiproject.org/botchan/botchanchapter01-020.html
#wget -O StudyGuide21.js http://www.sosekiproject.org/botchan/botchanchapter01-021.html
#wget -O StudyGuide22.js http://www.sosekiproject.org/botchan/botchanchapter01-022.html

vim -c 'source ~/soseki/convert/TextConvert.vim' Chapter1.js
vim -c 'bufdo source ~/soseki/convert/StudyConvert.vim' StudyGuide*.js
