// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Botchan' num={3}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span class="vocabdef">おやじ</span>はちっともおれを<span class="vocabdef"><ruby><rb>可愛</rb><rt>かわい</rt></ruby>がって</span>くれなかった。<span class="vocabdef"><ruby><rb>母</rb><rt>はは</rt></ruby></span>は<span class="vocabdef"><ruby><rb>兄</rb><rt>あに</rt></ruby></span>ばかり<span class="vocabdef"><ruby><rb>贔屓</rb><rt>ひいき</rt></ruby></span>にしていた。この兄はやに<span class="vocabdef"><ruby><rb>色</rb><rt>いろ</rt></ruby>が<ruby><rb>白</rb><rt>しろ</rt></ruby>くって</span>、<span class="vocabdef"><ruby><rb>芝居</rb><rt>しばい</rt></ruby></span>の<span class="vocabdef"><ruby><rb>真似</rb><rt>まね</rt></ruby></span>をして<span class="vocabdef"><ruby><rb>女形</rb><rt>おんながた</rt></ruby></span>になるのが<span class="vocabdef"><ruby><rb>好</rb><rt>す</rt></ruby>き</span>だった。おれを<span class="vocabdef"><ruby><rb>見</rb><rt>み</rt></ruby>る</span><span class="vocabdef"><ruby><rb>度</rb><rt>たび</rt></ruby>に</span><span class="vocabdef">こいつ</span>はどうせ<span class="vocabdef"><ruby><rb>碌</rb><rt>ろく</rt></ruby>な</span>ものにはならないと、おやじが<span class="vocabdef"><ruby><rb>云</rb><rt>い</rt></ruby>った</span>。<span class="vocabdef"><ruby><rb>乱暴</rb><rt>らんぼう</rt></ruby></span>で乱暴で<span class="vocabdef"><ruby><rb>行</rb><rt>ゆ</rt></ruby>く<ruby><rb>先</rb><rt>さき</rt></ruby></span>が<span class="vocabdef"><ruby><rb>案</rb><rt>あん</rt></ruby>じられる</span>と母が云った。なるほど碌なものにはならない。<span class="vocabdef">ご<ruby><rb>覧</rb><rt>らん</rt></ruby>の<ruby><rb>通</rb><rt>とお</rt></ruby>り</span>の<span class="vocabdef"><ruby><rb>始末</rb><rt>しまつ</rt></ruby></span>である。行く先が案じられたのも<span class="vocabdef"><ruby><rb>無理</rb><rt>むり</rt></ruby>はない</span>。ただ<span class="vocabdef"><ruby><rb>懲役</rb><rt>ちょうえき</rt></ruby></span>に<span class="vocabdef"><ruby><rb>行</rb><rt>い</rt></ruby>かないで</span><span class="vocabdef"><ruby><rb>生</rb><rt>い</rt></ruby>きて</span>いるばかりである。</p>
		<p>母が<span class="vocabdef"><ruby><rb>病気</rb><rt>びょうき</rt></ruby></span>で<span class="vocabdef"><ruby><rb>死</rb><rt>し</rt></ruby>ぬ</span><span class="vocabdef"><ruby><rb>二三日</rb><rt>にさんち</rt></ruby></span><span class="vocabdef"><ruby><rb>前</rb><rt>まえ</rt></ruby></span><span class="vocabdef"><ruby><rb>台所</rb><rt>だいどころ</rt></ruby></span>で<span class="vocabdef"><ruby><rb>宙返</rb><rt>ちゅうがえ</rt></ruby>り</span>をして<span class="vocabdef">へっつい</span>の<span class="vocabdef"><ruby><rb>角</rb><rt>かど</rt></ruby></span>で<span class="vocabdef"><ruby><rb>肋骨</rb><rt>あばらぼね</rt></ruby></span>を<span class="vocabdef"><ruby><rb>撲</rb><rt>う</rt></ruby>って</span><span class="vocabdef"><ruby><rb>大</rb><rt>おお</rt></ruby>いに</span><span class="vocabdef"><ruby><rb>痛</rb><rt>いた</rt></ruby>かった</span>。母が<span class="vocabdef"><ruby><rb>大層</rb><rt>たいそう</rt></ruby></span><span class="vocabdef"><ruby><rb>怒</rb><rt>おこ</rt></ruby>って</span>、<span class="vocabdef">お<ruby><rb>前</rb><rt>まえ</rt></ruby></span>のようなものの<span class="vocabdef"><ruby><rb>顔</rb><rt>かお</rt></ruby></span>は見たくないと云うから、<span class="vocabdef"><ruby><rb>親類</rb><rt>しんるい</rt></ruby></span>へ<span class="vocabdef"><ruby><rb>泊</rb><rt>とま</rt></ruby>り</span>に行っていた。すると<span class="vocabdef">とうとう</span>死んだと云う<span class="vocabdef"><ruby><rb>報知</rb><rt>しらせ</rt></ruby></span>が<span class="vocabdef"><ruby><rb>来</rb><rt>き</rt></ruby>た</span>。そう<span class="vocabdef"><ruby><rb>早</rb><rt>はや</rt></ruby>く</span>死ぬとは<span class="vocabdef"><ruby><rb>思</rb><rt>おも</rt></ruby>わなかった</span>。そんな<span class="vocabdef"><ruby><rb>大病</rb><rt>たいびょう</rt></ruby></span>なら、<span class="vocabdef">もう<ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span class="vocabdef"><ruby><rb>大人</rb><rt>おとな</rt></ruby>しく</span>すればよかったと思って<span class="vocabdef"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。そうしたら<span class="vocabdef"><ruby><rb>例</rb><rt>れい</rt></ruby>の</span>兄がおれを<span class="vocabdef"><ruby><rb>親不孝</rb><rt>おやふこう</rt></ruby></span>だ、おれのために、<span class="vocabdef">おっかさん</span>が早く死んだんだと云った。<span class="vocabdef"><ruby><rb>口惜</rb><rt>くや</rt></ruby>しかった</span>から、兄の<span class="vocabdef"><ruby><rb>横</rb><rt>よこ</rt></ruby>っ<ruby><rb>面</rb><rt>つら</rt></ruby></span>を<span class="vocabdef"><ruby><rb>張</rb><rt>は</rt></ruby>って</span><span class="vocabdef"><ruby><rb>大変</rb><rt>たいへん</rt></ruby></span><span class="vocabdef"><ruby><rb>叱</rb><rt>しか</rt></ruby>られた</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>Father was not at all fond of me. And Mother always favored my older brother. This older brother of mine had an eerie, pale white complexion. He enjoyed putting on feminine airs, and he looked very much like those theater actors who whiten their faces to play female roles on stage. Every time my father looked at me he would tell me how I'd never amount to anything. My mother worried that my hot-headedness would lead me into trouble. I guess it's no wonder that I didn't amount to much. I became nothing more than who I am today.  I can understand why they were anxious about my future. It's a miracle that I'm not behind bars somewhere.</p> 
		<p>Several days before my mother died of illness I did a somersault in the kitchen and hurt my ribs on the corner of the stove. Mother was furious and said she couldn't stand to see my face, so I was sent to stay with relatives. Then we received notice of her death. I had never thought she could pass away so soon. If I'd known her illness was so serious I would have behaved myself better. As I returned home with this regret, that older brother of mine told me my disrespect toward Mother had hastened her passing. I couldn't bear this and slapped his face, for which I was scolded severely.</p> 

		<h3 class="section">Vocabulary</h3>
		<span class="vocabdef">おやじ&nbsp;my father</span><span class="vocabdef"><ruby><rb>可愛</rb><rt>かわい</rt></ruby>がって&nbsp;love; be affectionate toward</span><span class="vocabdef"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;Mother</span><span class="vocabdef"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;my older brother</span><span class="vocabdef"><ruby><rb>贔屓</rb><rt>ひいき</rt></ruby>&nbsp;a favorite</span><span class="vocabdef"><ruby><rb>色</rb><rt>いろ</rt></ruby>が<ruby><rb>白</rb><rt>しろ</rt></ruby>くって&nbsp;be pale</span><span class="vocabdef"><ruby><rb>芝居</rb><rt>しばい</rt></ruby>&nbsp;theater</span><span class="vocabdef"><ruby><rb>真似</rb><rt>まね</rt></ruby>&nbsp;imitation</span><span class="vocabdef"><ruby><rb>女形</rb><rt>おんながた</rt></ruby>&nbsp;female role</span><span class="vocabdef"><ruby><rb>好</rb><rt>す</rt></ruby>き&nbsp;like; be fond of</span><span class="vocabdef"><ruby><rb>見</rb><rt>み</rt></ruby>る&nbsp;look at</span><span class="vocabdef"><ruby><rb>度</rb><rt>たび</rt></ruby>に&nbsp;each time ...</span><span class="vocabdef">こいつ&nbsp;this guy</span><span class="vocabdef"><ruby><rb>碌</rb><rt>ろく</rt></ruby>な&nbsp;respectable</span><span class="vocabdef"><ruby><rb>云</rb><rt>い</rt></ruby>った&nbsp;said</span><span class="vocabdef"><ruby><rb>乱暴</rb><rt>らんぼう</rt></ruby>&nbsp;violent; hot-headed</span><span class="vocabdef"><ruby><rb>行</rb><rt>ゆ</rt></ruby>く<ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;destination; end point</span><span class="vocabdef"><ruby><rb>案</rb><rt>あん</rt></ruby>じられる&nbsp;be worried about; be anxious over</span><span class="vocabdef">ご<ruby><rb>覧</rb><rt>らん</rt></ruby>の<ruby><rb>通</rb><rt>とお</rt></ruby>り&nbsp;as you can see</span><span class="vocabdef"><ruby><rb>始末</rb><rt>しまつ</rt></ruby>&nbsp;ending</span><span class="vocabdef"><ruby><rb>無理</rb><rt>むり</rt></ruby>はない&nbsp;not unreasonable; warranted</span><span class="vocabdef"><ruby><rb>懲役</rb><rt>ちょうえき</rt></ruby>&nbsp;imprisonment</span><span class="vocabdef"><ruby><rb>行</rb><rt>い</rt></ruby>かないで&nbsp;without going</span><span class="vocabdef"><ruby><rb>生</rb><rt>い</rt></ruby>きて&nbsp;live; be alive</span>
		<span class="vocabdef"><ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;illness</span><span class="vocabdef"><ruby><rb>死</rb><rt>し</rt></ruby>ぬ&nbsp;die; pass away</span><span class="vocabdef"><ruby><rb>二三日</rb><rt>にさんち</rt></ruby>&nbsp;two or three days</span><span class="vocabdef"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before</span><span class="vocabdef"><ruby><rb>台所</rb><rt>だいどころ</rt></ruby>&nbsp;kitchen</span><span class="vocabdef"><ruby><rb>宙返</rb><rt>ちゅうがえ</rt></ruby>り&nbsp;somersault</span><span class="vocabdef">へっつい&nbsp;hearth; kitchen stove</span><span class="vocabdef"><ruby><rb>角</rb><rt>かど</rt></ruby>&nbsp;corner</span><span class="vocabdef"><ruby><rb>肋骨</rb><rt>あばらぼね</rt></ruby>&nbsp;ribs</span><span class="vocabdef"><ruby><rb>撲</rb><rt>う</rt></ruby>って&nbsp;hit</span><span class="vocabdef"><ruby><rb>大</rb><rt>おお</rt></ruby>いに&nbsp;in a big way</span><span class="vocabdef"><ruby><rb>痛</rb><rt>いた</rt></ruby>かった&nbsp;was painful</span><span class="vocabdef"><ruby><rb>大層</rb><rt>たいそう</rt></ruby>&nbsp;a great deal</span><span class="vocabdef"><ruby><rb>怒</rb><rt>おこ</rt></ruby>って&nbsp;became angry</span><span class="vocabdef">お<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;you</span><span class="vocabdef"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabdef"><ruby><rb>親類</rb><rt>しんるい</rt></ruby>&nbsp;relatives</span><span class="vocabdef"><ruby><rb>泊</rb><rt>とま</rt></ruby>り&nbsp;stay (overnight)</span><span class="vocabdef">とうとう&nbsp;finally; at last</span><span class="vocabdef"><ruby><rb>報知</rb><rt>しらせ</rt></ruby>&nbsp;notice; notification (usual reading = ほうち)</span><span class="vocabdef"><ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came; arrived</span><span class="vocabdef"><ruby><rb>早</rb><rt>はや</rt></ruby>く&nbsp;soon</span><span class="vocabdef"><ruby><rb>思</rb><rt>おも</rt></ruby>わなかった&nbsp;didn't expect</span><span class="vocabdef"><ruby><rb>大病</rb><rt>たいびょう</rt></ruby>&nbsp;serious illness</span><span class="vocabdef">もう<ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little more</span><span class="vocabdef"><ruby><rb>大人</rb><rt>おとな</rt></ruby>しく&nbsp;well-behaved</span><span class="vocabdef"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;returned home</span><span class="vocabdef"><ruby><rb>例</rb><rt>れい</rt></ruby>の&nbsp;the aforementioned</span><span class="vocabdef"><ruby><rb>親不孝</rb><rt>おやふこう</rt></ruby>&nbsp;disrespectful towards one's parents</span><span class="vocabdef">おっかさん&nbsp;Mom</span><span class="vocabdef"><ruby><rb>口惜</rb><rt>くや</rt></ruby>しかった&nbsp;was hard to take</span><span class="vocabdef"><ruby><rb>横</rb><rt>よこ</rt></ruby>っ<ruby><rb>面</rb><rt>つら</rt></ruby>&nbsp;side of the face</span><span class="vocabdef"><ruby><rb>張</rb><rt>は</rt></ruby>って&nbsp;slapped</span><span class="vocabdef"><ruby><rb>大変</rb><rt>たいへん</rt></ruby>&nbsp;seriously; terribly</span><span class="vocabdef"><ruby><rb>叱</rb><rt>しか</rt></ruby>られた&nbsp;was scolded</span>

	</StudyGuide>
);
