// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Botchan' num={68}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「ところが、<span><ruby><rb>去年</rb><rt>きょねん</rt></ruby></span>あすこの<span>お<ruby><rb>父</rb><rt>とう</rt></ruby>さん</span>が、<span>お<ruby><rb>亡</rb><rt>な</rt></ruby>くなりて</span>、――それまでは<span>お<ruby><rb>金</rb><rt>かね</rt></ruby></span>もあるし、<span><ruby><rb>銀行</rb><rt>ぎんこう</rt></ruby></span>の<span><ruby><rb>株</rb><rt>かぶ</rt></ruby></span>も<span><ruby><rb>持</rb><rt>も</rt></ruby>ってお<ruby><rb>出</rb><rt>いで</rt></ruby>る</span>し、<span><ruby><rb>万事</rb><rt>ばんじ</rt></ruby></span><span><ruby><rb>都合</rb><rt>つごう</rt></ruby>がよかった</span>のじゃが――それからというものは、どういうものか<span><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span><span><ruby><rb>暮</rb><rt>くら</rt></ruby>し<ruby><rb>向</rb><rt>む</rt></ruby>き</span>が<span><ruby><rb>思</rb><rt>おも</rt></ruby>わしくなくなって</span>――つまり<span><ruby><rb>古賀</rb><rt>こが</rt></ruby></span>さんがあまり<span>お<ruby><rb>人</rb><rt>ひと</rt></ruby></span>が<span><ruby><rb>好過</rb><rt>よす</rt></ruby>ぎる</span>けれ、<span>お<ruby><rb>欺</rb><rt>だま</rt></ruby>された</span>んぞなもし。それや、これやで<span>お<ruby><rb>輿入</rb><rt>こしいれ</rt></ruby></span>も<span><ruby><rb>延</rb><rt>の</rt></ruby>びて</span>いるところへ、あの<span><ruby><rb>教頭</rb><rt>きょうとう</rt></ruby></span>さんが<span>お<ruby><rb>出</rb><rt>い</rt></ruby>でて</span>、<span><ruby><rb>是非</rb><rt>ぜひ</rt></ruby></span><span>お<ruby><rb>嫁</rb><rt>よめ</rt></ruby></span>にほしいと<span>お<ruby><rb>云</rb><rt>い</rt></ruby>いる</span>のじゃがなもし」</p>
		<p>「あの<span><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ</span>がですか。ひどい<span><ruby><rb>奴</rb><rt>やつ</rt></ruby></span>だ。どうもあのシャツはただのシャツじゃないと思ってた。それから？」</p>
		<p>「<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>を<span><ruby><rb>頼</rb><rt>たの</rt></ruby>んで</span><span><ruby><rb>懸合</rb><rt>かけお</rt></ruby>うて</span>おみると、<span><ruby><rb>遠山</rb><rt>とおやま</rt></ruby></span>さんでも古賀さんに<span><ruby><rb>義理</rb><rt>ぎり</rt></ruby></span>があるから、すぐには<span><ruby><rb>返事</rb><rt>へんじ</rt></ruby></span>は<span><ruby><rb>出来</rb><rt>でき</rt></ruby>かねて</span>――まあよう<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えて</span>みようぐらいの<span><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby></span>をおしたのじゃがなもし。すると赤シャツさんが、<span><ruby><rb>手蔓</rb><rt>てづる</rt></ruby></span>を<span><ruby><rb>求</rb><rt>もと</rt></ruby>めて</span>遠山さんの<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>へ<span><ruby><rb>出入</rb><rt>でいり</rt></ruby></span>をおしるようになって、とうとうあなた、<span>お<ruby><rb>嬢</rb><rt>じょう</rt></ruby>さん</span>を<span><ruby><rb>手馴付</rb><rt>てなづ</rt></ruby>けて</span>おしまいたのじゃがなもし。赤シャツさんも赤シャツさんじゃが、お嬢さんもお嬢さんじゃてて、みんなが<span><ruby><rb>悪</rb><rt>わ</rt></ruby>るく</span><span><ruby><rb>云</rb><rt>い</rt></ruby>います</span>のよ。いったん古賀さんへ嫁に<span><ruby><rb>行</rb><rt>い</rt></ruby>く</span>てて<span><ruby><rb>承知</rb><rt>しょうち</rt></ruby></span>をしときながら、<span><ruby><rb>今</rb><rt>いま</rt></ruby>さら</span><span><ruby><rb>学士</rb><rt>がくし</rt></ruby></span>さんがお出たけれ、その方に<span><ruby><rb>替</rb><rt>か</rt></ruby>えよ</span>てて、それじゃ<span><ruby><rb>今日様</rb><rt>こんにちさま</rt></ruby>へ<ruby><rb>済</rb><rt>す</rt></ruby>むまい</span>がなもし、あなた」</p>
		<p>「<span><ruby><rb>全</rb><rt>まった</rt></ruby>く</span><span><ruby><rb>済</rb><rt>す</rt></ruby>まない</span>ね。<span><ruby><rb>今日様</rb><rt>こんにちさま</rt></ruby></span>どころか<span><ruby><rb>明日様</rb><rt>あしたさま</rt></ruby></span>にも<span><ruby><rb>明後日様</rb><rt>みょうごにちさま</rt></ruby></span>にも、いつまで行ったって済みっこありませんね」</p>
		<p>「それで古賀さんに<span>お<ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby></span>じゃてて、<span>お<ruby><rb>友達</rb><rt>ともだち</rt></ruby></span>の<span><ruby><rb>堀田</rb><rt>ほった</rt></ruby></span>さんが教頭の<span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>へ<span><ruby><rb>意見</rb><rt>いけん</rt></ruby>をし</span>にお行きたら、赤シャツさんが、あしは<span><ruby><rb>約束</rb><rt>やくそく</rt></ruby></span>のあるものを<span><ruby><rb>横取</rb><rt>よこど</rt></ruby>りする</span>つもりはない。<span><ruby><rb>破約</rb><rt>はやく</rt></ruby></span>になれば<span><ruby><rb>貰</rb><rt>もら</rt></ruby>う</span><span>かも<ruby><rb>知</rb><rt>し</rt></ruby>れん</span>が、<span><ruby><rb>今</rb><rt>いま</rt></ruby>のところ</span>は<span><ruby><rb>遠山</rb><rt>とおやま</rt></ruby><ruby><rb>家</rb><rt>け</rt></ruby></span>とただ<span><ruby><rb>交際</rb><rt>こうさい</rt></ruby></span>をしているばかりじゃ、遠山家と交際をするには<span><ruby><rb>別段</rb><rt>べつだん</rt></ruby></span>古賀さんに済まん<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>もなかろうとお云いるけれ、堀田さんも<span><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がなしに</span><span>お<ruby><rb>戻</rb><rt>もど</rt></ruby>りた</span>そうな。赤シャツさんと堀田さんは、<span>それ<ruby><rb>以来</rb><rt>いらい</rt></ruby></span><span><ruby><rb>折合</rb><rt>おりあい</rt></ruby></span>がわるいという<span><ruby><rb>評判</rb><rt>ひょうばん</rt></ruby></span>ぞなもし」</p>

		<h3 class="section">Rough translation</h3>
		<p>"However, the senior Mr. Koga passed away last year. Up to that point they were a prosperous family, with money and an ownership stake in a bank. After his passing, for whatever reason, their circumstances took a sudden turn for the worse. It could be that someone took advantage of young Mr. Koga's good nature and cheated him. Things being what they are, the wedding was put off. Then that head teacher entered the scene with a burning desire to take her as his own."</p>
		<p>"Red Shirt? What a scoundrel! I thought there must be more to that shirt than just a shirt. Then what?"</p>
		<p>"He approached through a go-between, but the Tōyama house had an obligation to the Koga house, so they were not in a position to give him an immediate answer, saying only that they would consider things carefully. At this point Red Shirt began calling regularly to shore up his influence. Over time he won the young lady over. This brought both Red Shirt and the young lady into disrepute. After once committing to the Koga house, to jump now to this scholar is surely an offense against heaven."</p>
		<p>"An offense indeed. Not just against heaven, but against the earth and the moon as well. Utterly despicable."</p>
		<p>"Feeling sympathy for Koga, his friend Hotta paid a visit to the head teacher on his behalf. Red Shirt denied any intention of usurping one betrothed to another. He might take her for his bride if she broke her engagement, but for now he was merely a social acquaintance of the Tōyama family, and this was in no way a slight against Koga. Hotta could press the matter no further and left it at that, but they say there's been bad blood between the two of them ever since."</p> 

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>去年</rb><rt>きょねん</rt></ruby>&nbsp;last year</span><span class="vocabstudy">お<ruby><rb>父</rb><rt>とう</rt></ruby>さん&nbsp;father</span><span class="vocabstudy">お<ruby><rb>亡</rb><rt>な</rt></ruby>くなりて&nbsp;pass away; die</span><span class="vocabstudy">お<ruby><rb>金</rb><rt>かね</rt></ruby>&nbsp;money</span><span class="vocabstudy"><ruby><rb>銀行</rb><rt>ぎんこう</rt></ruby>&nbsp;bank</span><span class="vocabstudy"><ruby><rb>株</rb><rt>かぶ</rt></ruby>&nbsp;stock; shares; equity</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>ってお<ruby><rb>出</rb><rt>いで</rt></ruby>る&nbsp;have; possess</span><span class="vocabstudy"><ruby><rb>万事</rb><rt>ばんじ</rt></ruby>&nbsp;everything; all things</span><span class="vocabstudy"><ruby><rb>都合</rb><rt>つごう</rt></ruby>がよかった&nbsp;was favorable; was going well</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>暮</rb><rt>くら</rt></ruby>し<ruby><rb>向</rb><rt>む</rt></ruby>き&nbsp;circumstances</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>わしくなくなって&nbsp;went sour; became unfavorable</span><span class="vocabstudy"><ruby><rb>古賀</rb><rt>こが</rt></ruby>&nbsp;Koga (a.k.a. Uranari)</span><span class="vocabstudy">お<ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;character; as a person</span><span class="vocabstudy"><ruby><rb>好過</rb><rt>よす</rt></ruby>ぎる&nbsp;too good; too generous</span><span class="vocabstudy">お<ruby><rb>欺</rb><rt>だま</rt></ruby>された&nbsp;was taken advantage of</span><span class="vocabstudy">お<ruby><rb>輿入</rb><rt>こしいれ</rt></ruby>&nbsp;wedding</span><span class="vocabstudy"><ruby><rb>延</rb><rt>の</rt></ruby>びて&nbsp;be delayed</span><span class="vocabstudy"><ruby><rb>教頭</rb><rt>きょうとう</rt></ruby>&nbsp;head teacher (a.k.a. Red Shirt)</span><span class="vocabstudy">お<ruby><rb>出</rb><rt>い</rt></ruby>でて&nbsp;appeared</span><span class="vocabstudy"><ruby><rb>是非</rb><rt>ぜひ</rt></ruby>&nbsp;by all means</span><span class="vocabstudy">お<ruby><rb>嫁</rb><rt>よめ</rt></ruby>&nbsp;bride</span><span class="vocabstudy">お<ruby><rb>云</rb><rt>い</rt></ruby>いる&nbsp;say; declare</span>
		<span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ&nbsp;Red Shirt (nickname for the head teacher)</span><span class="vocabstudy"><ruby><rb>奴</rb><rt>やつ</rt></ruby>&nbsp;fellow; guy</span>
		<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;a person; someone</span><span class="vocabstudy"><ruby><rb>頼</rb><rt>たの</rt></ruby>んで&nbsp;request</span><span class="vocabstudy"><ruby><rb>懸合</rb><rt>かけお</rt></ruby>うて&nbsp;negotiate (dialect for <ruby><rb>懸合</rb><rt>かけあ</rt></ruby>って)</span><span class="vocabstudy"><ruby><rb>遠山</rb><rt>とおやま</rt></ruby>&nbsp;Tōyama (family name of Madonna)</span><span class="vocabstudy"><ruby><rb>義理</rb><rt>ぎり</rt></ruby>&nbsp;obligation</span><span class="vocabstudy"><ruby><rb>返事</rb><rt>へんじ</rt></ruby>&nbsp;answer</span><span class="vocabstudy"><ruby><rb>出来</rb><rt>でき</rt></ruby>かねて&nbsp;not in a position to do</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えて&nbsp;consider; think over</span><span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>&nbsp;answer; response</span><span class="vocabstudy"><ruby><rb>手蔓</rb><rt>てづる</rt></ruby>&nbsp;influence; contact</span><span class="vocabstudy"><ruby><rb>求</rb><rt>もと</rt></ruby>めて&nbsp;seek; pursue</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>出入</rb><rt>でいり</rt></ruby>&nbsp;come and go; call on</span><span class="vocabstudy">お<ruby><rb>嬢</rb><rt>じょう</rt></ruby>さん&nbsp;young lady</span><span class="vocabstudy"><ruby><rb>手馴付</rb><rt>てなづ</rt></ruby>けて&nbsp;bring round; win over</span><span class="vocabstudy"><ruby><rb>悪</rb><rt>わ</rt></ruby>るく&nbsp;badly</span><span class="vocabstudy"><ruby><rb>云</rb><rt>い</rt></ruby>います&nbsp;speak (of)</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>く&nbsp;go (to)</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>&nbsp;consent; agreement</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>さら&nbsp;at this (belated) point</span><span class="vocabstudy"><ruby><rb>学士</rb><rt>がくし</rt></ruby>&nbsp;scholar; degree holder</span><span class="vocabstudy"><ruby><rb>替</rb><rt>か</rt></ruby>えよ&nbsp;change; switch (to)</span><span class="vocabstudy"><ruby><rb>今日様</rb><rt>こんにちさま</rt></ruby>へ<ruby><rb>済</rb><rt>す</rt></ruby>むまい&nbsp;offensive before heaven (lit: unacceptable to the sun god)</span>
		<span class="vocabstudy"><ruby><rb>全</rb><rt>まった</rt></ruby>く&nbsp;completely</span><span class="vocabstudy"><ruby><rb>済</rb><rt>す</rt></ruby>まない&nbsp;unacceptable</span><span class="vocabstudy"><ruby><rb>今日様</rb><rt>こんにちさま</rt></ruby>&nbsp;the sun god (can also be read as "today" god)</span><span class="vocabstudy"><ruby><rb>明日様</rb><rt>あしたさま</rt></ruby>&nbsp;the tomorrow god (pun)</span><span class="vocabstudy"><ruby><rb>明後日様</rb><rt>みょうごにちさま</rt></ruby>&nbsp;the day after tomorrow god (pun)</span>
		<span class="vocabstudy">お<ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby>&nbsp;wretched; pitiable</span><span class="vocabstudy">お<ruby><rb>友達</rb><rt>ともだち</rt></ruby>&nbsp;friend</span><span class="vocabstudy"><ruby><rb>堀田</rb><rt>ほった</rt></ruby>&nbsp;Hotta (a.k.a. Yama Arashi)</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place; residence</span><span class="vocabstudy"><ruby><rb>意見</rb><rt>いけん</rt></ruby>をし&nbsp;argue a case</span><span class="vocabstudy"><ruby><rb>約束</rb><rt>やくそく</rt></ruby>&nbsp;promise</span><span class="vocabstudy"><ruby><rb>横取</rb><rt>よこど</rt></ruby>りする&nbsp;usurp; snatch</span><span class="vocabstudy"><ruby><rb>破約</rb><rt>はやく</rt></ruby>&nbsp;broken engagement</span><span class="vocabstudy"><ruby><rb>貰</rb><rt>もら</rt></ruby>う&nbsp;receive</span><span class="vocabstudy">かも<ruby><rb>知</rb><rt>し</rt></ruby>れん&nbsp;might (do)</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>のところ&nbsp;for now</span><span class="vocabstudy"><ruby><rb>遠山</rb><rt>とおやま</rt></ruby><ruby><rb>家</rb><rt>け</rt></ruby>&nbsp;the Tōyama household</span><span class="vocabstudy"><ruby><rb>交際</rb><rt>こうさい</rt></ruby>&nbsp;friendship; acquaintance</span><span class="vocabstudy"><ruby><rb>別段</rb><rt>べつだん</rt></ruby>&nbsp;in particular</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;matter; action</span><span class="vocabstudy"><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がなしに&nbsp;having no further recourse</span><span class="vocabstudy">お<ruby><rb>戻</rb><rt>もど</rt></ruby>りた&nbsp;took his leave; returned</span><span class="vocabstudy">それ<ruby><rb>以来</rb><rt>いらい</rt></ruby>&nbsp;since then</span><span class="vocabstudy"><ruby><rb>折合</rb><rt>おりあい</rt></ruby>&nbsp;relations</span><span class="vocabstudy"><ruby><rb>評判</rb><rt>ひょうばん</rt></ruby>&nbsp;rumor; gossip</span>

	</StudyGuide>
);
