// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Botchan' num={37}>

		<h3 className="section">Practice text with full furigana</h3>
		<p>おれが<span><ruby><rb>宿直部屋</rb><rt>しゅくちょくべや</rt></ruby></span>へ<span><ruby><rb>連</rb><rt>つ</rt></ruby>れてきた</span><span><ruby><rb>奴</rb><rt>やつ</rt></ruby></span>を<span><ruby><rb>詰問</rb><rt>きつもん</rt></ruby></span><span>し<ruby><rb>始</rb><rt>はじ</rt></ruby>める</span>と、<span><ruby><rb>豚</rb><rt>ぶた</rt></ruby></span>は、<span><ruby><rb>打</rb><rt>ぶ</rt></ruby>って</span>も<span><ruby><rb>擲</rb><rt>たた</rt></ruby>いて</span>も豚だから、ただ<span><ruby><rb>知</rb><rt>し</rt></ruby>らん</span>がなで、どこまでも<span><ruby><rb>通</rb><rt>とお</rt></ruby>す</span><span><ruby><rb>了見</rb><rt>りょうけん</rt></ruby></span>と<span><ruby><rb>見</rb><rt>み</rt></ruby>えて</span>、けっして<span><ruby><rb>白状</rb><rt>はくじょう</rt></ruby></span>しない。そのうち一人来る、二人来る、だんだん<span><ruby><rb>二階</rb><rt>にかい</rt></ruby></span>から宿直部屋へ<span><ruby><rb>集</rb><rt>あつ</rt></ruby>まって</span>くる。<span><ruby><rb>見</rb><rt>み</rt></ruby>る</span>とみんな<span><ruby><rb>眠</rb><rt>ねむ</rt></ruby>そう</span>に<span><ruby><rb>瞼</rb><rt>まぶた</rt></ruby>をはらしている</span>。<span>けちな</span><span><ruby><rb>奴等</rb><rt>やつら</rt></ruby></span>だ。<span><ruby><rb>一晩</rb><rt>ひとばん</rt></ruby></span>ぐらい<span><ruby><rb>寝</rb><rt>ね</rt></ruby>ない</span>で、そんな<span><ruby><rb>面</rb><rt>つら</rt></ruby></span>をして<span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>と<span><ruby><rb>云</rb><rt>い</rt></ruby>われる</span>か。面でも<span><ruby><rb>洗</rb><rt>あら</rt></ruby>って</span><span><ruby><rb>議論</rb><rt>ぎろん</rt></ruby></span>に来いと云ってやったが、<span><ruby><rb>誰</rb><rt>だれ</rt></ruby>も</span>面を洗いに<span><ruby><rb>行</rb><rt>い</rt></ruby>かない</span>。</p>
		<p>おれは<span><ruby><rb>五十人</rb><rt>ごじゅうにん</rt></ruby></span>あまりを<span><ruby><rb>相手</rb><rt>あいて</rt></ruby></span>に<span><ruby><rb>約</rb><rt>やく</rt></ruby></span><span><ruby><rb>一時間</rb><rt>いちじかん</rt></ruby></span>ばかり<span><ruby><rb>押問答</rb><rt>おしもんどう</rt></ruby></span>をしていると、<span>ひょっくり</span><span><ruby><rb>狸</rb><rt>たぬき</rt></ruby></span>がやって来た。あとから<span><ruby><rb>聞</rb><rt>き</rt></ruby>いたら</span>、<span><ruby><rb>小使</rb><rt>こづかい</rt></ruby></span>が<span><ruby><rb>学校</rb><rt>がっこう</rt></ruby></span>に<span><ruby><rb>騒動</rb><rt>そうどう</rt></ruby></span>がありますって、わざわざ<span><ruby><rb>知</rb><rt>し</rt></ruby>らせ</span>に行ったのだそうだ。<span>これしき</span>の<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>に、<span><ruby><rb>校長</rb><rt>こうちょう</rt></ruby></span>を<span><ruby><rb>呼</rb><rt>よ</rt></ruby>ぶ</span>なんて<span><ruby><rb>意気地</rb><rt>いくじ</rt></ruby>がなさ<ruby><rb>過</rb><rt>す</rt></ruby>ぎる</span>。それだから<span><ruby><rb>中学校</rb><rt>ちゅうがっこう</rt></ruby></span>の小使なんぞをしてるんだ。</p>

		<h3 className="section">Rough translation</h3>
		<p>I started grilling the two I'd brought to my room, but no matter how much you beat or berate pigs, they're still pigs. These guys seemed determined to plead ignorance to the end and confessed to nothing. As the grilling continued, others came down one or two at a time and gathered in my room. All of them had tired eyes with swollen eyelids. What a shabby bunch. They show up with sorry faces after one sleepless night and call themselves men? I told them we'd continue after they washed their faces, but not one of them moved.</p> 
		<p>I had interrogated fifty or so students for almost an hour when Tanuki suddenly appeared. I learned later that the janitor went and notified him that there was a disturbance at the school. Only an extreme weakling would call for the principal over a such a trivial matter as this. That must be why he's working as a middle school janitor.</p>   

		<h3 className="section">Vocabulary</h3>
		<span className="vocabstudy"><ruby><rb>宿直部屋</rb><rt>しゅくちょくべや</rt></ruby>&nbsp;night duty room</span><span className="vocabstudy"><ruby><rb>連</rb><rt>つ</rt></ruby>れてきた&nbsp;brought; led</span><span className="vocabstudy"><ruby><rb>奴</rb><rt>やつ</rt></ruby>&nbsp;fellows</span><span className="vocabstudy"><ruby><rb>詰問</rb><rt>きつもん</rt></ruby>&nbsp;questioning; grilling</span><span className="vocabstudy">し<ruby><rb>始</rb><rt>はじ</rt></ruby>める&nbsp;begin to do</span><span className="vocabstudy"><ruby><rb>豚</rb><rt>ぶた</rt></ruby>&nbsp;pigs; hogs</span><span className="vocabstudy"><ruby><rb>打</rb><rt>ぶ</rt></ruby>って&nbsp;hit</span><span className="vocabstudy"><ruby><rb>擲</rb><rt>たた</rt></ruby>いて&nbsp;strike</span><span className="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らん&nbsp;I don't know</span><span className="vocabstudy"><ruby><rb>通</rb><rt>とお</rt></ruby>す&nbsp;continue with; stick to</span><span className="vocabstudy"><ruby><rb>了見</rb><rt>りょうけん</rt></ruby>&nbsp;thought; notion</span><span className="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>えて&nbsp;appear</span><span className="vocabstudy"><ruby><rb>白状</rb><rt>はくじょう</rt></ruby>&nbsp;confess; own up</span><span className="vocabstudy"><ruby><rb>二階</rb><rt>にかい</rt></ruby>&nbsp;second floor</span><span className="vocabstudy"><ruby><rb>集</rb><rt>あつ</rt></ruby>まって&nbsp;gather</span><span className="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>る&nbsp;look at</span><span className="vocabstudy"><ruby><rb>眠</rb><rt>ねむ</rt></ruby>そう&nbsp;tired-looking</span><span className="vocabstudy"><ruby><rb>瞼</rb><rt>まぶた</rt></ruby>をはらしている&nbsp;have swollen eyelids</span><span className="vocabstudy">けちな&nbsp;mean; shabby</span><span className="vocabstudy"><ruby><rb>奴等</rb><rt>やつら</rt></ruby>&nbsp;folks</span><span className="vocabstudy"><ruby><rb>一晩</rb><rt>ひとばん</rt></ruby>&nbsp;one night</span><span className="vocabstudy"><ruby><rb>寝</rb><rt>ね</rt></ruby>ない&nbsp;lose sleep</span><span className="vocabstudy"><ruby><rb>面</rb><rt>つら</rt></ruby>&nbsp;face</span><span className="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man</span><span className="vocabstudy"><ruby><rb>云</rb><rt>い</rt></ruby>われる&nbsp;be called</span><span className="vocabstudy"><ruby><rb>洗</rb><rt>あら</rt></ruby>って&nbsp;wash</span><span className="vocabstudy"><ruby><rb>議論</rb><rt>ぎろん</rt></ruby>&nbsp;debate; dispute</span><span className="vocabstudy"><ruby><rb>誰</rb><rt>だれ</rt></ruby>も&nbsp;no one</span><span className="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>かない&nbsp;go</span>
		<span className="vocabstudy"><ruby><rb>五十人</rb><rt>ごじゅうにん</rt></ruby>&nbsp;fifty (people)</span><span className="vocabstudy"><ruby><rb>相手</rb><rt>あいて</rt></ruby>&nbsp;adversary</span><span className="vocabstudy"><ruby><rb>約</rb><rt>やく</rt></ruby>&nbsp;about</span><span className="vocabstudy"><ruby><rb>一時間</rb><rt>いちじかん</rt></ruby>&nbsp;one hour</span><span className="vocabstudy"><ruby><rb>押問答</rb><rt>おしもんどう</rt></ruby>&nbsp;repeated questioning and answering</span><span className="vocabstudy">ひょっくり&nbsp;suddenly; unexpectedly</span><span className="vocabstudy"><ruby><rb>狸</rb><rt>たぬき</rt></ruby>&nbsp;Tanuki (nickname for the school principal)</span><span className="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いたら&nbsp;asked; heard</span><span className="vocabstudy"><ruby><rb>小使</rb><rt>こづかい</rt></ruby>&nbsp;janitor</span><span className="vocabstudy"><ruby><rb>学校</rb><rt>がっこう</rt></ruby>&nbsp;the school</span><span className="vocabstudy"><ruby><rb>騒動</rb><rt>そうどう</rt></ruby>&nbsp;disturbance; trouble</span><span className="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らせ&nbsp;notify</span><span className="vocabstudy">これしき&nbsp;such a trifle</span><span className="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;matter</span><span className="vocabstudy"><ruby><rb>校長</rb><rt>こうちょう</rt></ruby>&nbsp;principal</span><span className="vocabstudy"><ruby><rb>呼</rb><rt>よ</rt></ruby>ぶ&nbsp;call for</span><span className="vocabstudy"><ruby><rb>意気地</rb><rt>いくじ</rt></ruby>がなさ<ruby><rb>過</rb><rt>す</rt></ruby>ぎる&nbsp;weak-willed to the extreme</span><span className="vocabstudy"><ruby><rb>中学校</rb><rt>ちゅうがっこう</rt></ruby>&nbsp;middle school</span>

	</StudyGuide>
);
