// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={60}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>は<span><ruby><rb>先刻</rb><rt>さっき</rt></ruby></span>そんなに<span><ruby><rb>昂奮</rb><rt>こうふん</rt></ruby>した</span>ように<span><ruby><rb>見</rb><rt>み</rt></ruby>えた</span>んですか」</p>
		<p>「そんなにというほどでもありませんが、<span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span>……」</p>
		<p>「いや見えても<span><ruby><rb>構</rb><rt>かま</rt></ruby>わない</span>。<span><ruby><rb>実際</rb><rt>じっさい</rt></ruby></span>昂奮するんだから。私は<span><ruby><rb>財産</rb><rt>ざいさん</rt></ruby></span><span>の<ruby><rb>事</rb><rt>こと</rt></ruby></span>をいうときっと昂奮するんです。<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>にはどう見えるか<span><ruby><rb>知</rb><rt>し</rt></ruby>らない</span>が、私はこれで<span><ruby><rb>大変</rb><rt>たいへん</rt></ruby></span><span><ruby><rb>執念</rb><rt>しゅうねん</rt></ruby><ruby><rb>深</rb><rt>ぶか</rt></ruby>い</span><span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>なんだから。<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>から<span><ruby><rb>受</rb><rt>う</rt></ruby>けた</span><span><ruby><rb>屈辱</rb><rt>くつじょく</rt></ruby></span>や<span><ruby><rb>損害</rb><rt>そんがい</rt></ruby></span>は、<span><ruby><rb>十年</rb><rt>じゅうねん</rt></ruby></span>たっても<span><ruby><rb>二十年</rb><rt>にじゅうねん</rt></ruby></span>たっても<span><ruby><rb>忘</rb><rt>わす</rt></ruby>れやしない</span>んだから」</p>
		<p><span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>の<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>は<span><ruby><rb>元</rb><rt>もと</rt></ruby>よりも</span>なお昂奮していた。しかし私の<span><ruby><rb>驚</rb><rt>おどろ</rt></ruby>いた</span>のは、<span><ruby><rb>決</rb><rt>けっ</rt></ruby>して</span>その<span><ruby><rb>調子</rb><rt>ちょうし</rt></ruby></span>ではなかった。むしろ先生の言葉が私の<span><ruby><rb>耳</rb><rt>みみ</rt></ruby></span>に<span><ruby><rb>訴</rb><rt>うった</rt></ruby>える</span><span><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>そのものであった。先生の<span><ruby><rb>口</rb><rt>くち</rt></ruby></span>からこんな<span><ruby><rb>自白</rb><rt>じはく</rt></ruby></span>を<span><ruby><rb>聞</rb><rt>き</rt></ruby>く</span>のは、いかな私にも<span><ruby><rb>全</rb><rt>まった</rt></ruby>く</span>の<span><ruby><rb>意外</rb><rt>いがい</rt></ruby></span><span>に<ruby><rb>相違</rb><rt>そうい</rt></ruby>なかった</span>。私は先生の<span><ruby><rb>性質</rb><rt>せいしつ</rt></ruby></span>の<span><ruby><rb>特色</rb><rt>とくしょく</rt></ruby></span>として、こんな<span><ruby><rb>執着力</rb><rt>しゅうじゃくりょく</rt></ruby></span>をいまだかつて<span><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>した</span>事さえなかった。私は先生をもっと<span><ruby><rb>弱</rb><rt>よわ</rt></ruby>い</span>人と<span><ruby><rb>信</rb><rt>しん</rt></ruby>じて</span>いた。そうしてその弱くて<span><ruby><rb>高</rb><rt>たか</rt></ruby>い</span><span><ruby><rb>処</rb><rt>ところ</rt></ruby></span>に、私の<span><ruby><rb>懐</rb><rt>なつ</rt></ruby>かしみ</span>の<span><ruby><rb>根</rb><rt>ね</rt></ruby></span>を<span><ruby><rb>置</rb><rt>お</rt></ruby>いて</span>いた。<span><ruby><rb>一時</rb><rt>いちじ</rt></ruby>の</span><span><ruby><rb>気分</rb><rt>きぶん</rt></ruby></span>で先生にちょっと<span><ruby><rb>盾</rb><rt>たて</rt></ruby>を<ruby><rb>突</rb><rt>つ</rt></ruby>いて</span>みようとした私は、この言葉の<span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>に<span><ruby><rb>小</rb><rt>ちい</rt></ruby>さくなった</span>。先生はこういった。</p>
		<p>「私は<span><ruby><rb>他</rb><rt>ひと</rt></ruby></span>に<span><ruby><rb>欺</rb><rt>あざむ</rt></ruby>かれた</span>のです。しかも<span><ruby><rb>血</rb><rt>ち</rt></ruby>のつづいた<ruby><rb>親戚</rb><rt>しんせき</rt></ruby></span>のものから欺かれたのです。私は決してそれを忘れないのです。私の<span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>の前には<span><ruby><rb>善人</rb><rt>ぜんにん</rt></ruby></span>であったらしい<span><ruby><rb>彼</rb><rt>かれ</rt></ruby>ら</span>は、父の<span><ruby><rb>死</rb><rt>し</rt></ruby>ぬ</span><span>や<ruby><rb>否</rb><rt>いな</rt></ruby>や</span><span><ruby><rb>許</rb><rt>ゆる</rt></ruby>しがたい</span><span><ruby><rb>不徳義漢</rb><rt>ふとくぎかん</rt></ruby></span>に<span><ruby><rb>変</rb><rt>かわ</rt></ruby>った</span>のです。私は彼らから受けた屈辱と損害を<span><ruby><rb>小供</rb><rt>こども</rt></ruby></span>の<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>から<span><ruby><rb>今日</rb><rt>きょう</rt></ruby></span>まで<span><ruby><rb>背負</rb><rt>しょ</rt></ruby>わされている</span>。<span><ruby><rb>恐</rb><rt>おそ</rt></ruby>らく</span>死ぬまで<span><ruby><rb>背負</rb><rt>しょ</rt></ruby>わされ<ruby><rb>通</rb><rt>どお</rt></ruby>し</span>でしょう。私は死ぬまでそれを忘れる事ができないんだから。しかし私はまだ<span><ruby><rb>復讐</rb><rt>ふくしゅう</rt></ruby></span>をしずにいる。<span><ruby><rb>考</rb><rt>かんが</rt></ruby>える</span>と私は<span><ruby><rb>個人</rb><rt>こじん</rt></ruby></span><span>に<ruby><rb>対</rb><rt>たい</rt></ruby>する</span>復讐<span><ruby><rb>以上</rb><rt>いじょう</rt></ruby></span>の事を<span><ruby><rb>現</rb><rt>げん</rt></ruby>に</span>やっているんだ。私は彼らを<span><ruby><rb>憎</rb><rt>にく</rt></ruby>む</span>ばかりじゃない、彼らが<span><ruby><rb>代表</rb><rt>だいひょう</rt></ruby>して</span>いる<span><ruby><rb>人間</rb><rt>にんげん</rt></ruby></span>というものを、<span><ruby><rb>一般</rb><rt>いっぱん</rt></ruby>に</span>憎む事を<span><ruby><rb>覚</rb><rt>おぼ</rt></ruby>えた</span>のだ。私はそれで<span><ruby><rb>沢山</rb><rt>たくさん</rt></ruby></span>だと思う」</p>
		<p>私は<span><ruby><rb>慰藉</rb><rt>いしゃ</rt></ruby></span>の言葉さえ<span><ruby><rb>口</rb><rt>くち</rt></ruby>へ<ruby><rb>出</rb><rt>だ</rt></ruby>せなかった</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>"Did I really seem worked up back there?"</p>
		<p>"Yes, a bit I suppose, but ..."</p>
		<p>"No, that's fine if I did. I was worked up. Discussions on wealth most easily set me off. You may not know it, but I'm terribly vindictive. I never forget a disgrace suffered or an injustice perpetrated. Ten years may pass, or even twenty, yet it all stays with me."</p>
		<p>Sensei spoke with even more passion than before. What surprised me most, though, was not the passion in his words, but the meaning of what he said. I had certainly never expected to hear such revelations from him first hand, and I had never imagined him to harbor such tenacity. I'd believed him a meek spirit. His meekness and decency were what endeared him to me. In a fit of anger I'd challenged him, and now his words appalled me. He continued on.</p>
		<p>"I was deceived. What's worse, I was deceived by my those of my own blood. I'll never forget it. While my father was alive, they had all seemed models of decency. However, the moment he died they began to reveal themselves - a pack of despicable rogues. The disgrace and injustice, all that I suffered at their hands, I've carried with me from childhood to this day. I expect I'll carry it forever. Only death will erase it from my mind. Nevertheless, I've yet to take my vengeance. Or then again, maybe it's no longer personal. I've already taken it further. I've come to despise the whole of humanity, of which those rogues are a part. I suppose that's enough."</p>
		<p>I had no words of consolation to offer.</p>   

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>先刻</rb><rt>さっき</rt></ruby>&nbsp;earlier; before</span><span class="vocabstudy"><ruby><rb>昂奮</rb><rt>こうふん</rt></ruby>した&nbsp;was worked up; became agitated</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>えた&nbsp;appeared; seemed</span>
		<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span>
		<span class="vocabstudy"><ruby><rb>構</rb><rt>かま</rt></ruby>わない&nbsp;doesn't matter; is okay</span><span class="vocabstudy"><ruby><rb>実際</rb><rt>じっさい</rt></ruby>&nbsp;actually; in fact</span><span class="vocabstudy"><ruby><rb>財産</rb><rt>ざいさん</rt></ruby>&nbsp;assets; wealth</span><span class="vocabstudy">の<ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;concerning ...</span><span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らない&nbsp;don't know</span><span class="vocabstudy"><ruby><rb>大変</rb><rt>たいへん</rt></ruby>&nbsp;terribly; a great deal</span><span class="vocabstudy"><ruby><rb>執念</rb><rt>しゅうねん</rt></ruby><ruby><rb>深</rb><rt>ぶか</rt></ruby>い&nbsp;vindictive; spiteful; vengeful</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;(other) people</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>けた&nbsp;received; sustained; suffered</span><span class="vocabstudy"><ruby><rb>屈辱</rb><rt>くつじょく</rt></ruby>&nbsp;disgrace; humiliation</span><span class="vocabstudy"><ruby><rb>損害</rb><rt>そんがい</rt></ruby>&nbsp;damage; injury; loss</span><span class="vocabstudy"><ruby><rb>十年</rb><rt>じゅうねん</rt></ruby>&nbsp;ten years</span><span class="vocabstudy"><ruby><rb>二十年</rb><rt>にじゅうねん</rt></ruby>&nbsp;twenty years</span><span class="vocabstudy"><ruby><rb>忘</rb><rt>わす</rt></ruby>れやしない&nbsp;don't forget</span>
		<span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>元</rb><rt>もと</rt></ruby>よりも&nbsp;more than before</span><span class="vocabstudy"><ruby><rb>驚</rb><rt>おどろ</rt></ruby>いた&nbsp;was surprised</span><span class="vocabstudy"><ruby><rb>決</rb><rt>けっ</rt></ruby>して&nbsp;by (no) means</span><span class="vocabstudy"><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>&nbsp;tone; mood</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>&nbsp;ears</span><span class="vocabstudy"><ruby><rb>訴</rb><rt>うった</rt></ruby>える&nbsp;raise; bring (to one's attention)</span><span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>&nbsp;mouth</span><span class="vocabstudy"><ruby><rb>自白</rb><rt>じはく</rt></ruby>&nbsp;confession</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>く&nbsp;hear</span><span class="vocabstudy"><ruby><rb>全</rb><rt>まった</rt></ruby>く&nbsp;completely; utterly</span><span class="vocabstudy"><ruby><rb>意外</rb><rt>いがい</rt></ruby>&nbsp;unexpected</span><span class="vocabstudy">に<ruby><rb>相違</rb><rt>そうい</rt></ruby>なかった&nbsp;without a doubt; surely</span><span class="vocabstudy"><ruby><rb>性質</rb><rt>せいしつ</rt></ruby>&nbsp;nature; disposition</span><span class="vocabstudy"><ruby><rb>特色</rb><rt>とくしょく</rt></ruby>&nbsp;feature; facet; idiosyncrasy</span><span class="vocabstudy"><ruby><rb>執着力</rb><rt>しゅうじゃくりょく</rt></ruby>&nbsp;tenacity</span><span class="vocabstudy"><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>した&nbsp;imagined</span><span class="vocabstudy"><ruby><rb>弱</rb><rt>よわ</rt></ruby>い&nbsp;meek; mild; passive</span><span class="vocabstudy"><ruby><rb>信</rb><rt>しん</rt></ruby>じて&nbsp;believe; think</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い&nbsp;lofty; noble</span><span class="vocabstudy"><ruby><rb>処</rb><rt>ところ</rt></ruby>&nbsp;point; aspect</span><span class="vocabstudy"><ruby><rb>懐</rb><rt>なつ</rt></ruby>かしみ&nbsp;fondness; attachment</span><span class="vocabstudy"><ruby><rb>根</rb><rt>ね</rt></ruby>&nbsp;roots</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いて&nbsp;set; place</span><span class="vocabstudy"><ruby><rb>一時</rb><rt>いちじ</rt></ruby>の&nbsp;one-time; momentary</span><span class="vocabstudy"><ruby><rb>気分</rb><rt>きぶん</rt></ruby>&nbsp;feeling; mood</span><span class="vocabstudy"><ruby><rb>盾</rb><rt>たて</rt></ruby>を<ruby><rb>突</rb><rt>つ</rt></ruby>いて&nbsp;oppose; defy; set oneself against</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before; in front of</span><span class="vocabstudy"><ruby><rb>小</rb><rt>ちい</rt></ruby>さくなった&nbsp;felt small; shrank back</span>
		<span class="vocabstudy"><ruby><rb>他</rb><rt>ひと</rt></ruby>&nbsp;others</span><span class="vocabstudy"><ruby><rb>欺</rb><rt>あざむ</rt></ruby>かれた&nbsp;was deceived</span><span class="vocabstudy"><ruby><rb>血</rb><rt>ち</rt></ruby>のつづいた<ruby><rb>親戚</rb><rt>しんせき</rt></ruby>&nbsp;blood relations</span><span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>善人</rb><rt>ぜんにん</rt></ruby>&nbsp;good people; virtuous people</span><span class="vocabstudy"><ruby><rb>彼</rb><rt>かれ</rt></ruby>ら&nbsp;they; them</span><span class="vocabstudy"><ruby><rb>死</rb><rt>し</rt></ruby>ぬ&nbsp;die; pass away</span><span class="vocabstudy">や<ruby><rb>否</rb><rt>いな</rt></ruby>や&nbsp;as soon as</span><span class="vocabstudy"><ruby><rb>許</rb><rt>ゆる</rt></ruby>しがたい&nbsp;inexcusable; unpardonable</span><span class="vocabstudy"><ruby><rb>不徳義漢</rb><rt>ふとくぎかん</rt></ruby>&nbsp;rogues; rascals; malefactors</span><span class="vocabstudy"><ruby><rb>変</rb><rt>かわ</rt></ruby>った&nbsp;changed; transformed (into)</span><span class="vocabstudy"><ruby><rb>小供</rb><rt>こども</rt></ruby>&nbsp;child (usually <ruby><rb>子供</rb><rt>こども</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; period</span><span class="vocabstudy"><ruby><rb>今日</rb><rt>きょう</rt></ruby>&nbsp;today; this day</span><span class="vocabstudy"><ruby><rb>背負</rb><rt>しょ</rt></ruby>わされている&nbsp;be burdened with</span><span class="vocabstudy"><ruby><rb>恐</rb><rt>おそ</rt></ruby>らく&nbsp;perhaps; most likely</span><span class="vocabstudy"><ruby><rb>背負</rb><rt>しょ</rt></ruby>わされ<ruby><rb>通</rb><rt>どお</rt></ruby>し&nbsp;be burdened throughout</span><span class="vocabstudy"><ruby><rb>復讐</rb><rt>ふくしゅう</rt></ruby>&nbsp;revenge; payback</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>える&nbsp;consider; think about</span><span class="vocabstudy"><ruby><rb>個人</rb><rt>こじん</rt></ruby>&nbsp;individuals</span><span class="vocabstudy">に<ruby><rb>対</rb><rt>たい</rt></ruby>する&nbsp;with respect to; in relation to</span><span class="vocabstudy"><ruby><rb>以上</rb><rt>いじょう</rt></ruby>&nbsp;above; beyond; more than</span><span class="vocabstudy"><ruby><rb>現</rb><rt>げん</rt></ruby>に&nbsp;in actuality; in fact</span><span class="vocabstudy"><ruby><rb>憎</rb><rt>にく</rt></ruby>む&nbsp;hate; despise</span><span class="vocabstudy"><ruby><rb>代表</rb><rt>だいひょう</rt></ruby>して&nbsp;represent</span><span class="vocabstudy"><ruby><rb>人間</rb><rt>にんげん</rt></ruby>&nbsp;human beings; humanity</span><span class="vocabstudy"><ruby><rb>一般</rb><rt>いっぱん</rt></ruby>に&nbsp;in general; as a whole</span><span class="vocabstudy"><ruby><rb>覚</rb><rt>おぼ</rt></ruby>えた&nbsp;learned (to do)</span><span class="vocabstudy"><ruby><rb>沢山</rb><rt>たくさん</rt></ruby>&nbsp;sufficient; enough</span>
		<span class="vocabstudy"><ruby><rb>慰藉</rb><rt>いしゃ</rt></ruby>&nbsp;consolation; comfort</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>へ<ruby><rb>出</rb><rt>だ</rt></ruby>せなかった&nbsp;could not voice</span>

	</StudyGuide>
);
