// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={67}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>三十四</rb><rt>さんじゅうし</rt></ruby></span></p>
		<p><span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>はその<span><ruby><rb>夜</rb><rt>よ</rt></ruby></span><span><ruby><rb>十時</rb><rt>じゅうじ</rt></ruby></span><span><ruby><rb>過</rb><rt>す</rt></ruby>ぎ</span>に<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>の<span><ruby><rb>家</rb><rt>いえ</rt></ruby></span>を<span><ruby><rb>辞</rb><rt>じ</rt></ruby>した</span>。<span><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三日</rb><rt>さんにち</rt></ruby></span>うちに<span><ruby><rb>帰国</rb><rt>きこく</rt></ruby></span>するはずになっていたので、<span><ruby><rb>座</rb><rt>ざ</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>つ</span><span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>に私はちょっと<span><ruby><rb>暇乞</rb><rt>いとまご</rt></ruby>い</span>の<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>を<span><ruby><rb>述</rb><rt>の</rt></ruby>べた</span>。</p>
		<p>「また<span><ruby><rb>当分</rb><rt>とうぶん</rt></ruby></span><span>お<ruby><rb>目</rb><rt>め</rt></ruby>にかかれません</span>から」</p>
		<p>「<span><ruby><rb>九月</rb><rt>くがつ</rt></ruby></span>には<span><ruby><rb>出</rb><rt>で</rt></ruby>ていらっしゃる</span>んでしょうね」</p>
		<p>私はもう<span><ruby><rb>卒業</rb><rt>そつぎょう</rt></ruby>した</span>のだから、<span><ruby><rb>必</rb><rt>かなら</rt></ruby>ず</span>九月に<span><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>く</rt></ruby>る</span><span><ruby><rb>必要</rb><rt>ひつよう</rt></ruby></span>もなかった。しかし<span><ruby><rb>暑</rb><rt>あつ</rt></ruby>い<ruby><rb>盛</rb><rt>さか</rt></ruby>り</span>の<span><ruby><rb>八月</rb><rt>はちがつ</rt></ruby></span>を<span><ruby><rb>東京</rb><rt>とうきょう</rt></ruby></span>まで<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span><span><ruby><rb>送</rb><rt>おく</rt></ruby>ろう</span>とも<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えて</span>いなかった。私には<span><ruby><rb>位置</rb><rt>いち</rt></ruby></span>を<span><ruby><rb>求</rb><rt>もと</rt></ruby>める</span>ための<span><ruby><rb>貴重</rb><rt>きちょう</rt></ruby>な</span><span><ruby><rb>時間</rb><rt>じかん</rt></ruby></span>というものがなかった。</p>
		<p>「まあ<span><ruby><rb>九月</rb><rt>くがつ</rt></ruby><ruby><rb>頃</rb><rt>ごろ</rt></ruby></span>になるでしょう」</p>
		<p>「じゃずいぶん<span>ご<ruby><rb>機嫌</rb><rt>きげん</rt></ruby>よう</span>。私たちもこの<span><ruby><rb>夏</rb><rt>なつ</rt></ruby></span>はことによるとどこかへ<span><ruby><rb>行</rb><rt>ゆ</rt></ruby>く</span><span>かも<ruby><rb>知</rb><rt>し</rt></ruby>れない</span>のよ。ずいぶん暑そうだから。<span><ruby><rb>行</rb><rt>い</rt></ruby>ったら</span>また<span><ruby><rb>絵端書</rb><rt>えはがき</rt></ruby></span>でも送って<span><ruby><rb>上</rb><rt>あ</rt></ruby>げましょう</span>」</p>
		<p>「どちらの<span><ruby><rb>見当</rb><rt>けんとう</rt></ruby></span>です。もしいらっしゃるとすれば」</p>
		<p>先生はこの<span><ruby><rb>問答</rb><rt>もんどう</rt></ruby></span>を<span>にやにや<ruby><rb>笑</rb><rt>わら</rt></ruby>って</span><span><ruby><rb>聞</rb><rt>き</rt></ruby>いて</span>いた。</p>
		<p>「<span><ruby><rb>何</rb><rt>なに</rt></ruby></span>まだ行くとも行かないとも<span><ruby><rb>極</rb><rt>き</rt></ruby>めて</span>いやしないんです」</p>
		<p><span><ruby><rb>席</rb><rt>せき</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>とう</span>とした<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>、先生は<span><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span>私をつらまえて、「<span><ruby><rb>時</rb><rt>とき</rt></ruby>に</span><span>お<ruby><rb>父</rb><rt>とう</rt></ruby>さん</span>の<span><ruby><rb>病気</rb><rt>びょうき</rt></ruby></span>はどうなんです」と聞いた。私は<span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>の<span><ruby><rb>健康</rb><rt>けんこう</rt></ruby></span>についてほとんど知るところがなかった。<span><ruby><rb>何</rb><rt>なん</rt></ruby>とも</span><span>いって<ruby><rb>来</rb><rt>こ</rt></ruby>ない</span><span><ruby><rb>以上</rb><rt>いじょう</rt></ruby></span>、<span><ruby><rb>悪</rb><rt>わる</rt></ruby>くはない</span>のだろうくらいに考えていた。</p>
		<p>「そんなに<span><ruby><rb>容易</rb><rt>たやす</rt></ruby>く</span>考えられる病気じゃありませんよ。<span><ruby><rb>尿毒症</rb><rt>にょうどくしょう</rt></ruby></span>が<span><ruby><rb>出</rb><rt>で</rt></ruby>る</span>と、もう<span><ruby><rb>駄目</rb><rt>だめ</rt></ruby></span>なんだから」</p>
		<p>尿毒症という言葉も<span><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>も私には<span><ruby><rb>解</rb><rt>わか</rt></ruby>らなかった</span>。この前の<span><ruby><rb>冬休</rb><rt>ふゆやす</rt></ruby>み</span>に<span><ruby><rb>国</rb><rt>くに</rt></ruby></span>で<span><ruby><rb>医者</rb><rt>いしゃ</rt></ruby></span>と<span><ruby><rb>会見</rb><rt>かいけん</rt></ruby>した</span>時に、私はそんな<span><ruby><rb>術語</rb><rt>じゅつご</rt></ruby></span>をまるで聞かなかった。</p>
		<p>「<span><ruby><rb>本当</rb><rt>ほんとう</rt></ruby>に</span><span><ruby><rb>大事</rb><rt>だいじ</rt></ruby>にして</span>お上げなさいよ」と<span><ruby><rb>奥</rb><rt>おく</rt></ruby>さん</span>もいった。「<span><ruby><rb>毒</rb><rt>どく</rt></ruby></span>が<span><ruby><rb>脳</rb><rt>のう</rt></ruby></span>へ<span><ruby><rb>廻</rb><rt>まわ</rt></ruby>る</span>ようになると、もうそれっきりよ、あなた。<span><ruby><rb>笑</rb><rt>わら</rt></ruby>い<ruby><rb>事</rb><rt>ごと</rt></ruby>じゃない</span>わ」</p>
		<p><span><ruby><rb>無経験</rb><rt>むけいけん</rt></ruby>な</span>私は<span><ruby><rb>気味</rb><rt>きみ</rt></ruby>を<ruby><rb>悪</rb><rt>わる</rt></ruby>がりながらも</span>、にやにやしていた。</p>
		<p>「どうせ<span><ruby><rb>助</rb><rt>たす</rt></ruby>からない<ruby><rb>病気</rb><rt>びょうき</rt></ruby></span>だそうですから、いくら<span><ruby><rb>心配</rb><rt>しんぱい</rt></ruby>した</span>って<span><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がありません</span>」</p>
		<p>「そう<span><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>切</rb><rt>き</rt></ruby>りよく</span>考えれば、それまでですけれども」</p>

		<h3 class="section">Rough translation</h3>
		<p>34</p>
		<p>It was after ten when I left Sensei's place. In several days I would return to the country, so before rising I offered parting words.</p>
		<p>"I won't see you again for some time."</p>
		<p>"Will you be back in September?" Sensei's wife asked.</p>
		<p>Now that I'd graduated, there was no particular need for me to return in September. I was sure, though, that I was not going to spend the dog days of August in Tōkyō. Nor was I compelled to come back early to seek a position.</p>
		<p>"I suppose around September."</p>
		<p>"Well, take care then. We may do some traveling this summer ourselves. It looks to be hot here this year. If we do go, we'll send you a postcard."</p>
		<p>"Where did you have in mind?"</p>
		<p>Sensei was grinning as he listened to this exchange. "We don't even know yet that we're going."</p>
		<p>Sensei suddenly stopped me as I prepared to rise from my seat. "By the way, how is your father's health?" he asked.</p>
		<p>There'd been no updates on my father's health. No news, I'd figured, was good news.</p>
		<p>"It's a serious condition. Renal failure is the end of the road."</p>
		<p>I'd never heard the term "renal failure," and I had no idea what it was. Back home during winter break, when we'd talked with the doctor, he hadn't voiced any such term.</p>
		<p>"Do take good care of him," Sensei's wife added, "Once the poison reaches his brain you've lost him. It really is serious."</p>
		<p>I had no experience in such things, and I floated an awkward grin to mask my disquietude. "His disease, they tell us, is incurable, so we'll just have to take things as they come."</p>
		<p>"As long as you're resigned to what's coming."</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>三十四</rb><rt>さんじゅうし</rt></ruby>&nbsp;(part) 34</span>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>夜</rb><rt>よ</rt></ruby>&nbsp;evening</span><span class="vocabstudy"><ruby><rb>十時</rb><rt>じゅうじ</rt></ruby>&nbsp;ten (o'clock)</span><span class="vocabstudy"><ruby><rb>過</rb><rt>す</rt></ruby>ぎ&nbsp;after; past</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>家</rb><rt>いえ</rt></ruby>&nbsp;house; home</span><span class="vocabstudy"><ruby><rb>辞</rb><rt>じ</rt></ruby>した&nbsp;quit; took one's leave</span><span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三日</rb><rt>さんにち</rt></ruby>&nbsp;two or three days; several days</span><span class="vocabstudy"><ruby><rb>帰国</rb><rt>きこく</rt></ruby>&nbsp;return home (to one's native place)</span><span class="vocabstudy"><ruby><rb>座</rb><rt>ざ</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>つ&nbsp;leave one's seat; get up from the table</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before</span><span class="vocabstudy"><ruby><rb>暇乞</rb><rt>いとまご</rt></ruby>い&nbsp;leave-taking; farewell</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>述</rb><rt>の</rt></ruby>べた&nbsp;spoke; expressed</span>
		<span class="vocabstudy"><ruby><rb>当分</rb><rt>とうぶん</rt></ruby>&nbsp;for a while</span><span class="vocabstudy">お<ruby><rb>目</rb><rt>め</rt></ruby>にかかれません&nbsp;won't be able to see</span>
		<span class="vocabstudy"><ruby><rb>九月</rb><rt>くがつ</rt></ruby>&nbsp;September</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>ていらっしゃる&nbsp;appear; be back</span>
		<span class="vocabstudy"><ruby><rb>卒業</rb><rt>そつぎょう</rt></ruby>した&nbsp;graduated</span><span class="vocabstudy"><ruby><rb>必</rb><rt>かなら</rt></ruby>ず&nbsp;necessarily</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come up; return</span><span class="vocabstudy"><ruby><rb>必要</rb><rt>ひつよう</rt></ruby>&nbsp;requirement; need</span><span class="vocabstudy"><ruby><rb>暑</rb><rt>あつ</rt></ruby>い<ruby><rb>盛</rb><rt>さか</rt></ruby>り&nbsp;the height of summer</span><span class="vocabstudy"><ruby><rb>八月</rb><rt>はちがつ</rt></ruby>&nbsp;August</span><span class="vocabstudy"><ruby><rb>東京</rb><rt>とうきょう</rt></ruby>&nbsp;Tōkyō</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;come (to)</span><span class="vocabstudy"><ruby><rb>送</rb><rt>おく</rt></ruby>ろう&nbsp;spend; pass (time)</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えて&nbsp;consider; think (to do)</span><span class="vocabstudy"><ruby><rb>位置</rb><rt>いち</rt></ruby>&nbsp;position</span><span class="vocabstudy"><ruby><rb>求</rb><rt>もと</rt></ruby>める&nbsp;seek; search for</span><span class="vocabstudy"><ruby><rb>貴重</rb><rt>きちょう</rt></ruby>な&nbsp;valuable; precious</span><span class="vocabstudy"><ruby><rb>時間</rb><rt>じかん</rt></ruby>&nbsp;time</span>
		<span class="vocabstudy"><ruby><rb>九月</rb><rt>くがつ</rt></ruby><ruby><rb>頃</rb><rt>ごろ</rt></ruby>&nbsp;around September</span>
		<span class="vocabstudy">ご<ruby><rb>機嫌</rb><rt>きげん</rt></ruby>よう&nbsp;take care</span><span class="vocabstudy"><ruby><rb>夏</rb><rt>なつ</rt></ruby>&nbsp;summer</span><span class="vocabstudy"><ruby><rb>行</rb><rt>ゆ</rt></ruby>く&nbsp;go (to)</span><span class="vocabstudy">かも<ruby><rb>知</rb><rt>し</rt></ruby>れない&nbsp;might ...; may ...</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>ったら&nbsp;go (to)</span><span class="vocabstudy"><ruby><rb>絵端書</rb><rt>えはがき</rt></ruby>&nbsp;(picture) postcard</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>げましょう&nbsp;do (something) for someone</span>
		<span class="vocabstudy"><ruby><rb>見当</rb><rt>けんとう</rt></ruby>&nbsp;direction</span>
		<span class="vocabstudy"><ruby><rb>問答</rb><rt>もんどう</rt></ruby>&nbsp;dialogue; exchange</span><span class="vocabstudy">にやにや<ruby><rb>笑</rb><rt>わら</rt></ruby>って&nbsp;with a grin</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;listen to</span>
		<span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>&nbsp;anyway; at any rate</span><span class="vocabstudy"><ruby><rb>極</rb><rt>き</rt></ruby>めて&nbsp;decide; determine</span>
		<span class="vocabstudy"><ruby><rb>席</rb><rt>せき</rt></ruby>を<ruby><rb>立</rb><rt>た</rt></ruby>とう&nbsp;leave one's seat; get up from the table</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>に&nbsp;by the way</span><span class="vocabstudy">お<ruby><rb>父</rb><rt>とう</rt></ruby>さん&nbsp;(your) father</span><span class="vocabstudy"><ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;illness; malady</span><span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>健康</rb><rt>けんこう</rt></ruby>&nbsp;health; condition</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>とも&nbsp;(no)thing</span><span class="vocabstudy">いって<ruby><rb>来</rb><rt>こ</rt></ruby>ない&nbsp;don't mention; don't report</span><span class="vocabstudy"><ruby><rb>以上</rb><rt>いじょう</rt></ruby>&nbsp;as long as ...; given that ...</span><span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>くはない&nbsp;not bad; all right</span>
		<span class="vocabstudy"><ruby><rb>容易</rb><rt>たやす</rt></ruby>く&nbsp;simply; lightly; casually</span><span class="vocabstudy"><ruby><rb>尿毒症</rb><rt>にょうどくしょう</rt></ruby>&nbsp;uremia (urea in the blood)</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>る&nbsp;appear; arise</span><span class="vocabstudy"><ruby><rb>駄目</rb><rt>だめ</rt></ruby>&nbsp;hopeless; the end</span>
		<span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning</span><span class="vocabstudy"><ruby><rb>解</rb><rt>わか</rt></ruby>らなかった&nbsp;were unknown; were unfamiliar</span><span class="vocabstudy"><ruby><rb>冬休</rb><rt>ふゆやす</rt></ruby>み&nbsp;winter break</span><span class="vocabstudy"><ruby><rb>国</rb><rt>くに</rt></ruby>&nbsp;home country; one's native place</span><span class="vocabstudy"><ruby><rb>医者</rb><rt>いしゃ</rt></ruby>&nbsp;doctor</span><span class="vocabstudy"><ruby><rb>会見</rb><rt>かいけん</rt></ruby>した&nbsp;met with; consulted</span><span class="vocabstudy"><ruby><rb>術語</rb><rt>じゅつご</rt></ruby>&nbsp;technical term</span>
		<span class="vocabstudy"><ruby><rb>本当</rb><rt>ほんとう</rt></ruby>に&nbsp;really</span><span class="vocabstudy"><ruby><rb>大事</rb><rt>だいじ</rt></ruby>にして&nbsp;take good care of</span><span class="vocabstudy"><ruby><rb>奥</rb><rt>おく</rt></ruby>さん&nbsp;Sensei's wife</span><span class="vocabstudy"><ruby><rb>毒</rb><rt>どく</rt></ruby>&nbsp;poison; toxin</span><span class="vocabstudy"><ruby><rb>脳</rb><rt>のう</rt></ruby>&nbsp;brain</span><span class="vocabstudy"><ruby><rb>廻</rb><rt>まわ</rt></ruby>る&nbsp;circulate</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>い<ruby><rb>事</rb><rt>ごと</rt></ruby>じゃない&nbsp;not to be taken lightly</span>
		<span class="vocabstudy"><ruby><rb>無経験</rb><rt>むけいけん</rt></ruby>な&nbsp;lacking in experience</span><span class="vocabstudy"><ruby><rb>気味</rb><rt>きみ</rt></ruby>を<ruby><rb>悪</rb><rt>わる</rt></ruby>がりながらも&nbsp;feeling ill at ease; feeling disquieted</span>
		<span class="vocabstudy"><ruby><rb>助</rb><rt>たす</rt></ruby>からない<ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;incurable disease</span><span class="vocabstudy"><ruby><rb>心配</rb><rt>しんぱい</rt></ruby>した&nbsp;worry; fret</span><span class="vocabstudy"><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がありません&nbsp;nothing can be done</span>
		<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>切</rb><rt>き</rt></ruby>りよく&nbsp;resolutely; resignedly</span>

	</StudyGuide>
);
