// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Botchan' num={83}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「<span><ruby><rb>校長</rb><rt>こうちょう</rt></ruby></span>さんが、ようまあ<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えて</span>みとこうと<span>お<ruby><rb>云</rb><rt>い</rt></ruby>いた</span>げな。それで<span>お<ruby><rb>母</rb><rt>かあ</rt></ruby>さん</span>も<span><ruby><rb>安心</rb><rt>あんしん</rt></ruby>して</span>、<span><ruby><rb>今</rb><rt>いま</rt></ruby>に</span><span><ruby><rb>増給</rb><rt>ぞうきゅう</rt></ruby></span>の<span>ご<ruby><rb>沙汰</rb><rt>さた</rt></ruby></span>があろぞ、<span><ruby><rb>今月</rb><rt>こんげつ</rt></ruby></span>か<span><ruby><rb>来月</rb><rt>らいげつ</rt></ruby></span>かと<span><ruby><rb>首</rb><rt>くび</rt></ruby>を<ruby><rb>長</rb><rt>なが</rt></ruby>くして</span><span><ruby><rb>待</rb><rt>ま</rt></ruby>って</span>おいでたところへ、校長さんがちょっと<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span>くれと<span><ruby><rb>古賀</rb><rt>こが</rt></ruby></span>さんにお云いるけれ、<span><ruby><rb>行</rb><rt>い</rt></ruby>って</span>みると、<span><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby></span>だが<span><ruby><rb>学校</rb><rt>がっこう</rt></ruby></span>は<span><ruby><rb>金</rb><rt>かね</rt></ruby></span>が<span><ruby><rb>足</rb><rt>た</rt></ruby>りん</span>けれ、<span><ruby><rb>月給</rb><rt>げっきゅう</rt></ruby></span>を<span><ruby><rb>上</rb><rt>あ</rt></ruby>げる</span><span><ruby><rb>訳</rb><rt>わけ</rt></ruby>にゆかん</span>。しかし<span><ruby><rb>延岡</rb><rt>のべおか</rt></ruby></span>になら<span><ruby><rb>空</rb><rt>あ</rt></ruby>いた</span><span><ruby><rb>口</rb><rt>くち</rt></ruby></span>があって、そっちなら<span><ruby><rb>毎月</rb><rt>まいつき</rt></ruby></span><span><ruby><rb>五円</rb><rt>ごえん</rt></ruby></span><span><ruby><rb>余分</rb><rt>よぶん</rt></ruby></span>にとれるから、<span>お<ruby><rb>望</rb><rt>のぞ</rt></ruby>み<ruby><rb>通</rb><rt>どお</rt></ruby>り</span>でよかろうと<span><ruby><rb>思</rb><rt>おも</rt></ruby>うて</span>、その<span><ruby><rb>手続</rb><rt>てつづ</rt></ruby>き</span>にしたから行くがええと云われたげな。――」</p>
		<p>「じゃ<span><ruby><rb>相談</rb><rt>そうだん</rt></ruby></span>じゃない、<span><ruby><rb>命令</rb><rt>めいれい</rt></ruby></span>じゃありませんか」</p>
		<p>「さよよ。古賀さんはよそへ行って月給が<span><ruby><rb>増</rb><rt>ま</rt></ruby>す</span>より、<span><ruby><rb>元</rb><rt>もと</rt></ruby>のまま</span>でもええから、ここに<span><ruby><rb>居</rb><rt>お</rt></ruby>りたい</span>。<span><ruby><rb>屋敷</rb><rt>やしき</rt></ruby></span>もあるし、<span><ruby><rb>母</rb><rt>はは</rt></ruby></span>もあるからと<span>お<ruby><rb>頼</rb><rt>たの</rt></ruby>みた</span>けれども、もうそう<span><ruby><rb>極</rb><rt>き</rt></ruby>めた</span>あとで、古賀さんの<span><ruby><rb>代</rb><rt>かわ</rt></ruby>り</span>は<span><ruby><rb>出来</rb><rt>でき</rt></ruby>ている</span>けれ<span><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がない</span>と校長がお云いたげな」</p>
		<p>「へん<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>を<span><ruby><rb>馬鹿</rb><rt>ばか</rt></ruby></span>にしてら、<span><ruby><rb>面白</rb><rt>おもしろ</rt></ruby>くもない</span>。じゃ古賀さんは行く<span><ruby><rb>気</rb><rt>き</rt></ruby></span>はないんですね。<span>どうれで</span><span><ruby><rb>変</rb><rt>へん</rt></ruby></span>だと<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>。五円ぐらい上がったって、あんな<span><ruby><rb>山</rb><rt>やま</rt></ruby></span>の<span><ruby><rb>中</rb><rt>なか</rt></ruby></span>へ<span><ruby><rb>猿</rb><rt>さる</rt></ruby></span>の<span>お<ruby><rb>相手</rb><rt>あいて</rt></ruby></span>をしに行く<span><ruby><rb>唐変木</rb><rt>とうへんぼく</rt></ruby></span>はまずないからね」</p>
		<p>「唐変木て、<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>なんぞなもし」</p>
		<p>「<span><ruby><rb>何</rb><rt>なん</rt></ruby>でもいいで</span>さあ、――<span><ruby><rb>全</rb><rt>まった</rt></ruby>く</span><span><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ</span>の<span><ruby><rb>作略</rb><rt>さりゃく</rt></ruby></span>だね。よくない<span><ruby><rb>仕打</rb><rt>しうち</rt></ruby></span>だ。まるで<span><ruby><rb>欺撃</rb><rt>だましうち</rt></ruby></span>ですね。それでおれの月給を上げるなんて、<span><ruby><rb>不都合</rb><rt>ふつごう</rt></ruby>な</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>があるものか。上げてやるったって、<span><ruby><rb>誰</rb><rt>だれ</rt></ruby></span>が上がってやるものか」</p>
		<p>「先生は月給がお上りるのかなもし」</p>
		<p>「上げてやるって云うから、<span class="vocabstudy"><ruby><rb>断</rb><rt>こと</rt></ruby>わろう</span>と思うんです」</p>
		<p>「何で、お断わりるのぞなもし」</p>
		<p>「何でもお断わりだ。<span class="vocabstudy">お<ruby><rb>婆</rb><rt>ばあ</rt></ruby>さん</span>、あの赤シャツは馬鹿ですぜ。<span class="vocabstudy"><ruby><rb>卑怯</rb><rt>ひきょう</rt></ruby></span>でさあ」</p>
		<p>「卑怯でもあんた、月給を上げておくれたら、<span class="vocabstudy"><ruby><rb>大人</rb><rt>おとな</rt></ruby>しく</span><span class="vocabstudy"><ruby><rb>頂</rb><rt>いただ</rt></ruby>いて</span>おく<span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>得</rb><rt>とく</rt></ruby></span>ぞなもし。<span class="vocabstudy"><ruby><rb>若</rb><rt>わか</rt></ruby>い</span>うちはよく<span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>立</rb><rt>た</rt></ruby>つ</span>ものじゃが、<span class="vocabstudy"><ruby><rb>年</rb><rt>とし</rt></ruby>をとって</span>から<span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>える</span>と、も<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span>の<span class="vocabstudy"><ruby><rb>我慢</rb><rt>がまん</rt></ruby></span>じゃあったのに<span class="vocabstudy"><ruby><rb>惜</rb><rt>お</rt></ruby>しい</span>事をした。腹立てたためにこないな<span class="vocabstudy"><ruby><rb>損</rb><rt>そん</rt></ruby></span>をしたと<span class="vocabstudy"><ruby><rb>悔</rb><rt>くや</rt></ruby>む</span>のが<span class="vocabstudy"><ruby><rb>当</rb><rt>あた</rt></ruby>り<ruby><rb>前</rb><rt>まえ</rt></ruby></span>じゃけれ、お婆の<span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う</span>事をきいて、赤シャツさんが月給をあげてやろとお言いたら、<span class="vocabstudy"><ruby><rb>難有</rb><rt>ありがと</rt></ruby>う</span>と<span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>けて</span>おおきなさいや」</p>
		<p>「<span class="vocabstudy"><ruby><rb>年寄</rb><rt>としより</rt></ruby></span><span class="vocabstudy">の<ruby><rb>癖</rb><rt>くせ</rt></ruby>に</span><span class="vocabstudy"><ruby><rb>余計</rb><rt>よけい</rt></ruby>な<ruby><rb>世話</rb><rt>せわ</rt></ruby>を<ruby><rb>焼</rb><rt>や</rt></ruby>かなくってもいい</span>。おれの月給は上がろうと<span class="vocabstudy"><ruby><rb>下</rb><rt>さ</rt></ruby>がろう</span>とおれの月給だ」</p>

		<h3 class="section">Rough translation</h3>
		<p>"The principal told her he would think it over. This reassured her, and she was anticipating positive news, expecting it would come either this month or next month. The principal asked Koga to his office, but when he went he was told that, unfortunately, school finances were such that a pay raise was not possible. However, there was an opening in Nobeoka that offered five yen more per month. This would meet his needs perfectly, and arrangements had already been made, so he should prepare to go."</p>
		<p>"It was an order then, rather than an offer?"</p>
		<p>"Exactly. Koga would rather stay put at his current salary than transfer elsewhere for a small increase. He made the case that his family home and his mother were here, but the principal told him it was already a done deal and his replacement was on the way."</p>
		<p>"They're playing him for a fool. Despicable. Then Koga has no desire to leave. I thought the whole thing seemed odd. No one could be such a buffoon as to move deep into the mountains and commune with monkeys for a five yen pay raise."</p>
		<p>"Tell me, what is a buffoon?"</p>
		<p>"Never mind. This is a Red Shirt scheme. Unethical and thoroughly foul. And raising my pay as part of the transaction - what could be more improper? Let's just see him try to raise it."</p>
		<p>"You'll be receiving a pay raise?"</p>
		<p>"I was told I'd be given a raise, but I think I'll refuse it."</p>
		<p>"Why would you refuse it?"</p>
		<p>"I have my reasons. Listen, that Red Shirt's an idiot, and he's a coward."</p>
		<p>"He may be a coward, but if he offers you a raise you should receive it gracefully. These things may bother you while you're young, but when you look back later you'll wish you'd been a little more tolerant. We always end up regretting things we lost on account of our passions. Listen to an old woman, and if Red Shirt offers you a raise then accept it with gratitude."</p>
		<p>"I don't need your 'wisdom of age' meddling in my business. I'll make my own decisions concerning my salary."</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>校長</rb><rt>こうちょう</rt></ruby>&nbsp;(school) principal</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えて&nbsp;consider; think over</span><span class="vocabstudy">お<ruby><rb>云</rb><rt>い</rt></ruby>いた&nbsp;said; answered</span><span class="vocabstudy">お<ruby><rb>母</rb><rt>かあ</rt></ruby>さん&nbsp;mother</span><span class="vocabstudy"><ruby><rb>安心</rb><rt>あんしん</rt></ruby>して&nbsp;be reassured</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>に&nbsp;soon</span><span class="vocabstudy"><ruby><rb>増給</rb><rt>ぞうきゅう</rt></ruby>&nbsp;salary increase</span><span class="vocabstudy">ご<ruby><rb>沙汰</rb><rt>さた</rt></ruby>&nbsp;notice; news (of)</span><span class="vocabstudy"><ruby><rb>今月</rb><rt>こんげつ</rt></ruby>&nbsp;this month</span><span class="vocabstudy"><ruby><rb>来月</rb><rt>らいげつ</rt></ruby>&nbsp;next month</span><span class="vocabstudy"><ruby><rb>首</rb><rt>くび</rt></ruby>を<ruby><rb>長</rb><rt>なが</rt></ruby>くして&nbsp;with great anticipation</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>って&nbsp;wait</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;come; stop in</span><span class="vocabstudy"><ruby><rb>古賀</rb><rt>こが</rt></ruby>&nbsp;Koga (a.k.a. Uranari)</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>って&nbsp;go (to); visit</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby>&nbsp;too bad; unfortunate</span><span class="vocabstudy"><ruby><rb>学校</rb><rt>がっこう</rt></ruby>&nbsp;school</span><span class="vocabstudy"><ruby><rb>金</rb><rt>かね</rt></ruby>&nbsp;money</span><span class="vocabstudy"><ruby><rb>足</rb><rt>た</rt></ruby>りん&nbsp;be insufficient</span><span class="vocabstudy"><ruby><rb>月給</rb><rt>げっきゅう</rt></ruby>&nbsp;(monthly) salary</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>げる&nbsp;increase</span><span class="vocabstudy"><ruby><rb>訳</rb><rt>わけ</rt></ruby>にゆかん&nbsp;cannot ...</span><span class="vocabstudy"><ruby><rb>延岡</rb><rt>のべおか</rt></ruby>&nbsp;Nobeoka (city in present-day Miyazaki Prefecture)</span><span class="vocabstudy"><ruby><rb>空</rb><rt>あ</rt></ruby>いた&nbsp;vacant</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>&nbsp;position (for employment)</span><span class="vocabstudy"><ruby><rb>毎月</rb><rt>まいつき</rt></ruby>&nbsp;each month</span><span class="vocabstudy"><ruby><rb>五円</rb><rt>ごえん</rt></ruby>&nbsp;five yen</span><span class="vocabstudy"><ruby><rb>余分</rb><rt>よぶん</rt></ruby>&nbsp;extra</span><span class="vocabstudy">お<ruby><rb>望</rb><rt>のぞ</rt></ruby>み<ruby><rb>通</rb><rt>どお</rt></ruby>り&nbsp;just as desired</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>うて&nbsp;regarding (as)</span><span class="vocabstudy"><ruby><rb>手続</rb><rt>てつづ</rt></ruby>き&nbsp;arrangements</span>
		<span class="vocabstudy"><ruby><rb>相談</rb><rt>そうだん</rt></ruby>&nbsp;talk; consultation</span><span class="vocabstudy"><ruby><rb>命令</rb><rt>めいれい</rt></ruby>&nbsp;order; command</span>
		<span class="vocabstudy"><ruby><rb>増</rb><rt>ま</rt></ruby>す&nbsp;increase</span><span class="vocabstudy"><ruby><rb>元</rb><rt>もと</rt></ruby>のまま&nbsp;as before</span><span class="vocabstudy"><ruby><rb>居</rb><rt>お</rt></ruby>りたい&nbsp;want to be; want to remain</span><span class="vocabstudy"><ruby><rb>屋敷</rb><rt>やしき</rt></ruby>&nbsp;estate; residence</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span><span class="vocabstudy">お<ruby><rb>頼</rb><rt>たの</rt></ruby>みた&nbsp;asked; requested</span><span class="vocabstudy"><ruby><rb>極</rb><rt>き</rt></ruby>めた&nbsp;decided</span><span class="vocabstudy"><ruby><rb>代</rb><rt>かわ</rt></ruby>り&nbsp;replacement</span><span class="vocabstudy"><ruby><rb>出来</rb><rt>でき</rt></ruby>ている&nbsp;be ready; be chosen</span><span class="vocabstudy"><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がない&nbsp;cannot be helped; nothing can be done</span>
		<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;a person</span><span class="vocabstudy"><ruby><rb>馬鹿</rb><rt>ばか</rt></ruby>&nbsp;fool</span><span class="vocabstudy"><ruby><rb>面白</rb><rt>おもしろ</rt></ruby>くもない&nbsp;unpleasant; disagreeable</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>&nbsp;desire; volition</span><span class="vocabstudy">どうれで&nbsp;no wonder ... (= どうりで)</span><span class="vocabstudy"><ruby><rb>変</rb><rt>へん</rt></ruby>&nbsp;strange; odd</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought</span><span class="vocabstudy"><ruby><rb>山</rb><rt>やま</rt></ruby>&nbsp;mountains</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;middle (of)</span><span class="vocabstudy"><ruby><rb>猿</rb><rt>さる</rt></ruby>&nbsp;monkey</span><span class="vocabstudy">お<ruby><rb>相手</rb><rt>あいて</rt></ruby>&nbsp;companion</span><span class="vocabstudy"><ruby><rb>唐変木</rb><rt>とうへんぼく</rt></ruby>&nbsp;blockhead; oaf</span>
		<span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;teacher (used here as form of address)</span>
		<span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>でもいいで&nbsp;never mind</span><span class="vocabstudy"><ruby><rb>全</rb><rt>まった</rt></ruby>く&nbsp;completely; utterly</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>シャツ&nbsp;Red Shirt (nickname for the head teacher)</span><span class="vocabstudy"><ruby><rb>作略</rb><rt>さりゃく</rt></ruby>&nbsp;scheme (= <ruby><rb>策略</rb><rt>さくりゃく</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>仕打</rb><rt>しうち</rt></ruby>&nbsp;behavior; conduct</span><span class="vocabstudy"><ruby><rb>欺撃</rb><rt>だましうち</rt></ruby>&nbsp;foul play</span><span class="vocabstudy"><ruby><rb>不都合</rb><rt>ふつごう</rt></ruby>な&nbsp;improper; nefarious</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;action; doing</span><span class="vocabstudy"><ruby><rb>誰</rb><rt>だれ</rt></ruby>&nbsp;who</span>
		<span class="vocabstudy"><ruby><rb>断</rb><rt>こと</rt></ruby>わろう&nbsp;decline; turn down (an offer)</span>
		<span class="vocabstudy">お<ruby><rb>婆</rb><rt>ばあ</rt></ruby>さん&nbsp;old woman (used here as form of address)</span><span class="vocabstudy"><ruby><rb>卑怯</rb><rt>ひきょう</rt></ruby>&nbsp;cowardly; dastardly</span>
		<span class="vocabstudy"><ruby><rb>大人</rb><rt>おとな</rt></ruby>しく&nbsp;quietly; submissively</span><span class="vocabstudy"><ruby><rb>頂</rb><rt>いただ</rt></ruby>いて&nbsp;receive; accept</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;choice; alternative</span><span class="vocabstudy"><ruby><rb>得</rb><rt>とく</rt></ruby>&nbsp;advantageous</span><span class="vocabstudy"><ruby><rb>若</rb><rt>わか</rt></ruby>い&nbsp;young</span><span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>立</rb><rt>た</rt></ruby>つ&nbsp;evoke anger; touch on one's nerves</span><span class="vocabstudy"><ruby><rb>年</rb><rt>とし</rt></ruby>をとって&nbsp;grow older</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>える&nbsp;consider</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a bit</span><span class="vocabstudy"><ruby><rb>我慢</rb><rt>がまん</rt></ruby>&nbsp;patience; perseverance</span><span class="vocabstudy"><ruby><rb>惜</rb><rt>お</rt></ruby>しい&nbsp;regrettable</span><span class="vocabstudy"><ruby><rb>損</rb><rt>そん</rt></ruby>&nbsp;loss</span><span class="vocabstudy"><ruby><rb>悔</rb><rt>くや</rt></ruby>む&nbsp;regret; rue</span><span class="vocabstudy"><ruby><rb>当</rb><rt>あた</rt></ruby>り<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;typical; normal</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;say; tell</span><span class="vocabstudy"><ruby><rb>難有</rb><rt>ありがと</rt></ruby>う&nbsp;thank you</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>けて&nbsp;receive</span>
		<span class="vocabstudy"><ruby><rb>年寄</rb><rt>としより</rt></ruby>&nbsp;older person</span><span class="vocabstudy">の<ruby><rb>癖</rb><rt>くせ</rt></ruby>に&nbsp;like a ...</span><span class="vocabstudy"><ruby><rb>余計</rb><rt>よけい</rt></ruby>な<ruby><rb>世話</rb><rt>せわ</rt></ruby>を<ruby><rb>焼</rb><rt>や</rt></ruby>かなくってもいい&nbsp;you don't need to meddle in my business</span><span class="vocabstudy"><ruby><rb>下</rb><rt>さ</rt></ruby>がろう&nbsp;decrease</span>

	</StudyGuide>
);
