// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={28}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「じゃ<span><ruby><rb>奥</rb><rt>おく</rt></ruby>さん</span>も<span><ruby><rb>信用</rb><rt>しんよう</rt></ruby>なさらない</span>んですか」と<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>に<span><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。</p>
		<p>先生は<span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span><ruby><rb>不安</rb><rt>ふあん</rt></ruby>な</span><span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>をした。そうして<span><ruby><rb>直接</rb><rt>ちょくせつ</rt></ruby>の</span><span><ruby><rb>答</rb><rt>こた</rt></ruby>え</span>を<span><ruby><rb>避</rb><rt>さ</rt></ruby>けた</span>。</p>
		<p>「<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>は<span><ruby><rb>私</rb><rt>わたくし</rt></ruby><ruby><rb>自身</rb><rt>じしん</rt></ruby></span>さえ信用していないのです。つまり<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>で自分が信用できないから、<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>も信用できないようになっているのです。自分を<span><ruby><rb>呪</rb><rt>のろ</rt></ruby>う</span><span>より<ruby><rb>外</rb><rt>ほか</rt></ruby>に</span><span><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がない</span>のです」</p>
		<p>「そうむずかしく<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えれば</span>、<span><ruby><rb>誰</rb><rt>だれ</rt></ruby>だって</span><span><ruby><rb>確</rb><rt>たし</rt></ruby>かな</span>ものはないでしょう」</p>
		<p>「いや考えたんじゃない。やったんです。やった<span><ruby><rb>後</rb><rt>あと</rt></ruby></span>で<span><ruby><rb>驚</rb><rt>おどろ</rt></ruby>いた</span>んです。そうして<span><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>に</span><span><ruby><rb>怖</rb><rt>こわ</rt></ruby>くなった</span>んです」</p>
		<p>私はもう少し<span><ruby><rb>先</rb><rt>さき</rt></ruby></span>まで<span><ruby><rb>同</rb><rt>おな</rt></ruby>じ</span><span><ruby><rb>道</rb><rt>みち</rt></ruby></span>を<span><ruby><rb>辿</rb><rt>たど</rt></ruby>って<ruby><rb>行</rb><rt>ゆ</rt></ruby>きたかった</span>。すると<span><ruby><rb>襖</rb><rt>ふすま</rt></ruby></span>の<span><ruby><rb>陰</rb><rt>かげ</rt></ruby></span>で「あなた、あなた」という奥さんの<span><ruby><rb>声</rb><rt>こえ</rt></ruby></span>が<span><ruby><rb>二度</rb><rt>にど</rt></ruby></span>聞こえた。先生は<span><ruby><rb>二度目</rb><rt>にどめ</rt></ruby></span>に「<span><ruby><rb>何</rb><rt>なん</rt></ruby>だい</span>」といった。奥さんは「ちょっと」と先生を<span><ruby><rb>次</rb><rt>つぎ</rt></ruby>の</span><span><ruby><rb>間</rb><rt>ま</rt></ruby></span>へ<span><ruby><rb>呼</rb><rt>よ</rt></ruby>んだ</span>。<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span><span>の<ruby><rb>間</rb><rt>あいだ</rt></ruby>に</span>どんな<span><ruby><rb>用事</rb><rt>ようじ</rt></ruby></span>が<span><ruby><rb>起</rb><rt>おこ</rt></ruby>った</span>のか、私には<span><ruby><rb>解</rb><rt>わか</rt></ruby>らなかった</span>。それを<span><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>する</span><span><ruby><rb>余裕</rb><rt>よゆう</rt></ruby></span>を<span><ruby><rb>与</rb><rt>あた</rt></ruby>えない</span>ほど<span><ruby><rb>早</rb><rt>はや</rt></ruby>く</span>先生はまた<span><ruby><rb>座敷</rb><rt>ざしき</rt></ruby></span>へ<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。</p>
		<p>「とにかくあまり私を信用してはいけませんよ。<span><ruby><rb>今</rb><rt>いま</rt></ruby>に</span><span><ruby><rb>後悔</rb><rt>こうかい</rt></ruby>する</span>から。そうして自分が<span><ruby><rb>欺</rb><rt>あざむ</rt></ruby>かれた</span><span><ruby><rb>返報</rb><rt>へんぽう</rt></ruby></span>に、<span><ruby><rb>残酷</rb><rt>ざんこく</rt></ruby>な</span><span><ruby><rb>復讐</rb><rt>ふくしゅう</rt></ruby></span>をするようになるものだから」</p>
		<p>「そりゃどういう<span><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>ですか」</p>
		<p>「かつてはその人の<span><ruby><rb>膝</rb><rt>ひざ</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby></span>に<span><ruby><rb>跪</rb><rt>ひざまず</rt></ruby>いた</span>という<span><ruby><rb>記憶</rb><rt>きおく</rt></ruby></span>が、<span><ruby><rb>今度</rb><rt>こんど</rt></ruby></span>はその人の<span><ruby><rb>頭</rb><rt>あたま</rt></ruby></span>の<span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>に<span><ruby><rb>足</rb><rt>あし</rt></ruby>を<ruby><rb>載</rb><rt>の</rt></ruby>せさせよう</span>とするのです。私は<span><ruby><rb>未来</rb><rt>みらい</rt></ruby></span>の<span><ruby><rb>侮辱</rb><rt>ぶじょく</rt></ruby></span>を<span><ruby><rb>受</rb><rt>う</rt></ruby>けない</span>ために、今の<span><ruby><rb>尊敬</rb><rt>そんけい</rt></ruby></span>を<span><ruby><rb>斥</rb><rt>しりぞ</rt></ruby>けたいと<ruby><rb>思</rb><rt>おも</rt></ruby>う</span>のです。私は今より<span><ruby><rb>一層</rb><rt>いっそう</rt></ruby></span><span><ruby><rb>淋</rb><rt>さび</rt></ruby>しい</span>未来の私を<span><ruby><rb>我慢</rb><rt>がまん</rt></ruby>する</span><span><ruby><rb>代</rb><rt>かわ</rt></ruby>りに</span>、淋しい今の私を我慢したいのです。<span><ruby><rb>自由</rb><rt>じゆう</rt></ruby></span>と<span><ruby><rb>独立</rb><rt>どくりつ</rt></ruby></span>と<span><ruby><rb>己</rb><rt>おの</rt></ruby>れ</span>と<span>に<ruby><rb>充</rb><rt>み</rt></ruby>ちた</span><span><ruby><rb>現代</rb><rt>げんだい</rt></ruby></span>に<span><ruby><rb>生</rb><rt>うま</rt></ruby>れた</span><span><ruby><rb>我々</rb><rt>われわれ</rt></ruby></span>は、その<span><ruby><rb>犠牲</rb><rt>ぎせい</rt></ruby></span>としてみんなこの淋しみを<span><ruby><rb>味</rb><rt>あじ</rt></ruby>わわなくてはならない</span>でしょう」</p>
		<p>私はこういう<span><ruby><rb>覚悟</rb><rt>かくご</rt></ruby></span>をもっている先生<span>に<ruby><rb>対</rb><rt>たい</rt></ruby>して</span>、いうべき<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>を<span><ruby><rb>知</rb><rt>し</rt></ruby>らなかった</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>"Then you don't trust even your wife?" I asked.</p>
		<p>Sensei looked a little uneasy. He did not answer me directly. "I don't trust even myself. If I can't trust myself, then how can I trust another? I'm cursed by my own soul."</p>
		<p>"You're thinking too critically. Who could withstand such scrutiny?"</p>
		<p>"No, it's not how I think, it's what I've done. I've been shocked, then horrified, by my own actions."</p>
		<p>I wanted to pursue this further, but Sensei's wife called out to him from the next room. He asked what it was, and she replied that she needed him for a moment. He went to her, and what transpired I cannot say. I had little time to wonder, as he quickly returned to the parlor.</p>
		<p>"At any rate, you mustn't place your faith in me. You'll only regret it. You'll come to feel deluded and retaliate most callously."</p>
		<p>"I'm not sure what you're implying."</p>
		<p>"The thought that you once admired a man will drive you later to tear him down. To preclude your future disdain, I wish to forgo your present admiration. I prefer my current loneliness to a future that's lonelier still. For this modern age, with its personal freedoms, independent thought, and egotistical pursuits, loneliness is the price we pay."</p>
		<p>Faced with such resignation from Sensei, I could offer no response.</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>奥</rb><rt>おく</rt></ruby>さん&nbsp;(your) wife</span><span class="vocabstudy"><ruby><rb>信用</rb><rt>しんよう</rt></ruby>なさらない&nbsp;distrust</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span>
		<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>不安</rb><rt>ふあん</rt></ruby>な&nbsp;uncomfortable; uneasy</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face; (facial) expression</span><span class="vocabstudy"><ruby><rb>直接</rb><rt>ちょくせつ</rt></ruby>の&nbsp;direct</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>え&nbsp;answer</span><span class="vocabstudy"><ruby><rb>避</rb><rt>さ</rt></ruby>けた&nbsp;avoided</span>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby><ruby><rb>自身</rb><rt>じしん</rt></ruby>&nbsp;one's own self</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;(other) people</span><span class="vocabstudy"><ruby><rb>呪</rb><rt>のろ</rt></ruby>う&nbsp;curse; loathe</span><span class="vocabstudy">より<ruby><rb>外</rb><rt>ほか</rt></ruby>に&nbsp;other than to ...</span><span class="vocabstudy"><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がない&nbsp;nothing can be done; there's nothing for it</span>
		<span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えれば&nbsp;consider; regard; view (as)</span><span class="vocabstudy"><ruby><rb>誰</rb><rt>だれ</rt></ruby>だって&nbsp;anyone; whosoever</span><span class="vocabstudy"><ruby><rb>確</rb><rt>たし</rt></ruby>かな&nbsp;reliable; trustworthy</span>
		<span class="vocabstudy"><ruby><rb>後</rb><rt>あと</rt></ruby>&nbsp;after</span><span class="vocabstudy"><ruby><rb>驚</rb><rt>おどろ</rt></ruby>いた&nbsp;was shocked; was taken aback</span><span class="vocabstudy"><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>に&nbsp;extremely; exceedingly</span><span class="vocabstudy"><ruby><rb>怖</rb><rt>こわ</rt></ruby>くなった&nbsp;was appalled; was horrified</span>
		<span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;ahead; further on</span><span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じ&nbsp;the same</span><span class="vocabstudy"><ruby><rb>道</rb><rt>みち</rt></ruby>&nbsp;avenue; path</span><span class="vocabstudy"><ruby><rb>辿</rb><rt>たど</rt></ruby>って<ruby><rb>行</rb><rt>ゆ</rt></ruby>きたかった&nbsp;wanted to follow; wanted to pursue</span><span class="vocabstudy"><ruby><rb>襖</rb><rt>ふすま</rt></ruby>&nbsp;fusuma (sliding screen)</span><span class="vocabstudy"><ruby><rb>陰</rb><rt>かげ</rt></ruby>&nbsp;other side</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice</span><span class="vocabstudy"><ruby><rb>二度</rb><rt>にど</rt></ruby>&nbsp;two times; twice</span><span class="vocabstudy"><ruby><rb>二度目</rb><rt>にどめ</rt></ruby>&nbsp;second time</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>だい&nbsp;yes; what is it</span><span class="vocabstudy"><ruby><rb>次</rb><rt>つぎ</rt></ruby>の&nbsp;adjacent; adjoining</span><span class="vocabstudy"><ruby><rb>間</rb><rt>ま</rt></ruby>&nbsp;room</span><span class="vocabstudy"><ruby><rb>呼</rb><rt>よ</rt></ruby>んだ&nbsp;called; summoned (to)</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy">の<ruby><rb>間</rb><rt>あいだ</rt></ruby>に&nbsp;between ...</span><span class="vocabstudy"><ruby><rb>用事</rb><rt>ようじ</rt></ruby>&nbsp;business; affair; matter</span><span class="vocabstudy"><ruby><rb>起</rb><rt>おこ</rt></ruby>った&nbsp;took place; transpired</span><span class="vocabstudy"><ruby><rb>解</rb><rt>わか</rt></ruby>らなかった&nbsp;was not known</span><span class="vocabstudy"><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>する&nbsp;imagine; guess at</span><span class="vocabstudy"><ruby><rb>余裕</rb><rt>よゆう</rt></ruby>&nbsp;leeway; leisure; time (to do something)</span><span class="vocabstudy"><ruby><rb>与</rb><rt>あた</rt></ruby>えない&nbsp;not provide; not impart to</span><span class="vocabstudy"><ruby><rb>早</rb><rt>はや</rt></ruby>く&nbsp;soon; quickly</span><span class="vocabstudy"><ruby><rb>座敷</rb><rt>ざしき</rt></ruby>&nbsp;living room; parlor</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;returned (to)</span>
		<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>に&nbsp;soon; before long</span><span class="vocabstudy"><ruby><rb>後悔</rb><rt>こうかい</rt></ruby>する&nbsp;regret; be sorry</span><span class="vocabstudy"><ruby><rb>欺</rb><rt>あざむ</rt></ruby>かれた&nbsp;deceived; deluded</span><span class="vocabstudy"><ruby><rb>返報</rb><rt>へんぽう</rt></ruby>&nbsp;requital; retaliatory action</span><span class="vocabstudy"><ruby><rb>残酷</rb><rt>ざんこく</rt></ruby>な&nbsp;harsh; cold-hearted</span><span class="vocabstudy"><ruby><rb>復讐</rb><rt>ふくしゅう</rt></ruby>&nbsp;retribution; reprisal</span>
		<span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning; implication</span>
		<span class="vocabstudy"><ruby><rb>膝</rb><rt>ひざ</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before one (lit: in front of the knees of one who is seated)</span><span class="vocabstudy"><ruby><rb>跪</rb><rt>ひざまず</rt></ruby>いた&nbsp;kneeled (before); showed deference (to)</span><span class="vocabstudy"><ruby><rb>記憶</rb><rt>きおく</rt></ruby>&nbsp;memory</span><span class="vocabstudy"><ruby><rb>今度</rb><rt>こんど</rt></ruby>&nbsp;now; this time</span><span class="vocabstudy"><ruby><rb>頭</rb><rt>あたま</rt></ruby>&nbsp;head</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;top of</span><span class="vocabstudy"><ruby><rb>足</rb><rt>あし</rt></ruby>を<ruby><rb>載</rb><rt>の</rt></ruby>せさせよう&nbsp;rest one's feet on; step on</span><span class="vocabstudy"><ruby><rb>未来</rb><rt>みらい</rt></ruby>&nbsp;future (times)</span><span class="vocabstudy"><ruby><rb>侮辱</rb><rt>ぶじょく</rt></ruby>&nbsp;contempt; scorn; disdain</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>けない&nbsp;not receive; not be subjected to</span><span class="vocabstudy"><ruby><rb>尊敬</rb><rt>そんけい</rt></ruby>&nbsp;respect; adoration; honor</span><span class="vocabstudy"><ruby><rb>斥</rb><rt>しりぞ</rt></ruby>けたいと<ruby><rb>思</rb><rt>おも</rt></ruby>う&nbsp;seek to repel; wish to drive away</span><span class="vocabstudy"><ruby><rb>一層</rb><rt>いっそう</rt></ruby>&nbsp;still more; even more</span><span class="vocabstudy"><ruby><rb>淋</rb><rt>さび</rt></ruby>しい&nbsp;lonely; forsaken</span><span class="vocabstudy"><ruby><rb>我慢</rb><rt>がまん</rt></ruby>する&nbsp;bear; endure</span><span class="vocabstudy"><ruby><rb>代</rb><rt>かわ</rt></ruby>りに&nbsp;instead of; rather than</span><span class="vocabstudy"><ruby><rb>自由</rb><rt>じゆう</rt></ruby>&nbsp;(personal) freedom</span><span class="vocabstudy"><ruby><rb>独立</rb><rt>どくりつ</rt></ruby>&nbsp;independence; self-sufficiency</span><span class="vocabstudy"><ruby><rb>己</rb><rt>おの</rt></ruby>れ&nbsp;self; ego</span><span class="vocabstudy">に<ruby><rb>充</rb><rt>み</rt></ruby>ちた&nbsp;filled with; having in abundance</span><span class="vocabstudy"><ruby><rb>現代</rb><rt>げんだい</rt></ruby>&nbsp;modern age</span><span class="vocabstudy"><ruby><rb>生</rb><rt>うま</rt></ruby>れた&nbsp;born (into)</span><span class="vocabstudy"><ruby><rb>我々</rb><rt>われわれ</rt></ruby>&nbsp;we; us</span><span class="vocabstudy"><ruby><rb>犠牲</rb><rt>ぎせい</rt></ruby>&nbsp;sacrifice; offering; recompense</span><span class="vocabstudy"><ruby><rb>味</rb><rt>あじ</rt></ruby>わわなくてはならない&nbsp;must taste; must experience</span>
		<span class="vocabstudy"><ruby><rb>覚悟</rb><rt>かくご</rt></ruby>&nbsp;resolution; resignation</span><span class="vocabstudy">に<ruby><rb>対</rb><rt>たい</rt></ruby>して&nbsp;against; as counter to</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らなかった&nbsp;did not know (of)</span>

	</StudyGuide>
);
