// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={26}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>が<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>から<span><ruby><rb>離</rb><rt>はな</rt></ruby>れて<ruby><rb>行</rb><rt>い</rt></ruby>く</span>ように<span>お<ruby><rb>思</rb><rt>おも</rt></ruby>いになれば</span><span><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がありません</span>が、私にそんな<span><ruby><rb>気</rb><rt>き</rt></ruby></span>の<span><ruby><rb>起</rb><rt>おこ</rt></ruby>った</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>はまだありません」</p>
		<p>先生は私の<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>に<span><ruby><rb>耳</rb><rt>みみ</rt></ruby>を<ruby><rb>貸</rb><rt>か</rt></ruby>さなかった</span>。</p>
		<p>「しかし<span><ruby><rb>気</rb><rt>き</rt></ruby>を<ruby><rb>付</rb><rt>つ</rt></ruby>けないといけない</span>。<span><ruby><rb>恋</rb><rt>こい</rt></ruby></span>は<span><ruby><rb>罪悪</rb><rt>ざいあく</rt></ruby></span>なんだから。私の<span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>では<span><ruby><rb>満足</rb><rt>まんぞく</rt></ruby></span>が<span><ruby><rb>得</rb><rt>え</rt></ruby>られない</span><span><ruby><rb>代</rb><rt>かわ</rt></ruby>りに</span><span><ruby><rb>危険</rb><rt>きけん</rt></ruby></span>もないが、――<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>、<span><ruby><rb>黒</rb><rt>くろ</rt></ruby>い</span><span><ruby><rb>長</rb><rt>なが</rt></ruby>い</span><span><ruby><rb>髪</rb><rt>かみ</rt></ruby></span>で<span><ruby><rb>縛</rb><rt>しば</rt></ruby>られた</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>の<span><ruby><rb>心持</rb><rt>こころもち</rt></ruby></span>を<span><ruby><rb>知</rb><rt>し</rt></ruby>って</span>いますか」</p>
		<p>私は<span><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>で</span>知っていた。しかし<span><ruby><rb>事実</rb><rt>じじつ</rt></ruby></span>としては知らなかった。いずれにしても先生のいう罪悪という<span><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>は<span><ruby><rb>朦朧</rb><rt>もうろう</rt></ruby>として</span>よく<span><ruby><rb>解</rb><rt>わか</rt></ruby>らなかった</span>。<span>その<ruby><rb>上</rb><rt>うえ</rt></ruby></span>私は<span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span><ruby><rb>不愉快</rb><rt>ふゆかい</rt></ruby></span>になった。</p>
		<p>「先生、罪悪という意味をもっと<span><ruby><rb>判然</rb><rt>はっきり</rt></ruby></span><span>いって<ruby><rb>聞</rb><rt>き</rt></ruby>かして</span><span><ruby><rb>下</rb><rt>くだ</rt></ruby>さい</span>。それでなければこの<span><ruby><rb>問題</rb><rt>もんだい</rt></ruby></span>をここで<span><ruby><rb>切</rb><rt>き</rt></ruby>り<ruby><rb>上</rb><rt>あ</rt></ruby>げて</span>下さい。私<span><ruby><rb>自身</rb><rt>じしん</rt></ruby></span>に罪悪という意味が判然解るまで」</p>
		<p>「<span><ruby><rb>悪</rb><rt>わる</rt></ruby>い</span>事をした。私はあなたに<span><ruby><rb>真実</rb><rt>まこと</rt></ruby></span>を<span><ruby><rb>話</rb><rt>はな</rt></ruby>して</span>いる気でいた。ところが<span><ruby><rb>実際</rb><rt>じっさい</rt></ruby>は</span>、あなたを<span><ruby><rb>焦慮</rb><rt>じら</rt></ruby>して</span>いたのだ。私は悪い事をした」</p>
		<p>先生と私とは<span><ruby><rb>博物館</rb><rt>はくぶつかん</rt></ruby></span>の<span><ruby><rb>裏</rb><rt>うら</rt></ruby></span>から<span><ruby><rb>鶯渓</rb><rt>うぐいすだに</rt></ruby></span>の<span><ruby><rb>方角</rb><rt>ほうがく</rt></ruby></span>に<span><ruby><rb>静</rb><rt>しず</rt></ruby>かな</span><span><ruby><rb>歩調</rb><rt>ほちょう</rt></ruby></span>で<span><ruby><rb>歩</rb><rt>ある</rt></ruby>いて<ruby><rb>行</rb><rt>い</rt></ruby>った</span>。<span><ruby><rb>垣</rb><rt>かき</rt></ruby></span>の<span><ruby><rb>隙間</rb><rt>すきま</rt></ruby></span>から<span><ruby><rb>広</rb><rt>ひろ</rt></ruby>い</span><span><ruby><rb>庭</rb><rt>にわ</rt></ruby></span>の<span><ruby><rb>一部</rb><rt>いちぶ</rt></ruby></span>に<span><ruby><rb>茂</rb><rt>しげ</rt></ruby>る</span><span><ruby><rb>熊笹</rb><rt>くまざさ</rt></ruby></span>が<span><ruby><rb>幽邃</rb><rt>ゆうすい</rt></ruby></span>に<span><ruby><rb>見</rb><rt>み</rt></ruby>えた</span>。</p>
		<p>「君は私がなぜ<span><ruby><rb>毎月</rb><rt>まいげつ</rt></ruby></span><span><ruby><rb>雑司ヶ谷</rb><rt>ぞうしがや</rt></ruby></span>の<span><ruby><rb>墓地</rb><rt>ぼち</rt></ruby></span>に<span><ruby><rb>埋</rb><rt>うま</rt></ruby>っている</span><span><ruby><rb>友人</rb><rt>ゆうじん</rt></ruby></span>の<span><ruby><rb>墓</rb><rt>はか</rt></ruby></span>へ<span><ruby><rb>参</rb><rt>まい</rt></ruby>る</span>のか知っていますか」</p>
		<p>先生のこの<span><ruby><rb>問</rb><rt>と</rt></ruby>い</span>は<span><ruby><rb>全</rb><rt>まった</rt></ruby>く</span><span><ruby><rb>突然</rb><rt>とつぜん</rt></ruby></span>であった。しかも先生は私がこの問い<span>に<ruby><rb>対</rb><rt>たい</rt></ruby>して</span><span><ruby><rb>答</rb><rt>こた</rt></ruby>えられない</span>という事もよく<span><ruby><rb>承知</rb><rt>しょうち</rt></ruby>していた</span>。私はしばらく<span><ruby><rb>返事</rb><rt>へんじ</rt></ruby></span>をしなかった。すると先生は<span><ruby><rb>始</rb><rt>はじ</rt></ruby>めて</span><span><ruby><rb>気</rb><rt>き</rt></ruby>が<ruby><rb>付</rb><rt>つ</rt></ruby>いた</span>ようにこういった。</p>
		<p>「また悪い事をいった。焦慮せるのが悪いと思って、<span><ruby><rb>説明</rb><rt>せつめい</rt></ruby>しようとする</span>と、その説明がまたあなたを焦慮せるような<span><ruby><rb>結果</rb><rt>けっか</rt></ruby></span>になる。どうも仕方がない。この問題はこれで<span><ruby><rb>止</rb><rt>や</rt></ruby>めましょう</span>。とにかく恋は罪悪ですよ、よござんすか。そうして<span><ruby><rb>神聖</rb><rt>しんせい</rt></ruby>な</span>ものですよ」</p>
		<p>私には先生の<span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>がますます解らなくなった。しかし先生はそれぎり恋を<span><ruby><rb>口</rb><rt>くち</rt></ruby>にしなかった</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>"If you're convinced that I'll turn from you, then so be it, but the thought's never crossed my mind."</p>
		<p>Sensei paid no heed to my words. "You have to be vigilant. Love is, indeed, iniquity. While you won't find contentment in my company, you won't face peril either. -- Do you know how it feels to be bound by long black hair?"</p>
		<p>I could imagine what he meant, but it was not something I'd experienced. At any rate, what Sensei meant by "love is iniquity" was not at all clear to me. I was growing a bit uncomfortable.</p>
		<p>"Sensei, explain to me clearly how love is iniquity. Otherwise, let's leave this subject for another day, some day when I might understand."</p>
		<p>"Forgive me. I'd intended to share a truth with you, but I've only confused the matter. I shouldn't have done that."</p>
		<p>We strolled on at a leisurely pace, passing behind the museum and on toward Uguisudani. A thicket of bamboo grass, growing in seclusion in one corner of a vast garden, was visible through gaps in the fence.</p>
		<p>"Do you know why I visit my friend's grave in Zōshigaya each month?"</p>
		<p>Sensei's question was entirely out of the blue, and he knew very well that I had no answer. I refrained for a bit from replying. Sensei, realizing as much, spoke further. "Forgive me again. I felt bad for confusing you, and in thinking to explain things I've only made matters worse. It's no use. Let's leave it at that. Anyway, love is iniquity. Trust me. It's also divine."</p>
		<p>Sensei's words only confounded things further. However, he talked no more of love.</p> 

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>離</rb><rt>はな</rt></ruby>れて<ruby><rb>行</rb><rt>い</rt></ruby>く&nbsp;distance oneself; move away (from)</span><span class="vocabstudy">お<ruby><rb>思</rb><rt>おも</rt></ruby>いになれば&nbsp;if (you) think ...</span><span class="vocabstudy"><ruby><rb>仕方</rb><rt>しかた</rt></ruby>がありません&nbsp;cannot be helped; is out of one's hands</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>&nbsp;inclination</span><span class="vocabstudy"><ruby><rb>起</rb><rt>おこ</rt></ruby>った&nbsp;occurred</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;act; instance</span>
		<span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>を<ruby><rb>貸</rb><rt>か</rt></ruby>さなかった&nbsp;paid no heed (to)</span>
		<span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>を<ruby><rb>付</rb><rt>つ</rt></ruby>けないといけない&nbsp;(you) must be careful; must watch yourself</span><span class="vocabstudy"><ruby><rb>恋</rb><rt>こい</rt></ruby>&nbsp;(romantic) love</span><span class="vocabstudy"><ruby><rb>罪悪</rb><rt>ざいあく</rt></ruby>&nbsp;iniquity; villainy</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place; residence; home</span><span class="vocabstudy"><ruby><rb>満足</rb><rt>まんぞく</rt></ruby>&nbsp;contentment; satisfaction</span><span class="vocabstudy"><ruby><rb>得</rb><rt>え</rt></ruby>られない&nbsp;cannot get; cannot obtain</span><span class="vocabstudy"><ruby><rb>代</rb><rt>かわ</rt></ruby>りに&nbsp;while ...; in return for ...</span><span class="vocabstudy"><ruby><rb>危険</rb><rt>きけん</rt></ruby>&nbsp;danger; peril; risk</span><span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you (used here as form of address)</span><span class="vocabstudy"><ruby><rb>黒</rb><rt>くろ</rt></ruby>い&nbsp;black</span><span class="vocabstudy"><ruby><rb>長</rb><rt>なが</rt></ruby>い&nbsp;long</span><span class="vocabstudy"><ruby><rb>髪</rb><rt>かみ</rt></ruby>&nbsp;hair; locks</span><span class="vocabstudy"><ruby><rb>縛</rb><rt>しば</rt></ruby>られた&nbsp;be tied; be bound (with)</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; instance; occasion</span><span class="vocabstudy"><ruby><rb>心持</rb><rt>こころもち</rt></ruby>&nbsp;feeling</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>って&nbsp;know; understand; be familiar with</span>
		<span class="vocabstudy"><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>で&nbsp;in one's mind; conceptually</span><span class="vocabstudy"><ruby><rb>事実</rb><rt>じじつ</rt></ruby>&nbsp;fact; reality</span><span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning; significance</span><span class="vocabstudy"><ruby><rb>朦朧</rb><rt>もうろう</rt></ruby>として&nbsp;dim; hazy; vague</span><span class="vocabstudy"><ruby><rb>解</rb><rt>わか</rt></ruby>らなかった&nbsp;did not understand; couldn't grasp</span><span class="vocabstudy">その<ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;on top of that; moreover</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>不愉快</rb><rt>ふゆかい</rt></ruby>&nbsp;uncomfortable; ill at ease</span>
		<span class="vocabstudy"><ruby><rb>判然</rb><rt>はっきり</rt></ruby>&nbsp;clearly; plainly</span><span class="vocabstudy">いって<ruby><rb>聞</rb><rt>き</rt></ruby>かして&nbsp;explain</span><span class="vocabstudy"><ruby><rb>下</rb><rt>くだ</rt></ruby>さい&nbsp;please ...</span><span class="vocabstudy"><ruby><rb>問題</rb><rt>もんだい</rt></ruby>&nbsp;subject; topic</span><span class="vocabstudy"><ruby><rb>切</rb><rt>き</rt></ruby>り<ruby><rb>上</rb><rt>あ</rt></ruby>げて&nbsp;drop; let go; bring to an end</span><span class="vocabstudy"><ruby><rb>自身</rb><rt>じしん</rt></ruby>&nbsp;oneself; personally</span>
		<span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>い&nbsp;wrong; unjust</span><span class="vocabstudy"><ruby><rb>真実</rb><rt>まこと</rt></ruby>&nbsp;truth; reality</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>して&nbsp;tell; explain; relate</span><span class="vocabstudy"><ruby><rb>実際</rb><rt>じっさい</rt></ruby>は&nbsp;in fact; in the end</span><span class="vocabstudy"><ruby><rb>焦慮</rb><rt>じら</rt></ruby>して&nbsp;tease; toy with; string along (usually <ruby><rb>焦</rb><rt>じ</rt></ruby>らして)</span>
		<span class="vocabstudy"><ruby><rb>博物館</rb><rt>はくぶつかん</rt></ruby>&nbsp;museum</span><span class="vocabstudy"><ruby><rb>裏</rb><rt>うら</rt></ruby>&nbsp;back side</span><span class="vocabstudy"><ruby><rb>鶯渓</rb><rt>うぐいすだに</rt></ruby>&nbsp;Uguisudani (place name)</span><span class="vocabstudy"><ruby><rb>方角</rb><rt>ほうがく</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かな&nbsp;quiet; calm; leisurely</span><span class="vocabstudy"><ruby><rb>歩調</rb><rt>ほちょう</rt></ruby>&nbsp;pace; cadence</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いて<ruby><rb>行</rb><rt>い</rt></ruby>った&nbsp;walked on; strolled further</span><span class="vocabstudy"><ruby><rb>垣</rb><rt>かき</rt></ruby>&nbsp;fence; hedge</span><span class="vocabstudy"><ruby><rb>隙間</rb><rt>すきま</rt></ruby>&nbsp;intervals; gaps</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い&nbsp;wide; expansive</span><span class="vocabstudy"><ruby><rb>庭</rb><rt>にわ</rt></ruby>&nbsp;garden</span><span class="vocabstudy"><ruby><rb>一部</rb><rt>いちぶ</rt></ruby>&nbsp;(one) part of</span><span class="vocabstudy"><ruby><rb>茂</rb><rt>しげ</rt></ruby>る&nbsp;grow thickly</span><span class="vocabstudy"><ruby><rb>熊笹</rb><rt>くまざさ</rt></ruby>&nbsp;bamboo grass</span><span class="vocabstudy"><ruby><rb>幽邃</rb><rt>ゆうすい</rt></ruby>&nbsp;solitary; quiet and secluded</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>えた&nbsp;appeared</span>
		<span class="vocabstudy"><ruby><rb>毎月</rb><rt>まいげつ</rt></ruby>&nbsp;each month</span><span class="vocabstudy"><ruby><rb>雑司ヶ谷</rb><rt>ぞうしがや</rt></ruby>&nbsp;Zōshigaya (place name)</span><span class="vocabstudy"><ruby><rb>墓地</rb><rt>ぼち</rt></ruby>&nbsp;cemetery</span><span class="vocabstudy"><ruby><rb>埋</rb><rt>うま</rt></ruby>っている&nbsp;be buried</span><span class="vocabstudy"><ruby><rb>友人</rb><rt>ゆうじん</rt></ruby>&nbsp;friend</span><span class="vocabstudy"><ruby><rb>墓</rb><rt>はか</rt></ruby>&nbsp;grave; gravesite</span><span class="vocabstudy"><ruby><rb>参</rb><rt>まい</rt></ruby>る&nbsp;go to; visit</span>
		<span class="vocabstudy"><ruby><rb>問</rb><rt>と</rt></ruby>い&nbsp;question</span><span class="vocabstudy"><ruby><rb>全</rb><rt>まった</rt></ruby>く&nbsp;completely; entirely</span><span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>&nbsp;unexpected; out of the blue</span><span class="vocabstudy">に<ruby><rb>対</rb><rt>たい</rt></ruby>して&nbsp;with respect to; regarding</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えられない&nbsp;cannot answer</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>していた&nbsp;was aware</span><span class="vocabstudy"><ruby><rb>返事</rb><rt>へんじ</rt></ruby>&nbsp;reply; response</span><span class="vocabstudy"><ruby><rb>始</rb><rt>はじ</rt></ruby>めて&nbsp;for the first time; at last; finally</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>が<ruby><rb>付</rb><rt>つ</rt></ruby>いた&nbsp;realized; took notice</span>
		<span class="vocabstudy"><ruby><rb>説明</rb><rt>せつめい</rt></ruby>しようとする&nbsp;try to explain</span><span class="vocabstudy"><ruby><rb>結果</rb><rt>けっか</rt></ruby>&nbsp;result; outcome</span><span class="vocabstudy"><ruby><rb>止</rb><rt>や</rt></ruby>めましょう&nbsp;let's dispense with</span><span class="vocabstudy"><ruby><rb>神聖</rb><rt>しんせい</rt></ruby>な&nbsp;sacred; divine</span>
		<span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;talk; speech</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>にしなかった&nbsp;made no mention; said nothing (of)</span>

	</StudyGuide>
);
