// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={27}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>十四</rb><rt>じゅうし</rt></ruby></span></p>
		<p><span><ruby><rb>年</rb><rt>とし</rt></ruby>の<ruby><rb>若</rb><rt>わか</rt></ruby>い</span><span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>はややともすると<span><ruby><rb>一図</rb><rt>いちず</rt></ruby></span>になりやすかった。<span><ruby><rb>少</rb><rt>すく</rt></ruby>なくとも</span><span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>の<span><ruby><rb>眼</rb><rt>め</rt></ruby></span>にはそう<span><ruby><rb>映</rb><rt>うつ</rt></ruby>って</span>いたらしい。私には<span><ruby><rb>学校</rb><rt>がっこう</rt></ruby></span>の<span><ruby><rb>講義</rb><rt>こうぎ</rt></ruby></span>よりも先生の<span><ruby><rb>談話</rb><rt>だんわ</rt></ruby></span>の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>が<span><ruby><rb>有益</rb><rt>ゆうえき</rt></ruby></span>なのであった。<span><ruby><rb>教授</rb><rt>きょうじゅ</rt></ruby></span>の<span><ruby><rb>意見</rb><rt>いけん</rt></ruby></span>よりも先生の<span><ruby><rb>思想</rb><rt>しそう</rt></ruby></span>の方が<span><ruby><rb>有難</rb><rt>ありがた</rt></ruby>い</span>のであった。<span>とどの<ruby><rb>詰</rb><rt>つ</rt></ruby>まりをいえば</span>、<span><ruby><rb>教壇</rb><rt>きょうだん</rt></ruby></span>に<span><ruby><rb>立</rb><rt>た</rt></ruby>って</span>私を<span><ruby><rb>指導</rb><rt>しどう</rt></ruby>して</span>くれる<span><ruby><rb>偉</rb><rt>えら</rt></ruby>い</span><span><ruby><rb>人々</rb><rt>ひとびと</rt></ruby></span>よりもただ<span><ruby><rb>独</rb><rt>ひと</rt></ruby>りを<ruby><rb>守</rb><rt>まも</rt></ruby>って</span><span><ruby><rb>多</rb><rt>おお</rt></ruby>く</span>を<span><ruby><rb>語</rb><rt>かた</rt></ruby>らない</span>先生の方が偉く<span><ruby><rb>見</rb><rt>み</rt></ruby>えた</span>のであった。</p>
		<p>「あんまり<span><ruby><rb>逆上</rb><rt>のぼせ</rt></ruby>ちゃ</span>いけません」と先生がいった。</p>
		<p>「<span><ruby><rb>覚</rb><rt>さ</rt></ruby>めた</span><span><ruby><rb>結果</rb><rt>けっか</rt></ruby></span>としてそう<span><ruby><rb>思</rb><rt>おも</rt></ruby>う</span>んです」と<span><ruby><rb>答</rb><rt>こた</rt></ruby>えた</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>の私には<span><ruby><rb>充分</rb><rt>じゅうぶん</rt></ruby>の</span><span><ruby><rb>自信</rb><rt>じしん</rt></ruby></span>があった。その自信を先生は<span><ruby><rb>肯</rb><rt>うけ</rt></ruby>がって</span>くれなかった。</p>
		<p>「あなたは<span><ruby><rb>熱</rb><rt>ねつ</rt></ruby></span>に<span><ruby><rb>浮</rb><rt>う</rt></ruby>かされて</span>いるのです。熱がさめると<span><ruby><rb>厭</rb><rt>いや</rt></ruby>になります</span>。私は<span><ruby><rb>今</rb><rt>いま</rt></ruby></span>のあなたからそれほどに思われるのを、<span><ruby><rb>苦</rb><rt>くる</rt></ruby>しく<ruby><rb>感</rb><rt>かん</rt></ruby>じて</span>います。しかしこれから<span><ruby><rb>先</rb><rt>さき</rt></ruby></span>のあなたに<span><ruby><rb>起</rb><rt>おこ</rt></ruby>るべき</span><span><ruby><rb>変化</rb><rt>へんか</rt></ruby></span>を<span><ruby><rb>予想</rb><rt>よそう</rt></ruby>して</span>見ると、なお苦しくなります」</p>
		<p>「私はそれほど<span><ruby><rb>軽薄</rb><rt>けいはく</rt></ruby></span>に思われているんですか。それほど<span><ruby><rb>不信用</rb><rt>ふしんよう</rt></ruby></span>なんですか」</p>
		<p>「私は<span>お<ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby></span>に思うのです」</p>
		<p>「気の毒だが<span><ruby><rb>信用</rb><rt>しんよう</rt></ruby>されない</span>とおっしゃるんですか」</p>
		<p>先生は<span><ruby><rb>迷惑</rb><rt>めいわく</rt></ruby>そうに</span><span><ruby><rb>庭</rb><rt>にわ</rt></ruby></span>の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>を<span><ruby><rb>向</rb><rt>む</rt></ruby>いた</span>。その庭に、<span>この<ruby><rb>間</rb><rt>あいだ</rt></ruby>まで</span><span><ruby><rb>重</rb><rt>おも</rt></ruby>そうな</span><span><ruby><rb>赤</rb><rt>あか</rt></ruby>い</span><span><ruby><rb>強</rb><rt>つよ</rt></ruby>い</span><span><ruby><rb>色</rb><rt>いろ</rt></ruby></span>を<span>ぽたぽた<ruby><rb>点</rb><rt>てん</rt></ruby>じて</span>いた<span><ruby><rb>椿</rb><rt>つばき</rt></ruby></span>の<span><ruby><rb>花</rb><rt>はな</rt></ruby></span>はもう<span><ruby><rb>一</rb><rt>ひと</rt></ruby>つも</span>見えなかった。先生は<span><ruby><rb>座敷</rb><rt>ざしき</rt></ruby></span>からこの椿の花をよく<span><ruby><rb>眺</rb><rt>なが</rt></ruby>める</span><span><ruby><rb>癖</rb><rt>くせ</rt></ruby></span>があった。</p>
		<p>「信用しないって、<span><ruby><rb>特</rb><rt>とく</rt></ruby>に</span>あなたを信用しないんじゃない。<span><ruby><rb>人間</rb><rt>にんげん</rt></ruby></span><span><ruby><rb>全体</rb><rt>ぜんたい</rt></ruby></span>を信用しないんです」</p>
		<p>その時<span><ruby><rb>生垣</rb><rt>いけがき</rt></ruby></span>の<span><ruby><rb>向</rb><rt>むこ</rt></ruby>う</span>で<span><ruby><rb>金魚</rb><rt>きんぎょ</rt></ruby><ruby><rb>売</rb><rt>う</rt></ruby>り</span>らしい<span><ruby><rb>声</rb><rt>こえ</rt></ruby></span>がした。その<span><ruby><rb>外</rb><rt>ほか</rt></ruby>に</span>は<span><ruby><rb>何</rb><rt>なん</rt></ruby>の</span><span><ruby><rb>聞</rb><rt>き</rt></ruby>こえる</span>ものもなかった。<span><ruby><rb>大通</rb><rt>おおどお</rt></ruby>り</span>から<span><ruby><rb>二丁</rb><rt>にちょう</rt></ruby></span>も<span><ruby><rb>深</rb><rt>ふか</rt></ruby>く</span><span><ruby><rb>折</rb><rt>お</rt></ruby>れ<ruby><rb>込</rb><rt>こ</rt></ruby>んだ</span><span><ruby><rb>小路</rb><rt>こうじ</rt></ruby></span>は<span><ruby><rb>存外</rb><rt>ぞんがい</rt></ruby></span><span><ruby><rb>静</rb><rt>しず</rt></ruby>か</span>であった。<span><ruby><rb>家</rb><rt>うち</rt></ruby></span>の<span><ruby><rb>中</rb><rt>なか</rt></ruby></span>は<span>いつもの<ruby><rb>通</rb><rt>とお</rt></ruby>り</span>ひっそりしていた。私は<span><ruby><rb>次</rb><rt>つぎ</rt></ruby>の</span><span><ruby><rb>間</rb><rt>ま</rt></ruby></span>に<span><ruby><rb>奥</rb><rt>おく</rt></ruby>さん</span>のいる<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>を<span><ruby><rb>知</rb><rt>し</rt></ruby>っていた</span>。<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span><span><ruby><rb>針</rb><rt>はり</rt></ruby><ruby><rb>仕事</rb><rt>しごと</rt></ruby></span>か<span><ruby><rb>何</rb><rt>なに</rt></ruby>か</span>している奥さんの<span><ruby><rb>耳</rb><rt>みみ</rt></ruby></span>に私の<span><ruby><rb>話</rb><rt>はな</rt></ruby>し<ruby><rb>声</rb><rt>ごえ</rt></ruby></span>が聞こえるという事も知っていた。しかし私は<span><ruby><rb>全</rb><rt>まった</rt></ruby>く</span>それを<span><ruby><rb>忘</rb><rt>わす</rt></ruby>れて</span>しまった。</p>

		<h3 class="section">Rough translation</h3>
		<p>14</p>
		<p>As a young man, I was prone to take counsel of my passions. That, at least, was how Sensei saw me. More that the lectures at school, I cherished my talks with him. More than the opinions of professors, I valued his insights. In short, more than the distinguished men who instructed me from their lecterns, I held in esteem the reticent and reclusive Sensei.</p>
		<p>"You mustn't put me on a pedestal," Sensei once cautioned me.</p>
		<p>"My opinion of you is rational and grounded," I answered back in full confidence.</p>
		<p>Sensei did not share my conviction. "You've let yourself be carried away. When you see me for what I am, you'll come to despise me. As it is, I bear your respect as a burden. However, what troubles me most is the thought of how you'll change, of how you must change."</p>
		<p>"Do you think me so fickle, so untrustworthy?"</p>
		<p>"I can't help but pity you."</p>
		<p>"You say you pity me, but you also say you can't trust me."</p>
		<p>Sensei turned toward the garden, a troubled look on his face. On the camellia bush, which had recently dazzled with brilliant splashes of red, not a single flower remained. Sensei was fond of gazing on this bush from his parlor.</p>
		<p>"As far as trust is concerned, I don't distrust you in particular. It's all of humanity whom I distrust."</p>
		<p>In that moment a voice, sounding like a goldfish vendor, sounded from beyond the hedge. Other than that, there was not a sound to be heard. The small lane, set back several blocks from the main thoroughfare, was surprisingly quiet. As always, all was still within the house. I knew that Sensei's wife was in the next room. I also knew she could hear my voice as she worked silently at her sewing or other tasks. At the same time, however, I was oblivious to her presence.</p> 

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>十四</rb><rt>じゅうし</rt></ruby>&nbsp;(part) 14</span>
		<span class="vocabstudy"><ruby><rb>年</rb><rt>とし</rt></ruby>の<ruby><rb>若</rb><rt>わか</rt></ruby>い&nbsp;few in years; young</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>一図</rb><rt>いちず</rt></ruby>&nbsp;earnest; intense; passionate</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すく</rt></ruby>なくとも&nbsp;at least</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>眼</rb><rt>め</rt></ruby>&nbsp;eyes</span><span class="vocabstudy"><ruby><rb>映</rb><rt>うつ</rt></ruby>って&nbsp;be reflected; appear</span><span class="vocabstudy"><ruby><rb>学校</rb><rt>がっこう</rt></ruby>&nbsp;school</span><span class="vocabstudy"><ruby><rb>講義</rb><rt>こうぎ</rt></ruby>&nbsp;lectures</span><span class="vocabstudy"><ruby><rb>談話</rb><rt>だんわ</rt></ruby>&nbsp;talk; conversation</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;alternative (of two things)</span><span class="vocabstudy"><ruby><rb>有益</rb><rt>ゆうえき</rt></ruby>&nbsp;beneficial; of value</span><span class="vocabstudy"><ruby><rb>教授</rb><rt>きょうじゅ</rt></ruby>&nbsp;professors</span><span class="vocabstudy"><ruby><rb>意見</rb><rt>いけん</rt></ruby>&nbsp;opinions; points of view</span><span class="vocabstudy"><ruby><rb>思想</rb><rt>しそう</rt></ruby>&nbsp;thoughts; ideas</span><span class="vocabstudy"><ruby><rb>有難</rb><rt>ありがた</rt></ruby>い&nbsp;welcome; appreciated</span><span class="vocabstudy">とどの<ruby><rb>詰</rb><rt>つ</rt></ruby>まりをいえば&nbsp;at the end of the day; after all is said and done</span><span class="vocabstudy"><ruby><rb>教壇</rb><rt>きょうだん</rt></ruby>&nbsp;platform; stage (for teaching or lecturing)</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;stand (on)</span><span class="vocabstudy"><ruby><rb>指導</rb><rt>しどう</rt></ruby>して&nbsp;guide; instruct</span><span class="vocabstudy"><ruby><rb>偉</rb><rt>えら</rt></ruby>い&nbsp;distinguished; esteemed</span><span class="vocabstudy"><ruby><rb>人々</rb><rt>ひとびと</rt></ruby>&nbsp;persons; men</span><span class="vocabstudy"><ruby><rb>独</rb><rt>ひと</rt></ruby>りを<ruby><rb>守</rb><rt>まも</rt></ruby>って&nbsp;keep to oneself</span><span class="vocabstudy"><ruby><rb>多</rb><rt>おお</rt></ruby>く&nbsp;much; a lot</span><span class="vocabstudy"><ruby><rb>語</rb><rt>かた</rt></ruby>らない&nbsp;not speak; not talk of; not mention</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>えた&nbsp;appeared; seemed</span>
		<span class="vocabstudy"><ruby><rb>逆上</rb><rt>のぼせ</rt></ruby>ちゃ&nbsp;be (over)enthusiastic toward</span>
		<span class="vocabstudy"><ruby><rb>覚</rb><rt>さ</rt></ruby>めた&nbsp;collected; composed; rational</span><span class="vocabstudy"><ruby><rb>結果</rb><rt>けっか</rt></ruby>&nbsp;result; outcome (of)</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>う&nbsp;think; consider</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた&nbsp;answered; replied</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; occasion</span><span class="vocabstudy"><ruby><rb>充分</rb><rt>じゅうぶん</rt></ruby>の&nbsp;sufficient; adequate</span><span class="vocabstudy"><ruby><rb>自信</rb><rt>じしん</rt></ruby>&nbsp;confidence</span><span class="vocabstudy"><ruby><rb>肯</rb><rt>うけ</rt></ruby>がって&nbsp;accept; give affirmation to</span>
		<span class="vocabstudy"><ruby><rb>熱</rb><rt>ねつ</rt></ruby>&nbsp;enthusiasm; zeal</span><span class="vocabstudy"><ruby><rb>浮</rb><rt>う</rt></ruby>かされて&nbsp;be carried away with</span><span class="vocabstudy"><ruby><rb>厭</rb><rt>いや</rt></ruby>になります&nbsp;be disaffected toward; tire of</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; at present</span><span class="vocabstudy"><ruby><rb>苦</rb><rt>くる</rt></ruby>しく<ruby><rb>感</rb><rt>かん</rt></ruby>じて&nbsp;feel strain; feel distress</span><span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;ahead; in the future</span><span class="vocabstudy"><ruby><rb>起</rb><rt>おこ</rt></ruby>るべき&nbsp;must (inevitably) occur</span><span class="vocabstudy"><ruby><rb>変化</rb><rt>へんか</rt></ruby>&nbsp;change; transition</span><span class="vocabstudy"><ruby><rb>予想</rb><rt>よそう</rt></ruby>して&nbsp;think of; anticipate</span>
		<span class="vocabstudy"><ruby><rb>軽薄</rb><rt>けいはく</rt></ruby>&nbsp;superficial; fickle; undependable</span><span class="vocabstudy"><ruby><rb>不信用</rb><rt>ふしんよう</rt></ruby>&nbsp;untrustworthy</span>
		<span class="vocabstudy">お<ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby>&nbsp;unfortunate; sorry (for someone)</span>
		<span class="vocabstudy"><ruby><rb>信用</rb><rt>しんよう</rt></ruby>されない&nbsp;not trust</span>
		<span class="vocabstudy"><ruby><rb>迷惑</rb><rt>めいわく</rt></ruby>そうに&nbsp;(appearing) troubled; vexed</span><span class="vocabstudy"><ruby><rb>庭</rb><rt>にわ</rt></ruby>&nbsp;garden</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>いた&nbsp;turned (toward)</span><span class="vocabstudy">この<ruby><rb>間</rb><rt>あいだ</rt></ruby>まで&nbsp;until recently</span><span class="vocabstudy"><ruby><rb>重</rb><rt>おも</rt></ruby>そうな&nbsp;heavy (looking); laden</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>い&nbsp;red</span><span class="vocabstudy"><ruby><rb>強</rb><rt>つよ</rt></ruby>い&nbsp;strong; intense</span><span class="vocabstudy"><ruby><rb>色</rb><rt>いろ</rt></ruby>&nbsp;color</span><span class="vocabstudy">ぽたぽた<ruby><rb>点</rb><rt>てん</rt></ruby>じて&nbsp;drop in splotches</span><span class="vocabstudy"><ruby><rb>椿</rb><rt>つばき</rt></ruby>&nbsp;camellia</span><span class="vocabstudy"><ruby><rb>花</rb><rt>はな</rt></ruby>&nbsp;flowers</span><span class="vocabstudy"><ruby><rb>一</rb><rt>ひと</rt></ruby>つも&nbsp;(not) one</span><span class="vocabstudy"><ruby><rb>座敷</rb><rt>ざしき</rt></ruby>&nbsp;living room; parlor</span><span class="vocabstudy"><ruby><rb>眺</rb><rt>なが</rt></ruby>める&nbsp;view; look at; gaze on</span><span class="vocabstudy"><ruby><rb>癖</rb><rt>くせ</rt></ruby>&nbsp;tendency; penchant</span>
		<span class="vocabstudy"><ruby><rb>特</rb><rt>とく</rt></ruby>に&nbsp;particularly; especially</span><span class="vocabstudy"><ruby><rb>人間</rb><rt>にんげん</rt></ruby>&nbsp;human beings; humanity</span><span class="vocabstudy"><ruby><rb>全体</rb><rt>ぜんたい</rt></ruby>&nbsp;in full; in entirety</span>
		<span class="vocabstudy"><ruby><rb>生垣</rb><rt>いけがき</rt></ruby>&nbsp;hedge</span><span class="vocabstudy"><ruby><rb>向</rb><rt>むこ</rt></ruby>う&nbsp;far side</span><span class="vocabstudy"><ruby><rb>金魚</rb><rt>きんぎょ</rt></ruby><ruby><rb>売</rb><rt>う</rt></ruby>り&nbsp;goldfish seller; goldfish vendor</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice; call</span><span class="vocabstudy"><ruby><rb>外</rb><rt>ほか</rt></ruby>に&nbsp;apart from; besides</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>の&nbsp;(no)thing</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>こえる&nbsp;be audible; be heard</span><span class="vocabstudy"><ruby><rb>大通</rb><rt>おおどお</rt></ruby>り&nbsp;broad street; main thoroughfare</span><span class="vocabstudy"><ruby><rb>二丁</rb><rt>にちょう</rt></ruby>&nbsp;2 chō (about 220 meters; about 240 yards)</span><span class="vocabstudy"><ruby><rb>深</rb><rt>ふか</rt></ruby>く&nbsp;deeply</span><span class="vocabstudy"><ruby><rb>折</rb><rt>お</rt></ruby>れ<ruby><rb>込</rb><rt>こ</rt></ruby>んだ&nbsp;tucked; nestled (into)</span><span class="vocabstudy"><ruby><rb>小路</rb><rt>こうじ</rt></ruby>&nbsp;lane; side street</span><span class="vocabstudy"><ruby><rb>存外</rb><rt>ぞんがい</rt></ruby>&nbsp;more than expected</span><span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>か&nbsp;quiet; still</span><span class="vocabstudy"><ruby><rb>家</rb><rt>うち</rt></ruby>&nbsp;house</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;inside</span><span class="vocabstudy">いつもの<ruby><rb>通</rb><rt>とお</rt></ruby>り&nbsp;as always</span><span class="vocabstudy"><ruby><rb>次</rb><rt>つぎ</rt></ruby>の&nbsp;next; adjacent</span><span class="vocabstudy"><ruby><rb>間</rb><rt>ま</rt></ruby>&nbsp;room</span><span class="vocabstudy"><ruby><rb>奥</rb><rt>おく</rt></ruby>さん&nbsp;Sensei's wife</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;fact; reality</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>っていた&nbsp;knew; was aware of</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;in silence</span><span class="vocabstudy"><ruby><rb>針</rb><rt>はり</rt></ruby><ruby><rb>仕事</rb><rt>しごと</rt></ruby>&nbsp;needlework; sewing</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>か&nbsp;something</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>&nbsp;ears</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>し<ruby><rb>声</rb><rt>ごえ</rt></ruby>&nbsp;voice (in conversation)</span><span class="vocabstudy"><ruby><rb>全</rb><rt>まった</rt></ruby>く&nbsp;utterly; completely</span><span class="vocabstudy"><ruby><rb>忘</rb><rt>わす</rt></ruby>れて&nbsp;forget; put out of one's mind</span>

	</StudyGuide>
);
