// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={205}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>として</span>、はじめて<span><ruby><rb>池</rb><rt>いけ</rt></ruby></span>の<span><ruby><rb>周囲</rb><rt>まわり</rt></ruby></span>で<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>に<span><ruby><rb>会</rb><rt>あ</rt></ruby>った</span><span><ruby><rb>暑</rb><rt>あつ</rt></ruby>い</span><span><ruby><rb>昔</rb><rt>むかし</rt></ruby></span>を<span><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「そら、あなた、<span><ruby><rb>椎</rb><rt>しい</rt></ruby></span>の<span><ruby><rb>木</rb><rt>き</rt></ruby></span>の<span><ruby><rb>下</rb><rt>した</rt></ruby></span>にしゃがんでいらしったじゃありませんか」</p>
		<p>「あなたは<span><ruby><rb>団扇</rb><rt>うちわ</rt></ruby></span>をかざして、<span><ruby><rb>高</rb><rt>たか</rt></ruby>い</span><span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>に<span><ruby><rb>立</rb><rt>た</rt></ruby>って</span>いた」</p>
		<p>「あの<span><ruby><rb>絵</rb><rt>え</rt></ruby></span>のとおりでしょう」</p>
		<p>「ええ。あのとおりです」</p>
		<p><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>を<ruby><rb>見合</rb><rt>みあ</rt></ruby>わした</span>。もう<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span>で<span class="vocabstudy"><ruby><rb>白山</rb><rt>はくさん</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>坂</rb><rt>さか</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>る</span>。</p>
		<p><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう</span>から<span class="vocabstudy"><ruby><rb>車</rb><rt>くるま</rt></ruby></span>が<span class="vocabstudy">かけて<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。<span class="vocabstudy"><ruby><rb>黒</rb><rt>くろ</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>帽子</rb><rt>ぼうし</rt></ruby></span>をかぶって、<span class="vocabstudy"><ruby><rb>金縁</rb><rt>きんぶち</rt></ruby>の</span><span class="vocabstudy"><ruby><rb>眼鏡</rb><rt>めがね</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>掛</rb><rt>か</rt></ruby>けて</span>、<span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くから</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て</span>も<span class="vocabstudy"><ruby><rb>色光沢</rb><rt>いろつや</rt></ruby>のいい</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>乗</rb><rt>の</rt></ruby>って</span>いる。この車が三四郎の<span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby></span>にはいった<span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby></span>から、車の上の<span class="vocabstudy"><ruby><rb>若</rb><rt>わか</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>紳士</rb><rt>しんし</rt></ruby></span>は美禰子の<span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby></span>を見つめているらしく<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>われた</span>。<span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三間</rb><rt>さんげん</rt></ruby></span><span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る</span>と、車を<span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span>とめた。<span class="vocabstudy"><ruby><rb>前掛</rb><rt>まえか</rt></ruby>け</span>を<span class="vocabstudy"><ruby><rb>器用</rb><rt>きよう</rt></ruby>に</span>はねのけて、<span class="vocabstudy"><ruby><rb>蹴込</rb><rt>けこ</rt></ruby>み</span>から<span class="vocabstudy"><ruby><rb>飛</rb><rt>と</rt></ruby>び<ruby><rb>降</rb><rt>お</rt></ruby>りた</span>ところを見ると、<span class="vocabstudy"><ruby><rb>背</rb><rt>せ</rt></ruby></span>の<span class="vocabstudy">すらりと</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>細面</rb><rt>ほそおもて</rt></ruby></span>のりっぱな<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby></span>であった。<span class="vocabstudy"><ruby><rb>髪</rb><rt>かみ</rt></ruby>をきれいにすっている</span>。それでいて、まったく男らしい。</p>
		<p>「<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby></span>まで<span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>って</span>いたけれども、あんまりおそいから<span class="vocabstudy"><ruby><rb>迎</rb><rt>むか</rt></ruby>えに<ruby><rb>来</rb><rt>き</rt></ruby>た</span>」と美禰子の<span class="vocabstudy">まん<ruby><rb>前</rb><rt>まえ</rt></ruby></span>に立った。見おろして<span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>って</span>いる。</p>
		<p>「そう、ありがとう」と美禰子も笑って、男の顔を<span class="vocabstudy"><ruby><rb>見返</rb><rt>みかえ</rt></ruby>した</span>が、その目をすぐ三四郎の方へ<span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>けた</span>。</p>
		<p>「どなた」と男が<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。</p>
		<p>「<span class="vocabstudy"><ruby><rb>大学</rb><rt>だいがく</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby></span>さん」と美禰子が<span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた</span>。</p>
		<p>男は<span class="vocabstudy"><ruby><rb>軽</rb><rt>かる</rt></ruby>く</span>帽子を<span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>って</span>、向こうから<span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby></span>をした。</p>
		<p>「はやく<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>こう</span>。にいさんも待っている」</p>
		<p>いいぐあいに三四郎は<span class="vocabstudy"><ruby><rb>追分</rb><rt>おいわけ</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>曲</rb><rt>ま</rt></ruby>がる</span>べき<span class="vocabstudy"><ruby><rb>横町</rb><rt>よこちょう</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>角</rb><rt>かど</rt></ruby></span>に立っていた。<span class="vocabstudy"><ruby><rb>金</rb><rt>かね</rt></ruby></span>はとうとう<span class="vocabstudy"><ruby><rb>返</rb><rt>かえ</rt></ruby>さずに</span><span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れた</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>Sanshirō, all of a sudden, was drawn back to that sultry day when he'd first seen Mineko at the edge of the pond.</p>
		<p>"Remember? You were crouched there under the oak tree."</p>
		<p>"And you were standing on the hilltop, holding up your fan."</p>
		<p>"Just like the painting."</p> 
		<p>"The exact same scene."</p>
		<p>The two of them looked at each other. They had almost crested the Hakusan hill.</p>
		<p>A cart approached from the opposite direction. Its passenger wore a black hat and sported gold-rimmed glasses. His complexion was discernibly healthy, even from a distance. As soon as the cart had come into view, it had seemed to Sanshirō that the young gentleman on board had his gaze fixed on Mineko. As it came closer, he had his driver pull to a stop. He pushed the apron deftly aside and jumped down from the kick board. He was a handsome man with a tall, straight back and a slender face. He was clean shaven, but masculine nonetheless.</p>
		<p>He stopped in front of Mineko. "After waiting so long, I finally came to get you." He looked down at her with a smile.</p>
		<p>"Thank you." Mineko looked at him and returned his smile. She immediately turned the same expression toward Sanshirō.</p>
		<p>"I don't believe we've met," the man said.</p>
		<p>"This is Ogawa-san, from the university," Mineko responded on Sanshirō's behalf.</p>
		<p>The man tipped his hat lightly by way of introduction.</p>
		<p>"We'd best be going. Your brother is waiting too."</p>
		<p>Sanshirō, conveniently, was left at the corner of the lane that led to Oiwake. In the end, he parted from Mineko with money still in hand.</p>     

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>として&nbsp;all of a sudden</span><span class="vocabstudy"><ruby><rb>池</rb><rt>いけ</rt></ruby>&nbsp;pond</span><span class="vocabstudy"><ruby><rb>周囲</rb><rt>まわり</rt></ruby>&nbsp;circumference; edge</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>会</rb><rt>あ</rt></ruby>った&nbsp;met; encountered</span><span class="vocabstudy"><ruby><rb>暑</rb><rt>あつ</rt></ruby>い&nbsp;hot; sultry</span><span class="vocabstudy"><ruby><rb>昔</rb><rt>むかし</rt></ruby>&nbsp;former time</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;remembered; recalled</span>
		<span class="vocabstudy"><ruby><rb>椎</rb><rt>しい</rt></ruby>&nbsp;chinquapin oak</span><span class="vocabstudy"><ruby><rb>木</rb><rt>き</rt></ruby>&nbsp;tree</span><span class="vocabstudy"><ruby><rb>下</rb><rt>した</rt></ruby>&nbsp;below; beneath</span>
		<span class="vocabstudy"><ruby><rb>団扇</rb><rt>うちわ</rt></ruby>&nbsp;(round) fan</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い&nbsp;high</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;stand</span>
		<span class="vocabstudy"><ruby><rb>絵</rb><rt>え</rt></ruby>&nbsp;painting</span>
		<span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>を<ruby><rb>見合</rb><rt>みあ</rt></ruby>わした&nbsp;looked at each other</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>白山</rb><rt>はくさん</rt></ruby>&nbsp;Hakusan (place name)</span><span class="vocabstudy"><ruby><rb>坂</rb><rt>さか</rt></ruby>&nbsp;hill; slope</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;top of</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>る&nbsp;arrive (at); emerge (onto)</span>
		<span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう&nbsp;the opposite direction</span><span class="vocabstudy"><ruby><rb>車</rb><rt>くるま</rt></ruby>&nbsp;car; cart (rickshaw)</span><span class="vocabstudy">かけて<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;drew near; approached</span><span class="vocabstudy"><ruby><rb>黒</rb><rt>くろ</rt></ruby>い&nbsp;black</span><span class="vocabstudy"><ruby><rb>帽子</rb><rt>ぼうし</rt></ruby>&nbsp;hat</span><span class="vocabstudy"><ruby><rb>金縁</rb><rt>きんぶち</rt></ruby>の&nbsp;gold-rimmed</span><span class="vocabstudy"><ruby><rb>眼鏡</rb><rt>めがね</rt></ruby>&nbsp;glasses</span><span class="vocabstudy"><ruby><rb>掛</rb><rt>か</rt></ruby>けて&nbsp;wear (glasses)</span><span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くから&nbsp;from a distance</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;see; look at</span><span class="vocabstudy"><ruby><rb>色光沢</rb><rt>いろつや</rt></ruby>のいい&nbsp;of healthy complexion</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man; fellow</span><span class="vocabstudy"><ruby><rb>乗</rb><rt>の</rt></ruby>って&nbsp;ride in</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>&nbsp;field of view</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>若</rb><rt>わか</rt></ruby>い&nbsp;young</span><span class="vocabstudy"><ruby><rb>紳士</rb><rt>しんし</rt></ruby>&nbsp;gentleman</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>われた&nbsp;it seemed that ...</span><span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三間</rb><rt>さんげん</rt></ruby>&nbsp;two or three ken (about 5 meters; about 5 yards)</span><span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;ahead</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come (to); arrive (at)</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly; abruptly</span><span class="vocabstudy"><ruby><rb>前掛</rb><rt>まえか</rt></ruby>け&nbsp;apron; front covering</span><span class="vocabstudy"><ruby><rb>器用</rb><rt>きよう</rt></ruby>に&nbsp;deftly</span><span class="vocabstudy"><ruby><rb>蹴込</rb><rt>けこ</rt></ruby>み&nbsp;kick board; running board</span><span class="vocabstudy"><ruby><rb>飛</rb><rt>と</rt></ruby>び<ruby><rb>降</rb><rt>お</rt></ruby>りた&nbsp;jumped down (from)</span><span class="vocabstudy"><ruby><rb>背</rb><rt>せ</rt></ruby>&nbsp;back</span><span class="vocabstudy">すらりと&nbsp;long, slender, and well-proportioned</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い&nbsp;tall</span><span class="vocabstudy"><ruby><rb>細面</rb><rt>ほそおもて</rt></ruby>&nbsp;slender face</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;person</span><span class="vocabstudy"><ruby><rb>髪</rb><rt>かみ</rt></ruby>をきれいにすっている&nbsp;be clean shaven</span>
		<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>って&nbsp;wait</span><span class="vocabstudy"><ruby><rb>迎</rb><rt>むか</rt></ruby>えに<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came to meet</span><span class="vocabstudy">まん<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;directly in front</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>って&nbsp;smile</span>
		<span class="vocabstudy"><ruby><rb>見返</rb><rt>みかえ</rt></ruby>した&nbsp;looked back at</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>けた&nbsp;turned toward</span>
		<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked; inquired</span>
		<span class="vocabstudy"><ruby><rb>大学</rb><rt>だいがく</rt></ruby>&nbsp;university</span><span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby>&nbsp;Ogawa (Sanshirō's family name)</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた&nbsp;answered</span>
		<span class="vocabstudy"><ruby><rb>軽</rb><rt>かる</rt></ruby>く&nbsp;lightly</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>って&nbsp;take (off); tip</span><span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>&nbsp;greeting; salutation</span>
		<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>こう&nbsp;go</span>
		<span class="vocabstudy"><ruby><rb>追分</rb><rt>おいわけ</rt></ruby>&nbsp;Oiwake (place name)</span><span class="vocabstudy"><ruby><rb>曲</rb><rt>ま</rt></ruby>がる&nbsp;turn (into; onto)</span><span class="vocabstudy"><ruby><rb>横町</rb><rt>よこちょう</rt></ruby>&nbsp;side street; lane</span><span class="vocabstudy"><ruby><rb>角</rb><rt>かど</rt></ruby>&nbsp;corner</span><span class="vocabstudy"><ruby><rb>金</rb><rt>かね</rt></ruby>&nbsp;money</span><span class="vocabstudy"><ruby><rb>返</rb><rt>かえ</rt></ruby>さずに&nbsp;without returning; without repaying</span><span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れた&nbsp;separated; parted ways</span>

	</StudyGuide>
);
