// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={114}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「<span><ruby><rb>細工</rb><rt>さいく</rt></ruby>に<ruby><rb>落</rb><rt>お</rt></ruby>ちる</span>というが、ぼくのやる<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>は<span><ruby><rb>自然</rb><rt>しぜん</rt></ruby>の</span><span><ruby><rb>手順</rb><rt>てじゅん</rt></ruby></span>が<span><ruby><rb>狂</rb><rt>くる</rt></ruby>わない</span>ようにあらかじめ<span><ruby><rb>人力</rb><rt>じんりょく</rt></ruby></span>で<span><ruby><rb>装置</rb><rt>そうち</rt></ruby>する</span>だけだ。自然にそむいた<span><ruby><rb>没分暁</rb><rt>ぼつぶんぎょう</rt></ruby>の</span>事を<span><ruby><rb>企</rb><rt>きわだ</rt></ruby>てる</span>のとは<span><ruby><rb>質</rb><rt>たち</rt></ruby>が<ruby><rb>違</rb><rt>ちが</rt></ruby>う</span>。細工だってかまわん。細工が<span><ruby><rb>悪</rb><rt>わる</rt></ruby>い</span>のではない。悪い細工が悪いのだ」</p>
		<p><span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span>ぐうの<ruby><rb>音</rb><rt>ね</rt></ruby>も<ruby><rb>出</rb><rt>で</rt></ruby>なかった</span>。なんだか<span><ruby><rb>文句</rb><rt>もんく</rt></ruby></span>があるようだけれども、<span><ruby><rb>口</rb><rt>くち</rt></ruby>へ<ruby><rb>出</rb><rt>で</rt></ruby>てこない</span>。<span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>の<span><ruby><rb>言</rb><rt>い</rt></ruby>いぐさ</span>のうちで、<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>がまだ<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えていなかった</span><span><ruby><rb>部分</rb><rt>ぶぶん</rt></ruby></span>だけがはっきり<span><ruby><rb>頭</rb><rt>あたま</rt></ruby></span>へ<span><ruby><rb>映</rb><rt>うつ</rt></ruby>って</span>いる。三四郎はむしろそのほうに<span><ruby><rb>感服</rb><rt>かんぷく</rt></ruby>した</span>。</p>
		<p>「それもそうだ」とすこぶる<span><ruby><rb>曖昧</rb><rt>あいまい</rt></ruby>な</span><span><ruby><rb>返事</rb><rt>へんじ</rt></ruby></span>をして、また<span><ruby><rb>肩</rb><rt>かた</rt></ruby>を<ruby><rb>並</rb><rt>なら</rt></ruby>べて</span><span><ruby><rb>歩</rb><rt>ある</rt></ruby>きだした</span>。<span><ruby><rb>正門</rb><rt>せいもん</rt></ruby></span>をはいると、<span><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span><span><ruby><rb>目</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby></span>が<span><ruby><rb>広</rb><rt>ひろ</rt></ruby>くなる</span>。<span><ruby><rb>大</rb><rt>おお</rt></ruby>きな</span><span><ruby><rb>建物</rb><rt>たてもの</rt></ruby></span>が<span><ruby><rb>所々</rb><rt>ところどころ</rt></ruby></span>に<span><ruby><rb>黒</rb><rt>くろ</rt></ruby>く</span><span><ruby><rb>立</rb><rt>た</rt></ruby>って</span>いる。その<span><ruby><rb>屋根</rb><rt>やね</rt></ruby></span>がはっきり<span><ruby><rb>尽</rb><rt>つ</rt></ruby>きる</span><span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>から<span><ruby><rb>明</rb><rt>あき</rt></ruby>らかな</span><span><ruby><rb>空</rb><rt>そら</rt></ruby></span>になる。<span><ruby><rb>星</rb><rt>ほし</rt></ruby></span>が<span>おびただしく</span><span><ruby><rb>多</rb><rt>おお</rt></ruby>い</span>。</p>
		<p>「<span><ruby><rb>美</rb><rt>うつく</rt></ruby>しい</span>空だ」と三四郎が言った。与次郎も空を<span><ruby><rb>見</rb><rt>み</rt></ruby>ながら</span>、<span><ruby><rb>一間</rb><rt>いっけん</rt></ruby></span>ばかり<span><ruby><rb>歩</rb><rt>ある</rt></ruby>いた</span>。<span><ruby><rb>突然</rb><rt>とつぜん</rt></ruby></span>、</p>
		<p>「おい、<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>」と三四郎を<span><ruby><rb>呼</rb><rt>よ</rt></ruby>んだ</span>。三四郎はまたさっきの<span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>の<span><ruby><rb>続</rb><rt>つづ</rt></ruby>き</span>かと<span><ruby><rb>思</rb><rt>おも</rt></ruby>って</span>「なんだ」と<span><ruby><rb>答</rb><rt>こた</rt></ruby>えた</span>。</p>
		<p>「君、こういう空を見てどんな<span><ruby><rb>感</rb><rt>かん</rt></ruby>じ</span>を<span><ruby><rb>起</rb><rt>お</rt></ruby>こす</span>」</p>
		<p>与次郎<span>に<ruby><rb>似合</rb><rt>にあ</rt></ruby>わぬ</span>ことを言った。<span><ruby><rb>無限</rb><rt>むげん</rt></ruby></span>とか<span><ruby><rb>永久</rb><rt>えいきゅう</rt></ruby></span>とかいう<span><ruby><rb>持</rb><rt>ま</rt></ruby>ち<ruby><rb>合</rb><rt>あ</rt></ruby>わせの</span><span><ruby><rb>答</rb><rt>こたえ</rt></ruby></span>はいくらでもあるが、そんなことを言うと与次郎に<span><ruby><rb>笑</rb><rt>わら</rt></ruby>われる</span>と思って三四郎は<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>いた。</p>
		<p>「つまらんなあ<span><ruby><rb>我々</rb><rt>われわれ</rt></ruby></span>は。あしたから、こんな<span><ruby><rb>運動</rb><rt>うんどう</rt></ruby></span>をするのはもうやめにしようかしら。<span><ruby><rb>偉大</rb><rt>いだい</rt></ruby>なる</span><span><ruby><rb>暗闇</rb><rt>くらやみ</rt></ruby></span>を<span><ruby><rb>書</rb><rt>か</rt></ruby>いて</span>も<span>なんの<ruby><rb>役</rb><rt>やく</rt></ruby>にも<ruby><rb>立</rb><rt>た</rt></ruby>ちそうにもない</span>」</p>
		<p>「なぜ急に<span>そんな<ruby><rb>事</rb><rt>こと</rt></ruby></span>を言いだしたのか」</p>
		<p>「この空を見ると、そういう考えになる。――君、<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>に<span>ほれた</span>ことがあるか」</p>
		<p>三四郎は<span><ruby><rb>即答</rb><rt>そくとう</rt></ruby></span>ができなかった。</p>

		<h3 class="section">Rough translation</h3>
		<p>"You talk about lack of tact, but what I'm doing is nothing more than an insertion of human effort to ensure things run their natural course. Attempting some foolish scheme that subverts the natural order of things is fundamentally different. In my case, tact is irrelevant. It's not about tact in poor form. Tact for poor ends is in poor form."</p>
		<p>Sanshirō was completely nonplussed. He wanted to object, but he couldn't find the words. His mind was fixed on points of Yojirō's that he hadn't thought of. He couldn't help being impressed.</p>
		<p>"I can see what you mean." He gave an ambiguous answer, and they resumed walking together. As they passed through the university's main gate, the world before them suddenly broadened. Grand buildings stood all about in silhouette. Above their crisp roof lines was a crystal clear sky. Endless stars were visible.</p>
		<p>"It's a beautiful night," Sanshirō remarked.</p>
		<p>Yojirō walked several paces with his gaze skyward. "Hey," he called out to Sanshirō.</p>
		<p>"What?" Sanshirō answered, assuming Yojirō would continue their earlier discussion.</p>
		<p>"When you see a sky like this, what do you feel?" Yojirō asked uncharacteristically.</p>
		<p>Yojirō was certain to ridicule a trite response like 'infinity' or 'eternity.' Sanshirō remained silent.</p>
		<p>"What are we really accomplishing? Maybe tomorrow I'll drop it all. My writing of 'Great Dark Void' was nothing but a waste of time."</p>
		<p>"What happened all of the sudden?"</p>
		<p>"That's what I feel when I see this sky. -- Tell me, have you ever fallen for a woman?"</p>
		<p>Sanshirō could not provide an immediate reply.</p>    

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>細工</rb><rt>さいく</rt></ruby>に<ruby><rb>落</rb><rt>お</rt></ruby>ちる&nbsp;lacking in tact</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;act; action</span><span class="vocabstudy"><ruby><rb>自然</rb><rt>しぜん</rt></ruby>の&nbsp;natural</span><span class="vocabstudy"><ruby><rb>手順</rb><rt>てじゅん</rt></ruby>&nbsp;process; course</span><span class="vocabstudy"><ruby><rb>狂</rb><rt>くる</rt></ruby>わない&nbsp;not go out of order; remain on track</span><span class="vocabstudy"><ruby><rb>人力</rb><rt>じんりょく</rt></ruby>&nbsp;human effort; manpower</span><span class="vocabstudy"><ruby><rb>装置</rb><rt>そうち</rt></ruby>する&nbsp;take care of; intervene</span><span class="vocabstudy"><ruby><rb>没分暁</rb><rt>ぼつぶんぎょう</rt></ruby>の&nbsp;foolish; ill-advised</span><span class="vocabstudy"><ruby><rb>企</rb><rt>きわだ</rt></ruby>てる&nbsp;attempt; undertake</span><span class="vocabstudy"><ruby><rb>質</rb><rt>たち</rt></ruby>が<ruby><rb>違</rb><rt>ちが</rt></ruby>う&nbsp;is fundamentally different</span><span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>い&nbsp;bad; in poor form</span>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy">ぐうの<ruby><rb>音</rb><rt>ね</rt></ruby>も<ruby><rb>出</rb><rt>で</rt></ruby>なかった&nbsp;was completely nonplussed</span><span class="vocabstudy"><ruby><rb>文句</rb><rt>もんく</rt></ruby>&nbsp;objection; counterpoint</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>へ<ruby><rb>出</rb><rt>で</rt></ruby>てこない&nbsp;couldn't give voice to; couldn't articulate</span><span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>いぐさ&nbsp;words; remarks</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えていなかった&nbsp;hadn't considered</span><span class="vocabstudy"><ruby><rb>部分</rb><rt>ぶぶん</rt></ruby>&nbsp;pieces; parts; points</span><span class="vocabstudy"><ruby><rb>頭</rb><rt>あたま</rt></ruby>&nbsp;head; mind</span><span class="vocabstudy"><ruby><rb>映</rb><rt>うつ</rt></ruby>って&nbsp;be reflected</span><span class="vocabstudy"><ruby><rb>感服</rb><rt>かんぷく</rt></ruby>した&nbsp;be impressed (by)</span>
		<span class="vocabstudy"><ruby><rb>曖昧</rb><rt>あいまい</rt></ruby>な&nbsp;vague; ambiguous</span><span class="vocabstudy"><ruby><rb>返事</rb><rt>へんじ</rt></ruby>&nbsp;reply; response</span><span class="vocabstudy"><ruby><rb>肩</rb><rt>かた</rt></ruby>を<ruby><rb>並</rb><rt>なら</rt></ruby>べて&nbsp;side by side; shoulder to shoulder</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>きだした&nbsp;began walking</span><span class="vocabstudy"><ruby><rb>正門</rb><rt>せいもん</rt></ruby>&nbsp;main gate (of the university)</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before one's eyes</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>くなる&nbsp;widen; broaden</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな&nbsp;large</span><span class="vocabstudy"><ruby><rb>建物</rb><rt>たてもの</rt></ruby>&nbsp;buildings</span><span class="vocabstudy"><ruby><rb>所々</rb><rt>ところどころ</rt></ruby>&nbsp;here and there; all about</span><span class="vocabstudy"><ruby><rb>黒</rb><rt>くろ</rt></ruby>く&nbsp;darkly; in silhouette</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;stand</span><span class="vocabstudy"><ruby><rb>屋根</rb><rt>やね</rt></ruby>&nbsp;rooftops</span><span class="vocabstudy"><ruby><rb>尽</rb><rt>つ</rt></ruby>きる&nbsp;end; terminate</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;places; locations</span><span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかな&nbsp;clear</span><span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby>&nbsp;sky</span><span class="vocabstudy"><ruby><rb>星</rb><rt>ほし</rt></ruby>&nbsp;stars</span><span class="vocabstudy">おびただしく&nbsp;tremendously</span><span class="vocabstudy"><ruby><rb>多</rb><rt>おお</rt></ruby>い&nbsp;numerous</span>
		<span class="vocabstudy"><ruby><rb>美</rb><rt>うつく</rt></ruby>しい&nbsp;beautiful</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>ながら&nbsp;looking at</span><span class="vocabstudy"><ruby><rb>一間</rb><rt>いっけん</rt></ruby>&nbsp;1 ken (about 2 meters; about 2 yards)</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いた&nbsp;walked on</span><span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>&nbsp;suddenly</span>
		<span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you (used here as form of address)</span><span class="vocabstudy"><ruby><rb>呼</rb><rt>よ</rt></ruby>んだ&nbsp;called to</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;discussion</span><span class="vocabstudy"><ruby><rb>続</rb><rt>つづ</rt></ruby>き&nbsp;continuation</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>って&nbsp;thought; assumed</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた&nbsp;answered; replied</span>
		<span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>じ&nbsp;feeling</span><span class="vocabstudy"><ruby><rb>起</rb><rt>お</rt></ruby>こす&nbsp;evoke; awaken</span>
		<span class="vocabstudy">に<ruby><rb>似合</rb><rt>にあ</rt></ruby>わぬ&nbsp;unbecoming of; uncharacteristic</span><span class="vocabstudy"><ruby><rb>無限</rb><rt>むげん</rt></ruby>&nbsp;infinity</span><span class="vocabstudy"><ruby><rb>永久</rb><rt>えいきゅう</rt></ruby>&nbsp;eternity</span><span class="vocabstudy"><ruby><rb>持</rb><rt>ま</rt></ruby>ち<ruby><rb>合</rb><rt>あ</rt></ruby>わせの&nbsp;expected; anticipated</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こたえ</rt></ruby>&nbsp;reply; response</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>われる&nbsp;be mocked; be ridiculed</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;remain silent</span>
		<span class="vocabstudy"><ruby><rb>我々</rb><rt>われわれ</rt></ruby>&nbsp;we; us</span><span class="vocabstudy"><ruby><rb>運動</rb><rt>うんどう</rt></ruby>&nbsp;movement; initiative</span><span class="vocabstudy"><ruby><rb>偉大</rb><rt>いだい</rt></ruby>なる&nbsp;great; mighty</span><span class="vocabstudy"><ruby><rb>暗闇</rb><rt>くらやみ</rt></ruby>&nbsp;darkness; void</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>いて&nbsp;write; compose</span><span class="vocabstudy">なんの<ruby><rb>役</rb><rt>やく</rt></ruby>にも<ruby><rb>立</rb><rt>た</rt></ruby>ちそうにもない&nbsp;doesn't look to be of any use; serves no purpose</span>
		<span class="vocabstudy">そんな<ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;that kind of thing</span>
		<span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;woman</span><span class="vocabstudy">ほれた&nbsp;fall in love</span>
		<span class="vocabstudy"><ruby><rb>即答</rb><rt>そくとう</rt></ruby>&nbsp;immediate reply</span>

	</StudyGuide>
);
