// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={107}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>は<span><ruby><rb>玄関</rb><rt>げんかん</rt></ruby></span>を<span><ruby><rb>上</rb><rt>あ</rt></ruby>がって</span>、<span><ruby><rb>教室</rb><rt>きょうしつ</rt></ruby></span>へはいって、<span><ruby><rb>机</rb><rt>つくえ</rt></ruby></span>に<span><ruby><rb>着</rb><rt>つ</rt></ruby>いた</span>。やがて<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>が<span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>。二人とも<span><ruby><rb>筆記</rb><rt>ひっき</rt></ruby></span>を<span><ruby><rb>始</rb><rt>はじ</rt></ruby>めた</span>。<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は「<span><ruby><rb>偉大</rb><rt>いだい</rt></ruby>なる</span><span><ruby><rb>暗闇</rb><rt>くらやみ</rt></ruby></span>」が<span><ruby><rb>気</rb><rt>き</rt></ruby>にかかる</span>ので、ノートのそばに<span><ruby><rb>文芸時評</rb><rt>ぶんげいじひょう</rt></ruby></span>をあけたまま、筆記のあいまあいまに先生に<span><ruby><rb>知</rb><rt>し</rt></ruby>れない</span>ように<span><ruby><rb>読</rb><rt>よ</rt></ruby>みだした</span>。先生はさいわい<span><ruby><rb>近眼</rb><rt>きんがん</rt></ruby></span>である。<span>のみならず</span><span><ruby><rb>自己</rb><rt>じこ</rt></ruby>の</span><span><ruby><rb>講義</rb><rt>こうぎ</rt></ruby></span>のうちに<span>ぜんぜん</span><span><ruby><rb>埋没</rb><rt>まいぼつ</rt></ruby>して</span>いる。三四郎の<span><ruby><rb>不心得</rb><rt>ふこころえ</rt></ruby></span>にはまるで<span><ruby><rb>関係</rb><rt>かんけい</rt></ruby>しない</span>。三四郎はいい気になって、こっちを筆記したり、あっちを読んだりしていったが、もともと二人でする<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>を<span><ruby><rb>一人</rb><rt>ひとり</rt></ruby>で</span><span><ruby><rb>兼</rb><rt>か</rt></ruby>ねる</span>むりな<span><ruby><rb>芸</rb><rt>げい</rt></ruby></span>だからしまいには「偉大なる暗闇」も講義の筆記も<span><ruby><rb>双方</rb><rt>そうほう</rt></ruby></span>ともに関係がわからなくなった。ただ<span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>の<span><ruby><rb>文章</rb><rt>ぶんしょう</rt></ruby></span>が<span><ruby><rb>一句</rb><rt>いっく</rt></ruby></span>だけはっきり<span><ruby><rb>頭</rb><rt>あたま</rt></ruby></span>にはいった。</p>
		<p>「<span><ruby><rb>自然</rb><rt>しぜん</rt></ruby></span>は<span><ruby><rb>宝石</rb><rt>ほうせき</rt></ruby></span>を<span><ruby><rb>作</rb><rt>つく</rt></ruby>る</span>に<span><ruby><rb>幾年</rb><rt>いくねん</rt></ruby></span>の<span><ruby><rb>星霜</rb><rt>せいそう</rt></ruby></span>を<span><ruby><rb>費</rb><rt>つい</rt></ruby>やした</span>か。またこの宝石が<span><ruby><rb>採掘</rb><rt>さいくつ</rt></ruby></span>の<span><ruby><rb>運</rb><rt>うん</rt></ruby></span>にあうまでに、幾年の星霜を<span><ruby><rb>静</rb><rt>しず</rt></ruby>かに</span><span><ruby><rb>輝</rb><rt>かが</rt></ruby>やいて</span>いたか」という<span><ruby><rb>句</rb><rt>く</rt></ruby></span>である。その<span><ruby><rb>他</rb><rt>ほか</rt></ruby></span>は<span><ruby><rb>不得</rb><rt>ふとく</rt></ruby><ruby><rb>要領</rb><rt>ようりょう</rt></ruby></span>に<span><ruby><rb>終</rb><rt>おわ</rt></ruby>った</span>。<span>その<ruby><rb>代</rb><rt>かわ</rt></ruby>り</span>この<span><ruby><rb>時間</rb><rt>じかん</rt></ruby></span>には stray sheep という<span><ruby><rb>字</rb><rt>じ</rt></ruby></span>を<span><ruby><rb>一</rb><rt>ひと</rt></ruby>つ</span>も<span><ruby><rb>書</rb><rt>か</rt></ruby>かず</span>にすんだ。</p>
		<p>講義が終るやいなや、与次郎は三四郎<span>に<ruby><rb>向</rb><rt>む</rt></ruby>かって</span>、</p>
		<p>「どうだ」と<span><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。じつはまだよく読まないと<span><ruby><rb>答</rb><rt>こた</rt></ruby>える</span>と、時間の<span><ruby><rb>経済</rb><rt>けいざい</rt></ruby></span>を知らない<span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>だといって<span><ruby><rb>非難</rb><rt>ひなん</rt></ruby>した</span>。ぜひ読めという。三四郎は<span><ruby><rb>家</rb><rt>うち</rt></ruby></span>へ<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>って</span>ぜひ読むと<span><ruby><rb>約束</rb><rt>やくそく</rt></ruby>した</span>。やがて<span><ruby><rb>昼</rb><rt>ひる</rt></ruby></span>になった。二人は<span><ruby><rb>連</rb><rt>つ</rt></ruby>れ<ruby><rb>立</rb><rt>だ</rt></ruby>って</span><span><ruby><rb>門</rb><rt>もん</rt></ruby></span>を<span><ruby><rb>出</rb><rt>で</rt></ruby>た</span>。</p>
		<p>「<span><ruby><rb>今晩</rb><rt>こんばん</rt></ruby></span><span><ruby><rb>出席</rb><rt>しゅっせき</rt></ruby>する</span>だろうな」と与次郎が<span><ruby><rb>西片町</rb><rt>にしかたまち</rt></ruby></span>へはいる<span><ruby><rb>横町</rb><rt>よこちょう</rt></ruby></span>の<span><ruby><rb>角</rb><rt>かど</rt></ruby></span>で<span><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>留</rb><rt>ど</rt></ruby>まった</span>。<span><ruby><rb>今夜</rb><rt>こんや</rt></ruby></span>は<span><ruby><rb>同級生</rb><rt>どうきゅうせい</rt></ruby></span>の<span><ruby><rb>懇親会</rb><rt>こんしんかい</rt></ruby></span>がある。三四郎は<span><ruby><rb>忘</rb><rt>わす</rt></ruby>れていた</span>。ようやく<span><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>して</span>、<span><ruby><rb>行</rb><rt>い</rt></ruby>く</span>つもりだと答えると、与次郎は、</p>
		<p>「出るまえにちょっと<span><ruby><rb>誘</rb><rt>さそ</rt></ruby>ってくれ</span>。<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>に<span><ruby><rb>話</rb><rt>はな</rt></ruby>す</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>がある」と<span><ruby><rb>言</rb><rt>い</rt></ruby>う</span>。<span><ruby><rb>耳</rb><rt>みみ</rt></ruby></span>のうしろへ<span>ペン<ruby><rb>軸</rb><rt>じく</rt></ruby></span>をはさんでいる。なんとなく<span><ruby><rb>得意</rb><rt>とくい</rt></ruby></span>である。三四郎は<span><ruby><rb>承知</rb><rt>しょうち</rt></ruby>した</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>The two of them went back inside, entered the lecture hall, and took their seats. By and by the professor appeared. They both began taking notes. Sanshirō's mind was on "Great Dark Void," so he set the copy of Literary Review, still open to the page, next to his notebook. When he wasn't writing notes, he was glancing discretely at the magazine. Fortunately, the professor was nearsighted. Furthermore, he was thoroughly absorbed in his own lecture and took no notice of Sanshirō's imprudence. Sanshirō enjoyed himself, note taking here and reading there. Doing the work of two men single-handedly, however, turned out to be an impossible feat. In the end, his lecture notes and "Great Dark Void" became jumbled in his mind. Only one line from Yojirō's writing stuck with clarity.</p>
		<p>"How many years does nature take to form a jewel? And then how many years does it sparkle in silence before fortune discovers it?" This was the line he remembered. The rest was a blur. On the other hand, he'd made it through this whole period without once writing 'stray sheep' in his notes.</p>
		<p>As soon as the lecture ended, Yojirō turned to Sanshirō and asked, "What did you think?"</p>
		<p>When Sanshirō replied that he hadn't read it through yet, Yojirō reproached him for mis-prioritizing his time. Then he implored him to read it. Sanshirō promised he would read it at home without fail. At noon, the two of them left together through the university gate.</p>
		<p>"I trust you're coming tonight?" Yojirō asked when they stopped at the corner in Nishikatamachi. There was a class get-together that evening. Sanshirō had forgotten about it. Finally recalling the details, he replied that he intended to go.</p>
		<p>"Stop by my place before. There's something I want to talk to you about." Yojirō had a pen barrel propped behind his ear, and he seemed in high spirits. Sanshirō accepted his request.</p>   

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>玄関</rb><rt>げんかん</rt></ruby>&nbsp;entryway</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>がって&nbsp;entered (up) into</span><span class="vocabstudy"><ruby><rb>教室</rb><rt>きょうしつ</rt></ruby>&nbsp;classroom; lecture hall</span><span class="vocabstudy"><ruby><rb>机</rb><rt>つくえ</rt></ruby>&nbsp;desk; study table</span><span class="vocabstudy"><ruby><rb>着</rb><rt>つ</rt></ruby>いた&nbsp;took (their) places</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;professor</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;arrived</span><span class="vocabstudy"><ruby><rb>筆記</rb><rt>ひっき</rt></ruby>&nbsp;note taking</span><span class="vocabstudy"><ruby><rb>始</rb><rt>はじ</rt></ruby>めた&nbsp;began</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>偉大</rb><rt>いだい</rt></ruby>なる&nbsp;great; mighty</span><span class="vocabstudy"><ruby><rb>暗闇</rb><rt>くらやみ</rt></ruby>&nbsp;darkness; void</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>にかかる&nbsp;weigh on one's mind</span><span class="vocabstudy"><ruby><rb>文芸時評</rb><rt>ぶんげいじひょう</rt></ruby>&nbsp;Literary Review (magazine)</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>れない&nbsp;not be known (to)</span><span class="vocabstudy"><ruby><rb>読</rb><rt>よ</rt></ruby>みだした&nbsp;began to read</span><span class="vocabstudy"><ruby><rb>近眼</rb><rt>きんがん</rt></ruby>&nbsp;nearsighted</span><span class="vocabstudy">のみならず&nbsp;furthermore; moreover</span><span class="vocabstudy"><ruby><rb>自己</rb><rt>じこ</rt></ruby>の&nbsp;one's own</span><span class="vocabstudy"><ruby><rb>講義</rb><rt>こうぎ</rt></ruby>&nbsp;lecture</span><span class="vocabstudy">ぜんぜん&nbsp;completely; thoroughly</span><span class="vocabstudy"><ruby><rb>埋没</rb><rt>まいぼつ</rt></ruby>して&nbsp;be absorbed in</span><span class="vocabstudy"><ruby><rb>不心得</rb><rt>ふこころえ</rt></ruby>&nbsp;indiscretion; imprudence</span><span class="vocabstudy"><ruby><rb>関係</rb><rt>かんけい</rt></ruby>しない&nbsp;took no notice of</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;activity</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>で&nbsp;by oneself</span><span class="vocabstudy"><ruby><rb>兼</rb><rt>か</rt></ruby>ねる&nbsp;find difficult; be unable to do</span><span class="vocabstudy"><ruby><rb>芸</rb><rt>げい</rt></ruby>&nbsp;feat; performance</span><span class="vocabstudy"><ruby><rb>双方</rb><rt>そうほう</rt></ruby>&nbsp;both (sides)</span><span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy"><ruby><rb>文章</rb><rt>ぶんしょう</rt></ruby>&nbsp;writing; composition</span><span class="vocabstudy"><ruby><rb>一句</rb><rt>いっく</rt></ruby>&nbsp;one line</span><span class="vocabstudy"><ruby><rb>頭</rb><rt>あたま</rt></ruby>&nbsp;head; mind</span>
		<span class="vocabstudy"><ruby><rb>自然</rb><rt>しぜん</rt></ruby>&nbsp;nature</span><span class="vocabstudy"><ruby><rb>宝石</rb><rt>ほうせき</rt></ruby>&nbsp;gem; jewel</span><span class="vocabstudy"><ruby><rb>作</rb><rt>つく</rt></ruby>る&nbsp;make; create</span><span class="vocabstudy"><ruby><rb>幾年</rb><rt>いくねん</rt></ruby>&nbsp;a number of years</span><span class="vocabstudy"><ruby><rb>星霜</rb><rt>せいそう</rt></ruby>&nbsp;years; time</span><span class="vocabstudy"><ruby><rb>費</rb><rt>つい</rt></ruby>やした&nbsp;expended; consumed</span><span class="vocabstudy"><ruby><rb>採掘</rb><rt>さいくつ</rt></ruby>&nbsp;digging (for); mining</span><span class="vocabstudy"><ruby><rb>運</rb><rt>うん</rt></ruby>&nbsp;fortune; luck</span><span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かに&nbsp;quietly</span><span class="vocabstudy"><ruby><rb>輝</rb><rt>かが</rt></ruby>やいて&nbsp;glitter; sparkle</span><span class="vocabstudy"><ruby><rb>句</rb><rt>く</rt></ruby>&nbsp;line; verse</span><span class="vocabstudy"><ruby><rb>他</rb><rt>ほか</rt></ruby>&nbsp;others; rest (of something)</span><span class="vocabstudy"><ruby><rb>不得</rb><rt>ふとく</rt></ruby><ruby><rb>要領</rb><rt>ようりょう</rt></ruby>&nbsp;vague; sketchy</span><span class="vocabstudy"><ruby><rb>終</rb><rt>おわ</rt></ruby>った&nbsp;ended; finished</span><span class="vocabstudy">その<ruby><rb>代</rb><rt>かわ</rt></ruby>り&nbsp;on the other hand</span><span class="vocabstudy"><ruby><rb>時間</rb><rt>じかん</rt></ruby>&nbsp;hour; (class) period</span><span class="vocabstudy"><ruby><rb>字</rb><rt>じ</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>一</rb><rt>ひと</rt></ruby>つ&nbsp;one (time)</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>かず&nbsp;without writing</span>
		<span class="vocabstudy">に<ruby><rb>向</rb><rt>む</rt></ruby>かって&nbsp;turning toward</span>
		<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>える&nbsp;respond; answer</span><span class="vocabstudy"><ruby><rb>経済</rb><rt>けいざい</rt></ruby>&nbsp;economy; efficient use of</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;fellow</span><span class="vocabstudy"><ruby><rb>非難</rb><rt>ひなん</rt></ruby>した&nbsp;criticized; reproached</span><span class="vocabstudy"><ruby><rb>家</rb><rt>うち</rt></ruby>&nbsp;home</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って&nbsp;return (to)</span><span class="vocabstudy"><ruby><rb>約束</rb><rt>やくそく</rt></ruby>した&nbsp;promised</span><span class="vocabstudy"><ruby><rb>昼</rb><rt>ひる</rt></ruby>&nbsp;noon</span><span class="vocabstudy"><ruby><rb>連</rb><rt>つ</rt></ruby>れ<ruby><rb>立</rb><rt>だ</rt></ruby>って&nbsp;go together</span><span class="vocabstudy"><ruby><rb>門</rb><rt>もん</rt></ruby>&nbsp;gate</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;departed (through)</span>
		<span class="vocabstudy"><ruby><rb>今晩</rb><rt>こんばん</rt></ruby>&nbsp;tonight</span><span class="vocabstudy"><ruby><rb>出席</rb><rt>しゅっせき</rt></ruby>する&nbsp;attend; take part</span><span class="vocabstudy"><ruby><rb>西片町</rb><rt>にしかたまち</rt></ruby>&nbsp;Nishikatamachi (place name)</span><span class="vocabstudy"><ruby><rb>横町</rb><rt>よこちょう</rt></ruby>&nbsp;side street; lane</span><span class="vocabstudy"><ruby><rb>角</rb><rt>かど</rt></ruby>&nbsp;corner</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>留</rb><rt>ど</rt></ruby>まった&nbsp;came to a stop</span><span class="vocabstudy"><ruby><rb>今夜</rb><rt>こんや</rt></ruby>&nbsp;tonight</span><span class="vocabstudy"><ruby><rb>同級生</rb><rt>どうきゅうせい</rt></ruby>&nbsp;classmates</span><span class="vocabstudy"><ruby><rb>懇親会</rb><rt>こんしんかい</rt></ruby>&nbsp;social gathering; get-together</span><span class="vocabstudy"><ruby><rb>忘</rb><rt>わす</rt></ruby>れていた&nbsp;had forgotten</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>して&nbsp;recalled</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>く&nbsp;go; attend</span>
		<span class="vocabstudy"><ruby><rb>誘</rb><rt>さそ</rt></ruby>ってくれ&nbsp;call on (a person)</span><span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>す&nbsp;discuss</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;matter</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;said</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>&nbsp;ear</span><span class="vocabstudy">ペン<ruby><rb>軸</rb><rt>じく</rt></ruby>&nbsp;pen barrel; pen shaft (for fountain pens with detachable tips)</span><span class="vocabstudy"><ruby><rb>得意</rb><rt>とくい</rt></ruby>&nbsp;proud; highly self-satisfied</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>した&nbsp;agreed (to do something)</span>

	</StudyGuide>
);
