// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={111}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span><span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>の<span><ruby><rb>批評</rb><rt>ひひょう</rt></ruby></span>を<span><ruby><rb>聞</rb><rt>き</rt></ruby>いて</span>いた。どっちの批評も<span>ふにおちない</span>。<span><ruby><rb>乱暴</rb><rt>らんぼう</rt></ruby></span>という<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>が、どうして<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span><span>の<ruby><rb>上</rb><rt>うえ</rt></ruby>に</span><span><ruby><rb>使</rb><rt>つか</rt></ruby>える</span>か、それからが<span><ruby><rb>第一</rb><rt>だいいち</rt></ruby></span><span><ruby><rb>不思議</rb><rt>ふしぎ</rt></ruby></span>であった。</p>
		<p><span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>はやがて、<span><ruby><rb>袴</rb><rt>はかま</rt></ruby></span>をはいて、<span><ruby><rb>改</rb><rt>あらた</rt></ruby>まって<ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>て</span>、</p>
		<p>「ちょっと<span><ruby><rb>行</rb><rt>い</rt></ruby>ってまいります</span>」と<span><ruby><rb>言</rb><rt>い</rt></ruby>う</span>。<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>は黙って<span><ruby><rb>茶</rb><rt>ちゃ</rt></ruby></span>を<span><ruby><rb>飲</rb><rt>の</rt></ruby>んで</span>いる。二人は<span><ruby><rb>表</rb><rt>おもて</rt></ruby></span>へ<span><ruby><rb>出</rb><rt>で</rt></ruby>た</span>。表はもう<span><ruby><rb>暗</rb><rt>くら</rt></ruby>い</span>。<span><ruby><rb>門</rb><rt>もん</rt></ruby></span>を<span><ruby><rb>離</rb><rt>はな</rt></ruby>れて</span><span><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三間</rb><rt>さんげん</rt></ruby></span><span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>と、三四郎はすぐ<span><ruby><rb>話</rb><rt>はな</rt></ruby>しかけた</span>。</p>
		<p>「先生は<span><ruby><rb>里見</rb><rt>さとみ</rt></ruby></span>の<span>お<ruby><rb>嬢</rb><rt>じょう</rt></ruby>さん</span>を乱暴だと言ったね」</p>
		<p>「うん。先生はかってな<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>をいう<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>だから、<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>と<span><ruby><rb>場合</rb><rt>ばあい</rt></ruby></span>によるとなんでも言う。第一先生が<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>を<span><ruby><rb>評</rb><rt>ひょう</rt></ruby>する</span>のが<span><ruby><rb>滑稽</rb><rt>こっけい</rt></ruby></span>だ。先生の女における<span><ruby><rb>知識</rb><rt>ちしき</rt></ruby></span>はおそらく<span><ruby><rb>零</rb><rt>れい</rt></ruby></span>だろう。<span>ラッブ</span>をしたことがないものに女がわかるものか」</p>
		<p>「先生はそれでいいとして、<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>は先生の<span><ruby><rb>説</rb><rt>せつ</rt></ruby></span>に<span><ruby><rb>賛成</rb><rt>さんせい</rt></ruby>した</span>じゃないか」</p>
		<p>「うん乱暴だと言った。なぜ」</p>
		<p>「どういうところを乱暴というのか」</p>
		<p>「どういうところも、こういうところもありゃしない。<span class="vocabstudy"><ruby><rb>現代</rb><rt>げんだい</rt></ruby>の</span><span class="vocabstudy"><ruby><rb>女性</rb><rt>にょしょう</rt></ruby></span>はみんな乱暴にきまっている。あの女ばかりじゃない」</p>
		<p>「君はあの人を<span class="vocabstudy">イブセン</span>の<span class="vocabstudy"><ruby><rb>人物</rb><rt>じんぶつ</rt></ruby></span>に<span class="vocabstudy"><ruby><rb>似</rb><rt>に</rt></ruby>て</span>いると言ったじゃないか」</p>
		<p>「言った」</p>
		<p>「イブセンのだれに似ているつもりなのか」</p>
		<p>「だれって……似ているよ」</p>
		<p>三四郎はむろん<span class="vocabstudy"><ruby><rb>納得</rb><rt>なっとく</rt></ruby>しない</span>。しかし<span class="vocabstudy"><ruby><rb>追窮</rb><rt>ついきゅう</rt></ruby>もしない</span>。黙って<span class="vocabstudy"><ruby><rb>一間</rb><rt>いっけん</rt></ruby></span>ばかり<span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いた</span>。すると<span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby></span>与次郎がこう言った。</p>
		<p>「イブセンの人物に似ているのは里見のお嬢さんばかりじゃない。<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>一般</rb><rt>いっぱん</rt></ruby>の</span>女性はみんな似ている。女性ばかりじゃない。<span class="vocabstudy">いやしくも</span><span class="vocabstudy"><ruby><rb>新</rb><rt>あたら</rt></ruby>しい</span><span class="vocabstudy"><ruby><rb>空気</rb><rt>くうき</rt></ruby></span>に<span class="vocabstudy"><ruby><rb>触</rb><rt>ふ</rt></ruby>れた</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>はみんなイブセンの人物に似たところがある。ただ男も女もイブセンのように<span class="vocabstudy"><ruby><rb>自由</rb><rt>じゆう</rt></ruby></span><span class="vocabstudy"><ruby><rb>行動</rb><rt>こうどう</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>らない</span>だけだ。<span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>のなかでは</span>たいてい<span class="vocabstudy">かぶれて</span>いる」</p>

		<h3 class="section">Rough translation</h3>
		<p>Sanshirō listened to their comments in silence. He didn't accept what they were saying. First of all, the use of the word 'unmanageable' with respect to Mineko left him puzzled.</p>
		<p>Yojirō finally went and changed into his hakata. "We're off," he called to the professor. The professor was quietly drinking tea. The two of them left through the front yard. It was already dark out. A few paces past the gate, Sanshirō engaged Yojirō.</p>
		<p>"The professor referred to Mineko as unmanageable."</p>  
		<p>"He always speaks his mind. Depending on the occasion or situation, he's likely to say anything. It's funny to hear him comment on women, though, a subject on which his knowledge is nil. If one's never been in love, how can one understand women?"</p>
		<p>"Be that as it may, weren't you in agreement with him?"</p>
		<p>"Yes, in regard to unmanageability. Why?"</p>
		<p>"In what way is Mineko unmanageable?"</p>
		<p>"It's nothing specific that you can put your finger on. Anyway, all modern women are unmanageable. It's not just her."</p>
		<p>"Didn't you liken her to a woman out of Ibsen?"</p> 
		<p>"I did."</p>
		<p>"Which woman from Ibsen did you mean?"</p>
		<p>"Which one ... take your pick."</p>
		<p>Sanshirō, of course, was unconvinced, but he pressed it no further. They continued for several paces in silence. Then Yojirō suddenly elaborated. "It's not just Mineko whom I associate with Ibsen. Most all the women of today fit the mold. The same for any man who breathes this modern air, even just a single breath. Very few, though, express it through freedom of action. Most of us are harboring frustrations."</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;in silence; without speaking</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>批評</rb><rt>ひひょう</rt></ruby>&nbsp;criticism; commentary</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;listen to</span><span class="vocabstudy">ふにおちない&nbsp;struggle to comprehend; find difficult to accept</span><span class="vocabstudy"><ruby><rb>乱暴</rb><rt>らんぼう</rt></ruby>&nbsp;wayward; unmanageable</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;word</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy">の<ruby><rb>上</rb><rt>うえ</rt></ruby>に&nbsp;in regard to; concerning</span><span class="vocabstudy"><ruby><rb>使</rb><rt>つか</rt></ruby>える&nbsp;can be used; can be applied (to)</span><span class="vocabstudy"><ruby><rb>第一</rb><rt>だいいち</rt></ruby>&nbsp;first of all</span><span class="vocabstudy"><ruby><rb>不思議</rb><rt>ふしぎ</rt></ruby>&nbsp;strange; curious</span>
		<span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy"><ruby><rb>袴</rb><rt>はかま</rt></ruby>&nbsp;man's formal pleated skirt</span><span class="vocabstudy"><ruby><rb>改</rb><rt>あらた</rt></ruby>まって<ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;reappeared</span>
		<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>ってまいります&nbsp;be off (to an outing)</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;called out</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;professor</span><span class="vocabstudy"><ruby><rb>茶</rb><rt>ちゃ</rt></ruby>&nbsp;tea</span><span class="vocabstudy"><ruby><rb>飲</rb><rt>の</rt></ruby>んで&nbsp;drink</span><span class="vocabstudy"><ruby><rb>表</rb><rt>おもて</rt></ruby>&nbsp;out front</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;came out (to)</span><span class="vocabstudy"><ruby><rb>暗</rb><rt>くら</rt></ruby>い&nbsp;dark</span><span class="vocabstudy"><ruby><rb>門</rb><rt>もん</rt></ruby>&nbsp;gate</span><span class="vocabstudy"><ruby><rb>離</rb><rt>はな</rt></ruby>れて&nbsp;move away from</span><span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三間</rb><rt>さんげん</rt></ruby>&nbsp;2 or 3 ken (about 5 meters; about 6 yards)</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come; advance</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>しかけた&nbsp;addressed (another party); began to talk</span>
		<span class="vocabstudy"><ruby><rb>里見</rb><rt>さとみ</rt></ruby>&nbsp;Satomi (Mineko's family name)</span><span class="vocabstudy">お<ruby><rb>嬢</rb><rt>じょう</rt></ruby>さん&nbsp;daughter; young lady</span>
		<span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;things</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;person</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time</span><span class="vocabstudy"><ruby><rb>場合</rb><rt>ばあい</rt></ruby>&nbsp;situation; circumstances</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;women</span><span class="vocabstudy"><ruby><rb>評</rb><rt>ひょう</rt></ruby>する&nbsp;comment on</span><span class="vocabstudy"><ruby><rb>滑稽</rb><rt>こっけい</rt></ruby>&nbsp;absurd; funny</span><span class="vocabstudy"><ruby><rb>知識</rb><rt>ちしき</rt></ruby>&nbsp;knowledge</span><span class="vocabstudy"><ruby><rb>零</rb><rt>れい</rt></ruby>&nbsp;zero</span><span class="vocabstudy">ラッブ&nbsp;love</span>
		<span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you</span><span class="vocabstudy"><ruby><rb>説</rb><rt>せつ</rt></ruby>&nbsp;opinion; view</span><span class="vocabstudy"><ruby><rb>賛成</rb><rt>さんせい</rt></ruby>した&nbsp;agreed; supported</span>
		<span class="vocabstudy"><ruby><rb>現代</rb><rt>げんだい</rt></ruby>の&nbsp;modern</span><span class="vocabstudy"><ruby><rb>女性</rb><rt>にょしょう</rt></ruby>&nbsp;women</span>
		<span class="vocabstudy">イブセン&nbsp;Henrik Johan Ibsen (Norwegian Playwright, 1828 – 1906, whose works include A Doll's House)</span><span class="vocabstudy"><ruby><rb>人物</rb><rt>じんぶつ</rt></ruby>&nbsp;character; figure</span><span class="vocabstudy"><ruby><rb>似</rb><rt>に</rt></ruby>て&nbsp;resemble</span>
		<span class="vocabstudy"><ruby><rb>納得</rb><rt>なっとく</rt></ruby>しない&nbsp;was not convinced; could not agree</span><span class="vocabstudy"><ruby><rb>追窮</rb><rt>ついきゅう</rt></ruby>もしない&nbsp;didn't press (the matter) further</span><span class="vocabstudy"><ruby><rb>一間</rb><rt>いっけん</rt></ruby>&nbsp;1 ken (about a meter; about a yard)</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いた&nbsp;walked</span><span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>&nbsp;suddenly</span>
		<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; at present</span><span class="vocabstudy"><ruby><rb>一般</rb><rt>いっぱん</rt></ruby>の&nbsp;ordinary; average</span><span class="vocabstudy">いやしくも&nbsp;even to a slight degree</span><span class="vocabstudy"><ruby><rb>新</rb><rt>あたら</rt></ruby>しい&nbsp;new; modern</span><span class="vocabstudy"><ruby><rb>空気</rb><rt>くうき</rt></ruby>&nbsp;air; atmosphere</span><span class="vocabstudy"><ruby><rb>触</rb><rt>ふ</rt></ruby>れた&nbsp;touched; came into contact with</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;men</span><span class="vocabstudy"><ruby><rb>自由</rb><rt>じゆう</rt></ruby>&nbsp;free; as one pleases</span><span class="vocabstudy"><ruby><rb>行動</rb><rt>こうどう</rt></ruby>&nbsp;conduct; behavior</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>らない&nbsp;don't take up; don't engage in</span><span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>のなかでは&nbsp;deep down; down inside</span><span class="vocabstudy">かぶれて&nbsp;react against (something)</span>

	</StudyGuide>
);
