// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={129}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>頭</rb><rt>あたま</rt></ruby></span>のなかに、こういう<span><ruby><rb>疑</rb><rt>うたが</rt></ruby>い</span>ある<span><ruby><rb>未来</rb><rt>みらい</rt></ruby></span>を、<span><ruby><rb>描</rb><rt>えが</rt></ruby>きながら</span>、<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>と<span><ruby><rb>応対</rb><rt>おうたい</rt></ruby>をして</span>いる。いっこうに<span><ruby><rb>気</rb><rt>き</rt></ruby>が<ruby><rb>乗</rb><rt>の</rt></ruby>らない</span>。それを<span><ruby><rb>外部</rb><rt>がいぶ</rt></ruby>の</span><span><ruby><rb>態度</rb><rt>たいど</rt></ruby></span>だけでも<span><ruby><rb>普通</rb><rt>ふつう</rt></ruby></span>のごとくつくろおうとすると<span><ruby><rb>苦痛</rb><rt>くつう</rt></ruby></span>になってくる。そこへうまいぐあいに<span>よし<ruby><rb>子</rb><rt>こ</rt></ruby></span>が<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>ってきて</span>くれた。<span><ruby><rb>女</rb><rt>おんな</rt></ruby><ruby><rb>同志</rb><rt>どうし</rt></ruby>のあいだ</span>には、<span>もう<ruby><rb>一</rb><rt>いっ</rt></ruby>ぺん</span><span><ruby><rb>競技</rb><rt>きょうぎ</rt></ruby></span>を<span><ruby><rb>見</rb><rt>み</rt></ruby>に<ruby><rb>行</rb><rt>い</rt></ruby>こう</span>かという<span><ruby><rb>相談</rb><rt>そうだん</rt></ruby></span>があったが、<span><ruby><rb>短</rb><rt>みじか</rt></ruby>くなりかけた</span><span><ruby><rb>秋</rb><rt>あき</rt></ruby></span>の<span><ruby><rb>日</rb><rt>ひ</rt></ruby></span>がだいぶ<span><ruby><rb>回</rb><rt>まわ</rt></ruby>った</span>のと、回るにつれて、<span><ruby><rb>広</rb><rt>ひろ</rt></ruby>い</span><span><ruby><rb>戸外</rb><rt>こがい</rt></ruby></span>の<span><ruby><rb>肌寒</rb><rt>はださむ</rt></ruby></span>がようやく<span><ruby><rb>増</rb><rt>ま</rt></ruby>してくる</span>ので、帰ることに<span><ruby><rb>話</rb><rt>はなし</rt></ruby>がきまる</span>。</p>
		<p>三四郎も<span><ruby><rb>女</rb><rt>おんな</rt></ruby><ruby><rb>連</rb><rt>れん</rt></ruby></span>に<span><ruby><rb>別</rb><rt>わか</rt></ruby>れて</span><span><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby></span>へもどろうと<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>が、<span><ruby><rb>三人</rb><rt>さんにん</rt></ruby></span>が話しながら、ずるずるべったりに<span><ruby><rb>歩</rb><rt>ある</rt></ruby>き<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>ものだから、<span>きわだった</span><span><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby></span>をする<span><ruby><rb>機会</rb><rt>きかい</rt></ruby></span>がない。<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>は<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>を<span><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>張</rb><rt>ぱ</rt></ruby>って</span>ゆくようにみえる。自分もまた引っ張られてゆきたいような気がする。それで二人にくっついて<span><ruby><rb>池</rb><rt>いけ</rt></ruby></span>の<span><ruby><rb>端</rb><rt>はた</rt></ruby></span>を<span><ruby><rb>図書館</rb><rt>としょかん</rt></ruby></span>の<span><ruby><rb>横</rb><rt>よこ</rt></ruby></span>から、<span><ruby><rb>方角</rb><rt>ほうがく</rt></ruby><ruby><rb>違</rb><rt>ちが</rt></ruby>い</span>の<span><ruby><rb>赤門</rb><rt>あかもん</rt></ruby></span>の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>へ<span><ruby><rb>向</rb><rt>む</rt></ruby>いて</span>きた。そのとき三四郎は、よし子に向かって、</p>
		<p>「<span>お<ruby><rb>兄</rb><rt>あに</rt></ruby>いさん</span>は下宿をなすったそうですね」と<span><ruby><rb>聞</rb><rt>き</rt></ruby>いたら</span>、よし子は、すぐ、</p>
		<p>「ええ。とうとう。ひとを美禰子さんの<span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>へ<span><ruby><rb>押</rb><rt>お</rt></ruby>しつけて</span>おいて。ひどいでしょう」と<span><ruby><rb>同意</rb><rt>どうい</rt></ruby></span>を<span><ruby><rb>求</rb><rt>もと</rt></ruby>める</span>ように<span><ruby><rb>言</rb><rt>い</rt></ruby>った</span>。三四郎は<span><ruby><rb>何</rb><rt>なに</rt></ruby>か</span><span><ruby><rb>返事</rb><rt>へんじ</rt></ruby></span>をしようとした。そのまえに美禰子が<span><ruby><rb>口</rb><rt>くち</rt></ruby>を<ruby><rb>開</rb><rt>ひら</rt></ruby>いた</span>。</p>
		<p>「<span><ruby><rb>宗八</rb><rt>そうはち</rt></ruby></span>さんのようなかたは、<span><ruby><rb>我々</rb><rt>われわれ</rt></ruby></span>の<span><ruby><rb>考</rb><rt>かんが</rt></ruby>え</span>じゃわかりませんよ。ずっと<span><ruby><rb>高</rb><rt>たか</rt></ruby>い</span>所にいて、<span><ruby><rb>大</rb><rt>おお</rt></ruby>きな</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>を考えていらっしゃるんだから」と大いに<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さんをほめだした。よし子は<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>聞いている。</p>

		<h3 class="section">Rough translation</h3>
		<p>Sanshirō kept company with Mineko as myriad futures flashed before his mind's eye. His thoughts were unsettled, and he struggled greatly to maintain his outward composure. Much to his relief, Yoshiko returned. The two young ladies talked of returning to the competition. They decided, however, that with the short autumn day getting late, and with a growing chill in the outdoor air, they should head home.</p>
		<p>Sanshirō thought to take his leave and return to his lodgings, but the three of them talked as they walked off, and no clear-cut point for disengagement arose. He felt that the two of them were sweeping him along. He also felt that he wanted to be swept along. Together, they skirted the pond, passed the library, and headed for the Red Gate, away from Sanshirō's lodgings.</p>
		<p>Sanshirō turned to Yoshiko. "I hear that your brother is back to boarding."</p>
		<p>"Yes, he's finally pawned me off on Mineko. Terrible, isn't it?" Yoshiko answered, looking for a little sympathy.</p>
		<p>Before Sanshirō could comment, Mineko spoke up. "It's hard for us to understand a man like Nonomiya. His mind works at a higher level, engaged in ground-breaking ideas."</p>
		<p>Mineko praised Nonomiya warmly. Yoshiko listened in silence.</p>      

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>頭</rb><rt>あたま</rt></ruby>&nbsp;head; mind</span><span class="vocabstudy"><ruby><rb>疑</rb><rt>うたが</rt></ruby>い&nbsp;doubt; uncertainty</span><span class="vocabstudy"><ruby><rb>未来</rb><rt>みらい</rt></ruby>&nbsp;future</span><span class="vocabstudy"><ruby><rb>描</rb><rt>えが</rt></ruby>きながら&nbsp;draw; depict</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>応対</rb><rt>おうたい</rt></ruby>をして&nbsp;deal with; keep company</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>が<ruby><rb>乗</rb><rt>の</rt></ruby>らない&nbsp;not be engaged; not find interest in</span><span class="vocabstudy"><ruby><rb>外部</rb><rt>がいぶ</rt></ruby>の&nbsp;external; superficial</span><span class="vocabstudy"><ruby><rb>態度</rb><rt>たいど</rt></ruby>&nbsp;manner; behavior</span><span class="vocabstudy"><ruby><rb>普通</rb><rt>ふつう</rt></ruby>&nbsp;usual; always</span><span class="vocabstudy"><ruby><rb>苦痛</rb><rt>くつう</rt></ruby>&nbsp;pain; discomfort</span><span class="vocabstudy">よし<ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;Yoshiko (Nonomiya's younger sister)</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>ってきて&nbsp;came back; returned</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby><ruby><rb>同志</rb><rt>どうし</rt></ruby>のあいだ&nbsp;among the young ladies</span><span class="vocabstudy">もう<ruby><rb>一</rb><rt>いっ</rt></ruby>ぺん&nbsp;one more time</span><span class="vocabstudy"><ruby><rb>競技</rb><rt>きょうぎ</rt></ruby>&nbsp;competition</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>に<ruby><rb>行</rb><rt>い</rt></ruby>こう&nbsp;go and watch</span><span class="vocabstudy"><ruby><rb>相談</rb><rt>そうだん</rt></ruby>&nbsp;discussion</span><span class="vocabstudy"><ruby><rb>短</rb><rt>みじか</rt></ruby>くなりかけた&nbsp;had grown shorter</span><span class="vocabstudy"><ruby><rb>秋</rb><rt>あき</rt></ruby>&nbsp;autumn</span><span class="vocabstudy"><ruby><rb>日</rb><rt>ひ</rt></ruby>&nbsp;day</span><span class="vocabstudy"><ruby><rb>回</rb><rt>まわ</rt></ruby>った&nbsp;run its course; be past</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い&nbsp;wide; open</span><span class="vocabstudy"><ruby><rb>戸外</rb><rt>こがい</rt></ruby>&nbsp;outdoors</span><span class="vocabstudy"><ruby><rb>肌寒</rb><rt>はださむ</rt></ruby>&nbsp;autumn chill</span><span class="vocabstudy"><ruby><rb>増</rb><rt>ま</rt></ruby>してくる&nbsp;increase; intensify</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>がきまる&nbsp;settled; decided (upon)</span>
		<span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby><ruby><rb>連</rb><rt>れん</rt></ruby>&nbsp;the ladies</span><span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れて&nbsp;separate (from); take leave of</span><span class="vocabstudy"><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby>&nbsp;lodgings</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought to</span><span class="vocabstudy"><ruby><rb>三人</rb><rt>さんにん</rt></ruby>&nbsp;three (people)</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>き<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;set off walking</span><span class="vocabstudy">きわだった&nbsp;clear-cut</span><span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>&nbsp;salutation</span><span class="vocabstudy"><ruby><rb>機会</rb><rt>きかい</rt></ruby>&nbsp;chance; opportunity</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>張</rb><rt>ぱ</rt></ruby>って&nbsp;pull; drag along</span><span class="vocabstudy"><ruby><rb>池</rb><rt>いけ</rt></ruby>&nbsp;pond</span><span class="vocabstudy"><ruby><rb>端</rb><rt>はた</rt></ruby>&nbsp;edge</span><span class="vocabstudy"><ruby><rb>図書館</rb><rt>としょかん</rt></ruby>&nbsp;library</span><span class="vocabstudy"><ruby><rb>横</rb><rt>よこ</rt></ruby>&nbsp;side (of)</span><span class="vocabstudy"><ruby><rb>方角</rb><rt>ほうがく</rt></ruby><ruby><rb>違</rb><rt>ちが</rt></ruby>い&nbsp;wrong direction</span><span class="vocabstudy"><ruby><rb>赤門</rb><rt>あかもん</rt></ruby>&nbsp;Red Gate</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>いて&nbsp;turn; head (toward)</span>
		<span class="vocabstudy">お<ruby><rb>兄</rb><rt>あに</rt></ruby>いさん&nbsp;(your) older brother</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いたら&nbsp;asked</span>
		<span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>押</rb><rt>お</rt></ruby>しつけて&nbsp;push; force (on)</span><span class="vocabstudy"><ruby><rb>同意</rb><rt>どうい</rt></ruby>&nbsp;sympathy</span><span class="vocabstudy"><ruby><rb>求</rb><rt>もと</rt></ruby>める&nbsp;seek; wish for</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;replied</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>か&nbsp;something</span><span class="vocabstudy"><ruby><rb>返事</rb><rt>へんじ</rt></ruby>&nbsp;answer</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>を<ruby><rb>開</rb><rt>ひら</rt></ruby>いた&nbsp;spoke</span>
		<span class="vocabstudy"><ruby><rb>宗八</rb><rt>そうはち</rt></ruby>&nbsp;Sōhachi (Nonomiya's first name)</span><span class="vocabstudy"><ruby><rb>我々</rb><rt>われわれ</rt></ruby>&nbsp;we; us</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>え&nbsp;reckoning; way of thinking</span><span class="vocabstudy"><ruby><rb>高</rb><rt>たか</rt></ruby>い&nbsp;elevated; lofty</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな&nbsp;great; important</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;affairs; matters</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;remain silent</span>

	</StudyGuide>
);
