// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={170}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>雲母</rb><rt>マイカ</rt></ruby></span>か<span><ruby><rb>何</rb><rt>なに</rt></ruby>か</span>で、<span><ruby><rb>十六</rb><rt>じゅうろく</rt></ruby><ruby><rb>武蔵</rb><rt>むさし</rt></ruby></span>ぐらいの<span><ruby><rb>大</rb><rt>おお</rt></ruby>きさ</span>の<span><ruby><rb>薄</rb><rt>うす</rt></ruby>い</span><span><ruby><rb>円盤</rb><rt>えんばん</rt></ruby></span>を<span><ruby><rb>作</rb><rt>つく</rt></ruby>って</span>、<span><ruby><rb>水晶</rb><rt>すいしょう</rt></ruby></span>の<span><ruby><rb>糸</rb><rt>いと</rt></ruby></span>で<span><ruby><rb>釣</rb><rt>つ</rt></ruby>るして</span>、<span><ruby><rb>真空</rb><rt>しんくう</rt></ruby></span>のうちに<span><ruby><rb>置</rb><rt>お</rt></ruby>いて</span>、この円盤の<span><ruby><rb>面</rb><rt>めん</rt></ruby></span>へ<span><ruby><rb>弧光燈</rb><rt>アークとう</rt></ruby></span>の<span><ruby><rb>光</rb><rt>ひかり</rt></ruby></span>を<span><ruby><rb>直角</rb><rt>ちょっかく</rt></ruby>に</span>あてると、この円盤が光に<span><ruby><rb>圧</rb><rt>お</rt></ruby>されて</span><span><ruby><rb>動</rb><rt>うご</rt></ruby>く</span>。と言うのである。</p>
		<p><span><ruby><rb>一座</rb><rt>いちざ</rt></ruby></span>は<span><ruby><rb>耳</rb><rt>みみ</rt></ruby>を<ruby><rb>傾</rb><rt>かたむ</rt></ruby>けて<ruby><rb>聞</rb><rt>き</rt></ruby>いて</span>いた。なかにも<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>腹</rb><rt>はら</rt></ruby>のなかで</span>、あの<span><ruby><rb>福神漬</rb><rt>ふくじんづけ</rt></ruby></span>の<span><ruby><rb>缶</rb><rt>かん</rt></ruby></span>のなかに、そんな<span><ruby><rb>装置</rb><rt>そうち</rt></ruby></span>がしてあるのだろうと、<span><ruby><rb>上京</rb><rt>じょうきょう</rt></ruby></span>のさい、<span><ruby><rb>望遠鏡</rb><rt>ぼうえんきょう</rt></ruby></span>で<span><ruby><rb>驚</rb><rt>おどろ</rt></ruby>かされた</span><span><ruby><rb>昔</rb><rt>むかし</rt></ruby></span>を<span><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>、水晶の糸があるのか」と<span><ruby><rb>小</rb><rt>ちい</rt></ruby>さい</span><span><ruby><rb>声</rb><rt>こえ</rt></ruby></span>で<span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>に聞いてみた。与次郎は<span><ruby><rb>頭</rb><rt>あたま</rt></ruby>を<ruby><rb>振</rb><rt>ふ</rt></ruby>って</span>いる。</p>
		<p>「<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さん、水晶の糸がありますか」</p>
		<p>「ええ、水晶の<span><ruby><rb>粉</rb><rt>こ</rt></ruby></span>をね。<span><ruby><rb>酸水素</rb><rt>さんすいそ</rt></ruby></span><span><ruby><rb>吹管</rb><rt>すいかん</rt></ruby></span>の<span><ruby><rb>炎</rb><rt>ほのう</rt></ruby></span>で<span><ruby><rb>溶</rb><rt>と</rt></ruby>かして</span>おいて、<span><ruby><rb>両方</rb><rt>りょうほう</rt></ruby>の<ruby><rb>手</rb><rt>て</rt></ruby></span>で、<span><ruby><rb>左右</rb><rt>さゆう</rt></ruby></span>へ<span><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>張</rb><rt>ぱ</rt></ruby>る</span>と<span><ruby><rb>細</rb><rt>ほそ</rt></ruby>い</span>糸ができるのです」</p>
		<p>三四郎は「そうですか」と<span><ruby><rb>言</rb><rt>い</rt></ruby>った</span>ぎり、<span><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>込</rb><rt>こ</rt></ruby>んだ</span>。<span><ruby><rb>今度</rb><rt>こんど</rt></ruby></span>は野々宮さんの<span><ruby><rb>隣</rb><rt>となり</rt></ruby></span>にいる<span><ruby><rb>縞</rb><rt>しま</rt></ruby></span>の<span><ruby><rb>羽織</rb><rt>はおり</rt></ruby></span>の<span><ruby><rb>批評家</rb><rt>ひひょうか</rt></ruby></span>が<span><ruby><rb>口</rb><rt>くち</rt></ruby>を<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「<span><ruby><rb>我々</rb><rt>われわれ</rt></ruby></span>はそういう<span><ruby><rb>方面</rb><rt>ほうめん</rt></ruby></span>へかけると、<span><ruby><rb>全然</rb><rt>ぜんぜん</rt></ruby><ruby><rb>無学</rb><rt>むがく</rt></ruby></span>なんですが、はじめはどうして<span><ruby><rb>気</rb><rt>き</rt></ruby>がついた</span>ものでしょうな」</p>
		<p>「<span><ruby><rb>理論</rb><rt>りろん</rt></ruby><ruby><rb>上</rb><rt>じょう</rt></ruby></span>は<span>マクスウェル</span><span><ruby><rb>以来</rb><rt>いらい</rt></ruby></span><span><ruby><rb>予想</rb><rt>よそう</rt></ruby>されて</span>いたのですが、それを<span>レベデフ</span>という<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>がはじめて<span><ruby><rb>実験</rb><rt>じっけん</rt></ruby></span>で<span><ruby><rb>証明</rb><rt>しょうめい</rt></ruby>した</span>のです。<span><ruby><rb>近</rb><rt>ちか</rt></ruby>ごろ</span>あの<span><ruby><rb>彗星</rb><rt>すいせい</rt></ruby></span>の<span><ruby><rb>尾</rb><rt>お</rt></ruby></span>が、<span><ruby><rb>太陽</rb><rt>たいよう</rt></ruby></span>の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>へ引きつけられべきはずであるのに、<span><ruby><rb>出</rb><rt>で</rt></ruby>る</span>たびにいつでも<span><ruby><rb>反対</rb><rt>はんたい</rt></ruby></span>の<span><ruby><rb>方角</rb><rt>ほうがく</rt></ruby></span>に<span>なびく</span>のは光の<span><ruby><rb>圧力</rb><rt>あつりょく</rt></ruby></span>で<span><ruby><rb>吹</rb><rt>ふ</rt></ruby>き<ruby><rb>飛</rb><rt>と</rt></ruby>ばされる</span>んじゃなかろうかと<span><ruby><rb>思</rb><rt>おも</rt></ruby>いついた</span>人もあるくらいです」</p>
		<p>批評家はだいぶ<span><ruby><rb>感心</rb><rt>かんしん</rt></ruby>した</span>らしい。</p>
		<p>「<span><ruby><rb>思</rb><rt>おも</rt></ruby>いつき</span>もおもしろいが、<span><ruby><rb>第一</rb><rt>だいいち</rt></ruby></span><span><ruby><rb>大</rb><rt>おお</rt></ruby>きくて</span>いいですね」と言った。</p>
		<p>「大きいばかりじゃない、<span><ruby><rb>罪</rb><rt>つみ</rt></ruby>がなくって</span><span><ruby><rb>愉快</rb><rt>ゆかい</rt></ruby></span>だ」と<span><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>が言った。</p>
		<p>「それでその思いつきがはずれたら、なお罪がなくっていい」と<span><ruby><rb>原口</rb><rt>はらぐち</rt></ruby></span>さんが<span><ruby><rb>笑</rb><rt>わら</rt></ruby>って</span>いる。</p>

		<h3 class="section">Rough translation</h3>
		<p>According to Nonomiya, a substance like mica is first shaped into a disk, about the size of a 'sixteen soldiers' playing piece. Then it's suspended from a crystal thread in a vacuum. The surface of the disk is hit square on with light from an arc lamp, and the disk is deflected by light pressure.</p> 
		<p>The party was listening with interest. Among them, Sanshirō was recalling the day, shortly after his arrival in Tōkyō, when he'd peered through Nonomiya's scope. The described apparatus must be housed in that pickled vegetable can.</p>
		<p>"Is there such thing as a crystal thread?" He whispered to Yojirō. Yojirō shook his head.</p>
		<p>"Nonomiya-san, is there really such thing as a crystal thread?"</p>
		<p>"There is. You melt crystal grains over an oxyhydrogen burner. Then, pulling with both hands, you draw out a fine thread."</p>
		<p>Sanshirō acknowledged the response and queried no further. Next to speak was the critic in the striped haori who was seated next to Nonomiya.</p>
		<p>"We're completely uninitiated in this field. How does one know what to look for in the first place?"</p>
		<p>"Maxwell's theory predicts their existence, and a man named Lebedev first confirmed it through experiment. It's been conjectured recently that light pressure affects comet tails. These tails, which were expected to bend toward the sun, are always observed to extend, in fact, in the opposite direction."</p>
		<p>The critic seemed duly impressed. "It's an interesting idea. Best of all, it plays on a grand scale."</p>
		<p>"It's not just grand," added Professor Hirota, "it's also comfortably innocuous."</p>
		<p>"And all the more innocuous if it proves wrong," laughed Haraguchi.</p>       

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>雲母</rb><rt>マイカ</rt></ruby>&nbsp;mica</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>か&nbsp;something</span><span class="vocabstudy"><ruby><rb>十六</rb><rt>じゅうろく</rt></ruby><ruby><rb>武蔵</rb><rt>むさし</rt></ruby>&nbsp;sixteen soldiers (game played with disk-shaped markers)</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きさ&nbsp;size</span><span class="vocabstudy"><ruby><rb>薄</rb><rt>うす</rt></ruby>い&nbsp;thin</span><span class="vocabstudy"><ruby><rb>円盤</rb><rt>えんばん</rt></ruby>&nbsp;disk</span><span class="vocabstudy"><ruby><rb>作</rb><rt>つく</rt></ruby>って&nbsp;make; fabricate</span><span class="vocabstudy"><ruby><rb>水晶</rb><rt>すいしょう</rt></ruby>&nbsp;crystal</span><span class="vocabstudy"><ruby><rb>糸</rb><rt>いと</rt></ruby>&nbsp;thread</span><span class="vocabstudy"><ruby><rb>釣</rb><rt>つ</rt></ruby>るして&nbsp;hang; suspend</span><span class="vocabstudy"><ruby><rb>真空</rb><rt>しんくう</rt></ruby>&nbsp;vacuum</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いて&nbsp;set; place</span><span class="vocabstudy"><ruby><rb>面</rb><rt>めん</rt></ruby>&nbsp;surface</span><span class="vocabstudy"><ruby><rb>弧光燈</rb><rt>アークとう</rt></ruby>&nbsp;arc lamp</span><span class="vocabstudy"><ruby><rb>光</rb><rt>ひかり</rt></ruby>&nbsp;light</span><span class="vocabstudy"><ruby><rb>直角</rb><rt>ちょっかく</rt></ruby>に&nbsp;perpendicularly</span><span class="vocabstudy"><ruby><rb>圧</rb><rt>お</rt></ruby>されて&nbsp;be pushed</span><span class="vocabstudy"><ruby><rb>動</rb><rt>うご</rt></ruby>く&nbsp;move</span>
		<span class="vocabstudy"><ruby><rb>一座</rb><rt>いちざ</rt></ruby>&nbsp;the party; those present</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>を<ruby><rb>傾</rb><rt>かたむ</rt></ruby>けて<ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;listen with interest</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>のなかで&nbsp;to oneself</span><span class="vocabstudy"><ruby><rb>福神漬</rb><rt>ふくじんづけ</rt></ruby>&nbsp;sliced vegetables preserved in soy sauce</span><span class="vocabstudy"><ruby><rb>缶</rb><rt>かん</rt></ruby>&nbsp;can</span><span class="vocabstudy"><ruby><rb>装置</rb><rt>そうち</rt></ruby>&nbsp;device; apparatus</span><span class="vocabstudy"><ruby><rb>上京</rb><rt>じょうきょう</rt></ruby>&nbsp;arrival in Tōkyō</span><span class="vocabstudy"><ruby><rb>望遠鏡</rb><rt>ぼうえんきょう</rt></ruby>&nbsp;telescope</span><span class="vocabstudy"><ruby><rb>驚</rb><rt>おどろ</rt></ruby>かされた&nbsp;was impressed</span><span class="vocabstudy"><ruby><rb>昔</rb><rt>むかし</rt></ruby>&nbsp;former time</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;remembered; recalled</span>
		<span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you (used here as form of address)</span><span class="vocabstudy"><ruby><rb>小</rb><rt>ちい</rt></ruby>さい&nbsp;small; quiet (voice)</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice</span><span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy"><ruby><rb>頭</rb><rt>あたま</rt></ruby>を<ruby><rb>振</rb><rt>ふ</rt></ruby>って&nbsp;shake one's head</span>
		<span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span>
		<span class="vocabstudy"><ruby><rb>粉</rb><rt>こ</rt></ruby>&nbsp;powder</span><span class="vocabstudy"><ruby><rb>酸水素</rb><rt>さんすいそ</rt></ruby>&nbsp;oxyhydrogen (mixture of oxygen and hydrogen gases)</span><span class="vocabstudy"><ruby><rb>吹管</rb><rt>すいかん</rt></ruby>&nbsp;blowpipe</span><span class="vocabstudy"><ruby><rb>炎</rb><rt>ほのう</rt></ruby>&nbsp;flame</span><span class="vocabstudy"><ruby><rb>溶</rb><rt>と</rt></ruby>かして&nbsp;melt</span><span class="vocabstudy"><ruby><rb>両方</rb><rt>りょうほう</rt></ruby>の<ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;both hands</span><span class="vocabstudy"><ruby><rb>左右</rb><rt>さゆう</rt></ruby>&nbsp;left and right</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>張</rb><rt>ぱ</rt></ruby>る&nbsp;pull; stretch</span><span class="vocabstudy"><ruby><rb>細</rb><rt>ほそ</rt></ruby>い&nbsp;slender; fine</span>
		<span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;remarked; replied</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>込</rb><rt>こ</rt></ruby>んだ&nbsp;withdrew; pursued no further</span><span class="vocabstudy"><ruby><rb>今度</rb><rt>こんど</rt></ruby>&nbsp;next</span><span class="vocabstudy"><ruby><rb>隣</rb><rt>となり</rt></ruby>&nbsp;adjacent; neighboring (position)</span><span class="vocabstudy"><ruby><rb>縞</rb><rt>しま</rt></ruby>&nbsp;stripe</span><span class="vocabstudy"><ruby><rb>羽織</rb><rt>はおり</rt></ruby>&nbsp;haori (Japanese half-coat)</span><span class="vocabstudy"><ruby><rb>批評家</rb><rt>ひひょうか</rt></ruby>&nbsp;critic</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>を<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;spoke up</span>
		<span class="vocabstudy"><ruby><rb>我々</rb><rt>われわれ</rt></ruby>&nbsp;we; us</span><span class="vocabstudy"><ruby><rb>方面</rb><rt>ほうめん</rt></ruby>&nbsp;area; field (of study)</span><span class="vocabstudy"><ruby><rb>全然</rb><rt>ぜんぜん</rt></ruby><ruby><rb>無学</rb><rt>むがく</rt></ruby>&nbsp;fully ignorant; completely uninitiated</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>がついた&nbsp;noticed; became aware (of)</span>
		<span class="vocabstudy"><ruby><rb>理論</rb><rt>りろん</rt></ruby><ruby><rb>上</rb><rt>じょう</rt></ruby>&nbsp;in theory; based on theory</span><span class="vocabstudy">マクスウェル&nbsp;James Clerk Maxwell (Scottish scientist; 1831-1879)</span><span class="vocabstudy"><ruby><rb>以来</rb><rt>いらい</rt></ruby>&nbsp;since ...</span><span class="vocabstudy"><ruby><rb>予想</rb><rt>よそう</rt></ruby>されて&nbsp;be expected; be predicted</span><span class="vocabstudy">レベデフ&nbsp;Pyotr Nikolaevich Lebedev (Russian physicist; 1866-1912)</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;person; man</span><span class="vocabstudy"><ruby><rb>実験</rb><rt>じっけん</rt></ruby>&nbsp;experiment</span><span class="vocabstudy"><ruby><rb>証明</rb><rt>しょうめい</rt></ruby>した&nbsp;confirmed</span><span class="vocabstudy"><ruby><rb>近</rb><rt>ちか</rt></ruby>ごろ&nbsp;recently</span><span class="vocabstudy"><ruby><rb>彗星</rb><rt>すいせい</rt></ruby>&nbsp;comet</span><span class="vocabstudy"><ruby><rb>尾</rb><rt>お</rt></ruby>&nbsp;tail</span><span class="vocabstudy"><ruby><rb>太陽</rb><rt>たいよう</rt></ruby>&nbsp;the sun</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>る&nbsp;come out; appear</span><span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby>&nbsp;opposite</span><span class="vocabstudy"><ruby><rb>方角</rb><rt>ほうがく</rt></ruby>&nbsp;direction</span><span class="vocabstudy">なびく&nbsp;flutter; wave; bend</span><span class="vocabstudy"><ruby><rb>圧力</rb><rt>あつりょく</rt></ruby>&nbsp;pressure</span><span class="vocabstudy"><ruby><rb>吹</rb><rt>ふ</rt></ruby>き<ruby><rb>飛</rb><rt>と</rt></ruby>ばされる&nbsp;be blown out; be blown away</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>いついた&nbsp;think of; be struck with (an idea)</span>
		<span class="vocabstudy"><ruby><rb>感心</rb><rt>かんしん</rt></ruby>した&nbsp;was impressed</span>
		<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>いつき&nbsp;idea</span><span class="vocabstudy"><ruby><rb>第一</rb><rt>だいいち</rt></ruby>&nbsp;first of all</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きくて&nbsp;big; grand</span>
		<span class="vocabstudy"><ruby><rb>罪</rb><rt>つみ</rt></ruby>がなくって&nbsp;harmless; innocuous</span><span class="vocabstudy"><ruby><rb>愉快</rb><rt>ゆかい</rt></ruby>&nbsp;pleasant; exhilarating</span><span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Professor Hirota</span>
		<span class="vocabstudy"><ruby><rb>原口</rb><rt>はらぐち</rt></ruby>&nbsp;Haraguchi (name)</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>って&nbsp;grin; laugh</span>

	</StudyGuide>
);
