// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={179}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>の<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は<span><ruby><rb>笑</rb><rt>わら</rt></ruby>いながら</span>そばへ<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span>、いっしょに<span>シャツ</span>を<span><ruby><rb>見</rb><rt>み</rt></ruby>て</span>くれた。しまいに、<span>よし<ruby><rb>子</rb><rt>こ</rt></ruby></span>が「これになさい」と<span><ruby><rb>言</rb><rt>い</rt></ruby>った</span>。<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>はそれにした。<span><ruby><rb>今度</rb><rt>こんど</rt></ruby></span>は三四郎のほうが<span><ruby><rb>香水</rb><rt>こうすい</rt></ruby></span>の<span><ruby><rb>相談</rb><rt>そうだん</rt></ruby>を<ruby><rb>受</rb><rt>う</rt></ruby>けた</span>。いっこうわからない。<span>ヘリオトロープ</span>と<span><ruby><rb>書</rb><rt>か</rt></ruby>いてある</span><span><ruby><rb>罎</rb><rt>びん</rt></ruby></span>を<span><ruby><rb>持</rb><rt>も</rt></ruby>って</span>、いいかげんに、これはどうですと言うと、<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>が、「それにしましょう」とすぐ<span><ruby><rb>決</rb><rt>き</rt></ruby>めた</span>。三四郎は<span><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby></span>なくらいであった。</p>
		<p><span><ruby><rb>表</rb><rt>おもて</rt></ruby></span>へ<span><ruby><rb>出</rb><rt>で</rt></ruby>て</span><span><ruby><rb>別</rb><rt>わか</rt></ruby>れよう</span>とすると、女のほうが<span><ruby><rb>互</rb><rt>たが</rt></ruby>いに</span><span>お<ruby><rb>辞儀</rb><rt>じぎ</rt></ruby></span>を<span><ruby><rb>始</rb><rt>はじ</rt></ruby>めた</span>。よし子が「じゃ<span><ruby><rb>行</rb><rt>い</rt></ruby>ってきて</span>よ」と言うと、美禰子が、「<span>お<ruby><rb>早</rb><rt>はや</rt></ruby>く</span>……」と言っている。<span><ruby><rb>聞</rb><rt>き</rt></ruby>いて</span>みて、<span><ruby><rb>妹</rb><rt>いもと</rt></ruby></span>が<span><ruby><rb>兄</rb><rt>あに</rt></ruby></span>の<span><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby></span>へ行くところだということがわかった。三四郎はまたきれいな女と<span><ruby><rb>二人連</rb><rt>ふたりづれ</rt></ruby>で</span><span><ruby><rb>追分</rb><rt>おいわけ</rt></ruby></span>の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>へ<span><ruby><rb>歩</rb><rt>ある</rt></ruby>く</span><span>べき</span><span><ruby><rb>宵</rb><rt>よい</rt></ruby></span>となった。<span><ruby><rb>日</rb><rt>ひ</rt></ruby></span>はまだまったく<span><ruby><rb>落</rb><rt>お</rt></ruby>ちて</span>いない。</p>
		<p>三四郎はよし子といっしょに歩くよりは、よし子といっしょに野々宮の下宿で<span><ruby><rb>落</rb><rt>お</rt></ruby>ち<ruby><rb>合</rb><rt>あ</rt></ruby>わねばならぬ</span><span><ruby><rb>機会</rb><rt>きかい</rt></ruby></span>をいささか<span><ruby><rb>迷惑</rb><rt>めいわく</rt></ruby></span>に<span><ruby><rb>感</rb><rt>かん</rt></ruby>じた</span>。<span>いっそのこと</span><span><ruby><rb>今夜</rb><rt>こんや</rt></ruby></span>は<span><ruby><rb>家</rb><rt>いえ</rt></ruby></span>へ<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>って</span>、また<span><ruby><rb>出直</rb><rt>でなお</rt></ruby>そう</span>かと<span><ruby><rb>考</rb><rt>かんが</rt></ruby>えた</span>。しかし、<span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>のいわゆる<span>お<ruby><rb>談義</rb><rt>だんぎ</rt></ruby></span>を聞くには、よし子がそばにいてくれるほうが<span><ruby><rb>便利</rb><rt>べんり</rt></ruby></span>かもしれない。まさか<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>の<span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>で、<span><ruby><rb>母</rb><rt>はは</rt></ruby></span>から、こういう<span><ruby><rb>依頼</rb><rt>いらい</rt></ruby></span>があったと、<span><ruby><rb>遠慮</rb><rt>えんりょ</rt></ruby>なし</span>の<span><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby></span>を<span><ruby><rb>与</rb><rt>あた</rt></ruby>える</span>わけはなかろう。ことによると、ただ<span><ruby><rb>金</rb><rt>かね</rt></ruby></span>を<span><ruby><rb>受</rb><rt>う</rt></ruby>け<ruby><rb>取</rb><rt>と</rt></ruby>る</span>だけで<span><ruby><rb>済</rb><rt>す</rt></ruby>む</span>かもわからない。――三四郎は<span><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>中</rb><rt>なか</rt></ruby>で</span>、ちょっとずるい<span><ruby><rb>決心</rb><rt>けっしん</rt></ruby></span>をした。</p>
		<p>「ぼくも野々宮さんの<span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>へ行くところです」</p>
		<p>「そう、<span>お<ruby><rb>遊</rb><rt>あそ</rt></ruby>び</span>に？」</p>
		<p>「いえ、すこし<span><ruby><rb>用</rb><rt>よう</rt></ruby></span>があるんです。あなたは遊びですか」</p>
		<p>「いいえ、<span><ruby><rb>私</rb><rt>わたし</rt></ruby></span>も<span><ruby><rb>御用</rb><rt>ごよう</rt></ruby></span>なの」</p>

		<h3 class="section">Rough translation</h3>
		<p>The two young ladies, smiling, came over to help him look at shirts. "Take this one," Yoshiko finally said. Sanshirō took her advice. Next they enlisted Sanshirō in choosing perfume. Having no idea, he picked up a bottle labeled 'Heliotrope' and, only half earnestly, asked what they thought. Much to his consternation, Mineko agreed on the spot to buy it.</p>
		<p>Back out front, the young ladies began taking leave of each other. Yoshiko said, "See you later," and Mineko replied with, "Don't be too late." As it turned out, Yoshiko was off to visit her brother. Sanshirō, once again on this evening, was obliged to accompany an attractive young lady to Oiwake. The sun had not yet fully set.</p>
		<p>Sanshirō didn't mind walking with Yoshiko, but he was mildly perturbed that she'd be there at Nonomiya's. He considered going home and trying again another night. However, if he were to be lectured as Yojirō surmised, then Yoshiko's presence might prove advantageous. Surely Nonomiya, with a third party present, would refrain from admonishment on behalf of Sanshirō's mother. He might, if it went well, just receive his money and leave. -- Scheming to himself, Sanshirō made up his mind.</p>
		<p>"I was going myself to see Nonomiya."</p>
		<p>"Really? Just to visit?"</p>
		<p>"No, for a bit of business. Are you just visiting?"</p>
		<p>"No, I have some business there too."</p>        

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;women; young ladies</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>いながら&nbsp;smiling</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;came (to); approached</span><span class="vocabstudy">シャツ&nbsp;shirts</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;look at</span><span class="vocabstudy">よし<ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;Yoshiko (name of Nonomiya's younger sister)</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;said; suggested</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>今度</rb><rt>こんど</rt></ruby>&nbsp;this time; next</span><span class="vocabstudy"><ruby><rb>香水</rb><rt>こうすい</rt></ruby>&nbsp;perfume; fragrance</span><span class="vocabstudy"><ruby><rb>相談</rb><rt>そうだん</rt></ruby>を<ruby><rb>受</rb><rt>う</rt></ruby>けた&nbsp;was consulted; was asked to advise on</span><span class="vocabstudy">ヘリオトロープ&nbsp;heliotrope (pink-purple flowering plant)</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>いてある&nbsp;be written; be labeled</span><span class="vocabstudy"><ruby><rb>罎</rb><rt>びん</rt></ruby>&nbsp;bottle</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って&nbsp;pick up</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>決</rb><rt>き</rt></ruby>めた&nbsp;decided; settled (on something)</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby>&nbsp;pitiful; unfortunate</span>
		<span class="vocabstudy"><ruby><rb>表</rb><rt>おもて</rt></ruby>&nbsp;out front</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て&nbsp;come out (to)</span><span class="vocabstudy"><ruby><rb>別</rb><rt>わか</rt></ruby>れよう&nbsp;take leave of</span><span class="vocabstudy"><ruby><rb>互</rb><rt>たが</rt></ruby>いに&nbsp;mutually; to each other</span><span class="vocabstudy">お<ruby><rb>辞儀</rb><rt>じぎ</rt></ruby>&nbsp;bow; curtsy</span><span class="vocabstudy"><ruby><rb>始</rb><rt>はじ</rt></ruby>めた&nbsp;engaged in</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>ってきて&nbsp;take care; see you later</span><span class="vocabstudy">お<ruby><rb>早</rb><rt>はや</rt></ruby>く&nbsp;hurry back; not too late</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;ask; inquire</span><span class="vocabstudy"><ruby><rb>妹</rb><rt>いもと</rt></ruby>&nbsp;younger sister (usually <ruby><rb>妹</rb><rt>いもうと</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;older brother</span><span class="vocabstudy"><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby>&nbsp;lodgings</span><span class="vocabstudy"><ruby><rb>二人連</rb><rt>ふたりづれ</rt></ruby>で&nbsp;one-on-one; as a pair</span><span class="vocabstudy"><ruby><rb>追分</rb><rt>おいわけ</rt></ruby>&nbsp;Oiwake (place name)</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>く&nbsp;walk; stroll</span><span class="vocabstudy">べき&nbsp;be obliged to ...</span><span class="vocabstudy"><ruby><rb>宵</rb><rt>よい</rt></ruby>&nbsp;evening</span><span class="vocabstudy"><ruby><rb>日</rb><rt>ひ</rt></ruby>&nbsp;the sun</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちて&nbsp;set (sun)</span>
		<span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ち<ruby><rb>合</rb><rt>あ</rt></ruby>わねばならぬ&nbsp;have to meet; have to come together</span><span class="vocabstudy"><ruby><rb>機会</rb><rt>きかい</rt></ruby>&nbsp;occasion</span><span class="vocabstudy"><ruby><rb>迷惑</rb><rt>めいわく</rt></ruby>&nbsp;bother; annoyance</span><span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>じた&nbsp;felt</span><span class="vocabstudy">いっそのこと&nbsp;rather; preferably</span><span class="vocabstudy"><ruby><rb>今夜</rb><rt>こんや</rt></ruby>&nbsp;this evening</span><span class="vocabstudy"><ruby><rb>家</rb><rt>いえ</rt></ruby>&nbsp;home</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って&nbsp;return (to)</span><span class="vocabstudy"><ruby><rb>出直</rb><rt>でなお</rt></ruby>そう&nbsp;set out anew</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えた&nbsp;considered</span><span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy">お<ruby><rb>談義</rb><rt>だんぎ</rt></ruby>&nbsp;lecture</span><span class="vocabstudy"><ruby><rb>便利</rb><rt>べんり</rt></ruby>&nbsp;convenient; advantageous</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;another (person)</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;front of</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span><span class="vocabstudy"><ruby><rb>依頼</rb><rt>いらい</rt></ruby>&nbsp;request</span><span class="vocabstudy"><ruby><rb>遠慮</rb><rt>えんりょ</rt></ruby>なし&nbsp;unrestrained</span><span class="vocabstudy"><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby>&nbsp;caution; admonition</span><span class="vocabstudy"><ruby><rb>与</rb><rt>あた</rt></ruby>える&nbsp;give; impart (to)</span><span class="vocabstudy"><ruby><rb>金</rb><rt>かね</rt></ruby>&nbsp;money</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>け<ruby><rb>取</rb><rt>と</rt></ruby>る&nbsp;receive; take charge of</span><span class="vocabstudy"><ruby><rb>済</rb><rt>す</rt></ruby>む&nbsp;finish; be settled</span><span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>中</rb><rt>なか</rt></ruby>で&nbsp;to oneself</span><span class="vocabstudy"><ruby><rb>決心</rb><rt>けっしん</rt></ruby>&nbsp;determination; resolution</span>
		<span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place; residence</span>
		<span class="vocabstudy">お<ruby><rb>遊</rb><rt>あそ</rt></ruby>び&nbsp;social call; visit</span>
		<span class="vocabstudy"><ruby><rb>用</rb><rt>よう</rt></ruby>&nbsp;matter of business</span>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>御用</rb><rt>ごよう</rt></ruby>&nbsp;matter of business</span>

	</StudyGuide>
);
