// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={172}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「すると、<span><ruby><rb>物理</rb><rt>ぶつり</rt></ruby><ruby><rb>学者</rb><rt>がくしゃ</rt></ruby></span>は<span><ruby><rb>浪漫</rb><rt>ローマン</rt></ruby><ruby><rb>的</rb><rt>てき</rt></ruby></span><span><ruby><rb>自然</rb><rt>しぜん</rt></ruby><ruby><rb>派</rb><rt>は</rt></ruby></span>ですね。<span><ruby><rb>文学</rb><rt>ぶんがく</rt></ruby></span>のほうでいうと、<span>イブセン</span>のようなものじゃないか」と<span><ruby><rb>筋</rb><rt>すじ</rt></ruby><ruby><rb>向</rb><rt>む</rt></ruby>こう</span>の<span><ruby><rb>博士</rb><rt>はかせ</rt></ruby></span>が<span><ruby><rb>比較</rb><rt>ひかく</rt></ruby></span>を<span><ruby><rb>持</rb><rt>も</rt></ruby>ち<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「さよう、イブセンの<span><ruby><rb>劇</rb><rt>げき</rt></ruby></span>は<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span><span><ruby><rb>君</rb><rt>くん</rt></ruby></span>と<span><ruby><rb>同</rb><rt>おな</rt></ruby>じ</span>くらいな<span><ruby><rb>装置</rb><rt>そうち</rt></ruby></span>があるが、その装置の<span><ruby><rb>下</rb><rt>もと</rt></ruby></span>に<span><ruby><rb>働</rb><rt>はたら</rt></ruby>く</span><span><ruby><rb>人物</rb><rt>じんぶつ</rt></ruby></span>は、<span><ruby><rb>光線</rb><rt>こうせん</rt></ruby></span>のように自然の<span><ruby><rb>法則</rb><rt>ほうそく</rt></ruby></span>に<span><ruby><rb>従</rb><rt>したが</rt></ruby>って</span>いるか<span><ruby><rb>疑</rb><rt>うたが</rt></ruby>わしい</span>」これは<span><ruby><rb>縞</rb><rt>しま</rt></ruby></span>の<span><ruby><rb>羽織</rb><rt>はおり</rt></ruby></span>の<span><ruby><rb>批評家</rb><rt>ひひょうか</rt></ruby></span>の<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>であった。</p>
		<p>「そうかもしれないが、こういうことは<span><ruby><rb>人間</rb><rt>にんげん</rt></ruby></span>の<span><ruby><rb>研究</rb><rt>けんきゅう</rt></ruby></span><span><ruby><rb>上</rb><rt>じょう</rt></ruby></span><span><ruby><rb>記憶</rb><rt>きおく</rt></ruby>して</span>おくべき事だと<span><ruby><rb>思</rb><rt>おも</rt></ruby>う</span>。――すなわち、ある<span><ruby><rb>状況</rb><rt>じょうきょう</rt></ruby></span>のもとに<span><ruby><rb>置</rb><rt>お</rt></ruby>かれた</span>人間は、<span><ruby><rb>反対</rb><rt>はんたい</rt></ruby></span>の<span><ruby><rb>方向</rb><rt>ほうこう</rt></ruby></span>に働きうる<span><ruby><rb>能力</rb><rt>のうりょく</rt></ruby></span>と<span><ruby><rb>権力</rb><rt>けんりょく</rt></ruby></span>とを<span><ruby><rb>有</rb><rt>ゆう</rt></ruby>して</span>いる。ということなんだが、――ところが<span><ruby><rb>妙</rb><rt>みょう</rt></ruby>な</span><span><ruby><rb>習慣</rb><rt>しゅうかん</rt></ruby></span>で、人間も光線も同じように<span><ruby><rb>器械的</rb><rt>きかいてき</rt></ruby></span>の法則に従って<span><ruby><rb>活動</rb><rt>かつどう</rt></ruby>する</span>と思うものだから、<span><ruby><rb>時々</rb><rt>ときどき</rt></ruby></span>とんだ<span><ruby><rb>間違</rb><rt>まちが</rt></ruby>い</span>ができる。おこらせようと思って装置をすると、<span><ruby><rb>笑</rb><rt>わら</rt></ruby>ったり</span>、笑わせようと<span>もくろんで</span>かかると、おこったり、まるで反対だ。しかしどちらにしても人間<span>に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない</span>」と<span><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>がまた<span><ruby><rb>問題</rb><rt>もんだい</rt></ruby></span>を<span><ruby><rb>大</rb><rt>おお</rt></ruby>きくして</span>しまった。</p>
		<p>「じゃ、ある状況のもとに、ある人間が、どんな<span><ruby><rb>所作</rb><rt>しょさ</rt></ruby></span>をしてもしぜんだということになりますね」と向こうの<span><ruby><rb>小説家</rb><rt>しょうせつか</rt></ruby></span>が<span><ruby><rb>質問</rb><rt>しつもん</rt></ruby>した</span>。広田先生は、すぐ、</p>
		<p>「ええ、ええ。どんな人間を、どう<span><ruby><rb>描</rb><rt>か</rt></ruby>いて</span>も<span><ruby><rb>世界</rb><rt>せかい</rt></ruby></span>に<span><ruby><rb>一人</rb><rt>ひとり</rt></ruby></span>くらいはいるようじゃないですか」と<span><ruby><rb>答</rb><rt>こた</rt></ruby>えた</span>。「じっさい人間たる<span><ruby><rb>我々</rb><rt>われわれ</rt></ruby></span>は、人間<span>らしからざる</span><span><ruby><rb>行為</rb><rt>こうい</rt></ruby></span><span><ruby><rb>動作</rb><rt>どうさ</rt></ruby></span>を、どうしたって<span><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>できる</span>ものじゃない。ただへたに<span><ruby><rb>書</rb><rt>か</rt></ruby>く</span>から人間<span>と<ruby><rb>思</rb><rt>おも</rt></ruby>われない</span>のじゃないですか」</p>
		<p>小説家はそれで<span><ruby><rb>黙</rb><rt>だま</rt></ruby>った</span>。<span><ruby><rb>今度</rb><rt>こんど</rt></ruby></span>は博士がまた<span><ruby><rb>口</rb><rt>くち</rt></ruby>をきいた</span>。</p>
		<p>「物理学者でも、<span>ガリレオ</span>が<span><ruby><rb>寺院</rb><rt>じいん</rt></ruby></span>の<span><ruby><rb>釣</rb><rt>つ</rt></ruby>りランプ</span>の<span><ruby><rb>一</rb><rt>いち</rt></ruby></span><span><ruby><rb>振動</rb><rt>しんどう</rt></ruby></span>の<span><ruby><rb>時間</rb><rt>じかん</rt></ruby></span>が、振動の<span><ruby><rb>大小</rb><rt>だいしょう</rt></ruby></span>にかかわらず<span><ruby><rb>同</rb><rt>おな</rt></ruby>じ</span>であることに<span><ruby><rb>気</rb><rt>き</rt></ruby>がついたり</span>、<span>ニュートン</span>が<span><ruby><rb>林檎</rb><rt>りんご</rt></ruby></span>が<span><ruby><rb>引力</rb><rt>いんりょく</rt></ruby></span>で<span><ruby><rb>落</rb><rt>お</rt></ruby>ちる</span>のを<span><ruby><rb>発見</rb><rt>はっけん</rt></ruby>したり</span>するのは、はじめから自然派ですね」</p>
		<p>「そういう自然派なら、文学のほうでも<span><ruby><rb>結構</rb><rt>けっこう</rt></ruby></span>でしょう。<span><ruby><rb>原口</rb><rt>はらぐち</rt></ruby></span>さん、<span><ruby><rb>絵</rb><rt>え</rt></ruby></span>のほうでも自然派がありますか」と<span><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さんが<span><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。</p>
		<p>「あるとも。<span><ruby><rb>恐</rb><rt>おそ</rt></ruby>るべき</span><span>クールベエ</span>というやつがいる。[<span>vérité vraie</span>.]なんでも<span><ruby><rb>事実</rb><rt>じじつ</rt></ruby></span>でなければ<span><ruby><rb>承知</rb><rt>しょうち</rt></ruby>しない</span>。しかしそう<span><ruby><rb>猖獗</rb><rt>しょうけつ</rt></ruby>を<ruby><rb>極</rb><rt>きわ</rt></ruby>めて</span>いるものじゃない。ただ<span><ruby><rb>一派</rb><rt>いっぱ</rt></ruby></span>として<span><ruby><rb>存在</rb><rt>そんざい</rt></ruby></span>を<span><ruby><rb>認</rb><rt>みと</rt></ruby>められる</span>だけさ。またそうでなくっちゃ<span><ruby><rb>困</rb><rt>こま</rt></ruby>る</span>からね。小説だって同じことだろう、ねえ<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>。やっぱり<span>モロー</span>や、<span>シャバンヌ</span>のようなのもいるはずだろうじゃないか」</p>
		<p>「いるはずだ」と隣の小説家が答えた。</p>

		<h3 class="section">Rough translation</h3>
		<p>"Then physicists are romantic naturalists. Their equivalent in literature might be Ibsen." Dr. Shōji, seated diagonally opposite, proposed this analogy.</p>
		<p>"True. The devices of Ibsen's dramas are much like Nonomiya's. But the characters who function within, unlike light beams, seem not to adhere to natural laws." This from the critic in the striped haori.</p>
		<p>"I expect you're right. There's one thing to remember with regard to humans. -- Namely, that a human being, placed in certain circumstances, has the ability, and reserves the right, to defy expectation. This is a key point. -- Curiously, however, we forget this and assume that human beings, like light beams, are governed by mechanics. Doing so results, oftentimes, in bad ends. You contrive to antagonize another and he laughs. Or you scheme amusement and stir up anger, the exact opposite outcome." Professor Hirota expanded the scope of the discourse.</p>
		<p>"Does that imply, then, that for a given individual, in a given situation, any behavior can pass as natural?" The novelist seated opposite inquired.</p>
		<p>Professor Hirota responded immediately. "Yes, precisely. Depict any type of human in any way you like. Wouldn't you suppose then, that somewhere in the world, one such individual exists? We humans, in fact, cannot imagine deed or manner that fall outside the bounds of humanity. It's only poor prose, isn't it, that renders a character inhuman?"</p>
		<p>The novelist had no response. Dr. Shōji spoke again next. "Even among physicists, when Galileo noticed that one swing of a cathedral pendant lamp, large or small, took a fixed amount of time, or when Newton attributed falling apples to gravitational force, didn't it begin as naturalism."</p>
		<p>"If that's naturalism," Nonomiya replied, "then I can see how it figures in literature. Haraguchi-san, is it present in painting as well?"</p>
		<p>"It is. Courbet is a dreadful example. Espousing 'vérité vraie,' he acknowledged only stark realism. His following was limited, but they're rightfully recognized as one distinct school. Isn't it the same with writers? There must, after all, be the same sort of types as Moreau and Chavannes."</p>
		<p>"There are indeed," answered the novelist.</p> 

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>物理</rb><rt>ぶつり</rt></ruby><ruby><rb>学者</rb><rt>がくしゃ</rt></ruby>&nbsp;physicist</span><span class="vocabstudy"><ruby><rb>浪漫</rb><rt>ローマン</rt></ruby><ruby><rb>的</rb><rt>てき</rt></ruby>&nbsp;romantic</span><span class="vocabstudy"><ruby><rb>自然</rb><rt>しぜん</rt></ruby><ruby><rb>派</rb><rt>は</rt></ruby>&nbsp;naturalist</span><span class="vocabstudy"><ruby><rb>文学</rb><rt>ぶんがく</rt></ruby>&nbsp;literature</span><span class="vocabstudy">イブセン&nbsp;Henrik Johan Ibsen (Norwegian Playwright, 1828 – 1906, whose works include A Doll's House)</span><span class="vocabstudy"><ruby><rb>筋</rb><rt>すじ</rt></ruby><ruby><rb>向</rb><rt>む</rt></ruby>こう&nbsp;diagonally opposite</span><span class="vocabstudy"><ruby><rb>博士</rb><rt>はかせ</rt></ruby>&nbsp;scholar</span><span class="vocabstudy"><ruby><rb>比較</rb><rt>ひかく</rt></ruby>&nbsp;comparison</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>ち<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;put forth; proposed</span>
		<span class="vocabstudy"><ruby><rb>劇</rb><rt>げき</rt></ruby>&nbsp;drama</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>君</rb><rt>くん</rt></ruby>&nbsp;(suffix of familiarity for males)</span><span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じ&nbsp;the same; equivalent</span><span class="vocabstudy"><ruby><rb>装置</rb><rt>そうち</rt></ruby>&nbsp;device</span><span class="vocabstudy"><ruby><rb>下</rb><rt>もと</rt></ruby>&nbsp;below; beneath</span><span class="vocabstudy"><ruby><rb>働</rb><rt>はたら</rt></ruby>く&nbsp;function; operate</span><span class="vocabstudy"><ruby><rb>人物</rb><rt>じんぶつ</rt></ruby>&nbsp;characters</span><span class="vocabstudy"><ruby><rb>光線</rb><rt>こうせん</rt></ruby>&nbsp;light beam</span><span class="vocabstudy"><ruby><rb>法則</rb><rt>ほうそく</rt></ruby>&nbsp;rules; laws</span><span class="vocabstudy"><ruby><rb>従</rb><rt>したが</rt></ruby>って&nbsp;follow; adhere to</span><span class="vocabstudy"><ruby><rb>疑</rb><rt>うたが</rt></ruby>わしい&nbsp;doubtful; questionable</span><span class="vocabstudy"><ruby><rb>縞</rb><rt>しま</rt></ruby>&nbsp;stripe</span><span class="vocabstudy"><ruby><rb>羽織</rb><rt>はおり</rt></ruby>&nbsp;haori (Japanese half-coat)</span><span class="vocabstudy"><ruby><rb>批評家</rb><rt>ひひょうか</rt></ruby>&nbsp;critic</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span>
		<span class="vocabstudy"><ruby><rb>人間</rb><rt>にんげん</rt></ruby>&nbsp;human beings</span><span class="vocabstudy"><ruby><rb>研究</rb><rt>けんきゅう</rt></ruby>&nbsp;study; research</span><span class="vocabstudy"><ruby><rb>上</rb><rt>じょう</rt></ruby>&nbsp;with respect to; concerning ...</span><span class="vocabstudy"><ruby><rb>記憶</rb><rt>きおく</rt></ruby>して&nbsp;remember</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>う&nbsp;think; believe</span><span class="vocabstudy"><ruby><rb>状況</rb><rt>じょうきょう</rt></ruby>&nbsp;situation; circumstances</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>かれた&nbsp;be put; be placed</span><span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby>&nbsp;opposite</span><span class="vocabstudy"><ruby><rb>方向</rb><rt>ほうこう</rt></ruby>&nbsp;direction; course (of action)</span><span class="vocabstudy"><ruby><rb>能力</rb><rt>のうりょく</rt></ruby>&nbsp;ability; faculty</span><span class="vocabstudy"><ruby><rb>権力</rb><rt>けんりょく</rt></ruby>&nbsp;power; authority</span><span class="vocabstudy"><ruby><rb>有</rb><rt>ゆう</rt></ruby>して&nbsp;have; possess</span><span class="vocabstudy"><ruby><rb>妙</rb><rt>みょう</rt></ruby>な&nbsp;odd; curious</span><span class="vocabstudy"><ruby><rb>習慣</rb><rt>しゅうかん</rt></ruby>&nbsp;custom; practice</span><span class="vocabstudy"><ruby><rb>器械的</rb><rt>きかいてき</rt></ruby>&nbsp;mechanistic</span><span class="vocabstudy"><ruby><rb>活動</rb><rt>かつどう</rt></ruby>する&nbsp;act; behave</span><span class="vocabstudy"><ruby><rb>時々</rb><rt>ときどき</rt></ruby>&nbsp;sometimes</span><span class="vocabstudy"><ruby><rb>間違</rb><rt>まちが</rt></ruby>い&nbsp;mishap; trouble</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>ったり&nbsp;smile; laugh</span><span class="vocabstudy">もくろんで&nbsp;plan; scheme</span><span class="vocabstudy">に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない&nbsp;without a doubt; assuredly</span><span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Professor Hirota</span><span class="vocabstudy"><ruby><rb>問題</rb><rt>もんだい</rt></ruby>&nbsp;subject; topic (of conversation)</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きくして&nbsp;expanded; broadened</span>
		<span class="vocabstudy"><ruby><rb>所作</rb><rt>しょさ</rt></ruby>&nbsp;conduct; behavior</span><span class="vocabstudy"><ruby><rb>小説家</rb><rt>しょうせつか</rt></ruby>&nbsp;novelist</span><span class="vocabstudy"><ruby><rb>質問</rb><rt>しつもん</rt></ruby>した&nbsp;asked; questioned</span>
		<span class="vocabstudy"><ruby><rb>描</rb><rt>か</rt></ruby>いて&nbsp;depict; describe</span><span class="vocabstudy"><ruby><rb>世界</rb><rt>せかい</rt></ruby>&nbsp;the world</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>&nbsp;one (person)</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた&nbsp;replied; answered</span><span class="vocabstudy"><ruby><rb>我々</rb><rt>われわれ</rt></ruby>&nbsp;we; us</span><span class="vocabstudy">らしからざる&nbsp;unbecoming of (= らしくない)</span><span class="vocabstudy"><ruby><rb>行為</rb><rt>こうい</rt></ruby>&nbsp;actions; deeds</span><span class="vocabstudy"><ruby><rb>動作</rb><rt>どうさ</rt></ruby>&nbsp;behavior; manner</span><span class="vocabstudy"><ruby><rb>想像</rb><rt>そうぞう</rt></ruby>できる&nbsp;imagine; conceive of</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>く&nbsp;write; compose; pen</span><span class="vocabstudy">と<ruby><rb>思</rb><rt>おも</rt></ruby>われない&nbsp;doesn't seem to be ...</span>
		<span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>った&nbsp;was silent; offered no response</span><span class="vocabstudy"><ruby><rb>今度</rb><rt>こんど</rt></ruby>&nbsp;now; next</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>をきいた&nbsp;spoke</span>
		<span class="vocabstudy">ガリレオ&nbsp;Galileo</span><span class="vocabstudy"><ruby><rb>寺院</rb><rt>じいん</rt></ruby>&nbsp;temple; church; cathedral</span><span class="vocabstudy"><ruby><rb>釣</rb><rt>つ</rt></ruby>りランプ&nbsp;pendant lamp</span><span class="vocabstudy"><ruby><rb>一</rb><rt>いち</rt></ruby>&nbsp;one</span><span class="vocabstudy"><ruby><rb>振動</rb><rt>しんどう</rt></ruby>&nbsp;period; oscillation</span><span class="vocabstudy"><ruby><rb>時間</rb><rt>じかん</rt></ruby>&nbsp;time</span><span class="vocabstudy"><ruby><rb>大小</rb><rt>だいしょう</rt></ruby>&nbsp;large or small; magnitude</span><span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じ&nbsp;the same</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>がついたり&nbsp;noticed; realized</span><span class="vocabstudy">ニュートン&nbsp;Newton</span><span class="vocabstudy"><ruby><rb>林檎</rb><rt>りんご</rt></ruby>&nbsp;apple</span><span class="vocabstudy"><ruby><rb>引力</rb><rt>いんりょく</rt></ruby>&nbsp;gravitational pull</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちる&nbsp;fall</span><span class="vocabstudy"><ruby><rb>発見</rb><rt>はっけん</rt></ruby>したり&nbsp;discover</span>
		<span class="vocabstudy"><ruby><rb>結構</rb><rt>けっこう</rt></ruby>&nbsp;acceptable; well enough</span><span class="vocabstudy"><ruby><rb>原口</rb><rt>はらぐち</rt></ruby>&nbsp;Haraguchi (name)</span><span class="vocabstudy"><ruby><rb>絵</rb><rt>え</rt></ruby>&nbsp;painting</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span>
		<span class="vocabstudy"><ruby><rb>恐</rb><rt>おそ</rt></ruby>るべき&nbsp;dreadful; fearsome</span><span class="vocabstudy">クールベエ&nbsp;Jean Désiré Gustave Courbet (French realist painter; 1819-1877)</span><span class="vocabstudy">vérité vraie&nbsp;(genuine truth; honest truth)</span><span class="vocabstudy"><ruby><rb>事実</rb><rt>じじつ</rt></ruby>&nbsp;reality</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>しない&nbsp;not accept; not acknowledge</span><span class="vocabstudy"><ruby><rb>猖獗</rb><rt>しょうけつ</rt></ruby>を<ruby><rb>極</rb><rt>きわ</rt></ruby>めて&nbsp;run rampant; be rife</span><span class="vocabstudy"><ruby><rb>一派</rb><rt>いっぱ</rt></ruby>&nbsp;one faction; one school</span><span class="vocabstudy"><ruby><rb>存在</rb><rt>そんざい</rt></ruby>&nbsp;existence; presence</span><span class="vocabstudy"><ruby><rb>認</rb><rt>みと</rt></ruby>められる&nbsp;be recognized; be acknowledged</span><span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>る&nbsp;be troubled; be bothered</span><span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you (used here as form of address)</span><span class="vocabstudy">モロー&nbsp;Gustave Moreau (French Symbolist painter; 1826–1898)</span><span class="vocabstudy">シャバンヌ&nbsp;Pierre Puvis de Chavannes (French Symbolist painter; 1824-1898)</span>

	</StudyGuide>
);
