// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={184}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「さっきの<span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>をしなくっちゃ」と<span><ruby><rb>兄</rb><rt>あに</rt></ruby></span>が<span><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby>した</span>。</p>
		<p>「よくってよ」と<span><ruby><rb>妹</rb><rt>いもうと</rt></ruby></span>が<span><ruby><rb>拒絶</rb><rt>きょぜつ</rt></ruby>した</span>。</p>
		<p>「よくはないよ」</p>
		<p>「よくってよ。<span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らない</span>わ」</p>
		<p>兄は妹の<span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>いる。妹は、またこう<span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った</span>。</p>
		<p>「だってしかたがないじゃ、ありませんか。知りもしない<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby></span>へ、<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>く</span>か行かないかって、<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>って。<span class="vocabstudy"><ruby><rb>好</rb><rt>す</rt></ruby>き</span>でもきらいでもないんだから、なんにも言いようはありゃしないわ。だから知らないわ」</p>
		<p><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は知らないわの<span class="vocabstudy"><ruby><rb>本意</rb><rt>ほんい</rt></ruby></span>をようやく<span class="vocabstudy"><ruby><rb>会得</rb><rt>えとく</rt></ruby>した</span>。<span class="vocabstudy"><ruby><rb>兄妹</rb><rt>きょうだい</rt></ruby></span>をそのままにして<span class="vocabstudy"><ruby><rb>急</rb><rt>いそ</rt></ruby>いで</span><span class="vocabstudy"><ruby><rb>表</rb><rt>おもて</rt></ruby>へ<ruby><rb>出</rb><rt>で</rt></ruby>た</span>。</p>
		<p><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>の<ruby><rb>通</rb><rt>とお</rt></ruby>らない</span><span class="vocabstudy"><ruby><rb>軒燈</rb><rt>けんとう</rt></ruby></span>ばかり<span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかな</span><span class="vocabstudy"><ruby><rb>路地</rb><rt>ろじ</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>抜</rb><rt>ぬ</rt></ruby>けて</span>表へ出ると、<span class="vocabstudy"><ruby><rb>風</rb><rt>かぜ</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>吹</rb><rt>ふ</rt></ruby>く</span>。<span class="vocabstudy"><ruby><rb>北</rb><rt>きた</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>き<ruby><rb>直</rb><rt>なお</rt></ruby>る</span>と、まともに顔へ<span class="vocabstudy"><ruby><rb>当</rb><rt>あた</rt></ruby>る</span>。<span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>を<ruby><rb>切</rb><rt>き</rt></ruby>って</span>、<span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>の</span><span class="vocabstudy"><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby></span>から吹いてくる。その時三四郎は<span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えた</span>。この風の<span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby></span>を、<span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さんは、妹を<span class="vocabstudy"><ruby><rb>送</rb><rt>おく</rt></ruby>って</span><span class="vocabstudy"><ruby><rb>里見</rb><rt>さとみ</rt></ruby></span>まで<span class="vocabstudy"><ruby><rb>連</rb><rt>つ</rt></ruby>れて</span>いってやるだろう。</p>
		<p>下宿の<span class="vocabstudy"><ruby><rb>二階</rb><rt>にかい</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>上</rb><rt>あが</rt></ruby>って</span>、自分の<span class="vocabstudy"><ruby><rb>部屋</rb><rt>へや</rt></ruby></span>へはいって、すわってみると、やっぱり風の<span class="vocabstudy"><ruby><rb>音</rb><rt>おと</rt></ruby></span>がする。三四郎はこういう風の音を聞くたびに、<span class="vocabstudy"><ruby><rb>運命</rb><rt>うんめい</rt></ruby></span>という<span class="vocabstudy"><ruby><rb>字</rb><rt>じ</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>す</span>。ごうと<span class="vocabstudy"><ruby><rb>鳴</rb><rt>な</rt></ruby>って</span>くるたびに<span class="vocabstudy">すくみたくなる</span>。自分ながらけっして<span class="vocabstudy"><ruby><rb>強</rb><rt>つよ</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>とは<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>って</span>いない。考えると、<span class="vocabstudy"><ruby><rb>上京</rb><rt>じょうきょう</rt></ruby></span><span class="vocabstudy"><ruby><rb>以来</rb><rt>いらい</rt></ruby></span>自分の運命はたいがい<span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span>のためにこしらえられている。しかも<span class="vocabstudy"><ruby><rb>多少</rb><rt>たしょう</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>程度</rb><rt>ていど</rt></ruby></span>において、<span class="vocabstudy"><ruby><rb>和気</rb><rt>わき</rt></ruby><ruby><rb>靄然</rb><rt>あいぜん</rt></ruby>たる</span><span class="vocabstudy"><ruby><rb>翻弄</rb><rt>ほんろう</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>ける</span>ようにこしらえられている。与次郎は<span class="vocabstudy"><ruby><rb>愛</rb><rt>あい</rt></ruby>すべき</span><span class="vocabstudy"><ruby><rb>悪戯者</rb><rt>いたずらもの</rt></ruby></span>である。<span class="vocabstudy"><ruby><rb>向後</rb><rt>こうご</rt></ruby></span>もこの愛すべき悪戯者のために、自分の運命を<span class="vocabstudy"><ruby><rb>握</rb><rt>にぎ</rt></ruby>られていそう</span>に思う。風がしきりに吹く。たしかに与次郎<span class="vocabstudy"><ruby><rb>以上</rb><rt>いじょう</rt></ruby></span>の風である。</p>

		<h3 class="section">Rough translation</h3>
		<p>"We have to have our talk," her brother cautioned her.</p>
		<p>"No we don't," she pushed back.</p>
		<p>"Yes we do."</p>
		<p>"No we don't. There's nothing to say."</p>
		<p>Nonomiya looked at his sister in silence. She continued. "What's there to talk about? You want my opinion on someone I don't even know, someone I neither like nor dislike. There's nothing to say."</p>
		<p>Sanshirō could see her point. He left them to their talk and hastily stepped outside.</p>
		<p>He walked back up the deserted lane, dark save the glow of door lamps. Stepping out of the lane, he was met by a stiff wind. After turning north, he fought against gusts to return to his lodgings. He imagined Nonomiya, in this same wind, walking his sister back to Mineko's place.</p>
		<p>Sanshirō climbed the stairs and entered his second-floor room. Inside, he could still hear the roar of the wind. Each time it roared, the word "fate" came to mind. When it roared loudly, he wanted to shrink and hide. He knew he was neither bold nor courageous. When he thought about it, his fate in Tōkyō had largely been shaped by Yojirō. And to some extent he'd been trifled with, albeit in a good-natured way. Yojirō was a lovable mischief-maker. Hereafter, too, this lovable mischief-maker would shape his fate. The wind outside continued to roar, with a force that bested even Yojirō.</p>        

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;talk; discussion</span><span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;older brother</span><span class="vocabstudy"><ruby><rb>注意</rb><rt>ちゅうい</rt></ruby>した&nbsp;cautioned</span>
		<span class="vocabstudy"><ruby><rb>妹</rb><rt>いもうと</rt></ruby>&nbsp;younger sister</span><span class="vocabstudy"><ruby><rb>拒絶</rb><rt>きょぜつ</rt></ruby>した&nbsp;refused</span>
		<span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らない&nbsp;don't know; have no opinion</span>
		<span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;look at</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;remain silent</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;said; continued</span>
		<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;person</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>く&nbsp;go (to)</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;ask</span><span class="vocabstudy"><ruby><rb>好</rb><rt>す</rt></ruby>き&nbsp;like (for something)</span>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>本意</rb><rt>ほんい</rt></ruby>&nbsp;true feelings; meaning behind ...</span><span class="vocabstudy"><ruby><rb>会得</rb><rt>えとく</rt></ruby>した&nbsp;understood; grasped</span><span class="vocabstudy"><ruby><rb>兄妹</rb><rt>きょうだい</rt></ruby>&nbsp;(older) brother and (younger) sister</span><span class="vocabstudy"><ruby><rb>急</rb><rt>いそ</rt></ruby>いで&nbsp;hastily</span><span class="vocabstudy"><ruby><rb>表</rb><rt>おもて</rt></ruby>へ<ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;went out (front); made one's exit</span>
		<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>の<ruby><rb>通</rb><rt>とお</rt></ruby>らない&nbsp;quiet; deserted</span><span class="vocabstudy"><ruby><rb>軒燈</rb><rt>けんとう</rt></ruby>&nbsp;door lamp</span><span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかな&nbsp;clear; visible</span><span class="vocabstudy"><ruby><rb>路地</rb><rt>ろじ</rt></ruby>&nbsp;alleyway; lane</span><span class="vocabstudy"><ruby><rb>抜</rb><rt>ぬ</rt></ruby>けて&nbsp;cut through</span><span class="vocabstudy"><ruby><rb>風</rb><rt>かぜ</rt></ruby>&nbsp;wind</span><span class="vocabstudy"><ruby><rb>吹</rb><rt>ふ</rt></ruby>く&nbsp;blow</span><span class="vocabstudy"><ruby><rb>北</rb><rt>きた</rt></ruby>&nbsp;north</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>き<ruby><rb>直</rb><rt>なお</rt></ruby>る&nbsp;turn toward</span><span class="vocabstudy"><ruby><rb>当</rb><rt>あた</rt></ruby>る&nbsp;hit; strike</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>を<ruby><rb>切</rb><rt>き</rt></ruby>って&nbsp;periodically; at intervals</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>の&nbsp;one's own</span><span class="vocabstudy"><ruby><rb>下宿</rb><rt>げしゅく</rt></ruby>&nbsp;lodgings</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えた&nbsp;considered</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;middle; midst</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>送</rb><rt>おく</rt></ruby>って&nbsp;see off; escort</span><span class="vocabstudy"><ruby><rb>里見</rb><rt>さとみ</rt></ruby>&nbsp;Satomi (Mineko's family name)</span><span class="vocabstudy"><ruby><rb>連</rb><rt>つ</rt></ruby>れて&nbsp;take; lead (a person)</span>
		<span class="vocabstudy"><ruby><rb>二階</rb><rt>にかい</rt></ruby>&nbsp;second floor</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あが</rt></ruby>って&nbsp;ascend; climb up (to)</span><span class="vocabstudy"><ruby><rb>部屋</rb><rt>へや</rt></ruby>&nbsp;room</span><span class="vocabstudy"><ruby><rb>音</rb><rt>おと</rt></ruby>&nbsp;sound</span><span class="vocabstudy"><ruby><rb>運命</rb><rt>うんめい</rt></ruby>&nbsp;fate; destiny</span><span class="vocabstudy"><ruby><rb>字</rb><rt>じ</rt></ruby>&nbsp;word</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>す&nbsp;call to mind</span><span class="vocabstudy"><ruby><rb>鳴</rb><rt>な</rt></ruby>って&nbsp;sound; resonate</span><span class="vocabstudy">すくみたくなる&nbsp;want to shrink; want to cower</span><span class="vocabstudy"><ruby><rb>強</rb><rt>つよ</rt></ruby>い&nbsp;strong; tough</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man; fellow</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>って&nbsp;think; consider</span><span class="vocabstudy"><ruby><rb>上京</rb><rt>じょうきょう</rt></ruby>&nbsp;arrival in Tōkyō</span><span class="vocabstudy"><ruby><rb>以来</rb><rt>いらい</rt></ruby>&nbsp;since ...</span><span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy"><ruby><rb>多少</rb><rt>たしょう</rt></ruby>&nbsp;more or less; somewhat</span><span class="vocabstudy"><ruby><rb>程度</rb><rt>ていど</rt></ruby>&nbsp;extent</span><span class="vocabstudy"><ruby><rb>和気</rb><rt>わき</rt></ruby><ruby><rb>靄然</rb><rt>あいぜん</rt></ruby>たる&nbsp;congenial; amiable</span><span class="vocabstudy"><ruby><rb>翻弄</rb><rt>ほんろう</rt></ruby>&nbsp;trifling with; leading by the nose</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>ける&nbsp;receive</span><span class="vocabstudy"><ruby><rb>愛</rb><rt>あい</rt></ruby>すべき&nbsp;lovable</span><span class="vocabstudy"><ruby><rb>悪戯者</rb><rt>いたずらもの</rt></ruby>&nbsp;mischief-maker</span><span class="vocabstudy"><ruby><rb>向後</rb><rt>こうご</rt></ruby>&nbsp;hereafter</span><span class="vocabstudy"><ruby><rb>握</rb><rt>にぎ</rt></ruby>られていそう&nbsp;look to be grasped (by); look to be subject (to)</span><span class="vocabstudy"><ruby><rb>以上</rb><rt>いじょう</rt></ruby>&nbsp;above and beyond</span>

	</StudyGuide>
);
