// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={103}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「<span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span><ruby><rb>寒</rb><rt>さむ</rt></ruby>くなった</span>ようですから、とにかく<span><ruby><rb>立</rb><rt>た</rt></ruby>ちましょう</span>。<span><ruby><rb>冷</rb><rt>ひ</rt></ruby>える</span>と<span><ruby><rb>毒</rb><rt>どく</rt></ruby></span>だ。しかし<span><ruby><rb>気分</rb><rt>きぶん</rt></ruby></span>はもうすっかり<span><ruby><rb>直</rb><rt>なお</rt></ruby>りました</span>か」</p>
		<p>「ええ、すっかり直りました」と<span><ruby><rb>明</rb><rt>あき</rt></ruby>らかに</span><span><ruby><rb>答</rb><rt>こた</rt></ruby>えた</span>が、<span>にわかに</span><span><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>上</rb><rt>あ</rt></ruby>がった</span>。立ち上がる<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>、<span><ruby><rb>小</rb><rt>ちい</rt></ruby>さな</span><span><ruby><rb>声</rb><rt>こえ</rt></ruby></span>で、ひとりごとのように、</p>
		<p>「<span><ruby><rb>迷える子</rb><rt>ストレイ・シープ</rt></ruby></span>」と<span><ruby><rb>長</rb><rt>なが</rt></ruby>く</span><span><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>張</rb><rt>ぱ</rt></ruby>って</span><span><ruby><rb>言</rb><rt>い</rt></ruby>った</span>。<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>はむろん答えなかった。</p>
		<p><span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>は、さっき<span><ruby><rb>洋服</rb><rt>ようふく</rt></ruby></span>を<span><ruby><rb>着</rb><rt>き</rt></ruby>た</span><span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>の<span><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た</span><span><ruby><rb>方角</rb><rt>ほうがく</rt></ruby></span>をさして、<span><ruby><rb>道</rb><rt>みち</rt></ruby></span>があるなら、あの<span><ruby><rb>唐辛子</rb><rt>とうがらし</rt></ruby></span>のそばを<span><ruby><rb>通</rb><rt>とお</rt></ruby>って</span><span><ruby><rb>行</rb><rt>い</rt></ruby>きたい</span>という。<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>は、その<span><ruby><rb>見当</rb><rt>けんとう</rt></ruby></span>へ<span><ruby><rb>歩</rb><rt>ある</rt></ruby>いて<ruby><rb>行</rb><rt>い</rt></ruby>った</span>。<span><ruby><rb>藁葺</rb><rt>わらぶき</rt></ruby></span>のうしろにはたして<span><ruby><rb>細</rb><rt>ほそ</rt></ruby>い</span><span><ruby><rb>三尺</rb><rt>さんじゃく</rt></ruby></span>ほどの道があった。その道を<span><ruby><rb>半分</rb><rt>はんぶん</rt></ruby></span>ほど<span><ruby><rb>来</rb><rt>き</rt></ruby>た</span><span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>で三四郎は<span><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。</p>
		<p>「<span>よし<ruby><rb>子</rb><rt>こ</rt></ruby></span>さんは、あなたの所へ<span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>ことにきまったんですか」</p>
		<p><span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は<span><ruby><rb>片頬</rb><rt>かたほお</rt></ruby></span>で<span><ruby><rb>笑</rb><rt>わら</rt></ruby>った</span>。そうして<span><ruby><rb>問</rb><rt>と</rt></ruby>い<ruby><rb>返</rb><rt>かえ</rt></ruby>した</span>。</p>
		<p>「なぜお聞きになるの」</p><p>三四郎が<span><ruby><rb>何</rb><rt>なに</rt></ruby>か</span>言おうとすると、<span><ruby><rb>足</rb><rt>あし</rt></ruby></span>の<span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>に<span><ruby><rb>泥濘</rb><rt>ぬかるみ</rt></ruby></span>があった。<span><ruby><rb>四尺</rb><rt>よんしゃく</rt></ruby></span>ばかりの所、<span><ruby><rb>土</rb><rt>つち</rt></ruby></span>がへこんで<span><ruby><rb>水</rb><rt>みず</rt></ruby></span>がぴたぴたにたまっている。その<span>まん<ruby><rb>中</rb><rt>なか</rt></ruby></span>に<span><ruby><rb>足掛</rb><rt>あしが</rt></ruby>かり</span>のためにてごろな<span><ruby><rb>石</rb><rt>いし</rt></ruby></span>を<span><ruby><rb>置</rb><rt>お</rt></ruby>いた</span><span><ruby><rb>者</rb><rt>もの</rt></ruby></span>がある。三四郎は石の<span><ruby><rb>助</rb><rt>たす</rt></ruby>け</span>をからずに、すぐに<span><ruby><rb>向</rb><rt>む</rt></ruby>こう</span>へ<span><ruby><rb>飛</rb><rt>と</rt></ruby>んだ</span>。そうして美禰子を<span><ruby><rb>振</rb><rt>ふ</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>って</span><span><ruby><rb>見</rb><rt>み</rt></ruby>た</span>。美禰子は<span><ruby><rb>右</rb><rt>みぎ</rt></ruby></span>の足を泥濘のまん中にある石の<span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>へ<span><ruby><rb>乗</rb><rt>の</rt></ruby>せた</span>。石のすわりがあまりよくない。足へ<span><ruby><rb>力</rb><rt>ちから</rt></ruby>を<ruby><rb>入</rb><rt>い</rt></ruby>れて</span>、<span><ruby><rb>肩</rb><rt>かた</rt></ruby>をゆすって</span><span><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>を<ruby><rb>取</rb><rt>と</rt></ruby>っている</span>。三四郎は<span>こちら<ruby><rb>側</rb><rt>がわ</rt></ruby></span>から<span><ruby><rb>手</rb><rt>て</rt></ruby></span>を<span><ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「おつかまりなさい」</p><p>「いえ<span><ruby><rb>大丈夫</rb><rt>だいじょうぶ</rt></ruby></span>」と女は笑っている。手を出しているあいだは、調子を取るだけで<span><ruby><rb>渡</rb><rt>わた</rt></ruby>らない</span>。三四郎は手を<span><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>込</rb><rt>こ</rt></ruby>めた</span>。すると美禰子は石の上にある右の足に、からだの<span><ruby><rb>重</rb><rt>おも</rt></ruby>み</span>を<span><ruby><rb>託</rb><rt>たく</rt></ruby>して</span>、<span><ruby><rb>左</rb><rt>ひだり</rt></ruby></span>の足で<span>ひらりと</span>こちら側へ渡った。あまりに<span><ruby><rb>下駄</rb><rt>げた</rt></ruby></span>をよごすまいと<span><ruby><rb>念</rb><rt>ねん</rt></ruby>を<ruby><rb>入</rb><rt>い</rt></ruby>れすぎた</span>ため、<span><ruby><rb>力</rb><rt>ちから</rt></ruby>が<ruby><rb>余</rb><rt>あま</rt></ruby>って</span>、<span><ruby><rb>腰</rb><rt>こし</rt></ruby></span>が<span><ruby><rb>浮</rb><rt>う</rt></ruby>いた</span>。<span>のめりそうに</span><span>胸</span>が<span><ruby><rb>前</rb><rt>まえ</rt></ruby>へ<ruby><rb>出</rb><rt>で</rt></ruby>る</span>。その<span><ruby><rb>勢</rb><rt>いきおい</rt></ruby></span>で美禰子の<span><ruby><rb>両手</rb><rt>りょうて</rt></ruby></span>が三四郎の<span><ruby><rb>両腕</rb><rt>りょううで</rt></ruby></span>の上へ<span><ruby><rb>落</rb><rt>お</rt></ruby>ちた</span>。</p>
		<p>「<span><ruby><rb>迷える子</rb><rt>ストレイ・シープ</rt></ruby></span>」と美禰子が<span><ruby><rb>口</rb><rt>くち</rt></ruby>の<ruby><rb>内</rb><rt>うち</rt></ruby></span>で言った。三四郎はその<span><ruby><rb>呼吸</rb><rt>いき</rt></ruby></span>を<span><ruby><rb>感</rb><rt>かん</rt></ruby>ずる</span>ことができた。</p>

		<h3 class="section">Rough translation</h3>
		<p>"It's getting a little cold. Let's get off the grass so we don't catch a chill. Are you feeling better?"</p>
		<p>"Yes, I'm much better now," she answered clearly and quickly rose to her feet. As she rose, she repeated slowly and deliberately, as though to herself, "Stray sheep." Sanshirō, of course, offered no reply.</p>
		<p>Mineko pointed in the direction from which the man in the suit had appeared earlier. If there was a path, then she'd like to go that way and pass by the chili peppers. The two of them set off in that direction. Behind the thatched-roof house there was indeed a narrow path, about a meter in width. Halfway down the path, Sanshirō asked her, "Is Yoshiko going to come live with you?"</p>
		<p>"Why do you ask?" she asked in response with a wry smile.</p>
		<p>As Sanshirō struggled for an answer, a muddy patch appeared in the path. The ground was low there, and water had collected in the depression. In the middle was a stone that someone had grabbed from nearby and placed as a step. Sanshirō jumped straight across, without the aid of the step. Then he turned back to Mineko. Mineko planted her right foot on top of the stone. The stone was not secure, and she had to use both her legs and her arms for balance. Sanshirō extended his hand to her.</p>
		<p>"Take hold."</p>
		<p>"I'm fine," said with a smile. While his hand was out, she recovered her balance but remained on the stone. Sanshirō withdrew his hand. Mineko shifted her weight to her right foot and leapt deftly over the puddle onto her left. Determined to clear the mud, she jumped too hard and stumbled forward from the excess momentum. She stopped herself with both hands against Sanshirō's arms.</p>
		<p>"Stray sheep," she whispered again to herself. She was so near that Sanshirō could feel her breath.</p>   

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>寒</rb><rt>さむ</rt></ruby>くなった&nbsp;become cold</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ちましょう&nbsp;stand up; get up</span><span class="vocabstudy"><ruby><rb>冷</rb><rt>ひ</rt></ruby>える&nbsp;get chilled</span><span class="vocabstudy"><ruby><rb>毒</rb><rt>どく</rt></ruby>&nbsp;poison; harmful</span><span class="vocabstudy"><ruby><rb>気分</rb><rt>きぶん</rt></ruby>&nbsp;feeling; mood</span><span class="vocabstudy"><ruby><rb>直</rb><rt>なお</rt></ruby>りました&nbsp;gotten better; improved</span>
		<span class="vocabstudy"><ruby><rb>明</rb><rt>あき</rt></ruby>らかに&nbsp;clearly</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた&nbsp;answered</span><span class="vocabstudy">にわかに&nbsp;quickly</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>上</rb><rt>あ</rt></ruby>がった&nbsp;stood up</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>小</rb><rt>ちい</rt></ruby>さな&nbsp;small; quiet (voice)</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice</span>
		<span class="vocabstudy"><ruby><rb>迷える子</rb><rt>ストレイ・シープ</rt></ruby>&nbsp;stray sheep</span><span class="vocabstudy"><ruby><rb>長</rb><rt>なが</rt></ruby>く&nbsp;lengthy</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>張</rb><rt>ぱ</rt></ruby>って&nbsp;stretch; draw out</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;said; uttered</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span>
		<span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>洋服</rb><rt>ようふく</rt></ruby>&nbsp;Western-style dress; a suit</span><span class="vocabstudy"><ruby><rb>着</rb><rt>き</rt></ruby>た&nbsp;wore</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;appeared (from)</span><span class="vocabstudy"><ruby><rb>方角</rb><rt>ほうがく</rt></ruby>&nbsp;direction; way</span><span class="vocabstudy"><ruby><rb>道</rb><rt>みち</rt></ruby>&nbsp;road; path</span><span class="vocabstudy"><ruby><rb>唐辛子</rb><rt>とうがらし</rt></ruby>&nbsp;chili peppers</span><span class="vocabstudy"><ruby><rb>通</rb><rt>とお</rt></ruby>って&nbsp;pass by</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>きたい&nbsp;want to go</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>見当</rb><rt>けんとう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いて<ruby><rb>行</rb><rt>い</rt></ruby>った&nbsp;walked toward</span><span class="vocabstudy"><ruby><rb>藁葺</rb><rt>わらぶき</rt></ruby>&nbsp;thatched roof</span><span class="vocabstudy"><ruby><rb>細</rb><rt>ほそ</rt></ruby>い&nbsp;narrow</span><span class="vocabstudy"><ruby><rb>三尺</rb><rt>さんじゃく</rt></ruby>&nbsp;3 shaku (about a meter; about a yard)</span><span class="vocabstudy"><ruby><rb>半分</rb><rt>はんぶん</rt></ruby>&nbsp;halfway</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;traversed</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span>
		<span class="vocabstudy">よし<ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;Yoshiko (Nonomiya's younger sister)</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come (to stay)</span>
		<span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;the young lady; she</span><span class="vocabstudy"><ruby><rb>片頬</rb><rt>かたほお</rt></ruby>&nbsp;one cheek</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>った&nbsp;smiled</span><span class="vocabstudy"><ruby><rb>問</rb><rt>と</rt></ruby>い<ruby><rb>返</rb><rt>かえ</rt></ruby>した&nbsp;asked in return</span>
		<span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>か&nbsp;something</span><span class="vocabstudy"><ruby><rb>足</rb><rt>あし</rt></ruby>&nbsp;feet</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;front of</span><span class="vocabstudy"><ruby><rb>泥濘</rb><rt>ぬかるみ</rt></ruby>&nbsp;mud puddle; muddy patch</span><span class="vocabstudy"><ruby><rb>四尺</rb><rt>よんしゃく</rt></ruby>&nbsp;4 shaku (about 1.2 meters; about 4 feet)</span><span class="vocabstudy"><ruby><rb>土</rb><rt>つち</rt></ruby>&nbsp;earth; ground</span><span class="vocabstudy"><ruby><rb>水</rb><rt>みず</rt></ruby>&nbsp;water</span><span class="vocabstudy">まん<ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;middle; center</span><span class="vocabstudy"><ruby><rb>足掛</rb><rt>あしが</rt></ruby>かり&nbsp;step</span><span class="vocabstudy"><ruby><rb>石</rb><rt>いし</rt></ruby>&nbsp;stone</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いた&nbsp;placed</span><span class="vocabstudy"><ruby><rb>者</rb><rt>もの</rt></ruby>&nbsp;person</span><span class="vocabstudy"><ruby><rb>助</rb><rt>たす</rt></ruby>け&nbsp;help; assistance</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう&nbsp;far side</span><span class="vocabstudy"><ruby><rb>飛</rb><rt>と</rt></ruby>んだ&nbsp;jumped (over to)</span><span class="vocabstudy"><ruby><rb>振</rb><rt>ふ</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>って&nbsp;turn back (toward)</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>た&nbsp;looked at</span><span class="vocabstudy"><ruby><rb>右</rb><rt>みぎ</rt></ruby>&nbsp;right (side)</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;top of</span><span class="vocabstudy"><ruby><rb>乗</rb><rt>の</rt></ruby>せた&nbsp;place onto</span><span class="vocabstudy"><ruby><rb>力</rb><rt>ちから</rt></ruby>を<ruby><rb>入</rb><rt>い</rt></ruby>れて&nbsp;apply force; flex</span><span class="vocabstudy"><ruby><rb>肩</rb><rt>かた</rt></ruby>をゆすって&nbsp;shift one's shoulders; swing one's arms</span><span class="vocabstudy"><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>を<ruby><rb>取</rb><rt>と</rt></ruby>っている&nbsp;find one's balance</span><span class="vocabstudy">こちら<ruby><rb>側</rb><rt>がわ</rt></ruby>&nbsp;this side</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;hand</span><span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;held out; extended</span>
		<span class="vocabstudy"><ruby><rb>大丈夫</rb><rt>だいじょうぶ</rt></ruby>&nbsp;okay; alright</span><span class="vocabstudy"><ruby><rb>渡</rb><rt>わた</rt></ruby>らない&nbsp;didn't cross</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>っ<ruby><rb>込</rb><rt>こ</rt></ruby>めた&nbsp;withdrew</span><span class="vocabstudy"><ruby><rb>重</rb><rt>おも</rt></ruby>み&nbsp;weight</span><span class="vocabstudy"><ruby><rb>託</rb><rt>たく</rt></ruby>して&nbsp;entrust to</span><span class="vocabstudy"><ruby><rb>左</rb><rt>ひだり</rt></ruby>&nbsp;left (side)</span><span class="vocabstudy">ひらりと&nbsp;nimbly; quickly</span><span class="vocabstudy"><ruby><rb>下駄</rb><rt>げた</rt></ruby>&nbsp;(wooden) clogs</span><span class="vocabstudy"><ruby><rb>念</rb><rt>ねん</rt></ruby>を<ruby><rb>入</rb><rt>い</rt></ruby>れすぎた&nbsp;took too much care</span><span class="vocabstudy"><ruby><rb>力</rb><rt>ちから</rt></ruby>が<ruby><rb>余</rb><rt>あま</rt></ruby>って&nbsp;be too forceful</span><span class="vocabstudy"><ruby><rb>腰</rb><rt>こし</rt></ruby>&nbsp;waist; hips</span><span class="vocabstudy"><ruby><rb>浮</rb><rt>う</rt></ruby>いた&nbsp;became unsteady</span><span class="vocabstudy">のめりそうに&nbsp;unsteadily</span><span class="vocabstudy">胸&nbsp;chest; upper body</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>へ<ruby><rb>出</rb><rt>で</rt></ruby>る&nbsp;move forward</span><span class="vocabstudy"><ruby><rb>勢</rb><rt>いきおい</rt></ruby>&nbsp;force; momentum</span><span class="vocabstudy"><ruby><rb>両手</rb><rt>りょうて</rt></ruby>&nbsp;both hands</span><span class="vocabstudy"><ruby><rb>両腕</rb><rt>りょううで</rt></ruby>&nbsp;both arms</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちた&nbsp;fell (onto)</span>
		<span class="vocabstudy"><ruby><rb>迷える子</rb><rt>ストレイ・シープ</rt></ruby>&nbsp;stray sheep</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>の<ruby><rb>内</rb><rt>うち</rt></ruby>&nbsp;(say) quietly; to oneself</span><span class="vocabstudy"><ruby><rb>呼吸</rb><rt>いき</rt></ruby>&nbsp;breath</span><span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>ずる&nbsp;feel</span>

	</StudyGuide>
);
