// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={88}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>しばらく<span><ruby><rb>無言</rb><rt>むごん</rt></ruby>のまま</span>、<span><ruby><rb>絵</rb><rt>え</rt></ruby></span>のなかをのぞいていると、<span>よし<ruby><rb>子</rb><rt>こ</rt></ruby></span>は<span>たんねんに</span><span><ruby><rb>藁葺</rb><rt>わらぶき</rt></ruby><ruby><rb>屋根</rb><rt>やね</rt></ruby></span>の<span><ruby><rb>黒</rb><rt>くろ</rt></ruby>い</span><span><ruby><rb>影</rb><rt>かげ</rt></ruby></span>を<span><ruby><rb>洗</rb><rt>あら</rt></ruby>って</span>いたが、あまり<span><ruby><rb>水</rb><rt>みず</rt></ruby></span>が<span><ruby><rb>多</rb><rt>おお</rt></ruby>すぎた</span>のと、<span><ruby><rb>筆</rb><rt>ふで</rt></ruby></span>の<span><ruby><rb>使</rb><rt>つか</rt></ruby>い<ruby><rb>方</rb><rt>かた</rt></ruby></span>がなかなか<span><ruby><rb>不慣</rb><rt>ふな</rt></ruby>れ</span>なので、黒いものがかってに<span><ruby><rb>四方</rb><rt>しほう</rt></ruby></span>へ<span><ruby><rb>浮</rb><rt>う</rt></ruby>き<ruby><rb>出</rb><rt>だ</rt></ruby>して</span>、せっかく<span><ruby><rb>赤</rb><rt>あか</rt></ruby>く</span>できた<span><ruby><rb>柿</rb><rt>かき</rt></ruby></span>が、<span><ruby><rb>陰干</rb><rt>かげぼし</rt></ruby>の</span><span><ruby><rb>渋柿</rb><rt>しぶがき</rt></ruby></span>のような<span><ruby><rb>色</rb><rt>いろ</rt></ruby></span>になった。よし子は<span><ruby><rb>画筆</rb><rt>えふで</rt></ruby></span>の<span><ruby><rb>手</rb><rt>て</rt></ruby></span>を<span><ruby><rb>休</rb><rt>やす</rt></ruby>めて</span>、<span><ruby><rb>両手</rb><rt>りょうて</rt></ruby></span>を<span><ruby><rb>伸</rb><rt>の</rt></ruby>ばして</span>、<span><ruby><rb>首</rb><rt>くび</rt></ruby></span>をあとへ<span><ruby><rb>引</rb><rt>ひ</rt></ruby>いて</span>、<span>ワットマン</span>をなるべく<span><ruby><rb>遠</rb><rt>とお</rt></ruby>くから</span>ながめていたが、しまいに、<span><ruby><rb>小</rb><rt>ちい</rt></ruby>さな</span><span><ruby><rb>声</rb><rt>こえ</rt></ruby></span>で、</p>
		<p>「もう<span><ruby><rb>駄目</rb><rt>だめ</rt></ruby></span>ね」と<span><ruby><rb>言</rb><rt>い</rt></ruby>う</span>。じっさいだめなのだから、しかたがない。<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby>になった</span>。</p>
		<p>「もうおよしなさい。そうして、また<span><ruby><rb>新</rb><rt>あたら</rt></ruby>しく</span>おかきなさい」</p>
		<p>よし子は<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>を絵に<span><ruby><rb>向</rb><rt>む</rt></ruby>けた</span>まま、<span>しりめに</span>三四郎を<span><ruby><rb>見</rb><rt>み</rt></ruby>た</span>。<span><ruby><rb>大</rb><rt>おお</rt></ruby>きな</span><span><ruby><rb>潤</rb><rt>うるお</rt></ruby>い</span>のある<span><ruby><rb>目</rb><rt>め</rt></ruby></span>である。三四郎はますます気の毒になった。すると<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>が<span><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span><span><ruby><rb>笑</rb><rt>わら</rt></ruby>いだした</span>。</p>
		<p>「ばかね。<span><ruby><rb>二</rb><rt>に</rt></ruby><ruby><rb>時間</rb><rt>じかん</rt></ruby></span>ばかり<span><ruby><rb>損</rb><rt>そん</rt></ruby></span>をして」と言いながら、せっかくかいた<span><ruby><rb>水彩</rb><rt>すいさい</rt></ruby></span>の<span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>へ、<span><ruby><rb>横縦</rb><rt>よこたて</rt></ruby>に</span><span><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三本</rb><rt>さんぼん</rt></ruby></span><span><ruby><rb>太</rb><rt>ふと</rt></ruby>い</span><span><ruby><rb>棒</rb><rt>ぼう</rt></ruby></span>を引いて、絵の<span><ruby><rb>具箱</rb><rt>ぐばこ</rt></ruby></span>の<span><ruby><rb>蓋</rb><rt>ふた</rt></ruby></span>を<span>ぱたりと</span><span><ruby><rb>伏</rb><rt>ふ</rt></ruby>せた</span>。</p>
		<p>「もうよしましょう。<span><ruby><rb>座敷</rb><rt>ざしき</rt></ruby></span>へおはいりなさい。<span>お<ruby><rb>茶</rb><rt>ちゃ</rt></ruby></span>をあげますから」と言いながら、<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>は上へ<span><ruby><rb>上</rb><rt>あ</rt></ruby>がった</span>。三四郎は<span><ruby><rb>靴</rb><rt>くつ</rt></ruby></span>を<span><ruby><rb>脱</rb><rt>ぬ</rt></ruby>ぐ</span>のが<span><ruby><rb>面倒</rb><rt>めんどう</rt></ruby></span>なので、やはり<span><ruby><rb>椽側</rb><rt>えんがわ</rt></ruby></span>に<span><ruby><rb>腰</rb><rt>こし</rt></ruby>をかけて</span>いた。<span><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>中</rb><rt>なか</rt></ruby>では</span>、<span><ruby><rb>今</rb><rt>いま</rt></ruby></span>になって、茶をやるという女を<span><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>に</span>おもしろいと<span><ruby><rb>思</rb><rt>おも</rt></ruby>って</span>いた。三四郎に<span><ruby><rb>度</rb><rt>ど</rt></ruby>はずれの</span>女をおもしろがるつもりは<span><ruby><rb>少</rb><rt>すこ</rt></ruby>しも</span>ないのだが、<span><ruby><rb>突然</rb><rt>とつぜん</rt></ruby></span>お茶をあげますといわれた<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>には、<span><ruby><rb>一種</rb><rt>いっしゅ</rt></ruby>の</span><span><ruby><rb>愉快</rb><rt>ゆかい</rt></ruby></span>を<span><ruby><rb>感</rb><rt>かん</rt></ruby>ぜぬわけにゆかなかった</span>のである。その感じは、どうしても<span><ruby><rb>異性</rb><rt>いせい</rt></ruby></span>に<span><ruby><rb>近</rb><rt>ちか</rt></ruby>づいて</span><span><ruby><rb>得</rb><rt>え</rt></ruby>られる</span>感じではなかった。</p>
		<p><span><ruby><rb>茶</rb><rt>ちゃ</rt></ruby>の<ruby><rb>間</rb><rt>ま</rt></ruby></span>で<span><ruby><rb>話</rb><rt>はな</rt></ruby>し<ruby><rb>声</rb><rt>ごえ</rt></ruby></span>がする。<span><ruby><rb>下女</rb><rt>げじょ</rt></ruby></span>はいた<span>に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない</span>。やがて<span><ruby><rb>襖</rb><rt>ふすま</rt></ruby></span>を<span><ruby><rb>開</rb><rt>ひら</rt></ruby>いて</span>、<span><ruby><rb>茶器</rb><rt>ちゃき</rt></ruby></span>を<span><ruby><rb>持</rb><rt>も</rt></ruby>って</span>、よし子があらわれた。その顔を<span><ruby><rb>正面</rb><rt>しょうめん</rt></ruby></span>から見た時に、三四郎はまた、<span><ruby><rb>女性中</rb><rt>じょせいちゅう</rt></ruby></span>のもっとも<span><ruby><rb>女性的</rb><rt>じょせいてき</rt></ruby>な</span>顔であると思った。</p>

		<h3 class="section">Rough translation</h3>
		<p>Yoshiko was quiet for a spell as she focused on her painting and worked carefully to thin down the dark shading of the thatched roof. Unfortunately, she applied too much water, and her technique with the brush was unpracticed. In the end, the dark color diffused in all directions, turning her sweet red persimmons the color of the shade-dried tart variety. She rested her brush hand, stretched her arms, and craned her neck back to gaze at the work from a distance. Finally she said in a low voice, "It's a lost cause."</p>
		<p>It really was. There was no saving it. Sanshirō felt bad for her. "Set this one aside and try again."</p>
		<p>Still facing her painting, she looked at him from the corner of her eye. The eye was large and moist. Sanshirō pitied her sincerely.</p>
		<p>All of a sudden she laughed. "I'm an idiot. Two hours gone to waste." With that, she wiped out her painting with thick strokes across and down. Then she emphatically closed the lid of her paint set.</p>
		<p>"Enough of that. Come inside. I'll make tea." She stepped up into the living room as she spoke.</p> 
		<p>Sanshirō, reluctant to take off his shoes, remained seated on the veranda. Inwardly, he found it most curious that she should suddenly offer him tea after all this time. He had no intention of amusing himself over her failure at decorum, but he couldn't help feeling a sense of exhilaration as she suddenly sprang into motion. It wasn't the sense one typically feels when interacting with a member of the opposite sex.</p>
		<p>He could hear voices from the hearth room. No doubt the maidservant had been home. Finally, the fusuma screen slid open and Yoshiko appeared with the tea service. As he watched her approach, Sanshirō was struck by the extraordinary femininity of her facial features.</p> 

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>無言</rb><rt>むごん</rt></ruby>のまま&nbsp;without speaking</span><span class="vocabstudy"><ruby><rb>絵</rb><rt>え</rt></ruby>&nbsp;painting</span><span class="vocabstudy">よし<ruby><rb>子</rb><rt>こ</rt></ruby>&nbsp;Yoshiko (Nonomiya's younger sister)</span><span class="vocabstudy">たんねんに&nbsp;carefully; painstakingly</span><span class="vocabstudy"><ruby><rb>藁葺</rb><rt>わらぶき</rt></ruby><ruby><rb>屋根</rb><rt>やね</rt></ruby>&nbsp;thatched roof</span><span class="vocabstudy"><ruby><rb>黒</rb><rt>くろ</rt></ruby>い&nbsp;black; dark</span><span class="vocabstudy"><ruby><rb>影</rb><rt>かげ</rt></ruby>&nbsp;shadow</span><span class="vocabstudy"><ruby><rb>洗</rb><rt>あら</rt></ruby>って&nbsp;wet; thin; wash (out)</span><span class="vocabstudy"><ruby><rb>水</rb><rt>みず</rt></ruby>&nbsp;water</span><span class="vocabstudy"><ruby><rb>多</rb><rt>おお</rt></ruby>すぎた&nbsp;too much</span><span class="vocabstudy"><ruby><rb>筆</rb><rt>ふで</rt></ruby>&nbsp;brush</span><span class="vocabstudy"><ruby><rb>使</rb><rt>つか</rt></ruby>い<ruby><rb>方</rb><rt>かた</rt></ruby>&nbsp;manner of using; technique</span><span class="vocabstudy"><ruby><rb>不慣</rb><rt>ふな</rt></ruby>れ&nbsp;inexperienced; unpracticed</span><span class="vocabstudy"><ruby><rb>四方</rb><rt>しほう</rt></ruby>&nbsp;all directions</span><span class="vocabstudy"><ruby><rb>浮</rb><rt>う</rt></ruby>き<ruby><rb>出</rb><rt>だ</rt></ruby>して&nbsp;appeared; emerged</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>く&nbsp;red</span><span class="vocabstudy"><ruby><rb>柿</rb><rt>かき</rt></ruby>&nbsp;persimmons</span><span class="vocabstudy"><ruby><rb>陰干</rb><rt>かげぼし</rt></ruby>の&nbsp;shade-dried</span><span class="vocabstudy"><ruby><rb>渋柿</rb><rt>しぶがき</rt></ruby>&nbsp;sour persimmon; tart persimmon</span><span class="vocabstudy"><ruby><rb>色</rb><rt>いろ</rt></ruby>&nbsp;color</span><span class="vocabstudy"><ruby><rb>画筆</rb><rt>えふで</rt></ruby>&nbsp;paint brush</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;hand</span><span class="vocabstudy"><ruby><rb>休</rb><rt>やす</rt></ruby>めて&nbsp;rest</span><span class="vocabstudy"><ruby><rb>両手</rb><rt>りょうて</rt></ruby>&nbsp;both hands</span><span class="vocabstudy"><ruby><rb>伸</rb><rt>の</rt></ruby>ばして&nbsp;stretched; extended</span><span class="vocabstudy"><ruby><rb>首</rb><rt>くび</rt></ruby>&nbsp;neck; head</span><span class="vocabstudy"><ruby><rb>引</rb><rt>ひ</rt></ruby>いて&nbsp;pull (back); draw back</span><span class="vocabstudy">ワットマン&nbsp;J Whatman (English paper company)</span><span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くから&nbsp;from a distance</span><span class="vocabstudy"><ruby><rb>小</rb><rt>ちい</rt></ruby>さな&nbsp;small; low (voice)</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice</span>
		<span class="vocabstudy"><ruby><rb>駄目</rb><rt>だめ</rt></ruby>&nbsp;no good</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;said; stated</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>の<ruby><rb>毒</rb><rt>どく</rt></ruby>になった&nbsp;felt bad (for her)</span>
		<span class="vocabstudy"><ruby><rb>新</rb><rt>あたら</rt></ruby>しく&nbsp;newly; anew</span>
		<span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>けた&nbsp;turned (toward)</span><span class="vocabstudy">しりめに&nbsp;corner of one's eye</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>た&nbsp;looked at</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな&nbsp;large</span><span class="vocabstudy"><ruby><rb>潤</rb><rt>うるお</rt></ruby>い&nbsp;moisture</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>&nbsp;eye</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;the girl; she</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>いだした&nbsp;laughed</span>
		<span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby><ruby><rb>時間</rb><rt>じかん</rt></ruby>&nbsp;two hours</span><span class="vocabstudy"><ruby><rb>損</rb><rt>そん</rt></ruby>&nbsp;loss; waste</span><span class="vocabstudy"><ruby><rb>水彩</rb><rt>すいさい</rt></ruby>&nbsp;watercolor</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;top of</span><span class="vocabstudy"><ruby><rb>横縦</rb><rt>よこたて</rt></ruby>に&nbsp;horizontally and vertically; across and lengthwise</span><span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三本</rb><rt>さんぼん</rt></ruby>&nbsp;several (lines)</span><span class="vocabstudy"><ruby><rb>太</rb><rt>ふと</rt></ruby>い&nbsp;thick</span><span class="vocabstudy"><ruby><rb>棒</rb><rt>ぼう</rt></ruby>&nbsp;bar; stripe</span><span class="vocabstudy"><ruby><rb>具箱</rb><rt>ぐばこ</rt></ruby>&nbsp;tool set</span><span class="vocabstudy"><ruby><rb>蓋</rb><rt>ふた</rt></ruby>&nbsp;lid</span><span class="vocabstudy">ぱたりと&nbsp;firmly; abruptly (= ばったり)</span><span class="vocabstudy"><ruby><rb>伏</rb><rt>ふ</rt></ruby>せた&nbsp;lowered; closed</span>
		<span class="vocabstudy"><ruby><rb>座敷</rb><rt>ざしき</rt></ruby>&nbsp;living room</span><span class="vocabstudy">お<ruby><rb>茶</rb><rt>ちゃ</rt></ruby>&nbsp;tea</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>がった&nbsp;entered (up into a room)</span><span class="vocabstudy"><ruby><rb>靴</rb><rt>くつ</rt></ruby>&nbsp;shoes</span><span class="vocabstudy"><ruby><rb>脱</rb><rt>ぬ</rt></ruby>ぐ&nbsp;take off</span><span class="vocabstudy"><ruby><rb>面倒</rb><rt>めんどう</rt></ruby>&nbsp;troublesome; too much effort</span><span class="vocabstudy"><ruby><rb>椽側</rb><rt>えんがわ</rt></ruby>&nbsp;veranda</span><span class="vocabstudy"><ruby><rb>腰</rb><rt>こし</rt></ruby>をかけて&nbsp;sit; be seated (on)</span><span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>中</rb><rt>なか</rt></ruby>では&nbsp;privately; to oneself</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; at this point</span><span class="vocabstudy"><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>に&nbsp;extremely; terribly</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>って&nbsp;consider; regard as</span><span class="vocabstudy"><ruby><rb>度</rb><rt>ど</rt></ruby>はずれの&nbsp;extraordinary; eccentric</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>しも&nbsp;(not) in the least</span><span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>一種</rb><rt>いっしゅ</rt></ruby>の&nbsp;a type of; a certain kind of</span><span class="vocabstudy"><ruby><rb>愉快</rb><rt>ゆかい</rt></ruby>&nbsp;pleasure; exhilaration</span><span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>ぜぬわけにゆかなかった&nbsp;couldn't help but feel</span><span class="vocabstudy"><ruby><rb>異性</rb><rt>いせい</rt></ruby>&nbsp;the opposite sex</span><span class="vocabstudy"><ruby><rb>近</rb><rt>ちか</rt></ruby>づいて&nbsp;approach; draw near to</span><span class="vocabstudy"><ruby><rb>得</rb><rt>え</rt></ruby>られる&nbsp;can get; can obtain</span>
		<span class="vocabstudy"><ruby><rb>茶</rb><rt>ちゃ</rt></ruby>の<ruby><rb>間</rb><rt>ま</rt></ruby>&nbsp;tea room; hearth room</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>し<ruby><rb>声</rb><rt>ごえ</rt></ruby>&nbsp;voices; the sound of voices</span><span class="vocabstudy"><ruby><rb>下女</rb><rt>げじょ</rt></ruby>&nbsp;maidservant</span><span class="vocabstudy">に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない&nbsp;there was no doubt that ...</span><span class="vocabstudy"><ruby><rb>襖</rb><rt>ふすま</rt></ruby>&nbsp;fusuma (sliding door panel)</span><span class="vocabstudy"><ruby><rb>開</rb><rt>ひら</rt></ruby>いて&nbsp;open</span><span class="vocabstudy"><ruby><rb>茶器</rb><rt>ちゃき</rt></ruby>&nbsp;tea set</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って&nbsp;bring; carry</span><span class="vocabstudy"><ruby><rb>正面</rb><rt>しょうめん</rt></ruby>&nbsp;straight on; the front</span><span class="vocabstudy"><ruby><rb>女性中</rb><rt>じょせいちゅう</rt></ruby>&nbsp;among women</span><span class="vocabstudy"><ruby><rb>女性的</rb><rt>じょせいてき</rt></ruby>な&nbsp;feminine</span>

	</StudyGuide>
);
