// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={96}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>ようやくのことで、<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>のそばまで<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span>、</p>
		<p>「<span><ruby><rb>里見</rb><rt>さとみ</rt></ruby></span>さん」と<span><ruby><rb>呼</rb><rt>よ</rt></ruby>んだ</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>に、美禰子は<span><ruby><rb>青竹</rb><rt>あおだけ</rt></ruby></span>の<span><ruby><rb>手欄</rb><rt>てすり</rt></ruby></span>に<span><ruby><rb>手</rb><rt>て</rt></ruby></span>を<span><ruby><rb>突</rb><rt>つ</rt></ruby>いて</span>、<span><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち</span><span><ruby><rb>首</rb><rt>くび</rt></ruby>をもどして</span>、<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>を<span><ruby><rb>見</rb><rt>み</rt></ruby>た</span>。<span>なんとも<ruby><rb>言</rb><rt>い</rt></ruby>わない</span>。手欄のなかは<span><ruby><rb>養老</rb><rt>ようろう</rt></ruby>の<ruby><rb>滝</rb><rt>たき</rt></ruby></span>である。<span><ruby><rb>丸</rb><rt>まる</rt></ruby>い</span><span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>の、<span><ruby><rb>腰</rb><rt>こし</rt></ruby></span>に<span><ruby><rb>斧</rb><rt>おの</rt></ruby></span>をさした<span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>が、<span><ruby><rb>瓢箪</rb><rt>ひょうたん</rt></ruby></span>を<span><ruby><rb>持</rb><rt>も</rt></ruby>って</span>、<span><ruby><rb>滝壺</rb><rt>たきつぼ</rt></ruby></span>のそばに<span>かがんで</span>いる。三四郎が美禰子の顔を見た時には、青竹のなかに<span><ruby><rb>何</rb><rt>なに</rt></ruby></span>があるかほとんど<span><ruby><rb>気</rb><rt>き</rt></ruby>がつかなかった</span>。</p>
		<p>「どうかしましたか」と<span><ruby><rb>思</rb><rt>おも</rt></ruby>わず</span><span><ruby><rb>言</rb><rt>い</rt></ruby>った</span>。美禰子はまだ<span>なんとも<ruby><rb>答</rb><rt>こた</rt></ruby>えない</span>。<span><ruby><rb>黒</rb><rt>くろ</rt></ruby>い</span><span><ruby><rb>目</rb><rt>め</rt></ruby></span>をさも<span>ものうそうに</span>三四郎の<span><ruby><rb>額</rb><rt>ひたい</rt></ruby></span>の<span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>にすえた。その時三四郎は美禰子の<span><ruby><rb>二重瞼</rb><rt>ふたえまぶた</rt></ruby></span>に<span><ruby><rb>不可思議</rb><rt>ふかしぎ</rt></ruby>な</span>ある<span><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>を<span><ruby><rb>認</rb><rt>みと</rt></ruby>めた</span>。その意味のうちには、<span><ruby><rb>霊</rb><rt>たましい</rt></ruby></span>の<span><ruby><rb>疲</rb><rt>つか</rt></ruby>れ</span>がある。<span><ruby><rb>肉</rb><rt>にく</rt></ruby></span>の<span>ゆるみ</span>がある。<span><ruby><rb>苦痛</rb><rt>くつう</rt></ruby></span><span>に<ruby><rb>近</rb><rt>ちか</rt></ruby>き</span><span><ruby><rb>訴</rb><rt>うった</rt></ruby>え</span>がある。三四郎は、美禰子の答を<span><ruby><rb>予期</rb><rt>よき</rt></ruby></span>しつつある<span><ruby><rb>今</rb><rt>いま</rt></ruby></span>の<span><ruby><rb>場合</rb><rt>ばあい</rt></ruby></span>を<span><ruby><rb>忘</rb><rt>わす</rt></ruby>れて</span>、この<span><ruby><rb>眸</rb><rt>ひとみ</rt></ruby></span>とこの<span><ruby><rb>瞼</rb><rt>まぶた</rt></ruby></span>の<span><ruby><rb>間</rb><rt>あいだ</rt></ruby></span>にすべてを<span><ruby><rb>遺却</rb><rt>いきゃく</rt></ruby>した</span>。すると、美禰子は言った。</p>
		<p>「もう<span><ruby><rb>出</rb><rt>で</rt></ruby>ましょう</span>」</p>
		<p>眸と瞼の<span><ruby><rb>距離</rb><rt>きょり</rt></ruby></span>が<span><ruby><rb>次第</rb><rt>しだい</rt></ruby>に</span>近づくようにみえた。近づく<span>に<ruby><rb>従</rb><rt>したが</rt></ruby>って</span>三四郎の<span><ruby><rb>心</rb><rt>こころ</rt></ruby></span>には<span><ruby><rb>女</rb><rt>おんな</rt></ruby>のため</span>に出なければすまない気がきざしてきた。それが<span><ruby><rb>頂点</rb><rt>ちょうてん</rt></ruby></span>に<span><ruby><rb>達</rb><rt>たっ</rt></ruby>した</span>ころ、女は<span><ruby><rb>首</rb><rt>くび</rt></ruby>を<ruby><rb>投</rb><rt>な</rt></ruby>げる</span>ように<span><ruby><rb>向</rb><rt>む</rt></ruby>こう</span>をむいた。手を青竹の手欄から<span><ruby><rb>離</rb><rt>はな</rt></ruby>して</span>、<span><ruby><rb>出口</rb><rt>でぐち</rt></ruby></span>の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>へ<span><ruby><rb>歩</rb><rt>ある</rt></ruby>いて<ruby><rb>行</rb><rt>い</rt></ruby>く</span>。三四郎はすぐあとからついて出た。</p>
		<p><span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>が<span><ruby><rb>表</rb><rt>おもて</rt></ruby></span>で<span><ruby><rb>並</rb><rt>なら</rt></ruby>んだ</span>時、美禰子は<span>うつむいて</span><span><ruby><rb>右</rb><rt>みぎ</rt></ruby>の<ruby><rb>手</rb><rt>て</rt></ruby></span>を額に<span><ruby><rb>当</rb><rt>あ</rt></ruby>てた</span>。<span><ruby><rb>周囲</rb><rt>しゅうい</rt></ruby></span>は<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>が<span><ruby><rb>渦</rb><rt>うず</rt></ruby></span>を<span><ruby><rb>巻</rb><rt>ま</rt></ruby>いて</span>いる。三四郎は女の<span><ruby><rb>耳</rb><rt>みみ</rt></ruby></span>へ<span><ruby><rb>口</rb><rt>くち</rt></ruby></span>を<span><ruby><rb>寄</rb><rt>よ</rt></ruby>せた</span>。</p>
		<p>「どうかしましたか」</p>
		<p>女は<span class="vocabstudy"><ruby><rb>人込</rb><rt>ひとご</rt></ruby>み</span>の<span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>谷中</rb><rt>やなか</rt></ruby></span>の方へ歩きだした。三四郎もむろんいっしょに歩きだした。<span class="vocabstudy"><ruby><rb>半町</rb><rt>はんちょう</rt></ruby></span>ばかり<span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>た</span>時、女は人の中で<span class="vocabstudy"><ruby><rb>留</rb><rt>と</rt></ruby>まった</span>。</p>
		<p>「ここはどこでしょう」</p>
		<p>「こっちへ行くと谷中の<span class="vocabstudy"><ruby><rb>天王寺</rb><rt>てんのうじ</rt></ruby></span>の方へ出てしまいます。<span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>り<ruby><rb>道</rb><rt>みち</rt></ruby></span>とはまるで<span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby></span>です」</p>
		<p>「そう。<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby></span><span class="vocabstudy"><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち</span>が<span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>くって</span>……」</p>
		<p>三四郎は<span class="vocabstudy"><ruby><rb>往来</rb><rt>おうらい</rt></ruby></span>のまん中で<span class="vocabstudy"><ruby><rb>助</rb><rt>たす</rt></ruby>けなき</span>苦痛を<span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>じた</span>。<span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えて</span>いた。</p>
		<p>「どこか<span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かな</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby></span>はないでしょうか」と女が<span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>Sanshirō finally made his way to Mineko and called her name. She was leaning against a handrail of green bamboo, and she turned her head just slightly to look his way. She didn't speak. Within the railing was a scene of Yōrō Falls. A round-faced man with a hatchet about his waist was stooping over the plunge basin, bottle gourd in hand. After seeing Mineko's face, Sanshirō paid no further notice to the objects beyond the railing.</p> 
		<p>"Are you alright?" he asked immediately. Mineko still said nothing. She fixed her dark eyes on his brow with a tired look. In that moment, Sanshirō recognized something profound in her handsomely contoured eyes. Part of what he recognized was a weariness of the spirit. The flesh was also slack, all but exposing an inner anguish. Sanshirō forgot that he'd been waiting on her answer and lost himself entirely in the space between her pupils and her eyelids. As he did so, she broke her silence.</p>
		<p>"Let's go outside."</p>
		<p>Her pupils and lids seemed to draw together. As they converged, a conviction grew within Sanshirō that they had to get out of there for Mineko's sake. Just as his conviction peaked, she turned away, released the handrail, and moved toward the exit. Sanshirō followed immediately after.</p>
		<p>Once the two of them were outside, Mineko stooped and pressed her right hand against her downturned forehead. The crowds milled about them. Sanshirō drew his mouth close to her ear. "Are you alright?"</p>
		<p>She began moving through the swell of sightseers toward Yanaka. Sanshirō, of course, accompanied her. Half a block on, she stopped in the midst of the crowd.</p>
		<p>"Where are we?"</p>
		<p>"This way leads to Tennōji, in Yanaka. Home is the opposite direction."</p>
		<p>"I see. I'm really not feeling well ..."</p>
		<p>Sanshirō felt pained as he stood there in the middle of the road, at a loss as to what he should do.</p>
		<p>"Is there some place quiet?" she asked him.</p>  

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;came (to)</span>
		<span class="vocabstudy"><ruby><rb>里見</rb><rt>さとみ</rt></ruby>&nbsp;Satomi (Mineko's family name)</span><span class="vocabstudy"><ruby><rb>呼</rb><rt>よ</rt></ruby>んだ&nbsp;called; addressed</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>青竹</rb><rt>あおだけ</rt></ruby>&nbsp;green bamboo</span><span class="vocabstudy"><ruby><rb>手欄</rb><rt>てすり</rt></ruby>&nbsp;handrail</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;hands</span><span class="vocabstudy"><ruby><rb>突</rb><rt>つ</rt></ruby>いて&nbsp;brace; prop (against)</span><span class="vocabstudy"><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち&nbsp;slightly; just a little</span><span class="vocabstudy"><ruby><rb>首</rb><rt>くび</rt></ruby>をもどして&nbsp;turned one's head</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>た&nbsp;looked at</span><span class="vocabstudy">なんとも<ruby><rb>言</rb><rt>い</rt></ruby>わない&nbsp;didn't speak; said nothing</span><span class="vocabstudy"><ruby><rb>養老</rb><rt>ようろう</rt></ruby>の<ruby><rb>滝</rb><rt>たき</rt></ruby>&nbsp;Yōrō Falls (waterfall in Gifu; tied to legend of young man who scooped its water to save his ailing father)</span><span class="vocabstudy"><ruby><rb>丸</rb><rt>まる</rt></ruby>い&nbsp;round</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>腰</rb><rt>こし</rt></ruby>&nbsp;waist</span><span class="vocabstudy"><ruby><rb>斧</rb><rt>おの</rt></ruby>&nbsp;axe; hatchet</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man</span><span class="vocabstudy"><ruby><rb>瓢箪</rb><rt>ひょうたん</rt></ruby>&nbsp;bottle gourd</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って&nbsp;have; hold</span><span class="vocabstudy"><ruby><rb>滝壺</rb><rt>たきつぼ</rt></ruby>&nbsp;plunge basin; basin under a waterfall</span><span class="vocabstudy">かがんで&nbsp;stoop (over)</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>&nbsp;what</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>がつかなかった&nbsp;took no notice of</span>
		<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>わず&nbsp;reflexively; intuitively</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;asked; inquired</span><span class="vocabstudy">なんとも<ruby><rb>答</rb><rt>こた</rt></ruby>えない&nbsp;didn't answer</span><span class="vocabstudy"><ruby><rb>黒</rb><rt>くろ</rt></ruby>い&nbsp;dark</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>&nbsp;eyes</span><span class="vocabstudy">ものうそうに&nbsp;with a weary look</span><span class="vocabstudy"><ruby><rb>額</rb><rt>ひたい</rt></ruby>&nbsp;forehead; brow</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;above</span><span class="vocabstudy"><ruby><rb>二重瞼</rb><rt>ふたえまぶた</rt></ruby>&nbsp;contoured eyelids</span><span class="vocabstudy"><ruby><rb>不可思議</rb><rt>ふかしぎ</rt></ruby>な&nbsp;mysterious; unfathomable</span><span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning</span><span class="vocabstudy"><ruby><rb>認</rb><rt>みと</rt></ruby>めた&nbsp;recognized</span><span class="vocabstudy"><ruby><rb>霊</rb><rt>たましい</rt></ruby>&nbsp;soul; spirit</span><span class="vocabstudy"><ruby><rb>疲</rb><rt>つか</rt></ruby>れ&nbsp;weariness; fatigue</span><span class="vocabstudy"><ruby><rb>肉</rb><rt>にく</rt></ruby>&nbsp;flesh</span><span class="vocabstudy">ゆるみ&nbsp;looseness; slack</span><span class="vocabstudy"><ruby><rb>苦痛</rb><rt>くつう</rt></ruby>&nbsp;pain; anguish</span><span class="vocabstudy">に<ruby><rb>近</rb><rt>ちか</rt></ruby>き&nbsp;close to; bordering on</span><span class="vocabstudy"><ruby><rb>訴</rb><rt>うった</rt></ruby>え&nbsp;appeal; petition</span><span class="vocabstudy"><ruby><rb>予期</rb><rt>よき</rt></ruby>&nbsp;expectation; anticipation (of)</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; the present</span><span class="vocabstudy"><ruby><rb>場合</rb><rt>ばあい</rt></ruby>&nbsp;situation</span><span class="vocabstudy"><ruby><rb>忘</rb><rt>わす</rt></ruby>れて&nbsp;forget</span><span class="vocabstudy"><ruby><rb>眸</rb><rt>ひとみ</rt></ruby>&nbsp;pupils</span><span class="vocabstudy"><ruby><rb>瞼</rb><rt>まぶた</rt></ruby>&nbsp;eyelids</span><span class="vocabstudy"><ruby><rb>間</rb><rt>あいだ</rt></ruby>&nbsp;midst</span><span class="vocabstudy"><ruby><rb>遺却</rb><rt>いきゃく</rt></ruby>した&nbsp;abandoned (to)</span>
		<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>ましょう&nbsp;leave; get out (of a place)</span>
		<span class="vocabstudy"><ruby><rb>距離</rb><rt>きょり</rt></ruby>&nbsp;distance</span><span class="vocabstudy"><ruby><rb>次第</rb><rt>しだい</rt></ruby>に&nbsp;gradually</span><span class="vocabstudy">に<ruby><rb>従</rb><rt>したが</rt></ruby>って&nbsp;in accordance with; in proportion to</span><span class="vocabstudy"><ruby><rb>心</rb><rt>こころ</rt></ruby>&nbsp;heart; soul</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>のため&nbsp;for her sake</span><span class="vocabstudy"><ruby><rb>頂点</rb><rt>ちょうてん</rt></ruby>&nbsp;peak; height</span><span class="vocabstudy"><ruby><rb>達</rb><rt>たっ</rt></ruby>した&nbsp;reached; achieved</span><span class="vocabstudy"><ruby><rb>首</rb><rt>くび</rt></ruby>を<ruby><rb>投</rb><rt>な</rt></ruby>げる&nbsp;toss one's head</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう&nbsp;away; in the other direction</span><span class="vocabstudy"><ruby><rb>離</rb><rt>はな</rt></ruby>して&nbsp;removed; separated (from)</span><span class="vocabstudy"><ruby><rb>出口</rb><rt>でぐち</rt></ruby>&nbsp;exit</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いて<ruby><rb>行</rb><rt>い</rt></ruby>く&nbsp;walk (toward)</span>
		<span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>表</rb><rt>おもて</rt></ruby>&nbsp;out front</span><span class="vocabstudy"><ruby><rb>並</rb><rt>なら</rt></ruby>んだ&nbsp;stood together</span><span class="vocabstudy">うつむいて&nbsp;look down</span><span class="vocabstudy"><ruby><rb>右</rb><rt>みぎ</rt></ruby>の<ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;right hand</span><span class="vocabstudy"><ruby><rb>当</rb><rt>あ</rt></ruby>てた&nbsp;applied; pressed against</span><span class="vocabstudy"><ruby><rb>周囲</rb><rt>しゅうい</rt></ruby>&nbsp;surroundings; all around</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;people</span><span class="vocabstudy"><ruby><rb>渦</rb><rt>うず</rt></ruby>&nbsp;whirlpool</span><span class="vocabstudy"><ruby><rb>巻</rb><rt>ま</rt></ruby>いて&nbsp;wind; coil</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>&nbsp;ear</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>&nbsp;mouth</span><span class="vocabstudy"><ruby><rb>寄</rb><rt>よ</rt></ruby>せた&nbsp;brought close to</span>
		<span class="vocabstudy"><ruby><rb>人込</rb><rt>ひとご</rt></ruby>み&nbsp;crowd (of people)</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;middle</span><span class="vocabstudy"><ruby><rb>谷中</rb><rt>やなか</rt></ruby>&nbsp;Yanaka (place name)</span><span class="vocabstudy"><ruby><rb>半町</rb><rt>はんちょう</rt></ruby>&nbsp;half of a chō (about 55 meter; about 60 yards)</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came; progressed</span><span class="vocabstudy"><ruby><rb>留</rb><rt>と</rt></ruby>まった&nbsp;stopped</span>
		<span class="vocabstudy"><ruby><rb>天王寺</rb><rt>てんのうじ</rt></ruby>&nbsp;Tennōji (temple)</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>り<ruby><rb>道</rb><rt>みち</rt></ruby>&nbsp;way home; way back</span><span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby>&nbsp;opposite</span>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>&nbsp;I</span><span class="vocabstudy"><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち&nbsp;feeling</span><span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>くって&nbsp;not well</span>
		<span class="vocabstudy"><ruby><rb>往来</rb><rt>おうらい</rt></ruby>&nbsp;road</span><span class="vocabstudy"><ruby><rb>助</rb><rt>たす</rt></ruby>けなき&nbsp;at a loss (as to what to do)</span><span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>じた&nbsp;felt</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;standing (still)</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>えて&nbsp;thinking; considering</span>
		<span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かな&nbsp;quiet</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span>

	</StudyGuide>
);
