// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={97}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>谷中</rb><rt>やなか</rt></ruby></span>と<span><ruby><rb>千駄木</rb><rt>せんだぎ</rt></ruby></span>が<span><ruby><rb>谷</rb><rt>たに</rt></ruby></span>で<span><ruby><rb>出会</rb><rt>であ</rt></ruby>う</span>と、いちばん<span><ruby><rb>低</rb><rt>ひく</rt></ruby>い</span><span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>に<span><ruby><rb>小川</rb><rt>おがわ</rt></ruby></span>が<span><ruby><rb>流</rb><rt>なが</rt></ruby>れて</span>いる。この小川を<span><ruby><rb>沿</rb><rt>そ</rt></ruby>うて</span>、<span><ruby><rb>町</rb><rt>まち</rt></ruby></span>を<span><ruby><rb>左</rb><rt>ひだり</rt></ruby></span>へ<span><ruby><rb>切</rb><rt>き</rt></ruby>れる</span>とすぐ<span><ruby><rb>野</rb><rt>の</rt></ruby></span>に<span><ruby><rb>出</rb><rt>で</rt></ruby>る</span>。<span><ruby><rb>川</rb><rt>かわ</rt></ruby></span>はまっすぐに<span><ruby><rb>北</rb><rt>きた</rt></ruby></span>へ<span><ruby><rb>通</rb><rt>かよ</rt></ruby>って</span>いる。<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>東京</rb><rt>とうきょう</rt></ruby></span>へ<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span>から<span><ruby><rb>何</rb><rt>なん</rt></ruby>べんも</span>この小川の<span><ruby><rb>向</rb><rt>む</rt></ruby>こう<ruby><rb>側</rb><rt>がわ</rt></ruby></span>を<span><ruby><rb>歩</rb><rt>ある</rt></ruby>いて</span>、何べんこっち側を歩いたかよく<span><ruby><rb>覚</rb><rt>おぼ</rt></ruby>えて</span>いる。<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>の<span><ruby><rb>立</rb><rt>た</rt></ruby>って</span>いる所は、この小川が、ちょうど谷中の町を<span><ruby><rb>横切</rb><rt>よこぎ</rt></ruby>って</span><span><ruby><rb>根津</rb><rt>ねづ</rt></ruby></span>へ<span><ruby><rb>抜</rb><rt>ぬ</rt></ruby>ける</span><span><ruby><rb>石橋</rb><rt>いしばし</rt></ruby></span>のそばである。</p>
		<p>「もう<span><ruby><rb>一町</rb><rt>いっちょう</rt></ruby></span>ばかり歩けますか」と美禰子に<span><ruby><rb>聞</rb><rt>き</rt></ruby>いて</span>みた。</p>
		<p>「歩きます」</p>
		<p>二人はすぐ石橋を<span class="vocabstudy"><ruby><rb>渡</rb><rt>わた</rt></ruby>って</span>、左へ<span class="vocabstudy"><ruby><rb>折</rb><rt>お</rt></ruby>れた</span>。<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>の<ruby><rb>家</rb><rt>うち</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>路地</rb><rt>ろじ</rt></ruby></span>のような所を<span class="vocabstudy"><ruby><rb>十間</rb><rt>じゅっけん</rt></ruby></span>ほど<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>き<ruby><rb>尽</rb><rt>つく</rt></ruby>して</span>、<span class="vocabstudy"><ruby><rb>門</rb><rt>もん</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>手前</rb><rt>てまえ</rt></ruby></span>から<span class="vocabstudy"><ruby><rb>板橋</rb><rt>いたばし</rt></ruby></span>をこちら側へ<span class="vocabstudy"><ruby><rb>渡</rb><rt>わた</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>して</span>、しばらく川の<span class="vocabstudy"><ruby><rb>縁</rb><rt>ふち</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>上</rb><rt>のぼ</rt></ruby>る</span>と、もう<span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>は<ruby><rb>通</rb><rt>とお</rt></ruby>らない</span>。<span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い</span>野である。</p>
		<p>三四郎はこの<span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かな</span><span class="vocabstudy"><ruby><rb>秋</rb><rt>あき</rt></ruby></span>のなかへ<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>たら</span>、<span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span><span class="vocabstudy">しゃべり<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「どうです、ぐあいは。<span class="vocabstudy"><ruby><rb>頭痛</rb><rt>ずつう</rt></ruby></span>でもしますか。あんまり人がおおぜい、いたせいでしょう。あの<span class="vocabstudy"><ruby><rb>人形</rb><rt>にんぎょう</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て</span>いる<span class="vocabstudy"><ruby><rb>連中</rb><rt>れんちゅう</rt></ruby></span>のうちにはずいぶん<span class="vocabstudy"><ruby><rb>下等</rb><rt>かとう</rt></ruby></span>なのがいたようだから――なにか<span class="vocabstudy"><ruby><rb>失礼</rb><rt>しつれい</rt></ruby></span>でもしましたか」</p>
		<p><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>いる。やがて川の流れから<span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>げて</span>、三四郎を見た。<span class="vocabstudy"><ruby><rb>二重瞼</rb><rt>ふたえまぶた</rt></ruby></span>にはっきりと<span class="vocabstudy"><ruby><rb>張</rb><rt>は</rt></ruby>り</span>があった。三四郎はその目つきでなかば<span class="vocabstudy"><ruby><rb>安心</rb><rt>あんしん</rt></ruby>した</span>。</p>
		<p>「ありがとう。だいぶよくなりました」と<span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う</span>。</p>
		<p>「<span class="vocabstudy"><ruby><rb>休</rb><rt>やす</rt></ruby>みましょう</span>か」</p>
		<p>「ええ」</p>
		<p>「もう<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span>歩けますか」</p>
		<p>「ええ」</p>
		<p>「歩ければ、もう少しお歩きなさい。ここはきたない。あすこまで<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>く</span>と、ちょうど休むにいい<span class="vocabstudy"><ruby><rb>場所</rb><rt>ばしょ</rt></ruby></span>があるから」</p>
		<p>「ええ」</p>

		<h3 class="section">Rough translation</h3>
		<p>Yanaka and Sendagi formed a valley at their common border, and a small stream ran through the bottom of the valley. Following the stream with the town to one's left led to open fields. The stream flowed due north. Sanshirō had often walked this stream, both the far side and the near side, since his arrival in Tōkyō. He was intimately familiar with the area. Mineko had stopped near a stone bridge, where the stream cut through Yanaka and flowed on toward Nezu.</p>
		<p>"Can you walk another block or so?" he asked her.</p>
		<p>"Yes, let's go."</p>
		<p>The two of them crossed the stone bridge and turned left. They walked twenty meters to the end of an alleyway that led to a private residence. Just before the gate, they crossed back to the near side on a plank bridge and continued upstream by the water's edge. They were out in the open now, away from the crowd.</p>
		<p>As they emerged into the quiet of autumn, Sanshirō suddenly felt talkative. "How are you feeling? Do you have a headache? Maybe it was the crowds. Some of those men viewing the dolls were quite vulgar -- did they do something to upset you?"</p> 
		<p>She didn't answer. Finally, she lifted her gaze from the stream and looked at him. The spirit in her well-formed eyes had rekindled itself. Sanshirō was relieved just by her look.</p>
		<p>"Thank you. I'm feeling better," she answered.</p>
		<p>"Would you like to rest?"</p>
		<p>"Yes."</p>
		<p>"Can you walk a little further?"</p>
		<p>"Yes."</p>
		<p>"If you can, let's walk a little more. It's not very nice here. Up ahead is a good place to rest."</p>
		<p>"Okay."</p>  

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>谷中</rb><rt>やなか</rt></ruby>&nbsp;Yanaka (place name)</span><span class="vocabstudy"><ruby><rb>千駄木</rb><rt>せんだぎ</rt></ruby>&nbsp;Sendagi (place name)</span><span class="vocabstudy"><ruby><rb>谷</rb><rt>たに</rt></ruby>&nbsp;valley</span><span class="vocabstudy"><ruby><rb>出会</rb><rt>であ</rt></ruby>う&nbsp;meet; come together</span><span class="vocabstudy"><ruby><rb>低</rb><rt>ひく</rt></ruby>い&nbsp;low</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place; region</span><span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby>&nbsp;small river; stream</span><span class="vocabstudy"><ruby><rb>流</rb><rt>なが</rt></ruby>れて&nbsp;flow</span><span class="vocabstudy"><ruby><rb>沿</rb><rt>そ</rt></ruby>うて&nbsp;follow (alongside)</span><span class="vocabstudy"><ruby><rb>町</rb><rt>まち</rt></ruby>&nbsp;town</span><span class="vocabstudy"><ruby><rb>左</rb><rt>ひだり</rt></ruby>&nbsp;left (side)</span><span class="vocabstudy"><ruby><rb>切</rb><rt>き</rt></ruby>れる&nbsp;curve; veer</span><span class="vocabstudy"><ruby><rb>野</rb><rt>の</rt></ruby>&nbsp;open fields</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>る&nbsp;come out; emerge (into)</span><span class="vocabstudy"><ruby><rb>川</rb><rt>かわ</rt></ruby>&nbsp;stream</span><span class="vocabstudy"><ruby><rb>北</rb><rt>きた</rt></ruby>&nbsp;north</span><span class="vocabstudy"><ruby><rb>通</rb><rt>かよ</rt></ruby>って&nbsp;make its way (to); flow (to)</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>東京</rb><rt>とうきょう</rt></ruby>&nbsp;Tōkyō</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;come (to)</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>べんも&nbsp;many times</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう<ruby><rb>側</rb><rt>がわ</rt></ruby>&nbsp;other side; opposite side</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いて&nbsp;walk (along)</span><span class="vocabstudy"><ruby><rb>覚</rb><rt>おぼ</rt></ruby>えて&nbsp;remember; be familiar with</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;be standing</span><span class="vocabstudy"><ruby><rb>横切</rb><rt>よこぎ</rt></ruby>って&nbsp;traverse</span><span class="vocabstudy"><ruby><rb>根津</rb><rt>ねづ</rt></ruby>&nbsp;Nezu (place name)</span><span class="vocabstudy"><ruby><rb>抜</rb><rt>ぬ</rt></ruby>ける&nbsp;cut through (to)</span><span class="vocabstudy"><ruby><rb>石橋</rb><rt>いしばし</rt></ruby>&nbsp;stone bridge</span>
		<span class="vocabstudy"><ruby><rb>一町</rb><rt>いっちょう</rt></ruby>&nbsp;1 chō (about 110 meters; about 120 yards)</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いて&nbsp;ask</span>
		<span class="vocabstudy"><ruby><rb>渡</rb><rt>わた</rt></ruby>って&nbsp;cross (over)</span><span class="vocabstudy"><ruby><rb>折</rb><rt>お</rt></ruby>れた&nbsp;turned (toward)</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>の<ruby><rb>家</rb><rt>うち</rt></ruby>&nbsp;someone's house</span><span class="vocabstudy"><ruby><rb>路地</rb><rt>ろじ</rt></ruby>&nbsp;alleyway; lane</span><span class="vocabstudy"><ruby><rb>十間</rb><rt>じゅっけん</rt></ruby>&nbsp;10 ken (about 18 meters; about 20 yards)</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>き<ruby><rb>尽</rb><rt>つく</rt></ruby>して&nbsp;go as far as one can; go to the end (of something)</span><span class="vocabstudy"><ruby><rb>門</rb><rt>もん</rt></ruby>&nbsp;gate</span><span class="vocabstudy"><ruby><rb>手前</rb><rt>てまえ</rt></ruby>&nbsp;just before; short of</span><span class="vocabstudy"><ruby><rb>板橋</rb><rt>いたばし</rt></ruby>&nbsp;wooden-plank bridge</span><span class="vocabstudy"><ruby><rb>渡</rb><rt>わた</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>して&nbsp;crossed back (to)</span><span class="vocabstudy"><ruby><rb>縁</rb><rt>ふち</rt></ruby>&nbsp;edge</span><span class="vocabstudy"><ruby><rb>上</rb><rt>のぼ</rt></ruby>る&nbsp;move upstream</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>は<ruby><rb>通</rb><rt>とお</rt></ruby>らない&nbsp;there were no people about</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い&nbsp;wide open; spacious</span>
		<span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かな&nbsp;quiet</span><span class="vocabstudy"><ruby><rb>秋</rb><rt>あき</rt></ruby>&nbsp;autumn</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>たら&nbsp;emerged (into)</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy">しゃべり<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;became talkative</span>
		<span class="vocabstudy"><ruby><rb>頭痛</rb><rt>ずつう</rt></ruby>&nbsp;headache</span><span class="vocabstudy"><ruby><rb>人形</rb><rt>にんぎょう</rt></ruby>&nbsp;dolls</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;see; look at</span><span class="vocabstudy"><ruby><rb>連中</rb><rt>れんちゅう</rt></ruby>&nbsp;crowd; company</span><span class="vocabstudy"><ruby><rb>下等</rb><rt>かとう</rt></ruby>&nbsp;base; vulgar</span><span class="vocabstudy"><ruby><rb>失礼</rb><rt>しつれい</rt></ruby>&nbsp;slight; impropriety</span>
		<span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;she</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;remain silent</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>&nbsp;eyes</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>げて&nbsp;lifted; raised</span><span class="vocabstudy"><ruby><rb>二重瞼</rb><rt>ふたえまぶた</rt></ruby>&nbsp;contoured eyelids</span><span class="vocabstudy"><ruby><rb>張</rb><rt>は</rt></ruby>り&nbsp;resilience; spirit</span><span class="vocabstudy"><ruby><rb>安心</rb><rt>あんしん</rt></ruby>した&nbsp;was reassured; was relieved</span>
		<span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;said; answered</span>
		<span class="vocabstudy"><ruby><rb>休</rb><rt>やす</rt></ruby>みましょう&nbsp;take a rest</span>
		<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span>
		<span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>く&nbsp;go (on); proceed</span><span class="vocabstudy"><ruby><rb>場所</rb><rt>ばしょ</rt></ruby>&nbsp;place</span>

	</StudyGuide>
);
