// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={102}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>はこういう<span><ruby><rb>場合</rb><rt>ばあい</rt></ruby></span>になると<span><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby></span>に<span><ruby><rb>困</rb><rt>こま</rt></ruby>る</span><span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>である。<span><ruby><rb>咄嗟</rb><rt>とっさ</rt></ruby></span>の<span><ruby><rb>機</rb><rt>き</rt></ruby></span>が<span><ruby><rb>過</rb><rt>す</rt></ruby>ぎて</span>、<span><ruby><rb>頭</rb><rt>あたま</rt></ruby></span>が<span><ruby><rb>冷</rb><rt>ひや</rt></ruby>やかに</span><span><ruby><rb>働</rb><rt>はたら</rt></ruby>きだした</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>、<span><ruby><rb>過去</rb><rt>かこ</rt></ruby></span>を<span><ruby><rb>顧</rb><rt>かえり</rt></ruby>みて</span>、ああ<span><ruby><rb>言</rb><rt>い</rt></ruby>えば</span>よかった、こうすればよかったと<span><ruby><rb>後悔</rb><rt>こうかい</rt></ruby>する</span>。といって、この後悔を<span><ruby><rb>予期</rb><rt>よき</rt></ruby>して</span>、むりに<span><ruby><rb>応急</rb><rt>おうきゅう</rt></ruby>の</span><span><ruby><rb>返事</rb><rt>へんじ</rt></ruby></span>を、さもしぜんらしく<span><ruby><rb>得意</rb><rt>とくい</rt></ruby>に</span><span><ruby><rb>吐</rb><rt>は</rt></ruby>き<ruby><rb>散</rb><rt>ち</rt></ruby>らす</span>ほどに<span><ruby><rb>軽薄</rb><rt>けいはく</rt></ruby></span>ではなかった。だからただ<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>いる。そうして黙っていることがいかにも<span><ruby><rb>半間</rb><rt>はんま</rt></ruby></span>であると<span><ruby><rb>自覚</rb><rt>じかく</rt></ruby></span>している。</p>
		<p><span><ruby><rb>迷える子</rb><rt>ストレイ・シープ</rt></ruby></span>という<span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>はわかったようでもある。またわからないようでもある。わかるわからないはこの言葉の<span><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>よりも、むしろこの言葉を<span><ruby><rb>使</rb><rt>つか</rt></ruby>った</span><span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>の意味である。三四郎は<span>いたずらに</span>女の<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>をながめて黙っていた。すると女は<span><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span>まじめになった。</p>
		<p>「<span><ruby><rb>私</rb><rt>わたし</rt></ruby></span>そんなに<span><ruby><rb>生意気</rb><rt>なまいき</rt></ruby></span>に<span><ruby><rb>見</rb><rt>み</rt></ruby>えます</span>か」</p>
		<p>その<span><ruby><rb>調子</rb><rt>ちょうし</rt></ruby></span>には<span><ruby><rb>弁解</rb><rt>べんかい</rt></ruby></span>の<span><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち</span>がある。三四郎は<span><ruby><rb>意外</rb><rt>いがい</rt></ruby>の</span><span><ruby><rb>感</rb><rt>かん</rt></ruby></span>に<span><ruby><rb>打</rb><rt>う</rt></ruby>たれた</span>。<span><ruby><rb>今</rb><rt>いま</rt></ruby></span>までは<span><ruby><rb>霧</rb><rt>きり</rt></ruby></span>の<span><ruby><rb>中</rb><rt>なか</rt></ruby></span>にいた。霧が<span><ruby><rb>晴</rb><rt>は</rt></ruby>れれば</span>いいと<span><ruby><rb>思</rb><rt>おも</rt></ruby>っていた</span>。この言葉で霧が晴れた。<span><ruby><rb>明瞭</rb><rt>めいりょう</rt></ruby>な</span>女が<span><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。晴れたのが<span><ruby><rb>恨</rb><rt>うら</rt></ruby>めしい</span><span><ruby><rb>気</rb><rt>き</rt></ruby></span>がする。</p>
		<p>三四郎は<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>の<span><ruby><rb>態度</rb><rt>たいど</rt></ruby></span>をもとのような、――<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>の頭の<span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>に<span><ruby><rb>広</rb><rt>ひろ</rt></ruby>がって</span>いる、<span><ruby><rb>澄</rb><rt>す</rt></ruby>む</span>とも<span><ruby><rb>濁</rb><rt>にご</rt></ruby>る</span>とも<span><ruby><rb>片</rb><rt>かた</rt></ruby>づかない</span><span><ruby><rb>空</rb><rt>そら</rt></ruby></span>のような、――意味のあるものにしたかった。けれども、それは女の<span>きげんを<ruby><rb>取</rb><rt>と</rt></ruby>る</span>ための挨拶ぐらいで<span><ruby><rb>戻</rb><rt>もど</rt></ruby>せる</span>ものではないと思った。女は<span><ruby><rb>卒然</rb><rt>そつぜん</rt></ruby>として</span>、</p>
		<p>「じゃ、もう<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>りましょう</span>」と言った。<span><ruby><rb>厭味</rb><rt>いやみ</rt></ruby>のある</span><span><ruby><rb>言</rb><rt>い</rt></ruby>い<ruby><rb>方</rb><rt>かた</rt></ruby></span>ではなかった。ただ三四郎にとって<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>は興味のないものとあきらめるように<span><ruby><rb>静</rb><rt>しず</rt></ruby>かな</span><span><ruby><rb>口調</rb><rt>くちょう</rt></ruby></span>であった。</p>
		<p>空はまた<span><ruby><rb>変</rb><rt>かわ</rt></ruby>ってきた</span>。<span><ruby><rb>風</rb><rt>かぜ</rt></ruby></span>が<span><ruby><rb>遠</rb><rt>とお</rt></ruby>くから</span><span><ruby><rb>吹</rb><rt>ふ</rt></ruby>いて</span>くる。広い<span><ruby><rb>畑</rb><rt>はたけ</rt></ruby></span>の上には<span><ruby><rb>日</rb><rt>ひ</rt></ruby></span>が<span><ruby><rb>限</rb><rt>かぎ</rt></ruby>って</span>、見ていると、<span><ruby><rb>寒</rb><rt>さむ</rt></ruby>い</span>ほど<span><ruby><rb>寂</rb><rt>さび</rt></ruby>しい</span>。<span><ruby><rb>草</rb><rt>くさ</rt></ruby></span>からあがる<span><ruby><rb>地息</rb><rt>じいき</rt></ruby></span>でからだは<span><ruby><rb>冷</rb><rt>ひ</rt></ruby>えて</span>いた。気がつけば、こんな<span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>に、よく今までべっとりすわっていられたものだと思う。自分<span><ruby><rb>一人</rb><rt>ひとり</rt></ruby></span>なら、とうにどこかへ<span><ruby><rb>行</rb><rt>い</rt></ruby>って</span>しまった<span>に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない</span>。美禰子も――美禰子はこんな所へすわる女かもしれない。</p>

		<h3 class="section">Rough translation</h3>
		<p>Sanshirō never had the right answer in situations like this. Later, when the chance had passed and he could think calmly, he would reflect with regret on the things he wished he'd said. Nevertheless, he was too sincere to circumvent this inevitable regret. He couldn't just spew out an offhand answer with feigned confidence, so instead he remained silent. Yet he was keenly aware of the inadequacy in his silence.</p> 
		<p>He felt he understood what 'stray sheep' meant. At the same time, he didn't understand. His hesitancy was less about the meaning of these words, but rather about the meaning of Mineko's use of these words. To push back a little, Sanshirō remained silent and looked directly into her eyes.</p>
		<p>Mineko suddenly grew serious. "Do I come across as affected?"</p>
		<p>In her tone was a sense of exculpation. Sanshirō was struck by an unexpected sensation. Until now he'd been wandering in a mist, wishing he could see clearly. Her words had cleared away the mist, and before him was a woman in plain view. The clarity left him dissatisfied.</p>
		<p>He preferred Mineko as she'd seemed before, intriguing and mysterious, clear and yet muddy, like the sky above their heads that defied description. However, he knew that no clever words on his part could restore what was lost.</p>
		<p>Mineko said abruptly, "We should be going." There was no bitterness in her voice. Her tone was modest, as though resigned to the fact that her spell over Sanshirō had been broken.</p>
		<p>The sky had changed again. A wind had blown up from the distance. Under the weak light that fell on it, the field looked cold and barren. The dampness of the ground, rising up through the grass, brought a chill. Sanshirō wondered how they'd stayed in this place for so long. If he'd been alone he certainly would have moved on sooner. Mineko too -- or maybe Mineko would have stayed.</p>        

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>場合</rb><rt>ばあい</rt></ruby>&nbsp;situation; circumstances</span><span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>&nbsp;(appropriate) response</span><span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>る&nbsp;struggle (with)</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man</span><span class="vocabstudy"><ruby><rb>咄嗟</rb><rt>とっさ</rt></ruby>&nbsp;instant; moment</span><span class="vocabstudy"><ruby><rb>機</rb><rt>き</rt></ruby>&nbsp;chance; opportunity</span><span class="vocabstudy"><ruby><rb>過</rb><rt>す</rt></ruby>ぎて&nbsp;pass; be over</span><span class="vocabstudy"><ruby><rb>頭</rb><rt>あたま</rt></ruby>&nbsp;head; mind</span><span class="vocabstudy"><ruby><rb>冷</rb><rt>ひや</rt></ruby>やかに&nbsp;objectively; with composure</span><span class="vocabstudy"><ruby><rb>働</rb><rt>はたら</rt></ruby>きだした&nbsp;began to work</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; occasion</span><span class="vocabstudy"><ruby><rb>過去</rb><rt>かこ</rt></ruby>&nbsp;past</span><span class="vocabstudy"><ruby><rb>顧</rb><rt>かえり</rt></ruby>みて&nbsp;look back at; reflect on</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>えば&nbsp;said; responded</span><span class="vocabstudy"><ruby><rb>後悔</rb><rt>こうかい</rt></ruby>する&nbsp;regret</span><span class="vocabstudy"><ruby><rb>予期</rb><rt>よき</rt></ruby>して&nbsp;anticipate</span><span class="vocabstudy"><ruby><rb>応急</rb><rt>おうきゅう</rt></ruby>の&nbsp;stopgap; makeshift</span><span class="vocabstudy"><ruby><rb>返事</rb><rt>へんじ</rt></ruby>&nbsp;response; answer</span><span class="vocabstudy"><ruby><rb>得意</rb><rt>とくい</rt></ruby>に&nbsp;proudly; with confidence</span><span class="vocabstudy"><ruby><rb>吐</rb><rt>は</rt></ruby>き<ruby><rb>散</rb><rt>ち</rt></ruby>らす&nbsp;spew forth</span><span class="vocabstudy"><ruby><rb>軽薄</rb><rt>けいはく</rt></ruby>&nbsp;frivolous; superficial</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;remain silent</span><span class="vocabstudy"><ruby><rb>半間</rb><rt>はんま</rt></ruby>&nbsp;inadequate; lacking (= <ruby><rb>中途半端</rb><rt>ちゅうとはんぱ</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>自覚</rb><rt>じかく</rt></ruby>&nbsp;(self-) awareness; insight</span>
		<span class="vocabstudy"><ruby><rb>迷える子</rb><rt>ストレイ・シープ</rt></ruby>&nbsp;stray sheep</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words; expression</span><span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning</span><span class="vocabstudy"><ruby><rb>使</rb><rt>つか</rt></ruby>った&nbsp;used</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;young lady</span><span class="vocabstudy">いたずらに&nbsp;for effect</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>&nbsp;I</span><span class="vocabstudy"><ruby><rb>生意気</rb><rt>なまいき</rt></ruby>&nbsp;impertinent; affected</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>えます&nbsp;appear; seem</span>
		<span class="vocabstudy"><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>&nbsp;tone</span><span class="vocabstudy"><ruby><rb>弁解</rb><rt>べんかい</rt></ruby>&nbsp;exculpation; apology</span><span class="vocabstudy"><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち&nbsp;feeling; mood</span><span class="vocabstudy"><ruby><rb>意外</rb><rt>いがい</rt></ruby>の&nbsp;unexpected</span><span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>&nbsp;feeling; sense</span><span class="vocabstudy"><ruby><rb>打</rb><rt>う</rt></ruby>たれた&nbsp;be struck by</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; the present</span><span class="vocabstudy"><ruby><rb>霧</rb><rt>きり</rt></ruby>&nbsp;fog; mist</span><span class="vocabstudy"><ruby><rb>中</rb><rt>なか</rt></ruby>&nbsp;inside; midst</span><span class="vocabstudy"><ruby><rb>晴</rb><rt>は</rt></ruby>れれば&nbsp;clear up (weather)</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>っていた&nbsp;had thought</span><span class="vocabstudy"><ruby><rb>明瞭</rb><rt>めいりょう</rt></ruby>な&nbsp;clear; plain; evident</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;appeared</span><span class="vocabstudy"><ruby><rb>恨</rb><rt>うら</rt></ruby>めしい&nbsp;regrettable; unfortunate</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>&nbsp;feeling</span>
		<span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>態度</rb><rt>たいど</rt></ruby>&nbsp;manner; behavior</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;above</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>がって&nbsp;spread out</span><span class="vocabstudy"><ruby><rb>澄</rb><rt>す</rt></ruby>む&nbsp;be clear</span><span class="vocabstudy"><ruby><rb>濁</rb><rt>にご</rt></ruby>る&nbsp;be muddied</span><span class="vocabstudy"><ruby><rb>片</rb><rt>かた</rt></ruby>づかない&nbsp;defy description</span><span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby>&nbsp;sky</span><span class="vocabstudy">きげんを<ruby><rb>取</rb><rt>と</rt></ruby>る&nbsp;curry favor with; humor (a person)</span><span class="vocabstudy"><ruby><rb>戻</rb><rt>もど</rt></ruby>せる&nbsp;put back; restore (to a previous state)</span><span class="vocabstudy"><ruby><rb>卒然</rb><rt>そつぜん</rt></ruby>として&nbsp;abruptly</span>
		<span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>りましょう&nbsp;return; go back</span><span class="vocabstudy"><ruby><rb>厭味</rb><rt>いやみ</rt></ruby>のある&nbsp;disagreeable</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>い<ruby><rb>方</rb><rt>かた</rt></ruby>&nbsp;manner of speaking</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かな&nbsp;quiet</span><span class="vocabstudy"><ruby><rb>口調</rb><rt>くちょう</rt></ruby>&nbsp;tone (of voice)</span>
		<span class="vocabstudy"><ruby><rb>変</rb><rt>かわ</rt></ruby>ってきた&nbsp;changed; transformed itself</span><span class="vocabstudy"><ruby><rb>風</rb><rt>かぜ</rt></ruby>&nbsp;wind</span><span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くから&nbsp;from far away</span><span class="vocabstudy"><ruby><rb>吹</rb><rt>ふ</rt></ruby>いて&nbsp;blow</span><span class="vocabstudy"><ruby><rb>畑</rb><rt>はたけ</rt></ruby>&nbsp;(farm) field</span><span class="vocabstudy"><ruby><rb>日</rb><rt>ひ</rt></ruby>&nbsp;sunlight</span><span class="vocabstudy"><ruby><rb>限</rb><rt>かぎ</rt></ruby>って&nbsp;be limited</span><span class="vocabstudy"><ruby><rb>寒</rb><rt>さむ</rt></ruby>い&nbsp;cold; frigid</span><span class="vocabstudy"><ruby><rb>寂</rb><rt>さび</rt></ruby>しい&nbsp;lonely; barren</span><span class="vocabstudy"><ruby><rb>草</rb><rt>くさ</rt></ruby>&nbsp;grass</span><span class="vocabstudy"><ruby><rb>地息</rb><rt>じいき</rt></ruby>&nbsp;dampness from the ground</span><span class="vocabstudy"><ruby><rb>冷</rb><rt>ひ</rt></ruby>えて&nbsp;be chilled</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>&nbsp;alone</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>って&nbsp;go; leave (for)</span><span class="vocabstudy">に<ruby><rb>違</rb><rt>ちが</rt></ruby>いない&nbsp;no doubt ...</span>

	</StudyGuide>
);
