// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={98}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>一丁</rb><rt>いっちょう</rt></ruby></span>ばかり<span><ruby><rb>来</rb><rt>き</rt></ruby>た</span>。また<span><ruby><rb>橋</rb><rt>はし</rt></ruby></span>がある。<span><ruby><rb>一尺</rb><rt>いっしゃく</rt></ruby></span><span>に<ruby><rb>足</rb><rt>た</rt></ruby>らない</span><span><ruby><rb>古板</rb><rt>ふるいた</rt></ruby></span>を<span><ruby><rb>造作</rb><rt>ぞうさ</rt></ruby>なく</span><span><ruby><rb>渡</rb><rt>わた</rt></ruby>した</span><span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>を、<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は<span><ruby><rb>大</rb><rt>おお</rt></ruby>またに</span><span><ruby><rb>歩</rb><rt>ある</rt></ruby>いた</span>。<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>もつづいて<span><ruby><rb>通</rb><rt>とお</rt></ruby>った</span>。<span><ruby><rb>待</rb><rt>ま</rt></ruby>ち<ruby><rb>合</rb><rt>あ</rt></ruby>わせた</span>三四郎の<span><ruby><rb>目</rb><rt>め</rt></ruby></span>には、女の<span><ruby><rb>足</rb><rt>あし</rt></ruby></span>が<span><ruby><rb>常</rb><rt>つね</rt></ruby>の</span><span><ruby><rb>大地</rb><rt>だいち</rt></ruby></span>を<span><ruby><rb>踏</rb><rt>ふ</rt></ruby>む</span>と<span><ruby><rb>同</rb><rt>おな</rt></ruby>じように</span><span><ruby><rb>軽</rb><rt>かる</rt></ruby>く</span>みえた。この女はすなおな足をまっすぐに<span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>へ<span><ruby><rb>運</rb><rt>はこ</rt></ruby>ぶ</span>。わざと女らしく<span><ruby><rb>甘</rb><rt>あま</rt></ruby>えた</span><span><ruby><rb>歩</rb><rt>ある</rt></ruby>き<ruby><rb>方</rb><rt>かた</rt></ruby></span>をしない。したがってむやみにこっちから<span><ruby><rb>手</rb><rt>て</rt></ruby>を<ruby><rb>貸</rb><rt>か</rt></ruby>す</span>わけにはいかない。</p>
		<p><span><ruby><rb>向</rb><rt>む</rt></ruby>こう</span>に<span><ruby><rb>藁</rb><rt>わら</rt></ruby><ruby><rb>屋根</rb><rt>やね</rt></ruby></span>がある。屋根の<span><ruby><rb>下</rb><rt>した</rt></ruby></span>が<span><ruby><rb>一面</rb><rt>いちめん</rt></ruby>に</span><span><ruby><rb>赤</rb><rt>あか</rt></ruby>い</span>。<span><ruby><rb>近寄</rb><rt>ちかよ</rt></ruby>って</span><span><ruby><rb>見</rb><rt>み</rt></ruby>る</span>と、<span><ruby><rb>唐辛子</rb><rt>とうがらし</rt></ruby></span>を<span><ruby><rb>干</rb><rt>ほ</rt></ruby>した</span>のであった。女はこの赤いものが、唐辛子であると<span><ruby><rb>見分</rb><rt>みわ</rt></ruby>け</span>のつくところまで来て<span><ruby><rb>留</rb><rt>と</rt></ruby>まった</span>。</p>
		<p>「<span><ruby><rb>美</rb><rt>うつく</rt></ruby>しい</span>こと」と<span><ruby><rb>言</rb><rt>い</rt></ruby>いながら</span>、<span><ruby><rb>草</rb><rt>くさ</rt></ruby></span>の上に<span><ruby><rb>腰</rb><rt>こし</rt></ruby>をおろした</span>。草は<span><ruby><rb>小川</rb><rt>おがわ</rt></ruby></span>の<span><ruby><rb>縁</rb><rt>ふち</rt></ruby></span>にわずかな<span><ruby><rb>幅</rb><rt>はば</rt></ruby></span>をはえているのみである。それすら<span><ruby><rb>夏</rb><rt>なつ</rt></ruby></span>の<span><ruby><rb>半</rb><rt>なか</rt></ruby>ば</span>のように<span><ruby><rb>青</rb><rt>あお</rt></ruby>く</span>はない。<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>は<span><ruby><rb>派手</rb><rt>はで</rt></ruby>な</span><span><ruby><rb>着物</rb><rt>きもの</rt></ruby></span>のよごれるのをまるで<span><ruby><rb>苦</rb><rt>く</rt></ruby>にしていない</span>。</p>
		<p>「もう<span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span><ruby><rb>歩</rb><rt>ある</rt></ruby>けませんか</span>」と三四郎は<span><ruby><rb>立</rb><rt>た</rt></ruby>ちながら</span>、<span><ruby><rb>促</rb><rt>うなが</rt></ruby>す</span>ように言ってみた。</p>
		<p>「ありがとう。これでたくさん」</p>
		<p>「やっぱり<span class="vocabstudy"><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち</span>が<span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>い</span>ですか」</p>
		<p>「あんまり<span class="vocabstudy"><ruby><rb>疲</rb><rt>つか</rt></ruby>れた</span>から」</p>
		<p>三四郎もとうとうきたない草の上にすわった。美禰子と三四郎の<span class="vocabstudy"><ruby><rb>間</rb><rt>あいだ</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>四尺</rb><rt>よんしゃく</rt></ruby></span>ばかり<span class="vocabstudy"><ruby><rb>離</rb><rt>はな</rt></ruby>れて</span>いる。<span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>の足の下には<span class="vocabstudy"><ruby><rb>小</rb><rt>ちい</rt></ruby>さな</span><span class="vocabstudy"><ruby><rb>川</rb><rt>かわ</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>流</rb><rt>なが</rt></ruby>れて</span>いる。<span class="vocabstudy"><ruby><rb>秋</rb><rt>あき</rt></ruby></span>になって<span class="vocabstudy"><ruby><rb>水</rb><rt>みず</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちた</span>から<span class="vocabstudy"><ruby><rb>浅</rb><rt>あさ</rt></ruby>い</span>。<span class="vocabstudy"><ruby><rb>角</rb><rt>かど</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た</span><span class="vocabstudy"><ruby><rb>石</rb><rt>いし</rt></ruby></span>の上に<span class="vocabstudy"><ruby><rb>鶺鴒</rb><rt>せきれい</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>一羽</rb><rt>いちわ</rt></ruby></span>とまったくらいである。三四郎は水の中をながめていた。水が<span class="vocabstudy"><ruby><rb>次第</rb><rt>しだい</rt></ruby>に</span><span class="vocabstudy"><ruby><rb>濁</rb><rt>にご</rt></ruby>って</span>くる。見ると<span class="vocabstudy"><ruby><rb>川上</rb><rt>かわかみ</rt></ruby></span>で<span class="vocabstudy"><ruby><rb>百姓</rb><rt>ひゃくしょう</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>大根</rb><rt>だいこん</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>洗</rb><rt>あら</rt></ruby>って</span>いた。美禰子の<span class="vocabstudy"><ruby><rb>視線</rb><rt>しせん</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くの</span>向こうにある。向こうは<span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>畑</rb><rt>はたけ</rt></ruby></span>で、畑の<span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>森</rb><rt>もり</rt></ruby></span>で森の上が<span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby></span>になる。空の<span class="vocabstudy"><ruby><rb>色</rb><rt>いろ</rt></ruby></span>がだんだん<span class="vocabstudy"><ruby><rb>変</rb><rt>かわ</rt></ruby>って</span>くる。</p>

		<h3 class="section">Rough translation</h3>
		<p>They walked a hundred meters further to the next bridge. This one was nothing more than an old plank, not very wide, that had been laid over the stream. Sanshirō crossed with broad steps, and Mineko followed. She stepped lightly, in her usual manner, as though treading on solid ground. Her feet were steady as she placed one before the other. She didn't feign female vulnerability, and thus offered no pretext for chivalrous assistance.</p>
		<p>In the distance was a thatched hut. Beneath its roof was a solid wall of red. Drawing closer, they saw that the red was chili peppers hung out to dry. At this distance, where the peppers were just discernible, Mineko stopped.</p>
		<p>"Beautiful!" As she spoke, she sat down on the grass. The grass grew only on a narrow strip at the edge of the stream. It was no longer green as in the height of summer. Mineko showed no concern for her colorful kimono.</p>
		<p>"Can you walk a little further?" Sanshirō remained standing and pressed her a little.</p>
		<p>"No, thank you. This is far enough."</p>
		<p>"You're still not feeling well?"</p>
		<p>"I'm feeling worn down."</p>
		<p>Sanshirō joined her by seating himself in the coarse grass, about a meter away. The small stream flowed by below their feet. It was shallow in the dry of autumn. A wagtail had lighted on an exposed corner of stone protruding from the water. Sanshirō gazed into the current. The water gradually clouded, and he saw that a farmer was rinsing daikon upstream. Mineko gazed into the distance. Beyond the stream was a wide field. At the far end of the field were woods, and over the woods hung the sky. The hue of the sky was slowly shifting.</p>  

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>一丁</rb><rt>いっちょう</rt></ruby>&nbsp;1 chō (about 110 meters; about 120 yards)</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came; progressed</span><span class="vocabstudy"><ruby><rb>橋</rb><rt>はし</rt></ruby>&nbsp;bridge</span><span class="vocabstudy"><ruby><rb>一尺</rb><rt>いっしゃく</rt></ruby>&nbsp;1 shaku (about 30cm; about a foot)</span><span class="vocabstudy">に<ruby><rb>足</rb><rt>た</rt></ruby>らない&nbsp;not even ...; less than ...</span><span class="vocabstudy"><ruby><rb>古板</rb><rt>ふるいた</rt></ruby>&nbsp;old board; old plank</span><span class="vocabstudy"><ruby><rb>造作</rb><rt>ぞうさ</rt></ruby>なく&nbsp;roughly; simply</span><span class="vocabstudy"><ruby><rb>渡</rb><rt>わた</rt></ruby>した&nbsp;laid across</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;over; on top of</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>またに&nbsp;with a long stride</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>いた&nbsp;walked; stepped</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;the young lady (Mineko)</span><span class="vocabstudy"><ruby><rb>通</rb><rt>とお</rt></ruby>った&nbsp;passed (over)</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>ち<ruby><rb>合</rb><rt>あ</rt></ruby>わせた&nbsp;waited for (someone)</span><span class="vocabstudy"><ruby><rb>目</rb><rt>め</rt></ruby>&nbsp;eyes; view</span><span class="vocabstudy"><ruby><rb>足</rb><rt>あし</rt></ruby>&nbsp;feet</span><span class="vocabstudy"><ruby><rb>常</rb><rt>つね</rt></ruby>の&nbsp;ordinary; usual</span><span class="vocabstudy"><ruby><rb>大地</rb><rt>だいち</rt></ruby>&nbsp;solid ground</span><span class="vocabstudy"><ruby><rb>踏</rb><rt>ふ</rt></ruby>む&nbsp;step on; tread on</span><span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じように&nbsp;in the same manner</span><span class="vocabstudy"><ruby><rb>軽</rb><rt>かる</rt></ruby>く&nbsp;light</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;forward</span><span class="vocabstudy"><ruby><rb>運</rb><rt>はこ</rt></ruby>ぶ&nbsp;carry; move</span><span class="vocabstudy"><ruby><rb>甘</rb><rt>あま</rt></ruby>えた&nbsp;dependent on the help of another</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>き<ruby><rb>方</rb><rt>かた</rt></ruby>&nbsp;manner of walking</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>を<ruby><rb>貸</rb><rt>か</rt></ruby>す&nbsp;lend a hand; assist</span>
		<span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう&nbsp;beyond; (in) the distance</span><span class="vocabstudy"><ruby><rb>藁</rb><rt>わら</rt></ruby><ruby><rb>屋根</rb><rt>やね</rt></ruby>&nbsp;thatched roof</span><span class="vocabstudy"><ruby><rb>下</rb><rt>した</rt></ruby>&nbsp;below</span><span class="vocabstudy"><ruby><rb>一面</rb><rt>いちめん</rt></ruby>に&nbsp;over the whole surface</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>い&nbsp;red</span><span class="vocabstudy"><ruby><rb>近寄</rb><rt>ちかよ</rt></ruby>って&nbsp;approach; draw near to</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>る&nbsp;look; see</span><span class="vocabstudy"><ruby><rb>唐辛子</rb><rt>とうがらし</rt></ruby>&nbsp;chili peppers</span><span class="vocabstudy"><ruby><rb>干</rb><rt>ほ</rt></ruby>した&nbsp;dried</span><span class="vocabstudy"><ruby><rb>見分</rb><rt>みわ</rt></ruby>け&nbsp;distinction; recognition</span><span class="vocabstudy"><ruby><rb>留</rb><rt>と</rt></ruby>まった&nbsp;stopped</span>
		<span class="vocabstudy"><ruby><rb>美</rb><rt>うつく</rt></ruby>しい&nbsp;beautiful</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>いながら&nbsp;say; remark</span><span class="vocabstudy"><ruby><rb>草</rb><rt>くさ</rt></ruby>&nbsp;grass</span><span class="vocabstudy"><ruby><rb>腰</rb><rt>こし</rt></ruby>をおろした&nbsp;sat down; lowered oneself (to sit)</span><span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby>&nbsp;small river; stream</span><span class="vocabstudy"><ruby><rb>縁</rb><rt>ふち</rt></ruby>&nbsp;edge</span><span class="vocabstudy"><ruby><rb>幅</rb><rt>はば</rt></ruby>&nbsp;width</span><span class="vocabstudy"><ruby><rb>夏</rb><rt>なつ</rt></ruby>&nbsp;summer</span><span class="vocabstudy"><ruby><rb>半</rb><rt>なか</rt></ruby>ば&nbsp;middle</span><span class="vocabstudy"><ruby><rb>青</rb><rt>あお</rt></ruby>く&nbsp;green</span><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>派手</rb><rt>はで</rt></ruby>な&nbsp;bright; colorful</span><span class="vocabstudy"><ruby><rb>着物</rb><rt>きもの</rt></ruby>&nbsp;kimono</span><span class="vocabstudy"><ruby><rb>苦</rb><rt>く</rt></ruby>にしていない&nbsp;had no concern for</span>
		<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>歩</rb><rt>ある</rt></ruby>けませんか&nbsp;can you walk?</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ちながら&nbsp;standing</span><span class="vocabstudy"><ruby><rb>促</rb><rt>うなが</rt></ruby>す&nbsp;press; prompt</span>
		<span class="vocabstudy"><ruby><rb>心持</rb><rt>こころも</rt></ruby>ち&nbsp;feeling</span><span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>い&nbsp;not well</span>
		<span class="vocabstudy"><ruby><rb>疲</rb><rt>つか</rt></ruby>れた&nbsp;be worn out</span>
		<span class="vocabstudy"><ruby><rb>間</rb><rt>あいだ</rt></ruby>&nbsp;interval; space between</span><span class="vocabstudy"><ruby><rb>四尺</rb><rt>よんしゃく</rt></ruby>&nbsp;4 shaku (about 1.2 meters; about 4 feet)</span><span class="vocabstudy"><ruby><rb>離</rb><rt>はな</rt></ruby>れて&nbsp;be separated (by)</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>小</rb><rt>ちい</rt></ruby>さな&nbsp;small</span><span class="vocabstudy"><ruby><rb>川</rb><rt>かわ</rt></ruby>&nbsp;stream</span><span class="vocabstudy"><ruby><rb>流</rb><rt>なが</rt></ruby>れて&nbsp;flow</span><span class="vocabstudy"><ruby><rb>秋</rb><rt>あき</rt></ruby>&nbsp;autumn</span><span class="vocabstudy"><ruby><rb>水</rb><rt>みず</rt></ruby>&nbsp;water (level)</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちた&nbsp;dropped; fallen</span><span class="vocabstudy"><ruby><rb>浅</rb><rt>あさ</rt></ruby>い&nbsp;shallow</span><span class="vocabstudy"><ruby><rb>角</rb><rt>かど</rt></ruby>&nbsp;corner</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;stick out; protrude</span><span class="vocabstudy"><ruby><rb>石</rb><rt>いし</rt></ruby>&nbsp;rock</span><span class="vocabstudy"><ruby><rb>鶺鴒</rb><rt>せきれい</rt></ruby>&nbsp;wagtail (bird)</span><span class="vocabstudy"><ruby><rb>一羽</rb><rt>いちわ</rt></ruby>&nbsp;one (bird)</span><span class="vocabstudy"><ruby><rb>次第</rb><rt>しだい</rt></ruby>に&nbsp;gradually</span><span class="vocabstudy"><ruby><rb>濁</rb><rt>にご</rt></ruby>って&nbsp;grow muddy; become cloudy</span><span class="vocabstudy"><ruby><rb>川上</rb><rt>かわかみ</rt></ruby>&nbsp;upstream</span><span class="vocabstudy"><ruby><rb>百姓</rb><rt>ひゃくしょう</rt></ruby>&nbsp;farmer</span><span class="vocabstudy"><ruby><rb>大根</rb><rt>だいこん</rt></ruby>&nbsp;daikon (white radish)</span><span class="vocabstudy"><ruby><rb>洗</rb><rt>あら</rt></ruby>って&nbsp;wash; rinse</span><span class="vocabstudy"><ruby><rb>視線</rb><rt>しせん</rt></ruby>&nbsp;line of sight; gaze</span><span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>くの&nbsp;distant</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い&nbsp;wide</span><span class="vocabstudy"><ruby><rb>畑</rb><rt>はたけ</rt></ruby>&nbsp;(farm) field</span><span class="vocabstudy"><ruby><rb>先</rb><rt>さき</rt></ruby>&nbsp;tip; end</span><span class="vocabstudy"><ruby><rb>森</rb><rt>もり</rt></ruby>&nbsp;woods</span><span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby>&nbsp;sky</span><span class="vocabstudy"><ruby><rb>色</rb><rt>いろ</rt></ruby>&nbsp;color</span><span class="vocabstudy"><ruby><rb>変</rb><rt>かわ</rt></ruby>って&nbsp;change; be transformed</span>

	</StudyGuide>
);
