// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={94}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「<span>もう<ruby><rb>一遍</rb><rt>いっぺん</rt></ruby></span><span><ruby><rb>手紙</rb><rt>てがみ</rt></ruby></span>を<span><ruby><rb>出</rb><rt>だ</rt></ruby>してご<ruby><rb>覧</rb><rt>らん</rt></ruby></span>な」と<span><ruby><rb>母</rb><rt>はは</rt></ruby></span>がいった。</p>
		<p><span><ruby><rb>役</rb><rt>やく</rt></ruby>に<ruby><rb>立</rb><rt>た</rt></ruby>たない</span>手紙を<span><ruby><rb>何通</rb><rt>なんつう</rt></ruby></span><span><ruby><rb>書</rb><rt>か</rt></ruby>こう</span>と、それが母の<span><ruby><rb>慰安</rb><rt>いあん</rt></ruby></span>になるなら、<span><ruby><rb>手数</rb><rt>てすう</rt></ruby></span>を<span><ruby><rb>厭</rb><rt>いと</rt></ruby>う</span>ような<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>ではなかった。けれどもこういう<span><ruby><rb>用件</rb><rt>ようけん</rt></ruby></span>で<span><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>にせまるのは私の<span><ruby><rb>苦痛</rb><rt>くつう</rt></ruby></span>であった。私は<span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>に<span><ruby><rb>叱</rb><rt>しか</rt></ruby>られたり</span>、母の<span><ruby><rb>機嫌</rb><rt>きげん</rt></ruby></span>を<span><ruby><rb>損</rb><rt>そん</rt></ruby>じたり</span>するよりも、先生から<span><ruby><rb>見下</rb><rt>みさ</rt></ruby>げられる</span>のを<span><ruby><rb>遥</rb><rt>はる</rt></ruby>かに</span><span><ruby><rb>恐</rb><rt>おそ</rt></ruby>れて</span>いた。あの<span><ruby><rb>依頼</rb><rt>いらい</rt></ruby></span><span>に<ruby><rb>対</rb><rt>たい</rt></ruby>して</span><span><ruby><rb>今</rb><rt>いま</rt></ruby></span>まで<span><ruby><rb>返事</rb><rt>へんじ</rt></ruby></span>の<span><ruby><rb>貰</rb><rt>もら</rt></ruby>えない</span>のも、あるいはそうした<span><ruby><rb>訳</rb><rt>わけ</rt></ruby></span>からじゃないかしらという<span><ruby><rb>邪推</rb><rt>じゃすい</rt></ruby></span>もあった。</p>
		<p>「手紙を書くのは<span><ruby><rb>訳</rb><rt>わけ</rt></ruby>はない</span>ですが、こういう<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>は<span><ruby><rb>郵便</rb><rt>ゆうびん</rt></ruby></span>じゃとても<span><ruby><rb>埒</rb><rt>らち</rt></ruby>は<ruby><rb>明</rb><rt>あ</rt></ruby>きません</span>よ。どうしても<span><ruby><rb>自分</rb><rt>じぶん</rt></ruby></span>で<span><ruby><rb>東京</rb><rt>とうきょう</rt></ruby></span>へ<span><ruby><rb>出</rb><rt>で</rt></ruby>て</span>、じかに<span><ruby><rb>頼</rb><rt>たの</rt></ruby>んで</span><span><ruby><rb>廻</rb><rt>まわ</rt></ruby>らなくっちゃ</span>」</p>
		<p>「だって<span>お<ruby><rb>父</rb><rt>とう</rt></ruby>さん</span>があの<span><ruby><rb>様子</rb><rt>ようす</rt></ruby></span>じゃ、<span>お<ruby><rb>前</rb><rt>まえ</rt></ruby></span>、いつ東京へ出られるか<span><ruby><rb>分</rb><rt>わか</rt></ruby>らない</span>じゃないか」</p>
		<p>「だから出やしません。<span><ruby><rb>癒</rb><rt>なお</rt></ruby>る</span>とも癒らないとも<span><ruby><rb>片付</rb><rt>かたづ</rt></ruby>かないうち</span>は、ちゃんとこうしているつもりです」</p>
		<p>「そりゃ<span><ruby><rb>解</rb><rt>わか</rt></ruby>り<ruby><rb>切</rb><rt>き</rt></ruby>った</span><span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>だね。今にもむずかしいという<span><ruby><rb>大病人</rb><rt>だいびょうにん</rt></ruby></span>を<span><ruby><rb>放</rb><rt>ほう</rt></ruby>ちらかして</span>おいて、<span><ruby><rb>誰</rb><rt>だれ</rt></ruby></span>が<span><ruby><rb>勝手</rb><rt>かって</rt></ruby>に</span>東京へなんか<span><ruby><rb>行</rb><rt>い</rt></ruby>ける</span>ものかね」</p>
		<p>私は<span><ruby><rb>始</rb><rt>はじ</rt></ruby>め</span><span><ruby><rb>心</rb><rt>こころ</rt></ruby>のなかで</span>、<span><ruby><rb>何</rb><rt>なに</rt></ruby>も</span><span><ruby><rb>知</rb><rt>し</rt></ruby>らない</span>母を<span><ruby><rb>憐</rb><rt>あわ</rt></ruby>れんだ</span>。しかし母がなぜこんな<span><ruby><rb>問題</rb><rt>もんだい</rt></ruby></span>をこの<span>ざわざわした</span><span><ruby><rb>際</rb><rt>さい</rt></ruby></span>に<span><ruby><rb>持</rb><rt>も</rt></ruby>ち<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>のか<span><ruby><rb>理解</rb><rt>りかい</rt></ruby>できなかった</span>。私が父の<span><ruby><rb>病気</rb><rt>びょうき</rt></ruby></span>をよそに、<span><ruby><rb>静</rb><rt>しず</rt></ruby>かに</span><span><ruby><rb>坐</rb><rt>すわ</rt></ruby>ったり</span><span><ruby><rb>書見</rb><rt>しょけん</rt></ruby>したり</span>する<span><ruby><rb>余裕</rb><rt>よゆう</rt></ruby></span>のあるごとくに、母も<span><ruby><rb>眼</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby></span>の<span><ruby><rb>病人</rb><rt>びょうにん</rt></ruby></span>を<span><ruby><rb>忘</rb><rt>わす</rt></ruby>れて</span>、<span><ruby><rb>外</rb><rt>ほか</rt></ruby>の</span>事を<span><ruby><rb>考</rb><rt>かんが</rt></ruby>える</span>だけ、<span><ruby><rb>胸</rb><rt>むね</rt></ruby></span>に<span><ruby><rb>空地</rb><rt>すきま</rt></ruby></span>があるのかしらと<span><ruby><rb>疑</rb><rt>うたぐ</rt></ruby>った</span>。その<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>「<span><ruby><rb>実</rb><rt>じつ</rt></ruby>はね</span>」と母が<span>いい<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>
		<p>「実はお父さんの<span><ruby><rb>生</rb><rt>い</rt></ruby>きてお<ruby><rb>出</rb><rt>いで</rt></ruby></span>のうちに、お前の<span><ruby><rb>口</rb><rt>くち</rt></ruby></span>が<span><ruby><rb>極</rb><rt>きま</rt></ruby>ったら</span>さぞ<span><ruby><rb>安心</rb><rt>あんしん</rt></ruby>なさる</span>だろうと<span><ruby><rb>思</rb><rt>おも</rt></ruby>う</span>んだがね。この様子じゃ、とても<span><ruby><rb>間</rb><rt>ま</rt></ruby>に<ruby><rb>合</rb><rt>あ</rt></ruby>わない</span><span>かも<ruby><rb>知</rb><rt>し</rt></ruby>れない</span>けれども、それにしても、まだああやって<span><ruby><rb>口</rb><rt>くち</rt></ruby>も<ruby><rb>慥</rb><rt>たし</rt></ruby>か</span>なら<span><ruby><rb>気</rb><rt>き</rt></ruby>も<ruby><rb>慥</rb><rt>たし</rt></ruby>か</span>なんだから、ああしてお出のうちに<span><ruby><rb>喜</rb><rt>よろこ</rt></ruby>ばして</span><span><ruby><rb>上</rb><rt>あ</rt></ruby>げる</span>ように<span><ruby><rb>親孝行</rb><rt>おやこうこう</rt></ruby></span>をおしな」</p>
		<p>憐れな私は親孝行のできない<span><ruby><rb>境遇</rb><rt>きょうぐう</rt></ruby></span>にいた。私はついに<span><ruby><rb>一行</rb><rt>いちぎょう</rt></ruby></span>の手紙も先生に出さなかった。</p>

		<h3 class="section">Rough translation</h3>
		<p>"Why not try writing once more?"</p>
		<p>I would gladly write any number of letters, even to no avail, for my mother's sake. However, the last thing I wanted to do was badger Sensei. Much more than my father's scolding or my mother's disappointment, I feared the loss of Sensei's respect. I was worried I might have perturbed him already, and hence his silence with respect to my request.</p>
		<p>"It's easy enough to write a letter, but this isn't something one manages by post. I'll need to get to Tōkyō and do some legwork."</p>
		<p>"True, but with your father's condition there's no telling when that might be."</p>
		<p>"I'm not going anywhere at present. Until we have an outcome, recovery or otherwise, I fully intend to stay put."</p>
		<p>"I should think so. One can't leave a man in your father's state to pursue one's interests in Tōkyō."</p>
		<p>At first, I was sympathetic toward my mother and her lack of worldly experience. I couldn't understand, though, why she insisted on raising this subject again at this time. I wondered if it was for her a form of diversion. Just as I could forget my ailing father and read quietly, maybe she too could shift her mind from caregiving and think on other things.</p>
		<p>"The truth is ..." my mother started again.</p>
		<p>"The truth is, I can't help thinking how it would ease your father's mind if you secured a post before he passed. It looks like it may be too late, but he's still conversant and his mind is still sound. If only you could manage this one last thing for him."</p>
		<p>I was in no position to perform such filial duty. I wrote not a word to Sensei.</p>   

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy">もう<ruby><rb>一遍</rb><rt>いっぺん</rt></ruby>&nbsp;one more time</span><span class="vocabstudy"><ruby><rb>手紙</rb><rt>てがみ</rt></ruby>&nbsp;letter</span><span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>してご<ruby><rb>覧</rb><rt>らん</rt></ruby>&nbsp;try sending</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span>
		<span class="vocabstudy"><ruby><rb>役</rb><rt>やく</rt></ruby>に<ruby><rb>立</rb><rt>た</rt></ruby>たない&nbsp;serve no purpose; be of no use</span><span class="vocabstudy"><ruby><rb>何通</rb><rt>なんつう</rt></ruby>&nbsp;any number (of letters)</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>こう&nbsp;write; compose</span><span class="vocabstudy"><ruby><rb>慰安</rb><rt>いあん</rt></ruby>&nbsp;comfort; solace</span><span class="vocabstudy"><ruby><rb>手数</rb><rt>てすう</rt></ruby>&nbsp;trouble; effort</span><span class="vocabstudy"><ruby><rb>厭</rb><rt>いと</rt></ruby>う&nbsp;grudge; be loath to (doing)</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>用件</rb><rt>ようけん</rt></ruby>&nbsp;matter of business</span><span class="vocabstudy"><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Sensei (elder one; teacher - used here as form of address)</span><span class="vocabstudy"><ruby><rb>苦痛</rb><rt>くつう</rt></ruby>&nbsp;hurt; pang</span><span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>叱</rb><rt>しか</rt></ruby>られたり&nbsp;be scolded; be reprimanded</span><span class="vocabstudy"><ruby><rb>機嫌</rb><rt>きげん</rt></ruby>&nbsp;temper; mood</span><span class="vocabstudy"><ruby><rb>損</rb><rt>そん</rt></ruby>じたり&nbsp;harm; damage</span><span class="vocabstudy"><ruby><rb>見下</rb><rt>みさ</rt></ruby>げられる&nbsp;be looked down on</span><span class="vocabstudy"><ruby><rb>遥</rb><rt>はる</rt></ruby>かに&nbsp;by far</span><span class="vocabstudy"><ruby><rb>恐</rb><rt>おそ</rt></ruby>れて&nbsp;fear; be averse to</span><span class="vocabstudy"><ruby><rb>依頼</rb><rt>いらい</rt></ruby>&nbsp;request</span><span class="vocabstudy">に<ruby><rb>対</rb><rt>たい</rt></ruby>して&nbsp;with respect to; regarding</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; the present</span><span class="vocabstudy"><ruby><rb>返事</rb><rt>へんじ</rt></ruby>&nbsp;answer; reply</span><span class="vocabstudy"><ruby><rb>貰</rb><rt>もら</rt></ruby>えない&nbsp;had not received</span><span class="vocabstudy"><ruby><rb>訳</rb><rt>わけ</rt></ruby>&nbsp;reason; rationale</span><span class="vocabstudy"><ruby><rb>邪推</rb><rt>じゃすい</rt></ruby>&nbsp;fear; suspicion</span>
		<span class="vocabstudy"><ruby><rb>訳</rb><rt>わけ</rt></ruby>はない&nbsp;easy; simple (enough)</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;matter; affair</span><span class="vocabstudy"><ruby><rb>郵便</rb><rt>ゆうびん</rt></ruby>&nbsp;mail; post</span><span class="vocabstudy"><ruby><rb>埒</rb><rt>らち</rt></ruby>は<ruby><rb>明</rb><rt>あ</rt></ruby>きません&nbsp;cannot be handled; cannot be settled</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>&nbsp;oneself</span><span class="vocabstudy"><ruby><rb>東京</rb><rt>とうきょう</rt></ruby>&nbsp;Tōkyō</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て&nbsp;set out (to); appear (in)</span><span class="vocabstudy"><ruby><rb>頼</rb><rt>たの</rt></ruby>んで&nbsp;ask; request</span><span class="vocabstudy"><ruby><rb>廻</rb><rt>まわ</rt></ruby>らなくっちゃ&nbsp;need to make the rounds</span>
		<span class="vocabstudy">お<ruby><rb>父</rb><rt>とう</rt></ruby>さん&nbsp;father</span><span class="vocabstudy"><ruby><rb>様子</rb><rt>ようす</rt></ruby>&nbsp;state; condition</span><span class="vocabstudy">お<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;you</span><span class="vocabstudy"><ruby><rb>分</rb><rt>わか</rt></ruby>らない&nbsp;don't know; can't say</span>
		<span class="vocabstudy"><ruby><rb>癒</rb><rt>なお</rt></ruby>る&nbsp;get better; recover</span><span class="vocabstudy"><ruby><rb>片付</rb><rt>かたづ</rt></ruby>かないうち&nbsp;until (something) is settled</span>
		<span class="vocabstudy"><ruby><rb>解</rb><rt>わか</rt></ruby>り<ruby><rb>切</rb><rt>き</rt></ruby>った&nbsp;goes without saying; is a given</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;argument; discussion</span><span class="vocabstudy"><ruby><rb>大病人</rb><rt>だいびょうにん</rt></ruby>&nbsp;critically ill person</span><span class="vocabstudy"><ruby><rb>放</rb><rt>ほう</rt></ruby>ちらかして&nbsp;leave alone; neglect</span><span class="vocabstudy"><ruby><rb>誰</rb><rt>だれ</rt></ruby>&nbsp;who</span><span class="vocabstudy"><ruby><rb>勝手</rb><rt>かって</rt></ruby>に&nbsp;arbitrarily; as one pleases</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>ける&nbsp;can go (off to)</span>
		<span class="vocabstudy"><ruby><rb>始</rb><rt>はじ</rt></ruby>め&nbsp;at first</span><span class="vocabstudy"><ruby><rb>心</rb><rt>こころ</rt></ruby>のなかで&nbsp;inwardly; to oneself</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>も&nbsp;(no)thing</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らない&nbsp;not know; not understand</span><span class="vocabstudy"><ruby><rb>憐</rb><rt>あわ</rt></ruby>れんだ&nbsp;pitied; felt compassion for</span><span class="vocabstudy"><ruby><rb>問題</rb><rt>もんだい</rt></ruby>&nbsp;subject; topic</span><span class="vocabstudy">ざわざわした&nbsp;busy; tumultuous</span><span class="vocabstudy"><ruby><rb>際</rb><rt>さい</rt></ruby>&nbsp;point in time; juncture</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>ち<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;brought up; raised</span><span class="vocabstudy"><ruby><rb>理解</rb><rt>りかい</rt></ruby>できなかった&nbsp;couldn't understand; struggled to fathom</span><span class="vocabstudy"><ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;illness; malady</span><span class="vocabstudy"><ruby><rb>静</rb><rt>しず</rt></ruby>かに&nbsp;quietly</span><span class="vocabstudy"><ruby><rb>坐</rb><rt>すわ</rt></ruby>ったり&nbsp;sit</span><span class="vocabstudy"><ruby><rb>書見</rb><rt>しょけん</rt></ruby>したり&nbsp;read</span><span class="vocabstudy"><ruby><rb>余裕</rb><rt>よゆう</rt></ruby>&nbsp;time; leeway; leisure (to do something)</span><span class="vocabstudy"><ruby><rb>眼</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before one's eyes</span><span class="vocabstudy"><ruby><rb>病人</rb><rt>びょうにん</rt></ruby>&nbsp;sick person; invalid</span><span class="vocabstudy"><ruby><rb>忘</rb><rt>わす</rt></ruby>れて&nbsp;forget; put out of one's mind</span><span class="vocabstudy"><ruby><rb>外</rb><rt>ほか</rt></ruby>の&nbsp;other</span><span class="vocabstudy"><ruby><rb>考</rb><rt>かんが</rt></ruby>える&nbsp;think about; consider</span><span class="vocabstudy"><ruby><rb>胸</rb><rt>むね</rt></ruby>&nbsp;breast; bosom</span><span class="vocabstudy"><ruby><rb>空地</rb><rt>すきま</rt></ruby>&nbsp;opening; spare capacity</span><span class="vocabstudy"><ruby><rb>疑</rb><rt>うたぐ</rt></ruby>った&nbsp;questioned; wondered</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>実</rb><rt>じつ</rt></ruby>はね&nbsp;actually; in truth</span><span class="vocabstudy">いい<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;spoke; started in</span>
		<span class="vocabstudy"><ruby><rb>生</rb><rt>い</rt></ruby>きてお<ruby><rb>出</rb><rt>いで</rt></ruby>&nbsp;be living; be alive</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>&nbsp;opening; position</span><span class="vocabstudy"><ruby><rb>極</rb><rt>きま</rt></ruby>ったら&nbsp;be decided; be settled</span><span class="vocabstudy"><ruby><rb>安心</rb><rt>あんしん</rt></ruby>なさる&nbsp;be assured; feel at ease</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>う&nbsp;think; consider</span><span class="vocabstudy"><ruby><rb>間</rb><rt>ま</rt></ruby>に<ruby><rb>合</rb><rt>あ</rt></ruby>わない&nbsp;not make it (in time)</span><span class="vocabstudy">かも<ruby><rb>知</rb><rt>し</rt></ruby>れない&nbsp;it may be that ...</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>も<ruby><rb>慥</rb><rt>たし</rt></ruby>か&nbsp;articulate; coherent</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>も<ruby><rb>慥</rb><rt>たし</rt></ruby>か&nbsp;of sound mind</span><span class="vocabstudy"><ruby><rb>喜</rb><rt>よろこ</rt></ruby>ばして&nbsp;make (someone) happy</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>げる&nbsp;do (something) for (someone)</span><span class="vocabstudy"><ruby><rb>親孝行</rb><rt>おやこうこう</rt></ruby>&nbsp;filial duty</span>
		<span class="vocabstudy"><ruby><rb>境遇</rb><rt>きょうぐう</rt></ruby>&nbsp;situation; circumstances</span><span class="vocabstudy"><ruby><rb>一行</rb><rt>いちぎょう</rt></ruby>&nbsp;one line (of writing)</span>

	</StudyGuide>
);
