// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={91}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>十</rb><rt>じゅう</rt></ruby></span></p>
		<p><span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>の<span><ruby><rb>病気</rb><rt>びょうき</rt></ruby></span>は<span><ruby><rb>同</rb><rt>おな</rt></ruby>じ</span>ような<span><ruby><rb>状態</rb><rt>じょうたい</rt></ruby></span>で<span><ruby><rb>一週間</rb><rt>いっしゅうかん</rt></ruby></span><span><ruby><rb>以上</rb><rt>いじょう</rt></ruby></span>つづいた。<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>は<span>その<ruby><rb>間</rb><rt>あいだ</rt></ruby>に</span><span><ruby><rb>長</rb><rt>なが</rt></ruby>い</span><span><ruby><rb>手紙</rb><rt>てがみ</rt></ruby></span>を<span><ruby><rb>九州</rb><rt>きゅうしゅう</rt></ruby></span>にいる<span><ruby><rb>兄</rb><rt>あに</rt></ruby></span><span><ruby><rb>宛</rb><rt>あて</rt></ruby></span>で<span><ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。<span><ruby><rb>妹</rb><rt>いもと</rt></ruby></span>へは<span><ruby><rb>母</rb><rt>はは</rt></ruby></span>から出させた。私は<span><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>中</rb><rt>なか</rt></ruby>で</span>、おそらくこれが父の<span><ruby><rb>健康</rb><rt>けんこう</rt></ruby></span><span>に<ruby><rb>関</rb><rt>かん</rt></ruby>して</span><span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>へやる<span><ruby><rb>最後</rb><rt>さいご</rt></ruby></span>の<span><ruby><rb>音信</rb><rt>たより</rt></ruby></span>だろうと<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>。それで<span><ruby><rb>両方</rb><rt>りょうほう</rt></ruby></span>へいよいよという<span><ruby><rb>場合</rb><rt>ばあい</rt></ruby></span>には<span><ruby><rb>電報</rb><rt>でんぽう</rt></ruby>を<ruby><rb>打</rb><rt>う</rt></ruby>つ</span>から<span><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>こ</rt></ruby>い</span>という<span><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>を<span><ruby><rb>書</rb><rt>か</rt></ruby>き<ruby><rb>込</rb><rt>こ</rt></ruby>めた</span>。</p>
		<p>兄は<span><ruby><rb>忙</rb><rt>いそが</rt></ruby>しい</span><span><ruby><rb>職</rb><rt>しょく</rt></ruby></span>にいた。妹は<span><ruby><rb>妊娠中</rb><rt>にんしんちゅう</rt></ruby></span>であった。だから父の<span><ruby><rb>危険</rb><rt>きけん</rt></ruby></span>が<span><ruby><rb>眼</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby></span>に<span><ruby><rb>逼</rb><rt>せま</rt></ruby>らないうちに</span><span><ruby><rb>呼</rb><rt>よ</rt></ruby>び<ruby><rb>寄</rb><rt>よ</rt></ruby>せる</span><span><ruby><rb>自由</rb><rt>じゆう</rt></ruby>は<ruby><rb>利</rb><rt>き</rt></ruby>かなかった</span>。といって、<span><ruby><rb>折角</rb><rt>せっかく</rt></ruby></span><span><ruby><rb>都合</rb><rt>つごう</rt></ruby>して</span><span><ruby><rb>来</rb><rt>き</rt></ruby>た</span>には来たが、<span><ruby><rb>間</rb><rt>ま</rt></ruby>に<ruby><rb>合</rb><rt>あ</rt></ruby>わなかった</span>といわれるのも<span><ruby><rb>辛</rb><rt>つら</rt></ruby>かった</span>。私は<span><ruby><rb>電報</rb><rt>でんぽう</rt></ruby>を<ruby><rb>掛</rb><rt>か</rt></ruby>ける</span><span><ruby><rb>時機</rb><rt>じき</rt></ruby></span>について、<span><ruby><rb>人</rb><rt>ひと</rt></ruby></span>の<span><ruby><rb>知</rb><rt>し</rt></ruby>らない</span><span><ruby><rb>責任</rb><rt>せきにん</rt></ruby></span>を<span><ruby><rb>感</rb><rt>かん</rt></ruby>じた</span>。</p>
		<p>「そう<span><ruby><rb>判然</rb><rt>はっき</rt></ruby>りした</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>になると私にも<span><ruby><rb>分</rb><rt>わか</rt></ruby>りません</span>。しかし危険はいつ<span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>か分らないという事だけは<span><ruby><rb>承知</rb><rt>しょうち</rt></ruby>していて</span><span><ruby><rb>下</rb><rt>くだ</rt></ruby>さい</span>」</p>
		<p><span><ruby><rb>停車場</rb><rt>ステーション</rt></ruby></span>のある<span><ruby><rb>町</rb><rt>まち</rt></ruby></span>から<span><ruby><rb>迎</rb><rt>むか</rt></ruby>えた</span><span><ruby><rb>医者</rb><rt>いしゃ</rt></ruby></span>は私にこういった。私は母と<span><ruby><rb>相談</rb><rt>そうだん</rt></ruby>して</span>、その医者の<span><ruby><rb>周旋</rb><rt>しゅうせん</rt></ruby></span>で、町の<span><ruby><rb>病院</rb><rt>びょういん</rt></ruby></span>から<span><ruby><rb>看護婦</rb><rt>かんごふ</rt></ruby></span>を<span><ruby><rb>一人</rb><rt>ひとり</rt></ruby></span><span><ruby><rb>頼</rb><rt>たの</rt></ruby>む</span><span><ruby><rb>事</rb><rt>こと</rt></ruby>にした</span>。父は<span><ruby><rb>枕元</rb><rt>まくらもと</rt></ruby></span>へ来て<span><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>する</span><span><ruby><rb>白</rb><rt>しろ</rt></ruby>い</span><span><ruby><rb>服</rb><rt>ふく</rt></ruby></span>を<span><ruby><rb>着</rb><rt>き</rt></ruby>た</span><span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>を<span><ruby><rb>見</rb><rt>み</rt></ruby>て</span><span><ruby><rb>変</rb><rt>へん</rt></ruby>な</span><span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>をした。</p>
		<p>父は<span><ruby><rb>死病</rb><rt>しびょう</rt></ruby></span><span>に<ruby><rb>罹</rb><rt>かか</rt></ruby>っている</span>事をとうから<span><ruby><rb>自覚</rb><rt>じかく</rt></ruby>していた</span>。それでいて、<span><ruby><rb>眼前</rb><rt>がんぜん</rt></ruby></span>にせまりつつある<span><ruby><rb>死</rb><rt>し</rt></ruby></span>そのものには<span><ruby><rb>気</rb><rt>き</rt></ruby>が<ruby><rb>付</rb><rt>つ</rt></ruby>かなかった</span>。</p>
		<p>「<span><ruby><rb>今</rb><rt>いま</rt></ruby>に</span><span><ruby><rb>癒</rb><rt>なお</rt></ruby>ったら</span><span>もう<ruby><rb>一返</rb><rt>いっぺん</rt></ruby></span><span><ruby><rb>東京</rb><rt>とうきょう</rt></ruby></span>へ<span><ruby><rb>遊</rb><rt>あそ</rt></ruby>びに<ruby><rb>行</rb><rt>い</rt></ruby>って</span>みよう。<span><ruby><rb>人間</rb><rt>にんげん</rt></ruby></span>はいつ死ぬか分らないからな。<span><ruby><rb>何</rb><rt>なん</rt></ruby>でも</span>やりたい事は、<span><ruby><rb>生</rb><rt>い</rt></ruby>きてる</span>うちにやっておく<span>に<ruby><rb>限</rb><rt>かぎ</rt></ruby>る</span>」</p>
		<p>母は<span><ruby><rb>仕方</rb><rt>しかた</rt></ruby>なしに</span>「その<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>は私もいっしょに<span><ruby><rb>伴</rb><rt>つ</rt></ruby>れて<ruby><rb>行</rb><rt>い</rt></ruby>って</span><span><ruby><rb>頂</rb><rt>いただ</rt></ruby>きましょう</span>」などと<span><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>を<ruby><rb>合</rb><rt>あわ</rt></ruby>せて</span>いた。</p>
		<p><span><ruby><rb>時</rb><rt>とき</rt></ruby>とすると</span>また<span><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>に</span><span><ruby><rb>淋</rb><rt>さみ</rt></ruby>しがった</span>。</p>
		<p>「おれが死んだら、どうか<span>お<ruby><rb>母</rb><rt>かあ</rt></ruby>さん</span>を<span><ruby><rb>大事</rb><rt>だいじ</rt></ruby>にして</span>やってくれ」</p>

		<h3 class="section">Rough translation</h3>
		<p>10</p>
		<p>A week or more passed with no change in Father's condition. During that time, I wrote a long letter to my brother in Kyūshū and had my mother write to my sister. I was convinced that these were the last letters we'd write them concerning Father's health. We indicated in both letters that when the time came we would send word by telegram, on receipt of which they should come at once.</p> 
		<p>My brother was steeped in his work, and my sister was expecting a child, so neither could be called home unless the moment demanded it. At the same time, I dreaded the thought of them making the journey only to arrive too late. The decision on when to summon them was mine, and they couldn't know how heavily it weighed on me.</p>
		<p>"I can't give you a definitive answer. All I can tell you is prepare yourselves. The critical stage could come any time now."</p>
		<p>These were the words of the doctor whom I'd fetched from the station in town. I talked with my mother, and we decided to ask him to send us a nurse from the clinic. Father looked strangely at the woman in white who arrived at his bedside.</p>
		<p>Father had known for some time that his illness was terminal. Even so, he had not yet acknowledged the actuality of death.</p>
		<p>"When I'm better, I'll go see Tōkyō once more. One never knows the number of one's days. One has to act while one can."</p>
		<p>"Take me with you when you go."</p>
		<p>My mother had no choice but to humor him.</p>
		<p>There were times too when he felt terribly despondent.</p>
		<p>"After I'm gone, take good care of your mother for me."</p>        

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>十</rb><rt>じゅう</rt></ruby>&nbsp;(part) 10</span>
		<span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;illness; malady</span><span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じ&nbsp;the same</span><span class="vocabstudy"><ruby><rb>状態</rb><rt>じょうたい</rt></ruby>&nbsp;condition; state</span><span class="vocabstudy"><ruby><rb>一週間</rb><rt>いっしゅうかん</rt></ruby>&nbsp;one week; a week</span><span class="vocabstudy"><ruby><rb>以上</rb><rt>いじょう</rt></ruby>&nbsp;more than</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy">その<ruby><rb>間</rb><rt>あいだ</rt></ruby>に&nbsp;during that time</span><span class="vocabstudy"><ruby><rb>長</rb><rt>なが</rt></ruby>い&nbsp;long; lengthy</span><span class="vocabstudy"><ruby><rb>手紙</rb><rt>てがみ</rt></ruby>&nbsp;letter</span><span class="vocabstudy"><ruby><rb>九州</rb><rt>きゅうしゅう</rt></ruby>&nbsp;Kyūshū</span><span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;older brother; elder brother</span><span class="vocabstudy"><ruby><rb>宛</rb><rt>あて</rt></ruby>&nbsp;addressed to</span><span class="vocabstudy"><ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;put out; sent</span><span class="vocabstudy"><ruby><rb>妹</rb><rt>いもと</rt></ruby>&nbsp;younger sister (usually <ruby><rb>妹</rb><rt>いもうと</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span><span class="vocabstudy"><ruby><rb>腹</rb><rt>はら</rt></ruby>の<ruby><rb>中</rb><rt>なか</rt></ruby>で&nbsp;inwardly; to oneself</span><span class="vocabstudy"><ruby><rb>健康</rb><rt>けんこう</rt></ruby>&nbsp;health; physical condition</span><span class="vocabstudy">に<ruby><rb>関</rb><rt>かん</rt></ruby>して&nbsp;concerning</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two people; the two of them</span><span class="vocabstudy"><ruby><rb>最後</rb><rt>さいご</rt></ruby>&nbsp;last; final</span><span class="vocabstudy"><ruby><rb>音信</rb><rt>たより</rt></ruby>&nbsp;letter; correspondence</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought; figured; believed</span><span class="vocabstudy"><ruby><rb>両方</rb><rt>りょうほう</rt></ruby>&nbsp;both (of them)</span><span class="vocabstudy"><ruby><rb>場合</rb><rt>ばあい</rt></ruby>&nbsp;situation; circumstance</span><span class="vocabstudy"><ruby><rb>電報</rb><rt>でんぽう</rt></ruby>を<ruby><rb>打</rb><rt>う</rt></ruby>つ&nbsp;send a telegram</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>こ</rt></ruby>い&nbsp;come</span><span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning; nuance</span><span class="vocabstudy"><ruby><rb>書</rb><rt>か</rt></ruby>き<ruby><rb>込</rb><rt>こ</rt></ruby>めた&nbsp;included; incorporated (in one's writing)</span>
		<span class="vocabstudy"><ruby><rb>忙</rb><rt>いそが</rt></ruby>しい&nbsp;busy; hectic</span><span class="vocabstudy"><ruby><rb>職</rb><rt>しょく</rt></ruby>&nbsp;work; occupation</span><span class="vocabstudy"><ruby><rb>妊娠中</rb><rt>にんしんちゅう</rt></ruby>&nbsp;pregnant; expecting; with child</span><span class="vocabstudy"><ruby><rb>危険</rb><rt>きけん</rt></ruby>&nbsp;danger; peril</span><span class="vocabstudy"><ruby><rb>眼</rb><rt>め</rt></ruby>の<ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;before one's eyes; right in front of one</span><span class="vocabstudy"><ruby><rb>逼</rb><rt>せま</rt></ruby>らないうちに&nbsp;while not pressing; until urgent</span><span class="vocabstudy"><ruby><rb>呼</rb><rt>よ</rt></ruby>び<ruby><rb>寄</rb><rt>よ</rt></ruby>せる&nbsp;call; summon</span><span class="vocabstudy"><ruby><rb>自由</rb><rt>じゆう</rt></ruby>は<ruby><rb>利</rb><rt>き</rt></ruby>かなかった&nbsp;was not at leisure to ...</span><span class="vocabstudy"><ruby><rb>折角</rb><rt>せっかく</rt></ruby>&nbsp;at great pains; taking the trouble to</span><span class="vocabstudy"><ruby><rb>都合</rb><rt>つごう</rt></ruby>して&nbsp;make arrangements</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came; arrived</span><span class="vocabstudy"><ruby><rb>間</rb><rt>ま</rt></ruby>に<ruby><rb>合</rb><rt>あ</rt></ruby>わなかった&nbsp;was too late</span><span class="vocabstudy"><ruby><rb>辛</rb><rt>つら</rt></ruby>かった&nbsp;would be hard to bear</span><span class="vocabstudy"><ruby><rb>電報</rb><rt>でんぽう</rt></ruby>を<ruby><rb>掛</rb><rt>か</rt></ruby>ける&nbsp;send a telegram</span><span class="vocabstudy"><ruby><rb>時機</rb><rt>じき</rt></ruby>&nbsp;time; timing</span><span class="vocabstudy"><ruby><rb>人</rb><rt>ひと</rt></ruby>&nbsp;people; others</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>らない&nbsp;not be aware of; not realize</span><span class="vocabstudy"><ruby><rb>責任</rb><rt>せきにん</rt></ruby>&nbsp;responsibility</span><span class="vocabstudy"><ruby><rb>感</rb><rt>かん</rt></ruby>じた&nbsp;felt</span>
		<span class="vocabstudy"><ruby><rb>判然</rb><rt>はっき</rt></ruby>りした&nbsp;clear; definitive</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;situation; state of affairs</span><span class="vocabstudy"><ruby><rb>分</rb><rt>わか</rt></ruby>りません&nbsp;don't know; can't say</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;come; arrive</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>していて&nbsp;be aware of; keep in mind</span><span class="vocabstudy"><ruby><rb>下</rb><rt>くだ</rt></ruby>さい&nbsp;please ...</span>
		<span class="vocabstudy"><ruby><rb>停車場</rb><rt>ステーション</rt></ruby>&nbsp;station</span><span class="vocabstudy"><ruby><rb>町</rb><rt>まち</rt></ruby>&nbsp;town</span><span class="vocabstudy"><ruby><rb>迎</rb><rt>むか</rt></ruby>えた&nbsp;went to meet; went to receive</span><span class="vocabstudy"><ruby><rb>医者</rb><rt>いしゃ</rt></ruby>&nbsp;doctor</span><span class="vocabstudy"><ruby><rb>相談</rb><rt>そうだん</rt></ruby>して&nbsp;discuss; consult</span><span class="vocabstudy"><ruby><rb>周旋</rb><rt>しゅうせん</rt></ruby>&nbsp;mediation; introduction</span><span class="vocabstudy"><ruby><rb>病院</rb><rt>びょういん</rt></ruby>&nbsp;hospital; clinic</span><span class="vocabstudy"><ruby><rb>看護婦</rb><rt>かんごふ</rt></ruby>&nbsp;nurse</span><span class="vocabstudy"><ruby><rb>一人</rb><rt>ひとり</rt></ruby>&nbsp;one person</span><span class="vocabstudy"><ruby><rb>頼</rb><rt>たの</rt></ruby>む&nbsp;request</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>にした&nbsp;decided to ...</span><span class="vocabstudy"><ruby><rb>枕元</rb><rt>まくらもと</rt></ruby>&nbsp;pillow side; bedside</span><span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>する&nbsp;greet; introduce oneself</span><span class="vocabstudy"><ruby><rb>白</rb><rt>しろ</rt></ruby>い&nbsp;white</span><span class="vocabstudy"><ruby><rb>服</rb><rt>ふく</rt></ruby>&nbsp;clothing; outfit</span><span class="vocabstudy"><ruby><rb>着</rb><rt>き</rt></ruby>た&nbsp;wore</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;woman</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;look at</span><span class="vocabstudy"><ruby><rb>変</rb><rt>へん</rt></ruby>な&nbsp;odd; strange</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face; (facial) expression</span>
		<span class="vocabstudy"><ruby><rb>死病</rb><rt>しびょう</rt></ruby>&nbsp;fatal disease; terminal illness</span><span class="vocabstudy">に<ruby><rb>罹</rb><rt>かか</rt></ruby>っている&nbsp;be afflicted with</span><span class="vocabstudy"><ruby><rb>自覚</rb><rt>じかく</rt></ruby>していた&nbsp;was resigned to</span><span class="vocabstudy"><ruby><rb>眼前</rb><rt>がんぜん</rt></ruby>&nbsp;before one's eyes</span><span class="vocabstudy"><ruby><rb>死</rb><rt>し</rt></ruby>&nbsp;death</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>が<ruby><rb>付</rb><rt>つ</rt></ruby>かなかった&nbsp;had not taken notice of</span>
		<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>に&nbsp;soon; even now</span><span class="vocabstudy"><ruby><rb>癒</rb><rt>なお</rt></ruby>ったら&nbsp;get better; feel better</span><span class="vocabstudy">もう<ruby><rb>一返</rb><rt>いっぺん</rt></ruby>&nbsp;one more time</span><span class="vocabstudy"><ruby><rb>東京</rb><rt>とうきょう</rt></ruby>&nbsp;Tōkyō</span><span class="vocabstudy"><ruby><rb>遊</rb><rt>あそ</rt></ruby>びに<ruby><rb>行</rb><rt>い</rt></ruby>って&nbsp;go and visit; travel (for pleasure)</span><span class="vocabstudy"><ruby><rb>人間</rb><rt>にんげん</rt></ruby>&nbsp;human beings; people; a person</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なん</rt></ruby>でも&nbsp;anything and everything</span><span class="vocabstudy"><ruby><rb>生</rb><rt>い</rt></ruby>きてる&nbsp;be alive</span><span class="vocabstudy">に<ruby><rb>限</rb><rt>かぎ</rt></ruby>る&nbsp;is limited to ...; can only ...</span>
		<span class="vocabstudy"><ruby><rb>仕方</rb><rt>しかた</rt></ruby>なしに&nbsp;having no choice; of necessity</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; occasion</span><span class="vocabstudy"><ruby><rb>伴</rb><rt>つ</rt></ruby>れて<ruby><rb>行</rb><rt>い</rt></ruby>って&nbsp;take along; take with</span><span class="vocabstudy"><ruby><rb>頂</rb><rt>いただ</rt></ruby>きましょう&nbsp;have (someone) do (something)</span><span class="vocabstudy"><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>を<ruby><rb>合</rb><rt>あわ</rt></ruby>せて&nbsp;go along with; humor</span>
		<span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>とすると&nbsp;sometimes; at times</span><span class="vocabstudy"><ruby><rb>非常</rb><rt>ひじょう</rt></ruby>に&nbsp;extremely; exceedingly</span><span class="vocabstudy"><ruby><rb>淋</rb><rt>さみ</rt></ruby>しがった&nbsp;felt despondent; felt forlorn</span>
		<span class="vocabstudy">お<ruby><rb>母</rb><rt>かあ</rt></ruby>さん&nbsp;mother</span><span class="vocabstudy"><ruby><rb>大事</rb><rt>だいじ</rt></ruby>にして&nbsp;take care of</span>

	</StudyGuide>
);
