// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='kokoro' num={95}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>十二</rb><rt>じゅうに</rt></ruby></span></p>
		<p><span><ruby><rb>兄</rb><rt>あに</rt></ruby></span>が<span><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>、<span><ruby><rb>父</rb><rt>ちち</rt></ruby></span>は<span><ruby><rb>寝</rb><rt>ね</rt></ruby>ながら</span><span><ruby><rb>新聞</rb><rt>しんぶん</rt></ruby></span>を<span><ruby><rb>読</rb><rt>よ</rt></ruby>んで</span>いた。父は<span><ruby><rb>平生</rb><rt>へいぜい</rt></ruby>から</span><span><ruby><rb>何</rb><rt>なに</rt></ruby>を<ruby><rb>措</rb><rt>お</rt></ruby>いても</span>新聞だけには<span><ruby><rb>眼</rb><rt>め</rt></ruby>を<ruby><rb>通</rb><rt>とお</rt></ruby>す</span><span><ruby><rb>習慣</rb><rt>しゅうかん</rt></ruby></span>であったが、<span><ruby><rb>床</rb><rt>とこ</rt></ruby></span>についてからは、<span><ruby><rb>退屈</rb><rt>たいくつ</rt></ruby></span>のため<span><ruby><rb>猶更</rb><rt>なおさら</rt></ruby></span>それを<span><ruby><rb>読</rb><rt>よ</rt></ruby>みたがった</span>。<span><ruby><rb>母</rb><rt>はは</rt></ruby></span>も<span><ruby><rb>私</rb><rt>わたくし</rt></ruby></span>も<span><ruby><rb>強</rb><rt>し</rt></ruby>いては</span><span><ruby><rb>反対</rb><rt>はんたい</rt></ruby>せずに</span>、なるべく<span><ruby><rb>病人</rb><rt>びょうにん</rt></ruby></span>の<span><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>通</rb><rt>どお</rt></ruby>り</span>にさせておいた。</p>
		<p>「そういう<span><ruby><rb>元気</rb><rt>げんき</rt></ruby></span>なら<span><ruby><rb>結構</rb><rt>けっこう</rt></ruby>な</span>ものだ。よっぽど<span><ruby><rb>悪</rb><rt>わる</rt></ruby>い</span>かと思って来たら、<span><ruby><rb>大変</rb><rt>たいへん</rt></ruby></span><span><ruby><rb>好</rb><rt>い</rt></ruby>い</span>ようじゃありませんか」</p>
		<p>兄はこんな<span><ruby><rb>事</rb><rt>こと</rt></ruby></span>をいいながら父と<span><ruby><rb>話</rb><rt>はなし</rt></ruby></span>をした。その<span><ruby><rb>賑</rb><rt>にぎ</rt></ruby>やか<ruby><rb>過</rb><rt>す</rt></ruby>ぎる</span><span><ruby><rb>調子</rb><rt>ちょうし</rt></ruby></span>が私にはかえって<span><ruby><rb>不調和</rb><rt>ふちょうわ</rt></ruby></span>に<span><ruby><rb>聞</rb><rt>き</rt></ruby>こえた</span>。それでも父の<span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>を<span><ruby><rb>外</rb><rt>はず</rt></ruby>して</span>私と<span><ruby><rb>差</rb><rt>さ</rt></ruby>し<ruby><rb>向</rb><rt>むか</rt></ruby>い</span>になった時は、むしろ<span><ruby><rb>沈</rb><rt>しず</rt></ruby>んでいた</span>。</p>
		<p>「新聞なんか読ましちゃいけなかないか」</p>
		<p>「<span><ruby><rb>私</rb><rt>わたし</rt></ruby></span>もそう思うんだけれども、読まないと<span><ruby><rb>承知</rb><rt>しょうち</rt></ruby>しない</span>んだから、<span><ruby><rb>仕様</rb><rt>しよう</rt></ruby>がない</span>」</p>
		<p>兄は私の<span><ruby><rb>弁解</rb><rt>べんかい</rt></ruby></span>を<span><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>聞いていた。やがて、「よく<span><ruby><rb>解</rb><rt>わか</rt></ruby>る</span>のかな」といった。兄は父の<span><ruby><rb>理解力</rb><rt>りかいりょく</rt></ruby></span>が<span><ruby><rb>病気</rb><rt>びょうき</rt></ruby></span>のために、平生よりはよっぽど<span><ruby><rb>鈍</rb><rt>にぶ</rt></ruby>っている</span>ように<span><ruby><rb>観察</rb><rt>かんさつ</rt></ruby>した</span>らしい。</p>
		<p>「そりゃ<span><ruby><rb>慥</rb><rt>たし</rt></ruby>か</span>です。私はさっき<span><ruby><rb>二十分</rb><rt>にじゅっぷん</rt></ruby></span>ばかり<span><ruby><rb>枕元</rb><rt>まくらもと</rt></ruby></span>に<span><ruby><rb>坐</rb><rt>すわ</rt></ruby>って</span><span><ruby><rb>色々</rb><rt>いろいろ</rt></ruby></span><span><ruby><rb>話</rb><rt>はな</rt></ruby>して</span>みたが、調子の<span><ruby><rb>狂</rb><rt>くる</rt></ruby>った</span>ところは<span><ruby><rb>少</rb><rt>すこ</rt></ruby>しも</span>ないです。あの様子じゃことによるとまだなかなか<span><ruby><rb>持</rb><rt>も</rt></ruby>つ</span><span>かも<ruby><rb>知</rb><rt>し</rt></ruby>れません</span>よ」</p>
		<p>兄<span>と<ruby><rb>前後</rb><rt>ぜんご</rt></ruby>して</span><span><ruby><rb>着</rb><rt>つ</rt></ruby>いた</span><span><ruby><rb>妹</rb><rt>いもと</rt></ruby></span>の<span><ruby><rb>夫</rb><rt>おっと</rt></ruby></span>の<span><ruby><rb>意見</rb><rt>いけん</rt></ruby></span>は、<span><ruby><rb>我々</rb><rt>われわれ</rt></ruby></span>よりもよほど<span><ruby><rb>楽観的</rb><rt>らっかんてき</rt></ruby></span>であった。父は<span><ruby><rb>彼</rb><rt>かれ</rt></ruby></span>に<span><ruby><rb>向</rb><rt>む</rt></ruby>かって</span>妹の事をあれこれと<span><ruby><rb>尋</rb><rt>たず</rt></ruby>ねて</span>いた。「<span><ruby><rb>身体</rb><rt>からだ</rt></ruby></span>が身体だからむやみに<span><ruby><rb>汽車</rb><rt>きしゃ</rt></ruby></span>になんぞ<span><ruby><rb>乗</rb><rt>の</rt></ruby>って</span><span><ruby><rb>揺</rb><rt>ゆ</rt></ruby>れない</span><span><ruby><rb>方</rb><rt>ほう</rt></ruby>が<ruby><rb>好</rb><rt>い</rt></ruby>い</span>。<span><ruby><rb>無理</rb><rt>むり</rt></ruby></span>をして<span><ruby><rb>見舞</rb><rt>みまい</rt></ruby></span>に<span><ruby><rb>来</rb><rt>こ</rt></ruby>られたりする</span>と、かえってこっちが<span><ruby><rb>心配</rb><rt>しんぱい</rt></ruby></span>だから」といっていた。「なに<span><ruby><rb>今</rb><rt>いま</rt></ruby>に</span><span><ruby><rb>治</rb><rt>なお</rt></ruby>ったら</span><span><ruby><rb>赤</rb><rt>あか</rt></ruby>ん<ruby><rb>坊</rb><rt>ぼう</rt></ruby></span>の<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>でも<span><ruby><rb>見</rb><rt>み</rt></ruby>に</span>、<span><ruby><rb>久</rb><rt>ひさ</rt></ruby>しぶりに</span>こっちから<span><ruby><rb>出掛</rb><rt>でか</rt></ruby>ける</span>から<span><ruby><rb>差支</rb><rt>さしつか</rt></ruby>えない</span>」ともいっていた。</p>
		<p><span><ruby><rb>乃木</rb><rt>のぎ</rt></ruby><ruby><rb>大将</rb><rt>だいしょう</rt></ruby></span>の<span><ruby><rb>死</rb><rt>し</rt></ruby>んだ</span>時も、父は<span><ruby><rb>一番</rb><rt>いちばん</rt></ruby></span>さきに新聞でそれを知った。</p>
		<p>「大変だ大変だ」といった。</p>
		<p><span><ruby><rb>何事</rb><rt>なにごと</rt></ruby>も<ruby><rb>知</rb><rt>し</rt></ruby>らない</span>私たちはこの<span><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>な</span><span><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>に<span><ruby><rb>驚</rb><rt>おどろ</rt></ruby>かされた</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>12</p>
		<p>When my brother arrived, Father was reading the paper in bed. Father had always been an avid reader of the news, and now that he was bedridden with nothing to do, his interest was even greater. My mother and I indulged him during his illness and did not try to dissuade him.</p>
		<p>"Great to see you're feeling so well. I'd feared for the worst, but it seems my fears were misplaced."</p>
		<p>My brother spoke thus toward my father. To me, his tone was much too upbeat and came across as disingenuous. Away from Father's side though, when we spoke in private, he was duly subdued.</p>
		<p>"Are you sure you should let him read the paper?"</p>
		<p>"I'd rather he took it easy, but he insists on reading, so what can we do?"</p>
		<p>My brother listened in silence as I explained myself.</p>
		<p>"Does he even know what he's reading?" he asked.</p>
		<p>He was questioning Father's mental faculty. He'd sensed, it seems, that Father's illness might have dulled his mind.</p>
		<p>"His mind is sound. I sat with him earlier, and we spoke for a good twenty minutes on various topics. Nothing he said was off-kilter. At the rate he's going, he may hold out a good while yet."</p>
		<p>My sister's husband, who arrived around the same time as my brother, was even more sanguine. Father talked with him at length, asking after my sister.</p>
		<p>"In her condition, I wouldn't want her rattled by the train. If she overexerts herself, she'll be the one at risk," Father said.</p>
		<p>"But don't you worry. As soon as I'm better, I'll go see the baby myself. It's time I did some traveling," he added.</p>
		<p>When General Nogi died, Father was first to learn of it through the paper.</p>
		<p>"It can't be! It can't be!" he exclaimed.</p>
		<p>The rest of us, who didn't know what had happened, were surprised by his outburst.</p>

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>十二</rb><rt>じゅうに</rt></ruby>&nbsp;(part) 12</span>
		<span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;older brother; elder brother</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came home; returned</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time</span><span class="vocabstudy"><ruby><rb>父</rb><rt>ちち</rt></ruby>&nbsp;father</span><span class="vocabstudy"><ruby><rb>寝</rb><rt>ね</rt></ruby>ながら&nbsp;lying down; resting</span><span class="vocabstudy"><ruby><rb>新聞</rb><rt>しんぶん</rt></ruby>&nbsp;newspaper</span><span class="vocabstudy"><ruby><rb>読</rb><rt>よ</rt></ruby>んで&nbsp;read</span><span class="vocabstudy"><ruby><rb>平生</rb><rt>へいぜい</rt></ruby>から&nbsp;generally; as a rule</span><span class="vocabstudy"><ruby><rb>何</rb><rt>なに</rt></ruby>を<ruby><rb>措</rb><rt>お</rt></ruby>いても&nbsp;first of all; above all else</span><span class="vocabstudy"><ruby><rb>眼</rb><rt>め</rt></ruby>を<ruby><rb>通</rb><rt>とお</rt></ruby>す&nbsp;look through; give a read</span><span class="vocabstudy"><ruby><rb>習慣</rb><rt>しゅうかん</rt></ruby>&nbsp;habit; practice</span><span class="vocabstudy"><ruby><rb>床</rb><rt>とこ</rt></ruby>&nbsp;bed</span><span class="vocabstudy"><ruby><rb>退屈</rb><rt>たいくつ</rt></ruby>&nbsp;tedium; boredom</span><span class="vocabstudy"><ruby><rb>猶更</rb><rt>なおさら</rt></ruby>&nbsp;all the more; even more so</span><span class="vocabstudy"><ruby><rb>読</rb><rt>よ</rt></ruby>みたがった&nbsp;wanted to read; was inclined to read</span><span class="vocabstudy"><ruby><rb>母</rb><rt>はは</rt></ruby>&nbsp;mother</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたくし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>強</rb><rt>し</rt></ruby>いては&nbsp;firmly; adamantly</span><span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby>せずに&nbsp;without opposing</span><span class="vocabstudy"><ruby><rb>病人</rb><rt>びょうにん</rt></ruby>&nbsp;sick person; patient</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>い<ruby><rb>通</rb><rt>どお</rt></ruby>り&nbsp;as one thinks; as one wishes (to do)</span>
		<span class="vocabstudy"><ruby><rb>元気</rb><rt>げんき</rt></ruby>&nbsp;energy; vigor</span><span class="vocabstudy"><ruby><rb>結構</rb><rt>けっこう</rt></ruby>な&nbsp;fine; splendid</span><span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>い&nbsp;bad; grave</span><span class="vocabstudy"><ruby><rb>大変</rb><rt>たいへん</rt></ruby>&nbsp;quite; terribly</span><span class="vocabstudy"><ruby><rb>好</rb><rt>い</rt></ruby>い&nbsp;good; fine</span>
		<span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;things</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はなし</rt></ruby>&nbsp;talk; conversation</span><span class="vocabstudy"><ruby><rb>賑</rb><rt>にぎ</rt></ruby>やか<ruby><rb>過</rb><rt>す</rt></ruby>ぎる&nbsp;overly enthusiastic</span><span class="vocabstudy"><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>&nbsp;manner; mood</span><span class="vocabstudy"><ruby><rb>不調和</rb><rt>ふちょうわ</rt></ruby>&nbsp;incongruous; disingenuous</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>こえた&nbsp;sounded; came across (as)</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;front of</span><span class="vocabstudy"><ruby><rb>外</rb><rt>はず</rt></ruby>して&nbsp;remove (oneself) from</span><span class="vocabstudy"><ruby><rb>差</rb><rt>さ</rt></ruby>し<ruby><rb>向</rb><rt>むか</rt></ruby>い&nbsp;face to face (with)</span><span class="vocabstudy"><ruby><rb>沈</rb><rt>しず</rt></ruby>んでいた&nbsp;was somber; was subdued</span>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>しない&nbsp;is not satisfied; is not content</span><span class="vocabstudy"><ruby><rb>仕様</rb><rt>しよう</rt></ruby>がない&nbsp;there's nothing one can do; there's no other choice</span>
		<span class="vocabstudy"><ruby><rb>弁解</rb><rt>べんかい</rt></ruby>&nbsp;justification; defense</span><span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;in silence; without speaking</span><span class="vocabstudy"><ruby><rb>解</rb><rt>わか</rt></ruby>る&nbsp;understand; comprehend</span><span class="vocabstudy"><ruby><rb>理解力</rb><rt>りかいりょく</rt></ruby>&nbsp;comprehensive faculty; mental capacity</span><span class="vocabstudy"><ruby><rb>病気</rb><rt>びょうき</rt></ruby>&nbsp;illness; malady</span><span class="vocabstudy"><ruby><rb>鈍</rb><rt>にぶ</rt></ruby>っている&nbsp;be dulled</span><span class="vocabstudy"><ruby><rb>観察</rb><rt>かんさつ</rt></ruby>した&nbsp;perceived; regarded</span>
		<span class="vocabstudy"><ruby><rb>慥</rb><rt>たし</rt></ruby>か&nbsp;sound; solid; firm</span><span class="vocabstudy"><ruby><rb>二十分</rb><rt>にじゅっぷん</rt></ruby>&nbsp;twenty minutes</span><span class="vocabstudy"><ruby><rb>枕元</rb><rt>まくらもと</rt></ruby>&nbsp;pillow side; bedside</span><span class="vocabstudy"><ruby><rb>坐</rb><rt>すわ</rt></ruby>って&nbsp;sit; seat oneself</span><span class="vocabstudy"><ruby><rb>色々</rb><rt>いろいろ</rt></ruby>&nbsp;various (things)</span><span class="vocabstudy"><ruby><rb>話</rb><rt>はな</rt></ruby>して&nbsp;talked; conversed</span><span class="vocabstudy"><ruby><rb>狂</rb><rt>くる</rt></ruby>った&nbsp;was amiss; was out of sorts</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>しも&nbsp;(not) in the least</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>つ&nbsp;hold out; last</span><span class="vocabstudy">かも<ruby><rb>知</rb><rt>し</rt></ruby>れません&nbsp;it may be that ...</span>
		<span class="vocabstudy">と<ruby><rb>前後</rb><rt>ぜんご</rt></ruby>して&nbsp;at about the same time</span><span class="vocabstudy"><ruby><rb>着</rb><rt>つ</rt></ruby>いた&nbsp;arrived</span><span class="vocabstudy"><ruby><rb>妹</rb><rt>いもと</rt></ruby>&nbsp;younger sister (usually <ruby><rb>妹</rb><rt>いもうと</rt></ruby>)</span><span class="vocabstudy"><ruby><rb>夫</rb><rt>おっと</rt></ruby>&nbsp;husband</span><span class="vocabstudy"><ruby><rb>意見</rb><rt>いけん</rt></ruby>&nbsp;opinion; point of view</span><span class="vocabstudy"><ruby><rb>我々</rb><rt>われわれ</rt></ruby>&nbsp;we; us</span><span class="vocabstudy"><ruby><rb>楽観的</rb><rt>らっかんてき</rt></ruby>&nbsp;positive; optimistic</span><span class="vocabstudy"><ruby><rb>彼</rb><rt>かれ</rt></ruby>&nbsp;he; him</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>かって&nbsp;turn toward</span><span class="vocabstudy"><ruby><rb>尋</rb><rt>たず</rt></ruby>ねて&nbsp;ask; inquire</span><span class="vocabstudy"><ruby><rb>身体</rb><rt>からだ</rt></ruby>&nbsp;body; physical condition</span><span class="vocabstudy"><ruby><rb>汽車</rb><rt>きしゃ</rt></ruby>&nbsp;(steam) train</span><span class="vocabstudy"><ruby><rb>乗</rb><rt>の</rt></ruby>って&nbsp;board; ride</span><span class="vocabstudy"><ruby><rb>揺</rb><rt>ゆ</rt></ruby>れない&nbsp;not be rocked; not be swayed</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>が<ruby><rb>好</rb><rt>い</rt></ruby>い&nbsp;it's better to ...</span><span class="vocabstudy"><ruby><rb>無理</rb><rt>むり</rt></ruby>&nbsp;overdoing things; overexertion</span><span class="vocabstudy"><ruby><rb>見舞</rb><rt>みまい</rt></ruby>&nbsp;calling on someone who's sick; well wishing</span><span class="vocabstudy"><ruby><rb>来</rb><rt>こ</rt></ruby>られたりする&nbsp;come; call; visit</span><span class="vocabstudy"><ruby><rb>心配</rb><rt>しんぱい</rt></ruby>&nbsp;worry; concern</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>に&nbsp;soon; shortly</span><span class="vocabstudy"><ruby><rb>治</rb><rt>なお</rt></ruby>ったら&nbsp;recover; get better</span><span class="vocabstudy"><ruby><rb>赤</rb><rt>あか</rt></ruby>ん<ruby><rb>坊</rb><rt>ぼう</rt></ruby>&nbsp;baby</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>に&nbsp;to see</span><span class="vocabstudy"><ruby><rb>久</rb><rt>ひさ</rt></ruby>しぶりに&nbsp;for the first time in a long while</span><span class="vocabstudy"><ruby><rb>出掛</rb><rt>でか</rt></ruby>ける&nbsp;travel; journey</span><span class="vocabstudy"><ruby><rb>差支</rb><rt>さしつか</rt></ruby>えない&nbsp;is no problem; is not a concern</span>
		<span class="vocabstudy"><ruby><rb>乃木</rb><rt>のぎ</rt></ruby><ruby><rb>大将</rb><rt>だいしょう</rt></ruby>&nbsp;General Nogi (committed suicide on day of Meiji Emperor's funeral)</span><span class="vocabstudy"><ruby><rb>死</rb><rt>し</rt></ruby>んだ&nbsp;died</span><span class="vocabstudy"><ruby><rb>一番</rb><rt>いちばん</rt></ruby>&nbsp;first; foremost</span>
		<span class="vocabstudy"><ruby><rb>何事</rb><rt>なにごと</rt></ruby>も<ruby><rb>知</rb><rt>し</rt></ruby>らない&nbsp;have no idea (what something might be about)</span><span class="vocabstudy"><ruby><rb>突然</rb><rt>とつぜん</rt></ruby>な&nbsp;sudden</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words; expression</span><span class="vocabstudy"><ruby><rb>驚</rb><rt>おどろ</rt></ruby>かされた&nbsp;were surprised (by)</span>

	</StudyGuide>
);
