// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={57}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>はなんとか<span><ruby><rb>言</rb><rt>い</rt></ruby>って</span>、<span><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby></span>をしようと<span><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>が、あまり<span><ruby><rb>時間</rb><rt>じかん</rt></ruby></span>がたっているので、どう<span><ruby><rb>口</rb><rt>くち</rt></ruby>をきいて</span>いいかわからない。ただ<span><ruby><rb>帽子</rb><rt>ぼうし</rt></ruby></span>を<span><ruby><rb>取</rb><rt>と</rt></ruby>って</span><span><ruby><rb>礼</rb><rt>れい</rt></ruby></span>をした。<span><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby></span><span>に<ruby><rb>対</rb><rt>たい</rt></ruby>して</span>は、あまり<span><ruby><rb>丁寧</rb><rt>ていねい</rt></ruby>すぎる</span>。<span><ruby><rb>広田</rb><rt>ひろた</rt></ruby></span>に対しては、<span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span><ruby><rb>簡略</rb><rt>かんりゃく</rt></ruby>すぎる</span>。三四郎はどっちつかずの<span><ruby><rb>中間</rb><rt>ちゅうかん</rt></ruby></span>にでた。すると与次郎が、すぐ、</p>
		<p>「この<span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>は<span><ruby><rb>私</rb><rt>わたし</rt></ruby>の</span><span><ruby><rb>同級生</rb><rt>どうきゅうせい</rt></ruby></span>です。<span><ruby><rb>熊本</rb><rt>くまもと</rt></ruby></span>の<span><ruby><rb>高等</rb><rt>こうとう</rt></ruby><ruby><rb>学校</rb><rt>がっこう</rt></ruby></span>からはじめて<span><ruby><rb>東京</rb><rt>とうきょう</rt></ruby></span>へ<span><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た</span>――」と<span><ruby><rb>聞</rb><rt>き</rt></ruby>かれもしないさきから</span><span>いなか<ruby><rb>者</rb><rt>もの</rt></ruby></span>を<span><ruby><rb>吹聴</rb><rt>ふいちょう</rt></ruby>して</span>おいて、それから三四郎の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>を<span><ruby><rb>向</rb><rt>む</rt></ruby>いて</span>、</p>
		<p>「これが<span><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby></span>。高等学校の……」と<span>わけもなく</span><span><ruby><rb>双方</rb><rt>そうほう</rt></ruby></span>を<span><ruby><rb>紹介</rb><rt>しょうかい</rt></ruby>して</span>しまった。</p>
		<p>この<span><ruby><rb>時</rb><rt>とき</rt></ruby></span>広田先生は「<span><ruby><rb>知</rb><rt>し</rt></ruby>ってる</span>、知ってる」と<span><ruby><rb>二</rb><rt>に</rt></ruby>へん</span><span><ruby><rb>繰</rb><rt>く</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>して</span>言ったので、与次郎は<span><ruby><rb>妙</rb><rt>みょう</rt></ruby>な</span><span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>をしている。しかしなぜ知ってるんですかなどと<span>めんどうな</span><span><ruby><rb>事</rb><rt>こと</rt></ruby></span>は聞かなかった。ただちに、</p>
		<p>「<span><ruby><rb>君</rb><rt>きみ</rt></ruby></span>、この<span><ruby><rb>辺</rb><rt>へん</rt></ruby></span>に<span><ruby><rb>貸家</rb><rt>かしや</rt></ruby></span>はないか。<span><ruby><rb>広</rb><rt>ひろ</rt></ruby>くて</span>、きれいな、<span><ruby><rb>書生</rb><rt>しょせい</rt></ruby><ruby><rb>部屋</rb><rt>べや</rt></ruby></span>のある」と<span><ruby><rb>尋</rb><rt>たず</rt></ruby>ねだした</span>。</p>
		<p>「貸家はと……ある」</p>
		<p>「どの辺だ。きたなくっちゃいけないぜ」</p>
		<p>「いやきれいなのがある。<span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな</span><span class="vocabstudy"><ruby><rb>石</rb><rt>いし</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>門</rb><rt>もん</rt></ruby></span>が<span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って</span>いるのがある」</p>
		<p>「そりゃうまい。どこだ。先生、石の門はいいですな。ぜひそれにしようじゃありませんか」と与次郎は大いに<span class="vocabstudy"><ruby><rb>進</rb><rt>すす</rt></ruby>んで</span>いる。</p>
		<p>「石の門はいかん」と先生が言う。</p>
		<p>「いかん？　そりゃ<span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>る</span>。なぜいかんです」</p>
		<p>「なぜでもいかん」</p>
		<p>「石の門はいいがな。<span class="vocabstudy"><ruby><rb>新</rb><rt>あたら</rt></ruby>しい</span><span class="vocabstudy"><ruby><rb>男爵</rb><rt>だんしゃく</rt></ruby></span>のようでいいじゃないですか、先生」</p>
		<p>与次郎はまじめである。広田先生は<span class="vocabstudy">にやにや<ruby><rb>笑</rb><rt>わら</rt></ruby>って</span>いる。とうとうまじめのほうが<span class="vocabstudy"><ruby><rb>勝</rb><rt>か</rt></ruby>って</span>、ともかくも<span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>る</span>ことに<span class="vocabstudy"><ruby><rb>相談</rb><rt>そうだん</rt></ruby>ができて</span>、三四郎が<span class="vocabstudy"><ruby><rb>案内</rb><rt>あんない</rt></ruby></span>をした。</p>

		<h3 class="section">Rough translation</h3>
		<p>Sanshirō thought to return the greeting, but the chance eluded him as he struggled for proper words. All he could manage was to remove his hat and bow modestly. This was too formal for Yojirō, and it was lacking in deference toward Professor Hirota. He'd split the difference and addressed neither party appropriately.</p>
		<p>Yojirō intervened immediately. "This fellow is one of my classmates. He went to high school in Kumamoto, and it's his first time here in Tōkyō." He seemed all too eager to divulge Sanshirō's provincial background. Then, turning to Sanshirō, "This is Professor Hirota. He's a high school ..." In his easy manner he concluded his introductions.</p>
		<p>At this point Professor Hirota told him, "We know each other. We know each other."</p> 
		<p>Yojirō took on a puzzled expression as the professor repeated this twice. However, rather than ask after mundane details, he charged ahead with his business at hand. "Say, do you know of any houses for rent nearby? We need something spacious, attractive, and with an extra room for a lodging student."</p>
		<p>"A house for rent ... actually, yes."</p>
		<p>"Whereabouts? Are you sure it's nice enough?"</p>
		<p>"It's quite nice. There's a large stone gate out front."</p>
		<p>Yojirō jumped at the thought of this. "Sounds good. How 'bout it Professor? A stone gate would be impressive. Maybe that's our house."</p> 
		<p>"I don't want a stone gate," said the Professor.</p>
		<p>"You don't want one? Why not?"</p>
		<p>"Because I just don't."</p>
		<p>"But stone gates are imposing. You'll look like a modern-day baron."</p>
		<p>Yojirō was earnest. The professor was grinning. In the end, earnest won the day, and it was decided to go have a look. Sanshirō led the way.</p>              

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>って&nbsp;say</span><span class="vocabstudy"><ruby><rb>挨拶</rb><rt>あいさつ</rt></ruby>&nbsp;greeting</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought (to)</span><span class="vocabstudy"><ruby><rb>時間</rb><rt>じかん</rt></ruby>&nbsp;time</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>をきいて&nbsp;speak; engage (in conversation)</span><span class="vocabstudy"><ruby><rb>帽子</rb><rt>ぼうし</rt></ruby>&nbsp;hat; cap</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>って&nbsp;take (off); remove</span><span class="vocabstudy"><ruby><rb>礼</rb><rt>れい</rt></ruby>&nbsp;salutation</span><span class="vocabstudy"><ruby><rb>与次郎</rb><rt>よじろう</rt></ruby>&nbsp;Yojirō (name)</span><span class="vocabstudy">に<ruby><rb>対</rb><rt>たい</rt></ruby>して&nbsp;with respect to; in relation to</span><span class="vocabstudy"><ruby><rb>丁寧</rb><rt>ていねい</rt></ruby>すぎる&nbsp;too polite</span><span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby>&nbsp;(Professor) Hirota</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>簡略</rb><rt>かんりゃく</rt></ruby>すぎる&nbsp;too simple; too brief</span><span class="vocabstudy"><ruby><rb>中間</rb><rt>ちゅうかん</rt></ruby>&nbsp;middle</span>
		<span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;fellow</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>の&nbsp;my</span><span class="vocabstudy"><ruby><rb>同級生</rb><rt>どうきゅうせい</rt></ruby>&nbsp;classmate</span><span class="vocabstudy"><ruby><rb>熊本</rb><rt>くまもと</rt></ruby>&nbsp;Kumamoto (city in Kyūshū)</span><span class="vocabstudy"><ruby><rb>高等</rb><rt>こうとう</rt></ruby><ruby><rb>学校</rb><rt>がっこう</rt></ruby>&nbsp;high school (equivalent to modern-day college)</span><span class="vocabstudy"><ruby><rb>東京</rb><rt>とうきょう</rt></ruby>&nbsp;Tōkyō</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came (to)</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>かれもしないさきから&nbsp;before being asked</span><span class="vocabstudy">いなか<ruby><rb>者</rb><rt>もの</rt></ruby>&nbsp;provincial (background); country upbringing</span><span class="vocabstudy"><ruby><rb>吹聴</rb><rt>ふいちょう</rt></ruby>して&nbsp;blurt out; broadcast</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>いて&nbsp;turn (toward)</span>
		<span class="vocabstudy"><ruby><rb>広田</rb><rt>ひろた</rt></ruby><ruby><rb>先生</rb><rt>せんせい</rt></ruby>&nbsp;Professor Hirota</span><span class="vocabstudy">わけもなく&nbsp;easily; casually</span><span class="vocabstudy"><ruby><rb>双方</rb><rt>そうほう</rt></ruby>&nbsp;both sides; both parties</span><span class="vocabstudy"><ruby><rb>紹介</rb><rt>しょうかい</rt></ruby>して&nbsp;introduce</span>
		<span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time; moment</span><span class="vocabstudy"><ruby><rb>知</rb><rt>し</rt></ruby>ってる&nbsp;(I) know</span><span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>へん&nbsp;twice; two times</span><span class="vocabstudy"><ruby><rb>繰</rb><rt>く</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>して&nbsp;in repetition</span><span class="vocabstudy"><ruby><rb>妙</rb><rt>みょう</rt></ruby>な&nbsp;odd; curious</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;look; facial expression</span><span class="vocabstudy">めんどうな&nbsp;troublesome; trifling</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;facts; details</span>
		<span class="vocabstudy"><ruby><rb>君</rb><rt>きみ</rt></ruby>&nbsp;you (used here as form of address)</span><span class="vocabstudy"><ruby><rb>辺</rb><rt>へん</rt></ruby>&nbsp;vicinity</span><span class="vocabstudy"><ruby><rb>貸家</rb><rt>かしや</rt></ruby>&nbsp;house for rent</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>くて&nbsp;large; spacious</span><span class="vocabstudy"><ruby><rb>書生</rb><rt>しょせい</rt></ruby><ruby><rb>部屋</rb><rt>べや</rt></ruby>&nbsp;lodging student room</span><span class="vocabstudy"><ruby><rb>尋</rb><rt>たず</rt></ruby>ねだした&nbsp;inquired</span>
		<span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな&nbsp;large</span><span class="vocabstudy"><ruby><rb>石</rb><rt>いし</rt></ruby>&nbsp;stone</span><span class="vocabstudy"><ruby><rb>門</rb><rt>もん</rt></ruby>&nbsp;gate</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;stand; be erected</span>
		<span class="vocabstudy"><ruby><rb>進</rb><rt>すす</rt></ruby>んで&nbsp;promote; get behind (an idea)</span>
		<span class="vocabstudy"><ruby><rb>困</rb><rt>こま</rt></ruby>る&nbsp;be a problem</span>
		<span class="vocabstudy"><ruby><rb>新</rb><rt>あたら</rt></ruby>しい&nbsp;new; modern</span><span class="vocabstudy"><ruby><rb>男爵</rb><rt>だんしゃく</rt></ruby>&nbsp;baron</span>
		<span class="vocabstudy">にやにや<ruby><rb>笑</rb><rt>わら</rt></ruby>って&nbsp;grin; smile</span><span class="vocabstudy"><ruby><rb>勝</rb><rt>か</rt></ruby>って&nbsp;won; triumphed</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>る&nbsp;take a look</span><span class="vocabstudy"><ruby><rb>相談</rb><rt>そうだん</rt></ruby>ができて&nbsp;discussion was concluded</span><span class="vocabstudy"><ruby><rb>案内</rb><rt>あんない</rt></ruby>&nbsp;guidance; leading the way</span>

	</StudyGuide>
);
