// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={74}>

		<h3 class="section">Practice text with full furigana</h3>
		<p><span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>が<span><ruby><rb>掃</rb><rt>は</rt></ruby>く</span>あとを、<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>が<span><ruby><rb>雑巾</rb><rt>ぞうきん</rt></ruby></span>をかける。三四郎が<span><ruby><rb>畳</rb><rt>たたみ</rt></ruby></span>をたたくあいだに、美禰子が<span><ruby><rb>障子</rb><rt>しょうじ</rt></ruby></span>を<span>はたく</span>。どうかこうか<span><ruby><rb>掃除</rb><rt>そうじ</rt></ruby></span>が<span>ひととおり</span><span><ruby><rb>済</rb><rt>す</rt></ruby>んだ</span><span><ruby><rb>時</rb><rt>とき</rt></ruby></span>は<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>ともだいぶ<span><ruby><rb>親</rb><rt>した</rt></ruby>しくなった</span>。</p>
		<p>三四郎がバケツの<span><ruby><rb>水</rb><rt>みず</rt></ruby></span>を<span><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>換</rb><rt>か</rt></ruby>え</span>に<span><ruby><rb>台所</rb><rt>だいどころ</rt></ruby></span>へ<span><ruby><rb>行</rb><rt>い</rt></ruby>った</span>あとで、美禰子が<span>はたき</span>と<span><ruby><rb>箒</rb><rt>ほうき</rt></ruby></span>を<span><ruby><rb>持</rb><rt>も</rt></ruby>って</span><span><ruby><rb>二階</rb><rt>にかい</rt></ruby></span>へ<span><ruby><rb>上</rb><rt>あ</rt></ruby>がった</span>。</p>
		<p>「ちょっと<span><ruby><rb>来</rb><rt>き</rt></ruby>て</span>ください」と<span><ruby><rb>上</rb><rt>うえ</rt></ruby></span>から三四郎を<span><ruby><rb>呼</rb><rt>よ</rt></ruby>ぶ</span>。</p>
		<p>「なんですか」とバケツをさげた三四郎が<span><ruby><rb>梯子段</rb><rt>はしごだん</rt></ruby></span>の<span><ruby><rb>下</rb><rt>した</rt></ruby></span>から<span><ruby><rb>言</rb><rt>い</rt></ruby>う</span>。<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は<span><ruby><rb>暗</rb><rt>くら</rt></ruby>い</span><span><ruby><rb>所</rb><rt>ところ</rt></ruby></span>に<span><ruby><rb>立</rb><rt>た</rt></ruby>って</span>いる。<span><ruby><rb>前</rb><rt>まえ</rt></ruby>だれ</span>だけが<span>まっ<ruby><rb>白</rb><rt>しろ</rt></ruby></span>だ。三四郎はバケツをさげたまま<span><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三段</rb><rt>さんだん</rt></ruby></span>上がった。女はじっとしている。三四郎はまた二段上がった。<span><ruby><rb>薄暗</rb><rt>うすぐら</rt></ruby>い</span>所で美禰子の<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>と三四郎の顔が<span><ruby><rb>一尺</rb><rt>いっしゃく</rt></ruby></span>ばかりの<span><ruby><rb>距離</rb><rt>きょり</rt></ruby></span>に来た。</p>
		<p>「なんですか」</p>
		<p>「なんだか暗くってわからないの」</p>
		<p>「なぜ」</p>
		<p>「なぜでも」</p>
		<p>三四郎は<span class="vocabstudy"><ruby><rb>追窮</rb><rt>ついきゅう</rt></ruby>する</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby></span>がなくなった。美禰子のそばを<span class="vocabstudy">すり<ruby><rb>抜</rb><rt>ぬ</rt></ruby>けて</span>上へ<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た</span>。バケツを暗い<span class="vocabstudy"><ruby><rb>椽側</rb><rt>えんがわ</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いて</span><span class="vocabstudy"><ruby><rb>戸</rb><rt>と</rt></ruby></span>をあける。なるほど<span class="vocabstudy"><ruby><rb>桟</rb><rt>さん</rt></ruby></span>のぐあいがよくわからない。そのうち美禰子も上がってきた。</p>
		<p>「<span class="vocabstudy">まだあからなくって</span>」</p>
		<p>美禰子は<span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>側</rb><rt>がわ</rt></ruby></span>へ行った。</p>
		<p>「こっちです」</p>
		<p>三四郎は<span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>、美禰子の<span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>近寄</rb><rt>ちかよ</rt></ruby>った</span>。もう<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span>で美禰子の<span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby></span>に<span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>の</span>手が<span class="vocabstudy"><ruby><rb>触</rb><rt>ふ</rt></ruby>れる<ruby><rb>所</rb><rt>ところ</rt></ruby></span>で、バケツに<span class="vocabstudy"><ruby><rb>蹴</rb><rt>け</rt></ruby>つまずいた</span>。<span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな<ruby><rb>音</rb><rt>おと</rt></ruby></span>がする。ようやくのことで戸を<span class="vocabstudy"><ruby><rb>一枚</rb><rt>いちまい</rt></ruby></span>あけると、<span class="vocabstudy"><ruby><rb>強</rb><rt>つよ</rt></ruby>い</span><span class="vocabstudy"><ruby><rb>日</rb><rt>ひ</rt></ruby></span>がまともに<span class="vocabstudy">さし<ruby><rb>込</rb><rt>こ</rt></ruby>んだ</span>。<span class="vocabstudy">まぼしい</span>くらいである。<span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>を<ruby><rb>見合</rb><rt>みあ</rt></ruby>わせて</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>わず</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>Mineko swept, and Sanshirō followed with a wet rag. While Sanshirō beat the dirt from the tatami mats, Mineko dusted the shōji. By the time they finished a once-through cleaning, they were working comfortably together.</p>
		<p>Sanshirō went to the kitchen to put fresh water in his bucket. Mineko took the duster and broom and headed upstairs.</p>
		<p>"Come up," she called to Sanshirō from above.</p>
		<p>"What is it?" Sanshirō appeared at the bottom of the stairs with his bucket. She was standing up on the dark landing. All he could see was the bright white of her apron. Still holding his bucket, he climbed up several steps. She didn't move. He climbed two more steps. On the dimly lit stairs, their faces were now quite close.</p>
		<p>"What is it?"</p>
		<p>"It's too dark. I can't go up."</p>
		<p>"Why not?"</p>
		<p>"I just can't."</p>
		<p>Sanshirō saw no reason to press the matter further. He slipped past her and stepped up onto the floor. He set his bucket down in the dark balcony corridor and tried to open a storm shutter. He couldn't find the bolt to unlatch it. Mineko came up after him.</p>
		<p>"Won't open yet?" She went to the opposite side. "Here it is."</p>
		<p>Without speaking, Sanshirō moved toward her. As their hands were almost touching, he stumbled over his bucket and kicked up a racket. When they finally succeeded in opening the shutter, bright sunlight flooded the room. It was almost blinding. They looked at each other and couldn't refrain from laughing.</p>              

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>掃</rb><rt>は</rt></ruby>く&nbsp;sweep</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>雑巾</rb><rt>ぞうきん</rt></ruby>&nbsp;cleaning rag</span><span class="vocabstudy"><ruby><rb>畳</rb><rt>たたみ</rt></ruby>&nbsp;tatami (mats)</span><span class="vocabstudy"><ruby><rb>障子</rb><rt>しょうじ</rt></ruby>&nbsp;shōji</span><span class="vocabstudy">はたく&nbsp;dust off</span><span class="vocabstudy"><ruby><rb>掃除</rb><rt>そうじ</rt></ruby>&nbsp;cleaning</span><span class="vocabstudy">ひととおり&nbsp;once over</span><span class="vocabstudy"><ruby><rb>済</rb><rt>す</rt></ruby>んだ&nbsp;be finished</span><span class="vocabstudy"><ruby><rb>時</rb><rt>とき</rt></ruby>&nbsp;time</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two people</span><span class="vocabstudy"><ruby><rb>親</rb><rt>した</rt></ruby>しくなった&nbsp;were on friendly terms</span>
		<span class="vocabstudy"><ruby><rb>水</rb><rt>みず</rt></ruby>&nbsp;water</span><span class="vocabstudy"><ruby><rb>取</rb><rt>と</rt></ruby>り<ruby><rb>換</rb><rt>か</rt></ruby>え&nbsp;exchange; change out</span><span class="vocabstudy"><ruby><rb>台所</rb><rt>だいどころ</rt></ruby>&nbsp;kitchen</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>った&nbsp;went (to)</span><span class="vocabstudy">はたき&nbsp;duster</span><span class="vocabstudy"><ruby><rb>箒</rb><rt>ほうき</rt></ruby>&nbsp;broom</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>って&nbsp;hold; carry</span><span class="vocabstudy"><ruby><rb>二階</rb><rt>にかい</rt></ruby>&nbsp;2nd floor; upstairs</span><span class="vocabstudy"><ruby><rb>上</rb><rt>あ</rt></ruby>がった&nbsp;went up (to)</span>
		<span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>て&nbsp;come</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;above</span><span class="vocabstudy"><ruby><rb>呼</rb><rt>よ</rt></ruby>ぶ&nbsp;call for</span>
		<span class="vocabstudy"><ruby><rb>梯子段</rb><rt>はしごだん</rt></ruby>&nbsp;staircase</span><span class="vocabstudy"><ruby><rb>下</rb><rt>した</rt></ruby>&nbsp;below; bottom</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>う&nbsp;say; reply</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;young lady</span><span class="vocabstudy"><ruby><rb>暗</rb><rt>くら</rt></ruby>い&nbsp;dark</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>って&nbsp;stand</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>だれ&nbsp;apron</span><span class="vocabstudy">まっ<ruby><rb>白</rb><rt>しろ</rt></ruby>&nbsp;pure white</span><span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三段</rb><rt>さんだん</rt></ruby>&nbsp;two or three steps</span><span class="vocabstudy"><ruby><rb>薄暗</rb><rt>うすぐら</rt></ruby>い&nbsp;dim</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>一尺</rb><rt>いっしゃく</rt></ruby>&nbsp;1 shaku (about 30 cm; about 1 foot)</span><span class="vocabstudy"><ruby><rb>距離</rb><rt>きょり</rt></ruby>&nbsp;distance</span>
		<span class="vocabstudy"><ruby><rb>追窮</rb><rt>ついきゅう</rt></ruby>する&nbsp;inquire further; press a matter</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>&nbsp;intention</span><span class="vocabstudy">すり<ruby><rb>抜</rb><rt>ぬ</rt></ruby>けて&nbsp;slip past</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>た&nbsp;arrived</span><span class="vocabstudy"><ruby><rb>椽側</rb><rt>えんがわ</rt></ruby>&nbsp;balcony; outer corridor</span><span class="vocabstudy"><ruby><rb>置</rb><rt>お</rt></ruby>いて&nbsp;place; set down</span><span class="vocabstudy"><ruby><rb>戸</rb><rt>と</rt></ruby>&nbsp;(storm) shutter</span><span class="vocabstudy"><ruby><rb>桟</rb><rt>さん</rt></ruby>&nbsp;sliding window bolt</span>
		<span class="vocabstudy">まだあからなくって&nbsp;Won't open yet?</span>
		<span class="vocabstudy"><ruby><rb>反対</rb><rt>はんたい</rt></ruby>&nbsp;opposite</span><span class="vocabstudy"><ruby><rb>側</rb><rt>がわ</rt></ruby>&nbsp;side</span>
		<span class="vocabstudy"><ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;without speaking</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>近寄</rb><rt>ちかよ</rt></ruby>った&nbsp;approached</span><span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>手</rb><rt>て</rt></ruby>&nbsp;hand</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>の&nbsp;one's own</span><span class="vocabstudy"><ruby><rb>触</rb><rt>ふ</rt></ruby>れる<ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;just short of touching</span><span class="vocabstudy"><ruby><rb>蹴</rb><rt>け</rt></ruby>つまずいた&nbsp;stumbled over (= <ruby><rb>躓</rb><rt>つまず</rt></ruby>いた)</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな<ruby><rb>音</rb><rt>おと</rt></ruby>&nbsp;loud sound; loud noise</span><span class="vocabstudy"><ruby><rb>一枚</rb><rt>いちまい</rt></ruby>&nbsp;one (door)</span><span class="vocabstudy"><ruby><rb>強</rb><rt>つよ</rt></ruby>い&nbsp;strong</span><span class="vocabstudy"><ruby><rb>日</rb><rt>ひ</rt></ruby>&nbsp;sunlight</span><span class="vocabstudy">さし<ruby><rb>込</rb><rt>こ</rt></ruby>んだ&nbsp;poured in</span><span class="vocabstudy">まぼしい&nbsp;blinding (= まぶしい)</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>を<ruby><rb>見合</rb><rt>みあ</rt></ruby>わせて&nbsp;look at each other</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>わず&nbsp;on impulse</span><span class="vocabstudy"><ruby><rb>笑</rb><rt>わら</rt></ruby>い<ruby><rb>出</rb><rt>だ</rt></ruby>した&nbsp;laughed</span>

	</StudyGuide>
);
