// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={157}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「なぜ。おいやなの？」</p>
		<p>「いやじゃないが、<span class="vocabstudy">お<ruby><rb>兄</rb><rt>あに</rt></ruby>いさん</span><span class="vocabstudy">に<ruby><rb>黙</rb><rt>だま</rt></ruby>って</span>、あなたから<span class="vocabstudy"><ruby><rb>借</rb><rt>か</rt></ruby>りちゃ</span>、<span class="vocabstudy"><ruby><rb>好</rb><rt>よ</rt></ruby>くない</span>からです」</p>
		<p>「どういうわけで？　でも<span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>している</span>んですもの」</p>
		<p>「そうですか。じゃ借りてもいい。――しかし借りないでもいい。<span class="vocabstudy"><ruby><rb>家</rb><rt>うち</rt></ruby></span>へそう<span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>って</span>やりさえすれば、<span class="vocabstudy"><ruby><rb>一週間</rb><rt>いっしゅうかん</rt></ruby></span>ぐらいすると<span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>ます</span>から」</p>
		<p>「<span class="vocabstudy"><ruby><rb>御迷惑</rb><rt>ごめいわく</rt></ruby></span>なら、しいて……」</p>
		<p><span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>は<span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に</span><span class="vocabstudy"><ruby><rb>冷淡</rb><rt>れいたん</rt></ruby></span>になった。<span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby></span>までそばにいたものが<span class="vocabstudy"><ruby><rb>一町</rb><rt>いっちょう</rt></ruby></span>ばかり<span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>のいた</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby></span>がする。<span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>は借りておけばよかったと<span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った</span>。けれども、もうしかたがない。<span class="vocabstudy"><ruby><rb>蝋燭立</rb><rt>ろうそくたて</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て</span>すましている。三四郎は<span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>から<ruby><rb>進</rb><rt>すす</rt></ruby>んで</span>、ひとのきげんをとったことのない<span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>である。女も遠ざかったぎり<span class="vocabstudy"><ruby><rb>近</rb><rt>ちか</rt></ruby>づいて<ruby><rb>来</rb><rt>こ</rt></ruby>ない</span>。しばらくするとまた<span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>上</rb><rt>あ</rt></ruby>がった</span>。<span class="vocabstudy"><ruby><rb>窓</rb><rt>まど</rt></ruby></span>から<span class="vocabstudy"><ruby><rb>戸外</rb><rt>そと</rt></ruby></span>を<span class="vocabstudy">すかして<ruby><rb>見</rb><rt>み</rt></ruby>て</span>、</p>
		<p>「<span class="vocabstudy"><ruby><rb>降</rb><rt>ふ</rt></ruby>りそう</span>もありませんね」と言う。三四郎も<span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じ</span><span class="vocabstudy"><ruby><rb>調子</rb><rt>ちょうし</rt></ruby></span>で、「降りそうもありません」と<span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた</span>。</p>
		<p>「降らなければ、<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby></span>ちょっと<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>よう</span>かしら」と窓の<span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby></span>で立ったまま言う。三四郎は<span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>ってくれ</span>という<span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby></span>に<span class="vocabstudy"><ruby><rb>解釈</rb><rt>かいしゃく</rt></ruby>した</span>。<span class="vocabstudy"><ruby><rb>光</rb><rt>ひか</rt></ruby>る</span><span class="vocabstudy"><ruby><rb>絹</rb><rt>きぬ</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>着換</rb><rt>きが</rt></ruby>えた</span>のも自分のためではなかった。</p>
		<p>「もう帰りましょう」と立ち上がった。美禰子は<span class="vocabstudy"><ruby><rb>玄関</rb><rt>げんかん</rt></ruby></span>まで<span class="vocabstudy"><ruby><rb>送</rb><rt>おく</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。<span class="vocabstudy"><ruby><rb>沓脱</rb><rt>くつぬぎ</rt></ruby></span>へ<span class="vocabstudy"><ruby><rb>降</rb><rt>お</rt></ruby>りて</span>、<span class="vocabstudy"><ruby><rb>靴</rb><rt>くつ</rt></ruby></span>をはいていると、<span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby></span>から美禰子が、</p>
		<p>「そこまでごいっしょに<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>ましょう</span>。いいでしょう」と言った。三四郎は靴の<span class="vocabstudy"><ruby><rb>紐</rb><rt>ひも</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>結</rb><rt>むす</rt></ruby>びながら</span>、「ええ、どうでも」と答えた。<span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby></span>はいつのまにか、<span class="vocabstudy"><ruby><rb>和土</rb><rt>たたき</rt></ruby></span>の上へ<span class="vocabstudy"><ruby><rb>下</rb><rt>お</rt></ruby>りた</span>。下りながら三四郎の<span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby></span>のそばへ<span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby></span>を<span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>ってきて</span>、「おこっていらっしゃるの」とささやいた。ところへ<span class="vocabstudy"><ruby><rb>下女</rb><rt>げじょ</rt></ruby></span>があわてながら、<span class="vocabstudy"><ruby><rb>送</rb><rt>おく</rt></ruby>りに</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。</p>

		<h3 class="section">Rough translation</h3>
		<p>"Why? It bothers you?"</p>
		<p>"It's not that it bothers me. But I shouldn't borrow from you behind your brother's back."</p>
		<p>"And why not? Anyway, my brother is aware of this."</p>
		<p>"He is? Then I guess it's okay. -- On the other hand, I don't have to borrow it. If I wired home, I could have it within the week."</p>
		<p>"If it bothers you so, I don't want to force it ..."</p>
		<p>Mineko seemed suddenly detached, as though she'd left him and drifted away. Sanshirō wished he'd just borrowed the money, but now it was too late. He fixed his gaze on the candle holders. He was never one to curry favor. Mineko, for her part, remained distant and did not reengage. After a moment she rose again and looked through the window.</p>
		<p>"It looks like the rain is holding off."</p>
		<p>Sanshirō echoed her tone in his answer. "Looks like it's holding off."</p>
		<p>"If it's not going to rain, I think I'll go out for a bit," she continued as she stood at the window. Sanshirō took this as a cue for him to go. It was not for his sake that she'd dressed in fine silk.</p>
		<p>"I should be going," he said as he rose. Mineko accompanied him to the entry hall. As he stepped down to retrieve his shoes, Mineko asked from above if she could walk part way with him.</p>
		<p>"Suit yourself," he replied.</p>
		<p>Before he knew it she was down by the entrance. In stepping down, she drew her mouth to Sanshirō's ear and whispered, "Are you angry?" At that point, the maidservant came hurrying out to see them off.</p>               

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy">お<ruby><rb>兄</rb><rt>あに</rt></ruby>いさん&nbsp;older brother</span><span class="vocabstudy">に<ruby><rb>黙</rb><rt>だま</rt></ruby>って&nbsp;without telling</span><span class="vocabstudy"><ruby><rb>借</rb><rt>か</rt></ruby>りちゃ&nbsp;borrow</span><span class="vocabstudy"><ruby><rb>好</rb><rt>よ</rt></ruby>くない&nbsp;not good; ill advised</span>
		<span class="vocabstudy"><ruby><rb>兄</rb><rt>あに</rt></ruby>&nbsp;older brother</span><span class="vocabstudy"><ruby><rb>承知</rb><rt>しょうち</rt></ruby>している&nbsp;is aware; is in agreement</span>
		<span class="vocabstudy"><ruby><rb>家</rb><rt>うち</rt></ruby>&nbsp;home</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>って&nbsp;ask; request</span><span class="vocabstudy"><ruby><rb>一週間</rb><rt>いっしゅうかん</rt></ruby>&nbsp;one week</span><span class="vocabstudy"><ruby><rb>来</rb><rt>き</rt></ruby>ます&nbsp;come; arrive</span>
		<span class="vocabstudy"><ruby><rb>御迷惑</rb><rt>ごめいわく</rt></ruby>&nbsp;trouble; bother</span>
		<span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>急</rb><rt>きゅう</rt></ruby>に&nbsp;suddenly</span><span class="vocabstudy"><ruby><rb>冷淡</rb><rt>れいたん</rt></ruby>&nbsp;cool; detached</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;now; the present</span><span class="vocabstudy"><ruby><rb>一町</rb><rt>いっちょう</rt></ruby>&nbsp;1 chō (about 110 meters; about 120 yards)</span><span class="vocabstudy"><ruby><rb>遠</rb><rt>とお</rt></ruby>のいた&nbsp;became distant; backed away (from)</span><span class="vocabstudy"><ruby><rb>気</rb><rt>き</rt></ruby>&nbsp;feeling</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>思</rb><rt>おも</rt></ruby>った&nbsp;thought</span><span class="vocabstudy"><ruby><rb>蝋燭立</rb><rt>ろうそくたて</rt></ruby>&nbsp;candle holder</span><span class="vocabstudy"><ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;look at</span><span class="vocabstudy"><ruby><rb>自分</rb><rt>じぶん</rt></ruby>から<ruby><rb>進</rb><rt>すす</rt></ruby>んで&nbsp;of one's own accord</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man</span><span class="vocabstudy"><ruby><rb>近</rb><rt>ちか</rt></ruby>づいて<ruby><rb>来</rb><rt>こ</rt></ruby>ない&nbsp;not come near; not come closer</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ち<ruby><rb>上</rb><rt>あ</rt></ruby>がった&nbsp;stood up</span><span class="vocabstudy"><ruby><rb>窓</rb><rt>まど</rt></ruby>&nbsp;window</span><span class="vocabstudy"><ruby><rb>戸外</rb><rt>そと</rt></ruby>&nbsp;outside</span><span class="vocabstudy">すかして<ruby><rb>見</rb><rt>み</rt></ruby>て&nbsp;look through to; peer through at</span>
		<span class="vocabstudy"><ruby><rb>降</rb><rt>ふ</rt></ruby>りそう&nbsp;look to rain; look like rain</span><span class="vocabstudy"><ruby><rb>同</rb><rt>おな</rt></ruby>じ&nbsp;same</span><span class="vocabstudy"><ruby><rb>調子</rb><rt>ちょうし</rt></ruby>&nbsp;tone (of voice)</span><span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えた&nbsp;answered</span>
		<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>よう&nbsp;go out (usually <ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>こ</rt></ruby>よう)</span><span class="vocabstudy"><ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>帰</rb><rt>かえ</rt></ruby>ってくれ&nbsp;please go; please leave</span><span class="vocabstudy"><ruby><rb>意味</rb><rt>いみ</rt></ruby>&nbsp;meaning; nuance</span><span class="vocabstudy"><ruby><rb>解釈</rb><rt>かいしゃく</rt></ruby>した&nbsp;understood; took as</span><span class="vocabstudy"><ruby><rb>光</rb><rt>ひか</rt></ruby>る&nbsp;shine; be bright</span><span class="vocabstudy"><ruby><rb>絹</rb><rt>きぬ</rt></ruby>&nbsp;silk</span><span class="vocabstudy"><ruby><rb>着換</rb><rt>きが</rt></ruby>えた&nbsp;changed (clothes)</span>
		<span class="vocabstudy"><ruby><rb>玄関</rb><rt>げんかん</rt></ruby>&nbsp;entry hall</span><span class="vocabstudy"><ruby><rb>送</rb><rt>おく</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;see a person (to); accompany a person (as far as)</span><span class="vocabstudy"><ruby><rb>沓脱</rb><rt>くつぬぎ</rt></ruby>&nbsp;platform for removing (or putting on) shoes</span><span class="vocabstudy"><ruby><rb>降</rb><rt>お</rt></ruby>りて&nbsp;descend; step down (to)</span><span class="vocabstudy"><ruby><rb>靴</rb><rt>くつ</rt></ruby>&nbsp;shoes</span><span class="vocabstudy"><ruby><rb>上</rb><rt>うえ</rt></ruby>&nbsp;above</span>
		<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>ましょう&nbsp;go out</span><span class="vocabstudy"><ruby><rb>紐</rb><rt>ひも</rt></ruby>&nbsp;(shoe) laces</span><span class="vocabstudy"><ruby><rb>結</rb><rt>むす</rt></ruby>びながら&nbsp;tie</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;young lady</span><span class="vocabstudy"><ruby><rb>和土</rb><rt>たたき</rt></ruby>&nbsp;hard-packed (clay) floor</span><span class="vocabstudy"><ruby><rb>下</rb><rt>お</rt></ruby>りた&nbsp;descended; stepped down (to)</span><span class="vocabstudy"><ruby><rb>耳</rb><rt>みみ</rt></ruby>&nbsp;ear</span><span class="vocabstudy"><ruby><rb>口</rb><rt>くち</rt></ruby>&nbsp;mouth</span><span class="vocabstudy"><ruby><rb>持</rb><rt>も</rt></ruby>ってきて&nbsp;bring to</span><span class="vocabstudy"><ruby><rb>下女</rb><rt>げじょ</rt></ruby>&nbsp;maidservant</span><span class="vocabstudy"><ruby><rb>送</rb><rt>おく</rt></ruby>りに&nbsp;to see (someone) off</span><span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>て<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;came out; appeared</span>

	</StudyGuide>
);
