// React
import React from 'react'

// Components
import StudyGuide from '../../components/StudyGuide'


export default () => (
	<StudyGuide book='Sanshirō' num={166}>

		<h3 class="section">Practice text with full furigana</h3>
		<p>「ほんとうにいいの？」と<span><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby></span>が<span><ruby><rb>小</rb><rt>ちい</rt></ruby>さい</span><span><ruby><rb>声</rb><rt>こえ</rt></ruby></span>で<span><ruby><rb>聞</rb><rt>き</rt></ruby>いた</span>。<span><ruby><rb>向</rb><rt>む</rt></ruby>こう</span>から<span><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三人連</rb><rt>さんにんづれ</rt></ruby></span>の<span><ruby><rb>観覧者</rb><rt>かんらんしゃ</rt></ruby></span>が<span><ruby><rb>来</rb><rt>く</rt></ruby>る</span>。</p>
		<p>「ともかく<span><ruby><rb>出</rb><rt>で</rt></ruby>ましょう</span>」と<span><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby></span>が<span><ruby><rb>言</rb><rt>い</rt></ruby>った</span>。<span><ruby><rb>下足</rb><rt>げそく</rt></ruby></span>を<span><ruby><rb>受</rb><rt>う</rt></ruby>け<ruby><rb>取</rb><rt>と</rt></ruby>って</span>、出ると<span><ruby><rb>戸外</rb><rt>そと</rt></ruby></span>は<span><ruby><rb>雨</rb><rt>あめ</rt></ruby></span>だ。</p>
		<p>「<span><ruby><rb>精養軒</rb><rt>せいようけん</rt></ruby></span>へ<span><ruby><rb>行</rb><rt>い</rt></ruby>きます</span>か」</p>
		<p>美禰子は<span><ruby><rb>答</rb><rt>こた</rt></ruby>えなかった</span>。雨のなかをぬれながら、<span><ruby><rb>博物館</rb><rt>はくぶつかん</rt></ruby></span><span><ruby><rb>前</rb><rt>まえ</rt></ruby></span>の<span><ruby><rb>広</rb><rt>ひろ</rt></ruby>い</span><span><ruby><rb>原</rb><rt>はら</rt></ruby></span>のなかに<span><ruby><rb>立</rb><rt>た</rt></ruby>った</span>。さいわい雨は<span><ruby><rb>今</rb><rt>いま</rt></ruby></span><span><ruby><rb>降</rb><rt>ふ</rt></ruby>りだした</span>ばかりである。そのうえ<span><ruby><rb>激</rb><rt>はげ</rt></ruby>しく</span>はない。<span><ruby><rb>女</rb><rt>おんな</rt></ruby></span>は雨のなかに立って、<span><ruby><rb>見回</rb><rt>みまわ</rt></ruby>しながら</span>、向こうの<span><ruby><rb>森</rb><rt>もり</rt></ruby></span>をさした。</p>
		<p>「あの<span><ruby><rb>木</rb><rt>き</rt></ruby></span>の<span><ruby><rb>陰</rb><rt>かげ</rt></ruby></span>へはいりましょう」</p>
		<p><span><ruby><rb>少</rb><rt>すこ</rt></ruby>し</span><span><ruby><rb>待</rb><rt>ま</rt></ruby>てば</span>やみそうである。<span><ruby><rb>二人</rb><rt>ふたり</rt></ruby></span>は<span><ruby><rb>大</rb><rt>おお</rt></ruby>きな</span><span><ruby><rb>杉</rb><rt>すぎ</rt></ruby></span>の<span><ruby><rb>下</rb><rt>した</rt></ruby></span>にはいった。雨を<span><ruby><rb>防</rb><rt>ふせ</rt></ruby>ぐ</span>にはつごうのよくない木である。けれども二人とも<span><ruby><rb>動</rb><rt>うご</rt></ruby>かない</span>。ぬれても立っている。二人とも<span><ruby><rb>寒</rb><rt>さむ</rt></ruby>くなった</span>。女が「<span><ruby><rb>小川</rb><rt>おがわ</rt></ruby></span>さん」と言う。<span><ruby><rb>男</rb><rt>おとこ</rt></ruby></span>は<span><ruby><rb>八</rb><rt>はち</rt></ruby>の<ruby><rb>字</rb><rt>じ</rt></ruby>を<ruby><rb>寄</rb><rt>よ</rt></ruby>せて</span>、<span><ruby><rb>空</rb><rt>そら</rt></ruby></span>を見ていた<span><ruby><rb>顔</rb><rt>かお</rt></ruby></span>を女の<span><ruby><rb>方</rb><rt>ほう</rt></ruby></span>へ<span><ruby><rb>向</rb><rt>む</rt></ruby>けた</span>。</p>
		<p>「<span><ruby><rb>悪</rb><rt>わる</rt></ruby>くって</span>？　さっきのこと」</p>
		<p>「いいです」</p>
		<p>「だって」と言いながら、<span class="vocabstudy"><ruby><rb>寄</rb><rt>よ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た</span>。「<span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby></span>、なぜだか、ああしたかったんですもの。<span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby></span>さんに<span class="vocabstudy"><ruby><rb>失礼</rb><rt>しつれい</rt></ruby>する</span>つもりじゃないんですけれども」</p>
		<p>女は<span class="vocabstudy"><ruby><rb>瞳</rb><rt>ひとみ</rt></ruby>を<ruby><rb>定</rb><rt>さだ</rt></ruby>めて</span>、三四郎を見た。三四郎はその瞳のなかに<span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby></span>よりも<span class="vocabstudy"><ruby><rb>深</rb><rt>ふか</rt></ruby>き</span><span class="vocabstudy"><ruby><rb>訴</rb><rt>うった</rt></ruby>え</span>を<span class="vocabstudy"><ruby><rb>認</rb><rt>みと</rt></ruby>めた</span>。――<span class="vocabstudy"><ruby><rb>必竟</rb><rt>ひっきょう</rt></ruby></span>あなたのためにした<span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby></span>じゃありませんかと、<span class="vocabstudy"><ruby><rb>二重</rb><rt>ふたえ</rt></ruby><ruby><rb>瞼</rb><rt>まぶた</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>奥</rb><rt>おく</rt></ruby></span>で訴えている。三四郎は、<span class="vocabstudy">もう<ruby><rb>一</rb><rt>いっ</rt></ruby>ぺん</span>、</p>
		<p>「だから、いいです」と答えた。</p>
		<p>雨はだんだん<span class="vocabstudy"><ruby><rb>濃</rb><rt>こ</rt></ruby>くなった</span>。<span class="vocabstudy"><ruby><rb>雫</rb><rt>しずく</rt></ruby></span>の<span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちない</span><span class="vocabstudy"><ruby><rb>場所</rb><rt>ばしょ</rt></ruby></span>はわずかしかない。二人はだんだん<span class="vocabstudy"><ruby><rb>一</rb><rt>ひと</rt></ruby>つ<ruby><rb>所</rb><rt>ところ</rt></ruby></span>へかたまってきた。<span class="vocabstudy"><ruby><rb>肩</rb><rt>かた</rt></ruby></span>と肩と<span class="vocabstudy">すれ<ruby><rb>合</rb><rt>あ</rt></ruby>う</span>くらいにして<span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ちすくんで</span>いた。雨の<span class="vocabstudy"><ruby><rb>音</rb><rt>おと</rt></ruby></span>のなかで、美禰子が、</p>
		<p>「さっきの<span class="vocabstudy">お<ruby><rb>金</rb><rt>かね</rt></ruby></span>を<span class="vocabstudy">お<ruby><rb>使</rb><rt>つか</rt></ruby>いなさい</span>」と言った。</p>
		<p>「<span class="vocabstudy"><ruby><rb>借</rb><rt>か</rt></ruby>りましょう</span>。<span class="vocabstudy"><ruby><rb>要</rb><rt>い</rt></ruby>るだけ</span>」と答えた。</p>
		<p>「みんな、お使いなさい」と言った。</p>

		<h3 class="section">Rough translation</h3>
		<p>"Are you really okay?" Mineko asked in a quiet voice. A small group of visitors approached from the other direction.</p>
		<p>"Anyway, let's go," Sanshirō replied. They retrieved their shoes and went outside. Rain was falling.</p>
		<p>"Are you going to Seiyōken?"</p>
		<p>Mineko didn't answer. They stood in the rain on the open field that fronted the museum. Fortunately, the rain had just started and was not falling hard. Mineko looked around and pointed out some trees in the distance.</p>
		<p>"Let's take shelter in those trees."</p>
		<p>It looked as though the rain might let up in a bit. The two of them ducked beneath a large cedar. It wasn't the best tree for sheltering from rain. However, neither moved. They stood there, getting wetter as the rain continued. Both felt chilled. Mineko said his name. He'd been surveying the sky with knitted brows. He turned to look at her.</p>
		<p>"Was it so bad, what I did?"</p>
		<p>"Don't worry about it."</p>
		<p>"But ..." she started, and drew nearer. "I couldn't help myself, somehow. I didn't really mean to slight Nonomiya."</p>
		<p>She fixed her gaze on Sanshirō. He recognized in her eyes a deeper appeal than her words conveyed. -- Behind her handsome eyelids, something seemed to say that, after all, she had done it on his account.</p>
		<p>"Please, just drop it," Sanshirō answered again.</p>
		<p>The rain fell harder. Water dripped down on all sides. The two of them, retreating from the drops, huddled so close that their shoulders were all but touching.</p>
		<p>Through the sound of the rain, Mineko said, "That money, it's for you to use."</p>
		<p>"I'll borrow what I need."</p>
		<p>"Please use it all."</p>              

		<h3 class="section">Vocabulary</h3>
		<span class="vocabstudy"><ruby><rb>美禰子</rb><rt>みねこ</rt></ruby>&nbsp;Mineko (name)</span><span class="vocabstudy"><ruby><rb>小</rb><rt>ちい</rt></ruby>さい&nbsp;small; low (voice)</span><span class="vocabstudy"><ruby><rb>声</rb><rt>こえ</rt></ruby>&nbsp;voice</span><span class="vocabstudy"><ruby><rb>聞</rb><rt>き</rt></ruby>いた&nbsp;asked</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>こう&nbsp;beyond; the other direction</span><span class="vocabstudy"><ruby><rb>二</rb><rt>に</rt></ruby>、<ruby><rb>三人連</rb><rt>さんにんづれ</rt></ruby>&nbsp;a small group; a party of several people</span><span class="vocabstudy"><ruby><rb>観覧者</rb><rt>かんらんしゃ</rt></ruby>&nbsp;visitors; viewers</span><span class="vocabstudy"><ruby><rb>来</rb><rt>く</rt></ruby>る&nbsp;came; approached</span>
		<span class="vocabstudy"><ruby><rb>出</rb><rt>で</rt></ruby>ましょう&nbsp;leave; go out</span><span class="vocabstudy"><ruby><rb>三四郎</rb><rt>さんしろう</rt></ruby>&nbsp;Sanshirō (name)</span><span class="vocabstudy"><ruby><rb>言</rb><rt>い</rt></ruby>った&nbsp;said; replied</span><span class="vocabstudy"><ruby><rb>下足</rb><rt>げそく</rt></ruby>&nbsp;outdoor shoes (exchanged for slippers on entering)</span><span class="vocabstudy"><ruby><rb>受</rb><rt>う</rt></ruby>け<ruby><rb>取</rb><rt>と</rt></ruby>って&nbsp;received; retrieved</span><span class="vocabstudy"><ruby><rb>戸外</rb><rt>そと</rt></ruby>&nbsp;outdoors; outside</span><span class="vocabstudy"><ruby><rb>雨</rb><rt>あめ</rt></ruby>&nbsp;rain</span>
		<span class="vocabstudy"><ruby><rb>精養軒</rb><rt>せいようけん</rt></ruby>&nbsp;Seiyōken (name of high-end Western-style restaurant)</span><span class="vocabstudy"><ruby><rb>行</rb><rt>い</rt></ruby>きます&nbsp;go (to)</span>
		<span class="vocabstudy"><ruby><rb>答</rb><rt>こた</rt></ruby>えなかった&nbsp;didn't answer</span><span class="vocabstudy"><ruby><rb>博物館</rb><rt>はくぶつかん</rt></ruby>&nbsp;museum</span><span class="vocabstudy"><ruby><rb>前</rb><rt>まえ</rt></ruby>&nbsp;front of</span><span class="vocabstudy"><ruby><rb>広</rb><rt>ひろ</rt></ruby>い&nbsp;wide; open</span><span class="vocabstudy"><ruby><rb>原</rb><rt>はら</rt></ruby>&nbsp;field</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>った&nbsp;stood</span><span class="vocabstudy"><ruby><rb>今</rb><rt>いま</rt></ruby>&nbsp;(just) now</span><span class="vocabstudy"><ruby><rb>降</rb><rt>ふ</rt></ruby>りだした&nbsp;started falling</span><span class="vocabstudy"><ruby><rb>激</rb><rt>はげ</rt></ruby>しく&nbsp;strong; intense</span><span class="vocabstudy"><ruby><rb>女</rb><rt>おんな</rt></ruby>&nbsp;woman; young lady</span><span class="vocabstudy"><ruby><rb>見回</rb><rt>みまわ</rt></ruby>しながら&nbsp;looking around</span><span class="vocabstudy"><ruby><rb>森</rb><rt>もり</rt></ruby>&nbsp;woods; trees</span>
		<span class="vocabstudy"><ruby><rb>木</rb><rt>き</rt></ruby>&nbsp;trees</span><span class="vocabstudy"><ruby><rb>陰</rb><rt>かげ</rt></ruby>&nbsp;shade; shelter</span>
		<span class="vocabstudy"><ruby><rb>少</rb><rt>すこ</rt></ruby>し&nbsp;a little; a bit</span><span class="vocabstudy"><ruby><rb>待</rb><rt>ま</rt></ruby>てば&nbsp;wait</span><span class="vocabstudy"><ruby><rb>二人</rb><rt>ふたり</rt></ruby>&nbsp;two (people)</span><span class="vocabstudy"><ruby><rb>大</rb><rt>おお</rt></ruby>きな&nbsp;large</span><span class="vocabstudy"><ruby><rb>杉</rb><rt>すぎ</rt></ruby>&nbsp;cedar (tree)</span><span class="vocabstudy"><ruby><rb>下</rb><rt>した</rt></ruby>&nbsp;beneath</span><span class="vocabstudy"><ruby><rb>防</rb><rt>ふせ</rt></ruby>ぐ&nbsp;avoid; protect (against)</span><span class="vocabstudy"><ruby><rb>動</rb><rt>うご</rt></ruby>かない&nbsp;didn't move</span><span class="vocabstudy"><ruby><rb>寒</rb><rt>さむ</rt></ruby>くなった&nbsp;felt cold; became chilled</span><span class="vocabstudy"><ruby><rb>小川</rb><rt>おがわ</rt></ruby>&nbsp;Ogawa (Sanshirō's family name)</span><span class="vocabstudy"><ruby><rb>男</rb><rt>おとこ</rt></ruby>&nbsp;man; fellow</span><span class="vocabstudy"><ruby><rb>八</rb><rt>はち</rt></ruby>の<ruby><rb>字</rb><rt>じ</rt></ruby>を<ruby><rb>寄</rb><rt>よ</rt></ruby>せて&nbsp;frown; knit one's brows</span><span class="vocabstudy"><ruby><rb>空</rb><rt>そら</rt></ruby>&nbsp;sky</span><span class="vocabstudy"><ruby><rb>顔</rb><rt>かお</rt></ruby>&nbsp;face</span><span class="vocabstudy"><ruby><rb>方</rb><rt>ほう</rt></ruby>&nbsp;direction</span><span class="vocabstudy"><ruby><rb>向</rb><rt>む</rt></ruby>けた&nbsp;turned toward</span>
		<span class="vocabstudy"><ruby><rb>悪</rb><rt>わる</rt></ruby>くって&nbsp;wrong</span>
		<span class="vocabstudy"><ruby><rb>寄</rb><rt>よ</rt></ruby>って<ruby><rb>来</rb><rt>き</rt></ruby>た&nbsp;approached; drew near</span><span class="vocabstudy"><ruby><rb>私</rb><rt>わたし</rt></ruby>&nbsp;I; me</span><span class="vocabstudy"><ruby><rb>野々宮</rb><rt>ののみや</rt></ruby>&nbsp;Nonomiya (name)</span><span class="vocabstudy"><ruby><rb>失礼</rb><rt>しつれい</rt></ruby>する&nbsp;be rude (to); slight</span>
		<span class="vocabstudy"><ruby><rb>瞳</rb><rt>ひとみ</rt></ruby>を<ruby><rb>定</rb><rt>さだ</rt></ruby>めて&nbsp;fix one's gaze</span><span class="vocabstudy"><ruby><rb>言葉</rb><rt>ことば</rt></ruby>&nbsp;words</span><span class="vocabstudy"><ruby><rb>深</rb><rt>ふか</rt></ruby>き&nbsp;deep; profound</span><span class="vocabstudy"><ruby><rb>訴</rb><rt>うった</rt></ruby>え&nbsp;appeal</span><span class="vocabstudy"><ruby><rb>認</rb><rt>みと</rt></ruby>めた&nbsp;recognized</span><span class="vocabstudy"><ruby><rb>必竟</rb><rt>ひっきょう</rt></ruby>&nbsp;after all</span><span class="vocabstudy"><ruby><rb>事</rb><rt>こと</rt></ruby>&nbsp;act; deed</span><span class="vocabstudy"><ruby><rb>二重</rb><rt>ふたえ</rt></ruby><ruby><rb>瞼</rb><rt>まぶた</rt></ruby>&nbsp;contoured eyelids</span><span class="vocabstudy"><ruby><rb>奥</rb><rt>おく</rt></ruby>&nbsp;interior; depths</span><span class="vocabstudy">もう<ruby><rb>一</rb><rt>いっ</rt></ruby>ぺん&nbsp;once more</span>
		<span class="vocabstudy"><ruby><rb>濃</rb><rt>こ</rt></ruby>くなった&nbsp;became thick; became heavy; intensified</span><span class="vocabstudy"><ruby><rb>雫</rb><rt>しずく</rt></ruby>&nbsp;drops</span><span class="vocabstudy"><ruby><rb>落</rb><rt>お</rt></ruby>ちない&nbsp;don't fall</span><span class="vocabstudy"><ruby><rb>場所</rb><rt>ばしょ</rt></ruby>&nbsp;place</span><span class="vocabstudy"><ruby><rb>一</rb><rt>ひと</rt></ruby>つ<ruby><rb>所</rb><rt>ところ</rt></ruby>&nbsp;one place; the same place</span><span class="vocabstudy"><ruby><rb>肩</rb><rt>かた</rt></ruby>&nbsp;shoulder</span><span class="vocabstudy">すれ<ruby><rb>合</rb><rt>あ</rt></ruby>う&nbsp;brush together</span><span class="vocabstudy"><ruby><rb>立</rb><rt>た</rt></ruby>ちすくんで&nbsp;be huddled</span><span class="vocabstudy"><ruby><rb>音</rb><rt>おと</rt></ruby>&nbsp;sound</span>
		<span class="vocabstudy">お<ruby><rb>金</rb><rt>かね</rt></ruby>&nbsp;money</span><span class="vocabstudy">お<ruby><rb>使</rb><rt>つか</rt></ruby>いなさい&nbsp;please make use of</span>
		<span class="vocabstudy"><ruby><rb>借</rb><rt>か</rt></ruby>りましょう&nbsp;borrow</span><span class="vocabstudy"><ruby><rb>要</rb><rt>い</rt></ruby>るだけ&nbsp;as necessary</span>

	</StudyGuide>
);
